
plugins {
    id 'org.hidetake.swagger.generator'
}

subprojects {

    apply plugin: 'org.hidetake.swagger.generator'

    /////// COMPILATION

    dependencies {
        swaggerUI generator.swaggerUI
    }


    swaggerSources {
        model {
            inputFile = file("../../services/$project.projectDir.name/src/main/modeling/swagger.yaml")
            ui {
                outputDir = file("./build/docs/api")
            }
        }
    }


}
