import com.vanniktech.maven.publish.SonatypeHost

plugins {
    id 'java'
    id 'jacoco'
    id 'org.openapi.generator'
    id "com.vanniktech.maven.publish" version "0.33.0"
}

subprojects {

    apply plugin: 'java-library'
    apply plugin: 'jacoco'
    apply plugin: 'maven-publish'
    apply plugin: 'signing'
    apply plugin: 'org.openapi.generator'
    apply plugin: "com.vanniktech.maven.publish"

    /////// COMPILATION

    dependencies {
        testRuntimeOnly testing_deps.junit5Engine
        testImplementation testing_deps.junit5Api
        testImplementation boot.starterTest, testing_deps.assertJ
        implementation misc.jacksonAnnotations
        // Required for Jackson databind annotations
        implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    }

    sourceSets {
        main {
            java {
                srcDir 'src/main/java'
                srcDir 'build/generate-resources/main/src/main/java'
            }
            resources{
                srcDir 'src/main/resources'
                srcDir 'build/src/generated/resources'
            }
        }
    }

    openApiGenerate {
        if (!project.projectDir.name.equals('cards')) {
            inputSpec = "${project.projectDir}/../../services/$project.projectDir.name/src/main/modeling/swagger.yaml"
        } else {
            inputSpec = "${project.projectDir}/../../services/cards-publication/src/main/modeling/swagger.yaml"
        }
        generatorName = 'java'
        outputDir = "${project.buildDir}/generate-resources/main"
        globalProperties = [
            models: "",
            modelTests: "false",
            apis: "false",
            supportingFiles: "false"
        ]
        additionalProperties = [
            modelPackage: "org.opfab." + project.projectDir.name.replace('-', '_') + ".model",
            hideGenerationTimestamp: "true",
            dateLibrary: "java8",
            useBeanValidation: "false",
            serializationLibrary: "jackson",
            library: "resttemplate",
            disallowAdditionalPropertiesIfNotPresent: "false",
            openApiNullable: "false",
            useJakartaEe: "false"
        ]
    }

task generateSwaggerUI(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    if (!project.projectDir.name.equals('cards')) {
        inputSpec = "${project.projectDir}/../../services/$project.projectDir.name/src/main/modeling/swagger.yaml"
        }
    else {
        inputSpec = "${project.projectDir}/../../services/cards-publication/src/main/modeling/swagger.yaml"
    }
    generatorName = 'html2'
    outputDir = "${project.projectDir}/build/docs/api"
}

    // Task to run the custom post-processing to remove javax.annotation imports
    // work around for problem : https://github.com/OpenAPITools/openapi-generator/issues/14010
    task postProcessGeneratedCode {
        dependsOn 'openApiGenerate'
        doLast {
            // Convert project directory name to package name (hyphens to underscores)
            def packageName = project.projectDir.name.replace('-', '_')
            def modelDir = file("${project.buildDir}/generate-resources/main/src/main/java/org/opfab/${packageName}/model")
            if (modelDir.exists()) {
                modelDir.listFiles().each { file ->
                    if (file.name.endsWith('.java')) {
                        def content = file.text
                        content = content.replaceAll(/\@javax\.annotation\.Nullable/, '')
                        content = content.replaceAll(/\@javax\.annotation\.Nonnull/, '')
                        content = content.replaceAll(/\@javax\.annotation\.Generated\([^\)]*\)/, '// Generated by OpenAPI Generator')
                        file.text = content
                    }
                }
            }
        }
    }

    /////// CONFIGURATION
    test {
        useJUnitPlatform()
        filter {
            includeTestsMatching "*Should"
        }
    }

    jacocoTestReport {
        group = "Reporting"
        reports {
            xml.required = true
            csv.required = false
            html.outputLocation = file("${buildDir}/reports/coverage")
        }
    }

    /////// CUSTOM TASKS

    /*Task that copies all the dependencies under build/support_libs so Sonar
    can make sense of the Lombok annotations for example */
    task copyDependencies(type: Copy) {
        description = 'copy dependencies to build/support_libs'
        from configurations.compileClasspath
        into 'build/support_libs'
    }

    tasks.jacocoTestReport.dependsOn test
    tasks.compileJava.dependsOn postProcessGeneratedCode
    tasks.compileTestJava.dependsOn postProcessGeneratedCode



    /** Configuration of publication of client jars to Maven Central */

    task sourcesJar(type: Jar){
        archiveClassifier='sources'
        from sourceSets.main.allJava
        duplicatesStrategy = 'include' // This is a temporary fix to avoid false build error, see (#1543)
    }

    tasks.sourcesJar.dependsOn postProcessGeneratedCode

    task javadocJar(type: Jar){
        archiveClassifier = 'javadoc'
        from javadoc.destinationDir
    }

    mavenPublishing {

        publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL)

        signAllPublications()

        pom {
            name = project.provider { project.longName }
            description = project.provider { project.description }
            version="${operatorfabric.version}"
            url="${operatorfabric.url}"
            licenses{
                license{
                    name = 'Mozilla Public License Version 2.0'
                    url = 'https://www.mozilla.org/en-US/MPL/'
                }
            }
            developers {
                developer {
                    id = 'freddidierRTE'
                    name = 'Frédéric Didier'
                    email = 'frederic-f.didier@rte-france.com'
                }
                developer {
                    id = 'vlo-rte'
                    name = 'Valérie Longa'
                    email = 'valerie.longa@rte-france.com'
                }
                developer {
                    id = 'ClementBouvierN'
                    name = 'Clément Bouvier'
                    email = 'clement.bouvierneveu@rte-france.com'
                }
            }
            scm {
                url = 'https://github.com/opfab/operatorfabric-core'
                connection = 'scm:git:git://github.com:opfab/operatorfabric-core.git'
                developerConnection = 'scm:git:ssh://github.com:opfab/operatorfabric-core.git'
            }
        }
    }

    signing {
        useGpgCmd() //These is needed to work with GPG2 See https://github.com/gradle/gradle/issues/888#issuecomment-708439524
    }
}
