operatorfabric:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:89/auth/realms/dev/protocol/openid-connect/certs
  mongodb:
    database: "operator-fabric"
    uri: "mongodb://root:password@localhost:27017/operator-fabric?authSource=admin"
  servicesUrls:
    authToken: "http://127.0.0.1:2002/auth/token"
    users: "http://127.0.0.1:2103"
    cardsPublication: "http://127.0.0.1:2102"
    cardsConsultation: "http://127.0.0.1:2104"
  internalAccount:
    login: opfab
    password: test
  logConfig:
    logFolder: logs/
    logFile: "%DATE%.log"
    logLevel: info
  supervisor:
    defaultConfig:
      considerConnectedIfUserInGroups: ["Dispatcher","Planner"]
      entitiesToSupervise:
      - entityId: ENTITY1_FR
        supervisors:
        - ENTITY2_FR
      - entityId: ENTITY2_FR
        supervisors:
        - ENTITY1_FR
      disconnectedCardTemplate:
        publisher: opfab
        processVersion: '1'
        process: supervisor
        state: disconnectedEntity
        severity: ALARM
      secondsBetweenConnectionChecks: 10
      nbOfConsecutiveNotConnectedToSendFirstCard: 3
      nbOfConsecutiveNotConnectedToSendSecondCard: 12
      processesToSupervise:
      - process: messageOrQuestionExample
        states:
        - messageState
        - questionState
      - process: defaultProcess
        states:
        - processState
      unackCardTemplate:
        publisher: opfab
        processVersion: '1'
        process: supervisor
        state: unacknowledgedCards
        severity: ALARM
      windowInSecondsForCardSearch: 1200
      secondsBetweenAcknowledgmentChecks: 10
      secondsAfterPublicationToConsiderCardAsNotAcknowledged: 600
    adminPort: 2108
    activeOnStartup: true

