
management:
  endpoints:
    web:
      exposure:
        include: '*'

operatorfabric:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: for_test_only # !!! TO BE CHANGED THIS IS ONLY FOR TEST AND DEMONSTRATION !!!
  customscreen:
    dataFields: ["keywords", "nested.field","comment","reason"]
  mongodb:
    uri: mongodb://root:password@mongodb:27017/operator-fabric?authSource=admin # !!! TO BE CHANGED THIS IS ONLY FOR TEST AND DEMONSTRATION !!!
  internalAccount:
    login: opfab
    password: test # !!! TO BE CHANGED THIS IS ONLY FOR TEST AND DEMONSTRATION !!!
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:89/auth/realms/dev/protocol/openid-connect/certs
    jwt:
      login-claim: preferred_username

### activate the following if you want the entities of the user to come from the token and not mongoDB
### entitiesIdClaim is the name of the field in the token     
#      entitiesIdClaim : entitiesId
#      entitiesIdClaimSingleString : false
#      gettingEntitiesFromToken: true
      gettingFirstAndLastNameFromToken: false
###

### activate the following if you want the groups of the user to come from the token and not mongoDB
#      groups: 
#        mode: JWT
#        rolesClaim:
#          rolesClaimStandard:
#            - path: "ATTR1"
#            - path: "ATTR2"            
#          rolesClaimStandardArray:  
#            - path: "resource_access/opfab-client/roles"
#          rolesClaimStandardList:  
#            - path: "groups" 
#              separator: ";"           
#          rolesClaimCheckExistPath: 
#            - path: "resource_access/AAA" 
#              roleValue: "roleAAA"      
#            - path: "resource_access/BBB"
#              roleValue: "roleBBB"  
### 
