
org.gradle.jvmargs=-XX:MaxMetaspaceSize=512m -Xmx2g

# spring libs
springBoot=4.1.0
springSecurity=7.1.0

# utilities & tools
apacheCommonsCompress=1.28.0
apacheCommonsCollections4=4.5.0
apacheCommonsPool=2.13.1
commonsIO=2.22.0

jlibmodbus=1.2.9.11
kavroSchemaRegistryClient=8.3.0
kavroAvroSerializer=8.3.0
micrometer=1.17.0
apacheCommonsText=1.15.0
apacheCommonsLang=3.20.0
rabbitMQ=5.32.0

# testing libs
assertj=3.27.7
junit5=6.1.1

# Explicitly defining the version of junitPlatformVersion was necessary to have a successful build
# with junit5 5.12.2 (see issue #8169)
junitPlatformVersion=6.1.1

karate=1.5.2
reactor=3.8.6

#Used for karate tests only
jacksonAnnotations=2.22


#Use for kafka testing
avro=1.12.1
kafka=8.3.0-ce

systemProp.sonar.gradle.skipCompile=true
