
org.gradle.jvmargs=-XX:MaxMetaspaceSize=512m -Xmx2g
# spring libs
springBoot=3.5.6
springRetry=2.0.4
springWebflux=6.2.11
springSecurity=6.5.5

# logging libs
slf4j=2.0.17

# utilities & tools
apacheCommonsCompress=1.28.0
apacheCommonsCollections4=4.5.0
apacheCommonsPool=2.12.1
commonsIO=2.20.0
jacksonAnnotations=2.20
jacksonDatabind=2.20.0
jlibmodbus=1.2.9.11
kavroSchemaRegistryClient=8.0.1
kavroAvroSerializer=8.0.1
kafka=8.0.1-ce
springKafka=3.3.10
micrometer=1.15.4
avro=1.12.0
apacheCommonsText=1.14.0
apacheCommonsLang=3.19.0
rabbitMQ=5.26.0

# testing libs
assertj=3.27.6
junit5=6.0.0
# Explicitly defining the version of junitPlatformVersion was necessary to have a successful build
# with junit5 5.12.2 (see issue #8169)
junitPlatformVersion=6.0.0
karate=1.5.1
reactor=3.7.11

# code generators
swagger=2.4.48
swaggerUI=5.28.1

systemProp.sonar.gradle.skipCompile=true
