
org.gradle.jvmargs=-XX:MaxMetaspaceSize=512m -Xmx2g
# spring libs
springBoot=3.5.4
springRetry=2.0.4
springWebflux=6.2.9
springSecurity=6.5.2

# logging libs
slf4j=2.0.17

# utilities & tools
apacheCommonsCompress=1.28.0
apacheCommonsCollections4=4.5.0
apacheCommonsPool=2.12.1
commonsIO=2.20.0
jacksonAnnotations=2.19.2
jacksonDatabind=2.19.2
jlibmodbus=1.2.9.11
kavroSchemaRegistryClient=8.0.0
kavroAvroSerializer=8.0.0
kafka=8.0.0-ce
springKafka=3.3.8
micrometer=1.15.3
avro=1.12.0
apacheCommonsText=1.14.0
apacheCommonsLang=3.18.0
rabbitMQ=5.26.0

# testing libs
assertj=3.27.4
junit5=5.13.4
# Explicitly defining the version of junitPlatformVersion was necessary to have a successful build
# with junit5 5.12.2 (see issue #8169)
junitPlatformVersion=1.13.4
karate=1.5.1
reactor=3.7.9

# code generators
swagger=2.4.46
swaggerUI=5.27.1

systemProp.sonar.gradle.skipCompile=true
