dependencyResolutionManagement {

    repositories {
        mavenCentral()
        maven { url = "https://repo1.maven.org/maven2" }
        maven { url = "https://packages.confluent.io/maven/" } // needed for kafka 
        maven { url = "https://plugins.gradle.org/m2/" }
        maven { url = "https://maven.google.com/" } // needed for transitive dependencies jlibmodbus : com.google.android.things:androidthings:1.0
    }
}

rootProject.name = 'operator-fabric'

include 'backend:java-common'
include 'backend:test-utilities'
include 'backend:businessconfig'
include 'backend:cards-publication'
include 'backend:cards-consultation'
include 'backend:users'
include 'backend:external-devices'
include 'backend:cards-external-diffusion'
include 'backend:cards-reminder'
include 'backend:node-common'
include 'backend:supervisor'
include 'backend:rabbitmq'
include 'ui:main'
include 'tests:externalApp'
include 'tests:api:karate'
include 'tests:api:karate:kafka:java-client'
include 'tests:cypress'
include 'tests:gatling'
include 'tests:dummyModbusDevice'
include 'cli'
include 'docs:api'


