dependencyResolutionManagement {

    repositories {
        mavenCentral()
        maven { url = "https://repo1.maven.org/maven2" }
        maven { url = "https://packages.confluent.io/maven/" } // needed for kafka 
        maven { url = "https://plugins.gradle.org/m2/" }
        maven { url = "https://maven.google.com/" } // needed for tranisitive dependencies jlibmodbus : com.google.android.things:androidthings:1.0
    }
}

rootProject.name = 'operator-fabric'

include 'tools:spring:spring-test-utilities'
include 'tools:generic:test-utilities'
include 'services:common'
include 'services:businessconfig'
include 'services:cards-publication'
include 'services:cards-consultation'
include 'services:users'
include 'services:external-devices'
include 'node-services:cards-external-diffusion'
include 'node-services:cards-reminder'
include 'node-services:common'
include 'node-services:supervisor'
include 'rabbitmq'
include 'ui:main'
include 'externalApp'
include 'karateTests'
include 'kafkaJavaClient'
include 'cypressTests'
include 'gatlingTests'
include 'dummyModbusDevice'
include 'cli'
include 'openApiDoc'

project(':services:common').name = 'common-service'
project(':services:businessconfig').name = 'businessconfig-service'
project(':services:users').name = 'users-service'
project(':services:cards-publication').name = 'cards-publication-service'
project(':services:cards-consultation').name = 'cards-consultation-service'
project(':services:external-devices').name = 'external-devices-service'
project(':node-services:cards-external-diffusion').name = 'cards-external-diffusion-service'
project(':node-services:cards-reminder').name = 'cards-reminder'
project(':node-services:common').name = 'node-common'
project(':node-services:supervisor').name = 'supervisor'
project(':rabbitmq').name = 'rabbitmq'
project(':ui:main').name = 'web-ui'
project(':externalApp').projectDir = file('src/test/externalApp')
project(':karateTests').projectDir = file('src/test/api/karate')
project(':kafkaJavaClient').projectDir = file('src/test/api/karate/kafka/java-client')
project(':cypressTests').projectDir = file('src/test/cypress')
project(':gatlingTests').projectDir = file('src/test/gatling')
project(':dummyModbusDevice').projectDir = file('src/test/dummyModbusDevice')
project(':cli').name = 'cli'
project(':openApiDoc').projectDir = file('src/docs/api')

//we check if the modules have gradle configuration files
rootProject.children.each { project ->
    project.buildFileName = "${project.name}.gradle"
    assert project.projectDir.isDirectory()
    assert project.buildFile.exists()
    assert project.buildFile.isFile()
}

