// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

== Technical overview

See link:../api/#__Models[the model section of the swagger generated 
documentation] for data layout

[[resource-serving]]
=== Resource serving

[[css]]
==== CSS

CSS 3 style sheet are supported, they allow custom styling of card template
detail all css selector must be prefixed by the `.detail.template` parent
selector

[[internationalization]]
==== Internationalization

Internationalization (i18n) files are json file (JavaScript Object Notation).
One file must be defined by module supported language. See 
link:../api/#__Models[the model section of the swagger
generated documentation] for data layout.

Sample json i18n file

....
{ "emergency": 
  {
    "message": "Emergency situation happened on {{date}}. Cause : {{cause}}."
    "module":
      {
        "name": "Emergency Module",
        "description": "The emergency module managed ermergencies"
      }
  }
}
....

i18n messages may include parameters, these parameters are framed with double
curly braces.

The bundled json files name must conform to the following pattern : [lang].json

ex:

....
fr.json
en.json
de.json
....

[[media-notification-sounds]]
==== Media (notification sounds)

Supported media files type : * ogg * wav * mp3

Due to web nature of Operator Fabric, we encourage business modules provider to
favor the lightest file formats (ogg,mp3, ...)

[[templates]]
==== Templates

Templates are https://handlebarsjs.com/[Handlebars] template files. Templates
are fuelled with a scope structure composed of

 * a *card* property (See link:../api/#__Models[card data model] for more information)
 * a *userContext* :
   ** *login*: user login
   ** *token*: user jwt token
   ** *firstName*: user first name
   ** *lastName*: user last name

In addition to Handlebars basic syntax and helpers, Operator Fabric defines the
following helpers :

[[numberformat]]
===== numberFormat

formats a number parameter using
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Nu
mberFormat[Intl.NumberFormat].
The locale used is the current user selected one, and options are passed as hash
parameters (https://handlebarsjs.com/[see Handlebars doc Literals section]).

....
{{numberFormat card.data.price style="currency" currency="EUR"}}
....

[[dateformat]]
===== dateFormat

formats the submitted parameters (millisecond since epoch) using
https://momentjs.com/[mement.format]. The locale used is the current user
selected one, the format is "format" hash parameter
(https://handlebarsjs.com/[see Handlebars doc Literals section]).

....
{{dateFormat card.data.birthday format="MMMM Do YYYY, h:mm:ss a"}}
....

[[slice]]
===== slice

extracts a sub array from ann array

example:

....
<!--
{"array": ["foo","bar","baz"]}
-->
<ul>
{{#each (slice array 0 2)}}
  <li>{{this}}</li>
{{/each}}
</ul>
....

outputs:

....
<ul>
  <li>foo</li>
  <li>bar</li>
</ul>
....

and

....
<!--
{"array": ["foo","bar","baz"]}
-->
<ul>
{{#each (slice array 1)}}
  <li>{{this}}</li>
{{/each}}
</ul>
....

outputs:

....
<ul>
  <li>bar</li>
  <li>baz</li>
</ul>
....

[[now]]
===== now

outputs the current date in millisecond from epoch. The date is computed from
application internal time service and thus may be different from the date that
one can compute from javascript api which relies on the browsers' system time.

NB: Due to Handlebars limitation you must provide at least one argument to
helpers otherwise, Handlebars will confuse a helper and a variable. In the
bellow example, we simply pass an empty string.

example:

....
<div>{{now ""}}</div>
<br>
<div>{{dateFormat (now "") format="MMMM Do YYYY, h:mm:ss a"}}</div>
....

outputs

....
<div>1551454795179</div>
<br>
<div>mars 1er 2019, 4:39:55 pm</div>
....

for a local set to `FR_fr`

[[preservespace]]
===== preserveSpace

preserves space in parameter string to avoid html standard space trimming.

....
{{preserveSpace card.data.businessId}}
....

[[bool]]
===== bool

returns a boolean result value on an arithmetical operation (including object
equality) or boolean operation.

Arguments: - v1: left value operand - op: operator (string value) - v2: right
value operand

arithmetical operators:

 - ==
 - ===
 - !=
 - !==
 - <
 - <=
 - >
 - >=

boolean operators:

- &&
- ||

examples:

....
{{#if (bool v1 '<' v2)}}
  v1 is strictly lower than v2
{{else}}
 V2 is lower or equal to v1
{{/if}}
....

[[math]]
===== math

returns the result of a mathematical operation.

arguments:

- v1: left value operand
- op: operator (string value)
- v2: right value operand

arithmetical operators:

* +
* -
* *
* /
* %

example:

....
{{math 1 '+' 2}}
....

[[split]]
===== split

splits a string into an array based on a split string.

example:

....
<ul>
{{#each (split 'my.example.string' '.')}}
  <li>{{this}}</li>
{{/each}}
</ul>
....

outputs

....
<ul>
  <li>my</li>
  <li>example</li>
  <li>string</li>
</ul>
....

[[cardaction]]
===== action

outputs a card action button whose card action id is the concatenation of an
arbitrary number of helper arguments

....
{{{action "PREREQUISITE_" id}}}
....

[[svg]]
===== svg

outputs a svg tag with lazy loading, and missing image replacement message. The
image url is the concatenation of an arbitrary number of helper arguments

....
{{{svg baseUri scheduledOpId "/" substation "/before/" 
computationPhaseOrdinal}}}
....

[[i18n]]
===== i18n

outputs a i18n result from a key and some parameters. There are two ways of
configuration :

* Pass an object as sole argument. The object must contain a key field (string)
and an optional parameter field (map of parameterKey => value)
+
....
{{i18n card.data.i18nTitle}}
....
* Pass a string key as sole argument and use hash parameters
(https://handlebarsjs.com/[see Handlebars doc Literals section]) for i18n string
parameters.

....
<!--
emergency.title=Emergency situation happened on {{date}}. Cause : {{cause}}.
-->
{{i18n "emergency.title" date="2018-06-14" cause="Broken Cofee Machine"}}
....

outputs

....
Emergency situation happened on 2018-06-14. Cause : Broken Cofee Machine
....

[[sort]]
===== sort

sorts an array or some object's properties (first argument) using an optional
field name (second argument) to sort the collection on this fields natural
order.

If there is no field argument provided :

* for an array, the original order of the array is kept ;
* for an object, the structure is sorted by the object field name.

....
<!--
users :

{"john": { "firstName": "John", "lastName": "Cleese"},
"graham": { "firstName": "Graham", "lastName": "Chapman"},
"terry": { "firstName": "Terry", "lastName": "Gilliam"},
"eric": { "firstName": "Eric", "lastName": "Idle"},
"terry": { "firstName": "Terry", "lastName": "Jones"},
"michael": { "firstName": "Michael", "lastName": "Palin"},
-->

<ul>
{{#each (sort users)}}
    <li>{{this.firstName}} {{this.lastName}}</li>
{{/each}}
</ul>
....

outputs :

....
<ul>
  <li>Eric Idle</li>
  <li>Graham Chapman</li>
  <li>John Cleese</li>
  <li>Michael Pallin</li>
  <li>Terry Gilliam</li>
  <li>Terry Jones</li>
</ul>
....

and

....
<ul>
{{#each (sort users "lastName")}}
    <li>{{this.firstName}} {{this.lastName</li>
{{/each}}
</ul>
....

outputs :

....
<ul>
  <li>Graham Chapman</li>
  <li>John Cleese</li>
  <li>Terry Gilliam</li>
  <li>Eric Idle</li>
  <li>Terry Jones</li>
  <li>Michael Pallin</li>
</ul>
....
