// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

[#TroubleShooting]
== Troubleshooting

=== My bundle is not loaded

The server send a `+{"status":"BAD_REQUEST","message":"unable to open submitted 
file","errors":["Error detected parsing the header"]}+`, despite correct http 
headers.

The uploaded bundle is corrupted. Test your bundle in a terminal (Linux 
solution).

Example for a bundle archive named `MyBundleToTest.tar.gz` giving the
mentioned error when uploaded :
....
tar -tzf MyBundleToTest.tar.gz >/dev/null
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
....

==== Solution
Extract content if possible and compress it to a correct compressed archive 
format.

=== I can't upload my bundle

The server responds with a message like the following:
`+{"status":"BAD_REQUEST","message":"unable to open submitted 
file","errors":["Input is not in the .gz format"]}+`

The bundle has been compressed using an unmanaged format. 

==== Format verification 

===== Linux solution

Command line example to verify the format of a bundle archive named 
`MyBundleToTest.tar.gz`(which gives the mentioned error when uploaded):
....
 tar -tzf MyBundleToTest.tar.gz >/dev/null
....

which should return in such case the following messages:

....
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
....

==== Solution

Use `tar.gz` format for the archive compression. Shell command is `tar -czvf 
MyBundleToTest.tar.gz config.json template/ css/` for a bundle containing 
templates and css files.

=== My bundle is rejected due to internal structure

The server sends `+{"status":"BAD_REQUEST","message":"Incorrect inner file 
structure","errors":["$OPERATOR_FABRIC_INSTANCE_PATH/d91ba68c-de6b-4635-a8e8-b58
fff77dfd2/config.json (Aucun fichier ou dossier de ce type)"]}+`

Where `$OPERATOR_FABRIC_INSTANCE_PATH` is the folder where thirds files are 
stored server side.

==== Reason
The internal file structure of your bundle is incorrect. `config.json` file and 
folders need to be at the first level.

==== Solution

Add or organize the files and folders of the bundle to fit the Third bundle 
requirements.

=== No template display 

The server send 404 for requested template with a response like
`+{"status":"NOT_FOUND","message":"The specified resource does not 
exist","errors":["$OPERATOR_FABRIC_INSTANCE_PATH/thirds-storage/BUNDLE_TEST/1/te
mplate/fr/template1.handlebars (Aucun fichier ou dossier de ce type)"]}+`

==== Verification 

The previous server response is return for a request like: 
`+http://localhost:2002/thirds/BUNDLE_TEST/templates/template1?locale=fr&version
=1+`

The bundle is lacking localized folder and doesn't contain the requested 
localization.

If you have access to the `card-publication` micro service source code you
should list the content of 
`$CARDS_PUBLICATION_PROJECT/build/docker-volume/third-storage`

==== Solution

Either request another l10n or add the requested one to the bundle and 
re-upload it.


=== My template is not used.

It need to be declared in the config.json of the bundle.

==== Solution

Add or verify the name of the templates declared in the `config.json` file of 
the bundle.

=== My value is not displayed in the detail template

There are several possibilities:

- the path of the data used in the template is incorrect;
- number of pair of `{` and `}` has to follow those rules: 
	** with no helper the good number is only 2 pairs;
	** with OperatorFabric helpers it's 3 pairs of them.
