// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


= Thirds Business service

Operator Fabric Thirds Business service is a Spring MVC application
bootstrapped using SpringBoot.

In our spring micro service architecture this service depends on Eureka
Registry.

== Mandatory configuration, Profiles and default properties

The service has no mandatory configuration beside global configuration and
usual bootstrap configuration.

For other configuration see:

* {springboot_doc}/reference/htmlsingle/[Spring Boot documentation].
* {spring_doc}spring-framework-reference/web.html#mvc[Spring MVC documentation].

=== Service specific properties

|===
|name|default|mandatory?|Description

|operatorfabric.thirds.storage.path|null|no|File path to data storage folder

|===

=== default properties

Note that you must provide a bootstrap file with a convenient registry configuration

_bootstrap.yml_
```
include::../../main/resources/bootstrap.yml[]
```

_bootstrap-docker.yml_
```
include::../../main/resources/bootstrap-docker.yml[]
```

_bootstrap-dev.yml_
```
include::../../main/resources/bootstrap-dev.yml[]
```

The bootstrap-docker.yml file is a replacement bootstrap file we use for our
docker images configuration.

The bootstrap-dev.yml file is a replacement bootstrap file we use for our
development environment

The above embedded configurations are the basic settings of the application:

* it sets its service name
* it sets the configuration name to use (which configuration file to retrieve)
* it must set the registry service (example in bootstrap-docker.yml)

=== Sample development configuration

```
include::../../../../../infra/config/src/main/docker/volume/dev-configurations/thirds.yml[]
```

=== Sample docker image configuration

```
include::../../../../../infra/config/src/main/docker/volume/docker-configurations/thirds.yml[]
```

== Specifying external configuration properties when launching a jar file

See {springboot_doc}/reference/htmlsingle/#boot-features-external-config-application-property-files[Application Property Files]
on how to setup an external spring properties or yml file.

See {springboot_doc}/reference/htmlsingle/#howto-set-active-spring-profiles[Set the Active Spring Profiles] for specifying alternate profile.


== Specifying configuration properties when launching a docker image

Our docker image expects optional property file to be stored in the container
/service-config folder. You can bind so docker volume to this path to make
properties or yml available.

At time of writing, you cannot specify an alternate profile at runThirds.
The default profiles activated are docker and native.

=== Available environment variables for docker image

* REGISTRY_HOST: Registry service host
* REGISTRY_PORT: Registry service port
* JAVA_OPTIONS: Additional java options

== Specifying configuration properties when launching on Kubernetes

In progress

=== Available environment variables when launching on Kubernetes

* REGISTRY_HOST: Registry service host
* REGISTRY_PORT: Registry service port
* JAVA_OPTIONS: Additional java options
