// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

== Users and Groups

User service manager users and groups.

=== Users

Users are the individuals and mainly physical person who can log in OperatorFabric.

The access to this service has to be authorized, in the `OAuth2` service used by the current `OperatorFabric` instance, at least to access User information and to manage Users. The membership of groups is stored in the user information.

==== Automation creation users

In case of an user does exist in a provided authentication service but he does not exist in the `OperatorFabric` instance, when he is authenticated and connected 
for the first time in the `OperatorFabric` instance, the user is automatically created in the system with no attached groups. 
The administration of the groups is dealt by the administrator manually. More details about automation creation user 
<<../user_guide/index#_operator_fabric_specific_configuration,[here]>> 

=== Groups

The notion of group is loose and can be used to simulate role in `OperatorFabric`. Groups are used to send cards to several users without name them specifically. The information about membership to a group is stored in the user information. The rules used to send cards are describe in the link:https://opfab.github.io/projects/services/core/cards-publication/1.0.0.RELEASE/reference/#_card_recipients[Card Publication Service].

==== Alternative way to manage groups

The standard way to handle groups in `OperatorFabric` instance is dealt on the user information. 
There is an alternative way to manage groups through the authentication token, the groups are defined by the administrator of the authentication service. 
<<../user_guide/index#_operator_fabric_specific_configuration,[here]>>  for more details to use this feature.







t
