
operatorfabric:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  mongodb:
    database: "operator-fabric"
    uri: "mongodb://root:password@localhost:27017/operator-fabric?authSource=admin"
  servicesUrls:
    authToken: "http://127.0.0.1:2002/auth/token"
    users: "http://127.0.0.1:2103"
    cardsPublication: "http://127.0.0.1:2102"
  internalAccount:
    login: opfab
    password: test
  logConfig:
    logFolder: "logs/"
    logFile: "%DATE%.log"
    logLevel: "info"
  cardsReminder:
    adminPort : 2107
    activeOnStartup : true
    checkPeriodInSeconds : 5

