opfab: 
  cardsPublicationUrl: "http://127.0.0.1:2102"
  usersUrl: "http://127.0.0.1:2103"
  getTokenUrl: "http://127.0.0.1:2002/auth/token"

operatorfabric:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  mongodb:
    database: "operator-fabric"
    uri: "mongodb://root:password@localhost:27017/operator-fabric?authSource=admin"
  logConfig:
    logFolder: "logs/"
    logFile: "%DATE%.log"
    logLevel: "info"
  cardsReminder:
    adminPort : 2107
    activeOnStartup : true
    checkPeriodInSeconds : 5
    opfab:
      login: "opfab_internal_account"
      password: "test"
