
operatorfabric:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:89/auth/realms/dev/protocol/openid-connect/certs
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  mongodb:
    database: "operator-fabric"
    uri: "mongodb://root:password@localhost:27017/operator-fabric?authSource=admin"
  servicesUrls:
    authToken: "http://127.0.0.1:2002/auth/token"
    users: "http://127.0.0.1:2103"
    cardsPublication: "http://127.0.0.1:2102"
  internalAccount:
    login: opfab
    password: test
  logConfig:
    logFolder: "logs/"
    logFile: "%DATE%.log"
    logLevel: "error" #set to error to avoid being polluted by logs in the CI/CD during unit tests
  cardsReminder:
    adminPort : 2107
    activeOnStartup : true
    checkPeriodInSeconds : 5

