opfab: 
  getTokenUrl: "http://web-ui/auth/token"

operatorfabric:
  rabbitmq:
    host: "rabbitmq"
    port: 5672
    username: "guest"
    password: "guest"
  mongodb:
    database: "operator-fabric"
  servicesUrls:
    users: "http://users:2103"
    cardsPublication: "http://cards-publication:2102"
  logConfig:
    logLevel: "info"

  cardsReminder:
    adminPort : 2107
    activeOnStartup : true
    checkPeriodInSeconds : 5
    opfab:
      login: "opfab_internal_account"
      password: "test"
