// Copyright (c) 2021-2026 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0


= Process monitoring

NOTE: This feature is experimental

The process monitoring screen has the following features :

- it is a realtime view of processes based on current cards received by the user
(i.e. the last version of cards visible by the user)
- not all the cards are visible, it depends on the business process they are part of. For a card to be visible on
this screen, the parameter `uiVisibility.processmonitoring` must be set to `true` in the `config.json` file of its
process.

The columns displayed on this screen can be configured. To do that, you have to define a JSON file and load the file by
sending an HTTP POST request to the `/processmonitoring` API of businessconfig service or using CLI command
`opfab process-monitoring load <file>`.

Here is an example of processMonitoring configuration file:
```
{
  "fields": [
    { "field": "startDate", "type": "date", "colName": "Start Date", "size": 200},
    { "field": "titleTranslated", "colName": "Title", "size": 250},
    { "field": "entityRecipients", "type": "array", "colName": "Entity Recipients", "size": 400},
    { "field": "data.stateName", "colName": "My field", "size": 300},
    { "field": "summaryTranslated", "colName": "Summary", "size": 250},
    { "field": "data.error", "colName": "My second field", "size": 100, "defaultVisibility": false}
  ],
  "fieldsForProcesses": [
    {
      "process": "process1",
      "fields" : [
        { "field": "startDate", "type": "date", "colName": "Start Date", "size": 200},
        { "field": "titleTranslated", "colName": "Title", "size": 250},
        { "field": "entityRecipients", "type": "array", "colName": "Entity Recipients", "size": 400}
      ]
    },
    {
      "process": "process2",
      "fields" : [
        { "field": "startDate", "type": "date", "colName": "Start Date", "size": 200},
        { "field": "endDate", "type": "date", "colName": "End Date", "size": 200},
        { "field": "titleTranslated", "colName": "Title", "size": 250},
        { "field": "entityRecipients", "type": "array", "colName": "Entity Recipients", "size": 400, "defaultVisibility":  false}
      ]
    }
  ],
  "filters": {
    "tags": [
        {
          "label": "Label for tag 1",
          "value": "tag1"
        },
        {
          "label": "Label for tag 2",
          "value": "tag2"
        }
      ],
    "pageSize": 10
  }
}
```

The `fields` field in the process monitoring configuration file defines the list of the fields you want to see in the
array.

You also have the possibility to define the columns displayed per process. To do that, you have to configure the field
`fieldsForProcesses`.

If more than one process is selected by the user or if a process has no configuration, the columns displayed will be
those of the default config (`fields`).
Depending on the permissions of the groups to which the user is attached, he can also see the cards he is not the
recipient of.

In the process monitoring config file it is possible to configure the page size `filters.pageSize` and the list of
available tags used in the UI to filter the results `filters.tags`.

If the geographical map view is enabled ('feed.geomap.enableMap' set to 'true' in web-ui.json) it is possible to view
the cards on the map by checking the "View Results on a Geographical Map" checkbox.


Here is the description of the fields :

- "field": the name of the field in the card (or in the database) you want to display
- "type": field type to be used for formatting. Possible values : `date`, `array`. Set to `date` if you want to display
a date/time field, set it to `array` to display an array as a comma separated list. Set to `set` if you want to have a
custom filter for a column. The possible values for the custom filter must be set with the field `possibleValues`.
- "colName": name of the column on the UI
- "size": size of the column on the UI (number of pixels)
- "defaultVisibility": Indicates whether the field will be displayed, before the user interacts with the column for the
first time.
- "possibleValues": List of values to display in the custom filter of a column. Must be used with field `type` set to
`set`.

