// Copyright (c) 2018-2026 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0


= UI Customization

== UI configuration

To customize the UI, declare specific parameters in the `web-ui.json` file as link:../deployment/index.html#ui_properties[listed here]

[[menu_entries]]
== Menu Entries

A json description is used :

* To manage the visibility of core OperatorFabric menus (feed, archives, etc.)
* To declare specific business menus to be displayed in the navigation bar of OperatorFabric

To update the menu, you can upload a file containing the json data via a POST HTTP request to the dedicated API endpoint
as described in
ifdef::single-page-doc[link:../api/index.html#tag/configurations/operation/uploadUIMenu[UI Menu API documentation]]
ifndef::single-page-doc[link:/documentation/current/api/index.html#tag/configurations/operation/uploadUIMenu[UI Menu API documentation]]

You can do it using the cli (command line interface), for example: `opfab ui-menu load <uiMenuFileName>`

This file contains 4 fields :

* `navigationBar` : contains the navigation bar mixing core menus and custom menus
* `topRightIconMenus` : contains only the two menu icons `agenda` and `usercard` on the top right of the screen
* `topRightMenus` : contains core menus you want to see when you click the user, on the top right of the screen
* `locales` : contains the translations for the custom menus
* `showDropdownMenuEvenIfOnlyOneEntry` : indicates if the name of the menu and a dropdown menu are displayed if it
contains only one submenu entry. If false, the submenu entry will be displayed directly in the navigation bar. This field is
optional, the default value is false.


[[core_menu_config]]
=== Core menus

Core menus are objects containing the following fields :

* `opfabCoreMenuId`: Id of the core menu (string)
* `visible`: Whether this menu should be visible for this OperatorFabric instance (boolean). This field is not
needed in `navigationBar` field but it is needed in `topRightIconMenus` and `topRightMenus`.
* `showOnlyForGroups` : List of groups for which this menu should be visible (array, optional)

.Menu visibility summary
* For a core menu with `"visible": true`:
** If `showOnlyForGroups` is not present, null or an empty array : the menu is visible for all users.
** If `showOnlyForGroups` is present and with a non-empty array as a value: menu is visible only for users from the
listed groups.


.List of core menus and corresponding ids
|===
|Location of menu |Menu |Id

.4+|Navigation bar

|Feed
|feed

|Archives
|archives


|Logging
|logging

.2+|Navigation bar (icon)

|User card
|usercard

|Calendar
|calendar

.11+|Top-right menu

|Administration
|admin

|External devices configuration
|externaldevicesconfiguration

|Real time users
|realtimeusers

|Settings
|settings

|Activity area
|activityarea

|Notification Configuration
|feedconfiguration

|User action logs
|useractionlogs

|About
|about

|Night/Day toggle
|nightdaymode

|Change password
|changepassword

|Logout
|logout

|===

NOTE: If you decide not to make the night/day toggle visible (globally or for certain users), you should consider
setting the `settings.styleWhenNightDayModeDesactivated` property in `web-ui.json` to specify which mode should be used.

=== Custom business menus

A menu can target directly a link or give access to several sub-menus when clicked.
Those sub-menus can target a link or an opfab core menu.
A targeted link can be open in an iframe or in a new tab.

In case of a single menu, the navigation bar displays the l10n of the `label` of the entry menu.
In this case, the `label` declared at the root level of the menu is useless and can be omitted (see example below).

A single menu or a menu with sub-menus has at least attributes named `id` and `entries`.
The `entries` attribute is an array of `menu entry`. It is possible to restrict the visibility of one menu entry
to one or more user groups by setting the `showOnlyForGroups` parameter.
Note that menus with sub-menus need a `label` declaring an i18n key.

A menu entry can target a core menu id or a link. If it targets a link, it must declare the attributes listed below:

- `customMenuId`: identifier of the entry menu in the UI;
- `url`: url opening a new page in a tab in the browser;
- `label`: it's an i18n key used to l10n the entry in the UI.
- `linkType`: Defines how to display business menu links in the navigation bar and how to open them. Possible values:
** `TAB`: displays only a text link. Clicking it opens the link in a new tab.
** `IFRAME`: displays only a text link. Clicking it opens the link in an iframe in the main content zone below the navigation bar.
** `BOTH`: default value. Displays a text link plus a little arrow icon. Clicking the text link opens the link in an iframe while clicking the icon opens in a new tab.
**
- `showOnlyForGroups`: Defines the list of user groups entitled to see the menu entry, if not defined or empty it will be visible to every user.

In the following example, the configuration file declares two additional business menus.
The first has only one entry, which targets a link. The second business menu has three entries, one which targets the
core menu `logging` and two others which target links.
The sample also contains the 2 top right icons (`usercard` and `calendar`), the composition of the top right menu and
the i18n translations in English and French.

.Example
[source, json]
----
{
  "navigationBar": [
    {
      "opfabCoreMenuId": "feed"
    },
    {
      "opfabCoreMenuId": "archives"
    },
    {
      "id": "menu1",
      "entries": [
        {
          "customMenuId": "uid_test_0",
          "url": "https://opfab.github.io/",
          "label": "entry.single",
          "linkType": "BOTH"
        }
      ]
    },
    {
      "id": "menu2",
      "label": "title.multi",
      "entries": [
        {
          "opfabCoreMenuId": "logging"
        },
        {
          "customMenuId": "uid_test_1",
          "url": "https://opfab.github.io/",
          "label": "entry.entry1",
          "linkType": "BOTH",
          "showOnlyForGroups": "Maintainer,Dispatcher"
        },
        {
          "customMenuId": "uid_test_2",
          "url": "https://www.wikipedia.org/",
          "label": "entry.entry2",
          "linkType": "BOTH",
          "showOnlyForGroups": "Planner"
        }
      ]
    }
  ],
  "topRightIconMenus": [
    {
      "opfabCoreMenuId": "usercard",
      "visible": true
    },
    {
      "opfabCoreMenuId": "calendar",
      "visible": true
    }
  ],
  "topRightMenus": [
    {
      "opfabCoreMenuId": "admin",
      "visible": true,
      "showOnlyForGroups": ["ADMIN"]
    },
    {
      "opfabCoreMenuId": "settings",
      "visible": true
    },
    {
      "opfabCoreMenuId": "activityarea",
      "visible": true
    },
    {
      "opfabCoreMenuId": "feedconfiguration",
      "visible": true
    },
    {
      "opfabCoreMenuId": "realtimeusers",
      "visible": true
    },
    {
      "opfabCoreMenuId": "externaldevicesconfiguration",
      "visible": true,
      "showOnlyForGroups": ["ADMIN"]
    },
    {
      "opfabCoreMenuId": "useractionlogs",
      "visible": true,
      "showOnlyForGroups": ["ADMIN", "Supervisor"]
    },
    {
      "opfabCoreMenuId": "nightdaymode",
      "visible": true
    },
    {
      "opfabCoreMenuId": "about",
      "visible": true
    },
    {
      "opfabCoreMenuId": "changepassword",
      "visible": true
    }, 
    {
      "opfabCoreMenuId": "logout",
      "visible": true
    }
  ],
  "locales": [
    {
      "language": "en",
      "i18n": {
        "entry": {
          "single": "Single menu entry",
          "entry1": "First menu entry",
          "entry2": "Second menu entry"
        },
        "title": {
          "multi": "Second menu"
        }
      }
    },
    {
      "language": "fr",
      "i18n": {
        "entry": {
          "single": "Premier élément",
          "entry1": "Premier élément",
          "entry2": "Deuxième élément"
        },
        "title": {
          "multi": "Deuxième menu"
        }
      }
    }
  ]
}
----

NOTE: For iframes opened from menu, the associated request uses an extra parameter containing the current theme information.
Named `opfab_theme`, this parameter has a value corresponding to the current theme: `DAY` or `NIGHT`. For example:
`http://mysite.com/index.htm?opfab_theme=NIGHT`. Switching theme will trigger reload of open iframes.


=== Custom screen menus

It is possible to add menus linked to custom screens of the application. See custom screen definition link:./single_page_doc.html#card_list_custom_screen[here]. To set up such a menu, it's important to give it a customMenuId and a customScreenId. See example below :

.Example
[source, json]
----
{
  "navigationBar": [
    {
      "opfabCoreMenuId": "feed"
    },
    {
      "id": "menu1",
      "entries": [
        {
            "customMenuId": "uid_test_0",
            "customScreenId": "testId",
            "label": "entry.custom"
        },
        {
          "customMenuId": "uid_test_1",
          "url": "https://opfab.github.io/",
          "label": "entry.single",
          "linkType": "BOTH"
        }
      ]
    }
  ],
  [...]
}
----

[[card_list_custom_screen]]
== Card List Custom Screen

You can define a custom screen containing a search header and a list of cards.

To do this, register the custom screen via a JavaScript script loaded on startup (To be loaded on startup, add your script to the `customJsToLoad` array in the `web-ui.json` file).

Here is an example of a custom screen registration:

----
const customScreenExample = {
    id: 'testId',
    name: 'testName',
    statesToExclude: [{processId: 'processId0', stateIds: ['stateId0', 'stateId1']}],
    headerFilters: ['PROCESS', 'TYPE_OF_STATE'],
    showAcknowledgmentButton: false,
    showBackButton: true,
    defaultSelectedTypeOfState: [
        'INPROGRESS',
        'FINISHED'
    ],
    includeOnlyCardsEmittedByCurrentUserEntities: false,
    excludeCardsEmittedByCurrentUserEntities: false,
    results: {
        columns: [
            {
                field: 'severity',
                cardField: 'severity',
                fieldType: 'SEVERITY',
            },
            {
                field: 'TIME',
                cardField: 'publishDate',
                fieldType: 'DATE_AND_TIME'
            },
            {
                fieldType: 'RESPONSE_FROM_MY_ENTITIES'
            },
            {
                fieldType: 'ACKNOWLEDGMENT'
            },
            {
                field: 'testField',
                headerName: 'TITLE',
                cardField: 'titleTranslated',
                fieldType: 'STRING',
                flex: 1
            },
            {
                field: 'testField2',
                headerName: 'SUMMARY',
                cardField: 'summaryTranslated',
                fieldType: 'STRING',
                flex: 2,
                showTooltips: true
            },
            {
                fieldType: 'TYPE_OF_STATE',
                headerName: 'STATUS'
            },
            {
                field: 'publisher',
                headerName: 'EMITTER',
                cardField: 'publisher',
                fieldType: 'PUBLISHER'
            },
            {
                field: 'urgency',
                headerName: 'URGENCY',
                fieldType: 'COLORED_CIRCLE',
                getValue: (card) => {
                    if (card.severity === 'ALARM') return {color: 'red', numericalValue: 20};
                    return {color: 'green', numericalValue: 10};
                },
                flex: 0.5
            },
            {
                headerName: 'ANSWERS',
                fieldType: 'RESPONSES',
                minWidth: 150, 
                flex: 2
            }
        ]
    }
}

opfab.businessconfig.registerCustomScreen(customScreenExample);
----

In this example, the custom screen is accessible via the URL `#/customscreen/testId`.

It is possible to : 

- exclude specific states from being display by adding them to the `statesToExclude` array. State ids are not unique and should be associated to their process id.
- include only cards emitted by the entities of the current user by setting the `includeOnlyCardsEmittedByCurrentUserEntities` field to `true`.The default value is `false`.
- exclude cards emitted by the entities of the current user by setting the `excludeCardsEmittedByCurrentUserEntities` field to `true`. The default value is `false`.

You can define the filters to be displayed in the header of the screen by adding them to the `headerFilters` array. The following filters are available: `PROCESS`, `TYPE_OF_STATE`, `READ_ACK`, `RESPONSE_FROM_MY_ENTITIES` and `RESPONSE_FROM_ALL_ENTITIES`.

You can define pre-selected values : 

- for the type of state multiselect filter by setting the field `defaultSelectedTypeOfState`. The possible values are `INPROGRESS`, `FINISHED`, `CANCELED`.
- for the read and ack multiselect filter by setting the field `defaultSelectedReadAndAck`. The possible values are `READ`, `NOT_READ`, `ACKNOWLEDGED`, `NOT_ACKNOWLEDGED`.

You can define the initial business period you want to display for each custom screen, using the field `initialBusinessPeriod`.
The possible values are:

- `FEED` (default value): the period is based on the feed period
- `FROM_TODAY_TO_YEAR_END`: the period is from now to the end of the year

For each field you want to display in the result table, define a column object. The following field types are available:

- `ACKNOWLEDGMENT`: Displays a blue check if the card has been acknowledged.
- `BUSINESS_PERIOD`: Displays the business period of the card on two lines
- `COLORED_CIRCLE`: Displays a colored circle. The value is to be defined with a custom method `getValue` that shall contain two fields:
  ** `color`: The color of the circle.
  ** `numericalValue`: The numerical value of the circle that will be used for sorting and filtering.
- `DATE_AND_TIME`: Displays the date and time formatted according to the user's locale.
- `HTML`: Renders the HTML contained in the `getValue` method.
- `INPUT`: Displays an input field. The value of the input field will be used for response cards if the custom screen has response buttons (see below).
- `NUMBER` : Displays a number.
- `NUMBER_ARRAY` : Displays an array of numbers based on a json array.
- `PERIOD_ARRAY` : Displays an array of period based on a json array of objects, each object containing `startDate` and `endDate` fields as epoch date or Date object.
- `PROCESS_NAME`: Displays the name of the card's process.
- `PUBLISHER`: Displays the publisher entity if the card is published by an entity, otherwise displays the user who published the card.
- `RESPONSES`: Displays the list of entities that must respond, with the color indicating the severity of the response if the entity has responded. It uses the `entitiesRequiredToRespond` field of the card. If this field is empty, it will use the `entitiesAllowedToRespond` field of the card.
- `RESPONSE_FROM_MY_ENTITIES`: Displays a blue arrow if one of the user's entity has responded to the card.
- `SEVERITY`: Displays the severity as a color rectangle.
- `STATE_NAME`: Displays the name of the card's state.
- `STRING`: Displays a string value.
- `TYPE_OF_STATE`: Displays the name of the type of state (`INPROGRESS`, `FINISHED`, `CANCELED`) with a corresponding color. The color is defined as follows:
  * `INPROGRESS`: orange
  * `FINISHED`: 
    ** orange if not all entities required to respond have responded
    ** red if one or more entities responded with a severity of `ALARM`
    ** green otherwise
  * `CANCELED`: red
  * none: grey

You can define the column header text using the `headerName` field.

`cardField` is the field of the card that will be displayed in the result. It is not used for the following field types: `COLORED_CIRCLE`, `SEVERITY`, `TYPE_OF_STATE`,`RESPONSES` and `RESPONSE_FROM_MY_ENTITIES`.

For `STRING` field type if the method `getValue` is defined, the value of the field will be the result of this method instead of the value of the cardField.

For `HTML` field type, the HTML tags need to be injected by the `getHTMLValue` method of the column. The value for sorting and filtering the column will be the content of the field `cardField` or the result of the `getValue` method if defined. For example:

```
{
    field: 'testField',
    headerName: 'TITLE',
    cardField: 'titleTranslated',
    fieldType: 'HTML',
    getHTMLValue: (card) => {
        const title = opfab.utils.escapeHtml(card.titleTranslated);
        return `<span style="color:red">${title}</span>`;
    }
}
```

Warning: Be cautious when using the `getHTMLValue` method, as it can lead to XSS (Cross-Site Scripting) vulnerabilities if you do not properly sanitize the input. Use `opfab.utils.escapeHtml` to sanitize the input before injecting it into the HTML.

=== Cell size

To better control cell size, you can use the following fields in the column definition:
- `flex`: Specifies the CSS flex property for the cell.
- `minWidth`: Defines the minimum width of the column in pixels.
- `multiLinesInCell`: Allows the cell to display multiple lines of text if set to `true`. The default value is `false`.

=== Tooltips

Sometimes columns are not wide enough to display all the content. In this case, you can enable tooltips for the column by setting the `showTooltips` field to `true` in the column definition.


=== Acknowledgment 

It is possible to define a custom screen with an acknowledgment button allowing the user to acknowledge multiple cards at once. This is possible by setting the `showAcknowledgmentButton` field to `true` in the custom screen object.

=== Back button

A back button can be displayed in the top-left corner of the screen by setting `showBackButton` to `true` (default is `false`). When clicked, it behaves like the browser's back button and navigates to the previous page.

=== Response buttons 

It is possible to define custom response buttons for the custom screen allowing the user to send multiple responses at once.

To do this, add a `responseButtons` array to the custom screen object. Each button object must contain the following fields:

- `id`: The button identifier.
- `label`: The button label.
- `getUserResponses`: a function that retrieves data for response cards.

The getUserResponses function takes two parameters: 

- an array of cards
- a map of responseInput indexed by card id. The responseInput is an object containing the response input fields and their values.

The method shall return an object containing the following fields:

- `valid`: A boolean indicating if the action is valid.
- `errorMsg`: An error message to display if the action is not valid.
- `responseCards`: An array of response cards to send, each containing a `data` field containing a response card data .

 

Here is an example of a custom screen configuration with response buttons:

----
const customScreenExample = {
        id: 'testId2',
        name: 'testName',
        responseOnlyAllowedForEntitiesRequiredToRespond: false,
        initialBusinessPeriod: 'FROM_TODAY_TO_YEAR_END',

        .....

        responseButtons: [
            {
                id: 'button1',
                label: 'ACCEPT PROPOSALS',
                getUserResponses: (cards, userInputs) => {
                    const responseCards = [];

                    cards.forEach((card) => {

                        const userInput = responsesData.get(card.id);
                        const comment = userInput?.comment ?? '';
                        const responseData = { "choice1": "on", "choice2": "on", "choice3": "on", "comment": comment }
                        responseCards.push({ data: responseData });
                    });
                    return { valid: true, errorMsg: '', responseCards: responseCards };
                }
            },
            {
                id: 'button2',
                label: 'REFUSE PROPOSALS',
                getUserResponses: (cards, userInputs) => {
                    const responseCards = [];
                    let hasAlwaysComment = true;
                    cards.forEach((card) => {
                        const userInput = responsesData.get(card.id);
                        const comment = userInput?.comment ?? '';
                        if (comment === '') {
                            hasAlwaysComment = false;
                        }
                        const responseData = { "comment": comment }
                        responseCards.push({ data: responseData });
                    });
                    if (!hasAlwaysComment) {
                        return { valid: false, errorMsg: 'Please fill in the comment field for all cards' };
                    }
                    return { valid: true, errorMsg: '', responseCards: responseCards };
                }
            }
        ]

----


==== Input fields 

The input fields are to be defined in the columns definition with fieldType set to `INPUT` , for example :  

----
{
    field: 'comment',
    headerName: 'Comment',
    fieldType: 'INPUT',
    flex: 1
}
----
If you want the input to be restricted to a certain number of characters, you can set the `maxInputLength` field in the column definition.


==== Select fields 

It is possible instead of using an input field to use a select field by setting the fieldType to `SELECT` and defining the options in the column definition, for example : 


----
{
    field: 'choice',
    headerName: 'Choice',
    fieldType: 'SELECT',
    possibleValues: [
        { value: 'on', label: 'Accept' },
        { value: 'off', label: 'Refuse' }
    ],
    allowNewOptionForSelect: true,
    flex: 1
}
----

The option `allowNewOptionForSelect` allows the user to enter a new value that is not in the list of possible values. If set to `false`, the user will only be able to select from the list of possible values.

If you want the input for new options to be restricted to a certain number of characters, you can set the `maxInputLength` field in the column definition.

==== Response restrictions

It is possible to restrict the possibility to respond to entities that are defined as required (field `entitiesRequiredToRespond` in the card). To do this, you need to set `responseOnlyAllowedForEntitiesRequiredToRespond` to `true` in the custom screen definition.

It is also possible to restrict the possibility to respond to certain process states. To do this, you need to set the `responsePossibleOnlyForProcessStates` field in the custom screen definition. This field is an array of objects containing the `process` and an array of `states` to include. For example:

----
responsePossibleOnlyForProcessStates: [
    {
        process: 'processId0',
        states: ['stateId0', 'stateId1']
    },
    {
        process: 'processId1',
        states: ['stateId2']
    }
]
----

If the `responsePossibleOnlyForProcessStates` field is not defined, the response will be possible for all process states (provided that the user is allowed to respond to the card).

=== Card data fields

It is possible to define data fields you want to display in the custom screen. To do this, you have to define the data
fields in the configuration file shared by all the services (for example `/config/docker/common.yml`), the variable is
`operatorfabric.customscreen.dataFields` and it must be a list of string values, for example :

----
operatorfabric:
  customscreen:
    dataFields: ["keywords", "nested.field"]
----

Then you have to add the fields in the `results.columns` field in the custom screen configuration file. For example :
----
                ...
                {
                    field: 'keywords',
                    headerName: 'keywords field',
                    cardField: 'data.keywords',
                    fieldType: 'STRING',
                    flex: 1
                },
                {
                    field: 'nestedField',
                    headerName: 'nested field',
                    cardField: 'data.nested.field',
                    fieldType: 'STRING',
                    flex: 1
                },
                ...
----

WARNING: Be cautious when adding too many data fields in the configuration files. If there are numerous cards with many data fields (or fields containing large amounts of data) in the service configuration file, it may slow down the application due to the volume of data to be loaded. The fields are loaded even if the user does not navigate to the custom screen.



=== Current user child card field 


It is possible to define a field in the custom screen that will display the field value of the child card of the current user if any.
To do this, you have to set the value `isFieldFromCurrentUserChildCard` to true in the column definition. For example :

----
                {
                    fieldType: 'INPUT',
                    field: 'comment',
                    cardField: 'data.comment',
                    isFieldFromCurrentUserChildCard: true,
                    headerName: 'COMMENT'
                }

----

WARNING: This feature is not yet taking into account the fact that the user may be member of several entities allowed to respond to the card. In this case the field will display the value of the first child card found.

=== Exporting responses by type and not responded

When exporting the data of a custom screen, you can add columns per type of response (severity), with the column name defined by configuration

To enable this, define a `responseSeverityColumnLabelsForExportFile` field in your custom screen JS definition:

----
responseSeverityColumnLabelsForExportFile: {
    COMPLIANT: "yes",
    ALARM: "no"
},
results: {
    columns: [
        // Only declare the visible columns for the UI, e.g.:
        { headerName: 'ANSWERS', fieldType: 'RESPONSES', flex: 2, minWidth: 400 }
        // Do NOT declare export-only columns here
    ]
}
----

For each configured severity, a column will be exported (but not shown in the UI) with the entities that responded with that severity.These columns are only present in the export, not in the UI.

=== User notification filter  


It is possible to see cards in custom screens even if cards are filtered by the user via the notification configuration screen. To do so, you can configure in the web-ui.json the list of processes/states for which the card should be visible even if it is filtered. The parameter to configure is `processStatesAlwaysLoaded` and the value is an array of process/state in the format "processName.stateName".

For example, if you want to see the cards of the state "state1" of the process "process1" even if the user has filtered the state, you can set the parameter as follows:

....
"processStatesAlwaysLoaded": [
    "process1.state1"
]
....



== Dashboard screen

The dashboard screen presents the number of cards per process and state. To the right of each state, bubbles display the number of visible cards by severity.

=== Declaring a dashboard

In OperatorFabric, a dashboard is declared as a custom screen with type `DASHBOARD`.

It must be defined in a JavaScript file loaded at application startup and registered using the `opfab.businessconfig.registerCustomScreen` method.

A dashboard requires at least the following fields:

- `id`: unique identifier of the dashboard
- `name`: name displayed in the UI
- `type`: must be set to `"DASHBOARD"`

.Minimal example
[source, javascript]
----
{
    const myDashboard = {
        id: "my-dashboard",
        name: "My Dashboard",
        type: "DASHBOARD"
    };

    opfab.businessconfig.registerCustomScreen(myDashboard);
}
----

=== Adding a dashboard to the menu

A dashboard registered via registerCustomScreen is not automatically displayed in the navigation bar.
To make it accessible to users, you must declare a corresponding menu entry in the UI menu configuration (uimenu.json).

Once your dashboard is declared, you need to create a menu entry that references it using its customScreenId.

Example :

If your dashboard is declared with:
----
id: "dashboard2"
----

You can add it to any existing menu, for example:

----
{
  "id": "menu2",
  "label": "title.multi",
  "entries": [
    {
      "customMenuId": "uid_test_6",
      "customScreenId": "dashboard2",
      "label": "entry.dashboard2"
    }
  ]
}
----

=== Loading the configuration

To apply the dashboard configuration, you need to:

1. Create a JavaScript file containing your dashboard definition
2. Register it using the `opfab.businessconfig.registerCustomScreen` method
3. Load this file at application startup

Then, declare this file in `web-ui.json` to load it at startup:

[source, json]
----
{
  "customJsToLoad": [
    "/externalJs/DashboardExample.js"
  ]
}
----

=== processList

This optional field allows you to restrict the dashboard to a specific subset of processes. When defined, only processes whose IDs are included in the list will be considered when building the visible process tiles. Processes not in the list are ignored, even if the user has receive rights for them.

When `processList` is absent or empty, all processes accessible to the user are displayed (default behaviour).

.Example restricting the dashboard to two processes
[source, json]
----
"processList": ["process1", "process2"]
----

=== initialBusinessPeriod

This optional field defines the initial business period applied when opening the dashboard.

It controls the default time window used to filter cards displayed in the dashboard and the computation of severity bubbles.

Possible values are:

- `FEED` (default): the business period is aligned with the feed configuration period.
- `FROM_TODAY_TO_YEAR_END`: the period starts at the current day (00:00) and ends at the end of the current year (23:59).

This setting affects:
- the initial filtering of cards displayed in the dashboard
- the computation of severity bubbles (only cards within the period are counted)

=== customTiles

Custom tiles can be added to a dashboard to provide access to custom screens.
They are configured in the dashboard JavaScript configuration object registered at application startup.

Each custom tile contains:

- a `title`: displayed as the tile title
- a list of `cells`: each cell defines a link to a custom screen

Each cell has this structure :

- `label`: text displayed in the cell
- `customScreenId`: identifier of the custom screen to open

.Example
[source, javascript]
----
{
    const dashboardExample = {
        id: "dashboard",
        name: "Dashboard",
        type: "DASHBOARD",
        customTiles: [
            {
                title: "My custom tile 1",
                cells: [
                    {
                        label: "Custom screen",
                        customScreenId: "testId"
                    },
                    {
                        label: "Custom screen 2",
                        customScreenId: "testId2"
                    }
                ]
            },
            {
                title: "My custom tile 2",
                cells: [
                    {
                        label: "Custom screen",
                        customScreenId: "testId"
                    }
                ]
            }
        ]
    };

    opfab.businessconfig.registerCustomScreen(dashboardExample);
}
----

Clicking on the title of a custom tile does not trigger any navigation. Navigation is only available through the cells, which open the associated custom screens.

The bubbles with the number of cards per severity are still displayed on the dashboard tiles, but they take into account the list of cards that will be displayed in the custom screen linked to the cell instead of the total number of cards of the process/state.


== Customizing browser notification sounds

The sounds used by default by the browser to signal a card of a given severity
can be found under `frontend/src/assets/sounds` in the core repository and are packaged in the `web-ui` docker image.

To customize these sounds, you can put the files in the current directory and mount that directory as a volume for
the web-ui container:

.Under web-ui.volumes, add:
[source,yaml]
```
- "./custom-sounds:/usr/share/nginx/html/assets/sounds"
```

NOTE: When testing, if the sounds seem not to be taken into account try clearing your browser's cache.

IMPORTANT: The name of the file needs to match the existing file (for example `alarm.mp3`).
