// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

:imagesdir: ../images

= Documentation Guidelines

The aim of this section is to explain how the documentation is currently organized and to give a few guidelines on how
it should be written.

== Structure

All the sources for the AsciiDoc documentation published on our link:https://opfab.github.io/[website] are found under
the link:https://github.com/opfab/operatorfabric-core/tree/master/src/docs/asciidoc[src/docs/asciidoc] folder in the
operatorfabric-core repository.

Its is organized into several folders (architecture documentation, deployment documentation, etc.). Each of these
folders represent a document and contain an *index.adoc* file, optionally referencing other adoc files (to break it
down into sections).

In addition, an *images* folder contains images for all documents.

The table below gives a short summary of the content of each document as well as advice on which ones you should focus
on depending on your profile.

[horizontal]
Contributor:: A developer who contributes (or wishes to) to the OperatorFabric project
Developer:: A developer working on an application using OperatorFabric or a third-party application posting content to
an OperatorFabric instance
Admin:: Someone who is in charge of deploying and maintaining OperatorFabric in production as part of an integrated
solution
Product Owner:: Project managers, anyone interested in using OperatorFabric for their business requirements.

[caption=,cols="1,4,4*^1", options="header"]
.Documentation Structure and Intended Readers
|===
|Folder
|Content
|Contributor
|Developer
|Admin
|Product Owner

|architecture
|*Architecture documentation*

Describes the business objects and concepts handled by OperatorFabric as well as the microservices architecture
behind it.
|Yes
|Yes
|Yes
|

|CICD
|*CICD Pipeline documentation*

Describes our CICD pipeline and release process
|Yes
|
|
|

|community
|*OF Community documentation*

Everything about the OperatorFabric Community: Code of conduct, governance, contribution guidelines,
communication channels.
|Yes
|
|
|

|deployment
|*Deployment documentation*

Explains how to deploy and configure an OperatorFabric instance
|
|
|Yes
|

|dev_env
|*Development Environment documentation*

Explains how to set up a working development environment for OperatorFabric with all the appropriate tooling and how to
run OperatorFabric in development mode.
|Yes
|
|
|

|docs
|
This folder contains the documentation that should be archived for previous releases (as of today, the release notes
and single page documentation - see below).
|Yes
|Yes
|Yes
|Yes

|getting_started
|*Getting Started Guide*
guides you through setting up OperatorFabric and experimenting with its main features
|Yes
|Yes
|
|Maybe

|reference_doc
|*Reference Documentation*
contains the reference documentation for each microservice. It starts off with a high-level functional documentation
and then goes into more technical details when needed.
|Yes
|Yes
|
|Yes

|===

In addition to this asciidoctor documentation, API documentation is available in the form of SwaggerUI-generated html
pages. It is generated by the `generateSaggerUI` Gradle task, using the swagger.yaml files from each service (for
example for the
link:https://github.com/opfab/operatorfabric-core/blob/master/services/core/actions/src/main/modeling/swagger.yaml[Actions API]
). It can be found under the *build/docs/api* folder for each client or service project.

== Conventions

* In addition to the "visible" structure described above, documents are broken down into coherent parts using the
link:https://asciidoctor.org/docs/user-manual/#include-directive["include" feature of AsciiDoc]. This is done mostly to
avoid long files that are harder to edit, but it also allows us to reuse some content in different places.

* Given the number of files this creates, we try to keep header attributes in files to a minimum. Instead, they're
set in the configuration of the asciidoctor gradle task:
+
.build.gradle
[source,groovy]
----
include::../../../../build.gradle[tag=asciidoctor_gradle_task_config]
----
+
In particular, the version and revision date are set automatically from the version defined in the
link:https://github.com/opfab/operatorfabric-core/blob/master/VERSION[VERSION] file at the root of the project and
the current date.

* All files are created starting with level 0 titles so:
** They can be generated on their own if need be.
** They can be included at different levels in different documents using
link:https://asciidoctor.org/docs/user-manual/#include-partitioning[leveloffset].

* In addition to being available as separate documents (architecture, reference, etc.) for the current release, the
documentation is also generated as a single page document available for all releases from the
link:https://opfab.github.io/pages/releases.html[releases] page. This is also a way to make searching the documentation
for specific terms easier, and could be used to generate a single page pdf documentation.

* Unfortunately, this entails a little complexity for cross-references and relative links, because the path to
the content is a little different depending on whether the content is generated as different pages or as a single
page document.
+
For example, to link to the "Card Structure" section of the reference document from the architecture
document, one needs to use the following external cross-reference:
+
----
<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#card_structure, Card Structure>>
----
+
In the case of the single-page documentation however, both the architecture content and the reference content are part
of the same document, so the cross-reference becomes a simple internal cross-reference:
+
----
<<card_structure, Card Structure>>
----
+
This is managed by using the
link:https://asciidoctor.org/docs/user-manual/#conditional-preprocessor-directives[`ifdef` and `indef` directives] to
define which link syntax should be used:
+
----
\ifdef::single-page-doc[<<card_structure, Card Structure>>]
\ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#card_structure, Card Structure>>]
----
+
NOTE: The label ("Card Structure" in this example) is defined with each link because it seems that defining it in the
target file along with the ID (`\[[my_section_id, text to display]]`) doesn't work with relative links.
+
In the same way, for relative links to external files (mostly the API documentation):
+
----
\ifdef::single-page-doc[link:../api/cards/index.html#/archives[here]]
\ifndef::single-page-doc[link:{gradle-rootdir}/documentation/current/api/cards/index.html#/archives[here]]
----
+
IMPORTANT: For this to work, the
link:https://github.com/opfab/operatorfabric-core/blob/master/src/docs/asciidoc/docs/single_page_doc.adoc[single_page_doc.adoc]
file needs to have `:single-page-doc:` as a header attribute.

* As you can see in the examples above, we are using custom-defined section ids as anchors rather than taking advantage
of generated ones (see link:https://asciidoctor.org/docs/user-manual/#auto-generated-ids[documentation]).
This is cumbersome but:
** Generation will give a warning if duplicate ids are defined, whereas with generated ids it will silently link to the
wrong section.
** Restructuring the document might change the generated section ID, creating broken links.
** Its easier to find referenced text (ctrl-f on id)
** The presence of a custom-defined ID is a sign that the content is referenced somewhere else, which you should take
into account if you're thinking of deleting or moving this content.

* The :imagesdir: attribute is set globally as `../images`, because all images are stored under `src/docs/asciidoc/images`.

* In addition to links, it is sometimes necessary to display the actual content of files (or part of it) in
the documentation (in the case of configuration examples, for instance).
Whenever possible, this should be done by using the
link:https://asciidoctor.org/docs/user-manual/#include-directive[include directive] rather than copying the content
into the adoc file.
This way the documentation will always be up to date with the file content at the time of generation.
+
_See the *build.gradle* include above for an example using
link:https://asciidoctor.org/docs/user-manual/#by-tagged-regions[tags] to include only part of a file._

* Source-highlighting is done using link:http://coderay.rubychan.de/[Coderay]. See their documentation for supported
languages, and the AsciiDoctor documentation on
link:https://asciidoctor.org/docs/user-manual/#applying-source-highlighting[how to apply source-highlighting].

* Avoid long lines whenever possible (for example, try not to go beyond 120 characters). This makes editing the
documentation easier and diffs more readable.

* Most links to other OperatorFabric documents should be relative (see above) so they automatically point to the
document in the same version rather than the latest version.
Links starting with *https://opfab.github.io/documentation/current/* should only be used when we want to always refer to
the latest (release) version of the documentation.
