// Copyright (c) 2018-2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= OperatorFabric Community

The aim of this document is to present the OperatorFabric community, its code of conduct and to welcome contributors!

First of all, thank you for your interest !

We can't stress enough that feedback, discussions, questions and contributions on OperatorFabric are very much
appreciated.
However, because the project is still in its early stages, we're not fully equipped for any of it yet, so please bear
with us while the contribution process and tooling are sorted out.


This project is governed by the link:../pdf/technical-charter.pdf[OperatorFabric Technical Charter].

This project applies the LF Energy Code of Conduct. By participating, you are expected to uphold this code.
Please report unacceptable behavior to mailto:opfab_AT_lists.lfenergy.org[opfab_AT_lists.lfenergy.org].

== License and Developer Certificate of Origin

OperatorFabric is an open source project licensed under the link:https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License 2.0].
By contributing to OperatorFabric, you accept and agree to the terms and conditions for your present and future
contributions submitted to OperatorFabric.

The project also uses a mechanism known as a link:https://developercertificate.org/[Developer Certificate of Origin (DCO)]
to ensure that we are legally allowed to distribute all the code and assets for the project. A DCO is a legally binding
statement that asserts that you are the author of your contribution, and that you wish to allow OperatorFabric to use
your work.

Contributors sign-off that they adhere to these requirements by adding a `Signed-off-by` line to commit messages. All
commits to any repository of the OperatorFabric organization have to be signed-off like this:

----
This is my commit message.

Signed-off-by: John Doe <john.doe@email-provider.com>
----

You can write it manually but Git has a -s command line option to append it automatically to your commit message:

----
$ git commit -s -m 'This is my commit message'
----

Most IDEs can also take care of this for you.

A check will be performed during the integration, making sure all commits in the Pull Request
contain a valid `Signed-off-by` line.

These processes and templates have been adapted from the ones defined by the link:https://github.com/powsybl[PowSyBl]
project.

== Reporting Bugs or Vulnerabilities and Suggesting Enhancements

Anyone is welcome to report bugs and suggest enhancements or new features by opening a GitHub issue on this repository.
Vulnerabilities can be reported publicly in the same way.

== Contributing Code or Documentation

include::workflow.adoc[leveloffset=+2]

=== Code Guidelines

* We don't mention specific authors by name in each file (in Javadoc or in the documentation for example), so as not
to have to maintain these mentions (since this information is tracked by git anyway).
* For ui code, you must use a linter with rules provided in ui/main/tslint.json

==== Angular/TypeScript development caution and guidelines

* Use `!!myVariable` to test if a variable is undefined or null except for number where zero will return false ( !!0 is equal to false)
* Use `foreach` to iterate over an array (instead of `for(let i = ..`) . In some cases, foreach do not work and you can use it this way `Array.prototype.forEach.call(myArray, element => .... )` (see https://stackoverflow.com/questions/43743560/foreach-vs-array-prototype-foreach-call)
* Do not use ngFor / ngIf  with methods with computing as angular will call these methods very regularly
(around ten times per seconds), use instead variables and compute them only when necessary.
* ngInit() :  ngInit is called when component is created, the creation is made by the parent component : be careful to check when initialization is done when calling method inside ngInit. When the context of the parent component change, it can lead to a new initialization or not.

include::documentation.adoc[leveloffset=+2]

include::copyright.adoc[leveloffset=+2]

== Project Governance

=== Project Owner

OperatorFabric is part of the link:https://www.lfenergy.org/[LF Energy Foundation], a project of the
link:https://www.linuxfoundation.org/[Linux Foundation] that supports open source innovation projects within the energy
and electricity sectors.

=== Committers

Committers are contributors who have made several valuable contributions to the project and are now relied upon to both
write code directly to the repository and screen the contributions of others. In many cases they are programmers but it
is also possible that they contribute in a different role. Typically, a committer will focus on a specific aspect of
the project, and will bring a level of expertise and understanding that earns them the respect of the community and the
project owner.

=== Technical Steering Committee

See the https://opfab.github.io/pages/tsc.html[dedicated page] for more details on the Technical Steering Committee (scheduled meetings, minutes of past meetings, etc.).

=== Contributors

Contributors include anyone in the technical community that contributes code, documentation, or other technical
artifacts to the project.

Anyone can become a contributor. There is no expectation of commitment to the project, no specific skill requirements
and no selection process. To become a contributor, a community member simply has to perform one or more actions that
are beneficial to the project.

== Communication channels

In addition to GitHub we have set up:

=== Website: http://opfab.org

Our website contains all the documentation and resources we're currently working on. Here is what we aim to provide:

* Architecture documentation
* REST API documentation
* Reference documentation for each component
* Javadoc/Compodoc for each component
* Tutorials and QuickStart guides and videos

*This documentation is our priority* right now so future contributors can quickly find their way around the project.
Needless to say, it's a work in progress so feel free to tell us what you feel is missing or what type of documentation
you would be interested in as a contributor.

=== LF Energy Mailing Lists

Several mailing lists have been created by LF Energy for the project, please feel free to subscribe to the ones you
could be interested in:

* https://lists.lfenergy.org/g/opfab-announce[OperatorFabric Announcements] (such as new releases)
* https://lists.lfenergy.org/g/opfab[OperatorFabric General Discussion]
* https://lists.lfenergy.org/g/opfab-dev[OperatorFabric Developers] for project development discussions

And if you're interested in LF Energy in general:
https://lists.lfenergy.org/g/lfenergy[LF Energy General Discussion]

include::CODE_OF_CONDUCT.adoc[leveloffset=+1]
