operatorfabric:
  mail:
    host: mailhog
    port: 1025
    auth:
      user: guest
      pass: guest
  cardsExternalDiffusion:
    defaultConfig:
      mailFrom: opfab@localhost.it
      subjectPrefix: 'Opfab card received '
      bodyPrefix: 'You received a card in opfab : '
      bodyPostfix: 'This email has been sent by Opfab, there is no need to reply.'
      opfabUrlInMailContent: http://localhost:2002
#  logConfig:
#    logLevel: debug