
management:
  endpoints:
    web:
      exposure:
        include: '*'

operatorfabric:
  rabbitmq:
    # host: rabbitmq
    # SECURITY WARNING : To set and change in production if rabbit port is open outside of docker network
    # username: guest
    # password: guest
  mongodb:
    uri: mongodb://root:password@mongodb:27017/operator-fabric?authSource=admin&authMode=scram-sha1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:89/auth/realms/dev/protocol/openid-connect/certs


### activate the following if you want to the groups or entities to come from the token and not mongo DB
#    jwt:

### activate the folLowing if you want the entities of the user to come from the token and not mongoDB
### entitiesIdClaim is the name of the field in the token     
#      entitiesIdClaim : entitiesId
#      gettingEntitiesFromToken: true
###

### activate the following if you want the groups of the user to come from the token and not mongoDB
#      groups: 
#        mode: JWT
#        rolesClaim:
#          rolesClaimStandard:
#            - path: "ATTR1"
#            - path: "ATTR2"            
#          rolesClaimStandardArray:  
#            - path: "resource_access/opfab-client/roles"
#          rolesClaimStandardList:  
#            - path: "groups" 
#              separator: ";"           
#          rolesClaimCheckExistPath: 
#            - path: "resource_access/AAA" 
#              roleValue: "roleAAA"      
#            - path: "resource_access/BBB"
#              roleValue: "roleBBB"  
### 