version: '2.1'
services:
  # Dummy external devices using Modbus Protocol
  dummy-modbus-device_1:
    container_name: dummy-modbus-device_1
    image: "lfeoperatorfabric/of-dummy-modbus-device:SNAPSHOT"
    user: ${USER_ID}:${USER_GID}
    ports:
      - "4031:4030"
    environment:
      - SPRING_PROFILES_ACTIVE
    volumes:
      - "../certificates:/certificates_to_add"
      - "./common-docker.yml:/config/common-docker.yml"
      - "./dummy-modbus-device-docker.yml:/config/application-docker.yml"
      - ${CONFIG_PATH}:/external-config
  dummy-modbus-device_2:
    container_name: dummy-modbus-device_2
    image: "lfeoperatorfabric/of-dummy-modbus-device:SNAPSHOT"
    user: ${USER_ID}:${USER_GID}
    ports:
      - "4032:4030"
    environment:
      - SPRING_PROFILES_ACTIVE
    volumes:
      - "../certificates:/certificates_to_add"
      - "./common-docker.yml:/config/common-docker.yml"
      - "./dummy-modbus-device-docker.yml:/config/application-docker.yml"
      - ${CONFIG_PATH}:/external-config