opfab:
  usersUrl: http://users:2103
  cardsPublicationUrl: "http://cards-publication:2102"
  cardsConsultationUrl: http://cards-consultation:2104
  getTokenUrl: http://web-ui/auth/token
rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
mongodb:
  database: operator-fabric
  uri: mongodb://root:password@mongodb:27017/operator-fabric?authSource=admin
mail:
  host: mailhog
  port: 1025
  auth:
    user: guest
    pass: guest
logConfig:
  logLevel: info
cardsExternalDiffusion:
  adminPort: 2106
  activeOnStartup: true
  opfab:
    login: admin
    password: test
  defaultConfig:
    mailFrom: opfab@localhost.it
    subjectPrefix: 'Opfab card received '
    bodyPrefix: 'You received a card in opfab : '
    opfabUrlInMailContent: http://localhost:2002
    windowInSecondsForCardSearch: 360
    secondsAfterPublicationToConsiderCardAsNotRead: 60
    checkPeriodInSeconds: 10
cardsReminder:
  adminPort: 2107
  activeOnStartup: true
  checkPeriodInSeconds: 5
  opfab:
    login: opfab_internal_account
    password: test
supervisor:
  adminPort: 2108
  activeOnStartup: false
  defaultConfig:
    entitiesToSupervise:
    - id: ENTITY1_FR
      supervisors:
      - ENTITY2_FR
    - id: ENTITY2_FR
      supervisors:
      - ENTITY1_FR
    disconnectedCardTemplate:
      publisher: service_supervisor
      processVersion: '1'
      process: supervisor
      state: disconnectedEntity
      severity: ALARM
    secondsBetweenConnectionChecks: 10
    nbOfConsecutiveNotConnectedToSendFirstCard: 3
    nbOfConsecutiveNotConnectedToSendSecondCard: 12
    processesToSupervise:
    - process: messageOrQuestionExample
      states:
      - messageState
      - questionState
    - process: defaultProcess
      states:
      - processState
    unackCardTemplate:
      publisher: service_supervisor
      processVersion: '1'
      process: supervisor
      state: unacknowledgedCards
      severity: ALARM
    windowInSecondsForCardSearch: 1200
    secondsBetweenAcknowledgmentChecks: 10
    secondsAfterPublicationToConsiderCardAsNotAcknowledged: 600