operatorfabric:
  supervisor:
    activeOnStartup : false
    defaultConfig:
      considerConnectedIfUserInGroups: ["Dispatcher","Planner"]
      entitiesToSupervise:
      - id: ENTITY1_FR
        supervisors:
        - ENTITY2_FR
      - id: ENTITY2_FR
        supervisors:
        - ENTITY1_FR
      disconnectedCardTemplate:
        publisher: opfab
        processVersion: '1'
        process: supervisor
        state: disconnectedEntity
        severity: ALARM
      secondsBetweenConnectionChecks: 10
      nbOfConsecutiveNotConnectedToSendFirstCard: 3
      nbOfConsecutiveNotConnectedToSendSecondCard: 12
      processesToSupervise:
      - process: messageOrQuestionExample
        states:
        - messageState
        - questionState
      - process: defaultProcess
        states:
        - processState
      unackCardTemplate:
        publisher: opfab
        processVersion: '1'
        process: supervisor
        state: unacknowledgedCards
        severity: ALARM
      windowInSecondsForCardSearch: 1200
      secondsBetweenAcknowledgmentChecks: 10
      secondsAfterPublicationToConsiderCardAsNotAcknowledged: 600
#  logConfig:
#    logLevel: debug