// Copyright (c) 2018-2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




= Pipeline Configuration

This section briefly describes the organization of our CICD pipeline. 

Most of the access and permissions required by our CICD plateform are managed by tokens that are created on
each of the required services (SonarCloud, DockerHub, GitHub).
A technical user account (opfabtech) has been created for each of these services so that these tokens are not linked
to the account of any member of the team.

== CICD Pipeline

=== Github Actions 

We use github Actions to manage our pipeline (https://github.com/opfab/operatorfabric-core/actions).


=== SonarCloud

To be allowed to push results to SonarCloud, github needs to be authenticated. This is done by generating a token on
SonarCloud with an account (opfabtech) that has admin rights to the organization, and then providing this token to github using https://github.com/opfab/operatorfabric-core/settings/secrets/actions[actions secrets] .

=== GitHub (documentation)

To be allowed to push the generated documentation to the opfab.github.io, Github needs write access to the repository.
This is done by setting up a Personal Access Token in GitHub using the technical account.
This token is then passed to Github  using https://github.com/opfab/operatorfabric-core/settings/secrets/actions[actions secrets] .

NOTE: After new content is pushed to the opfab.github.io repository, it can take a few minutes before this content is
visible on the website because it needs to be built by GitHub pages, and this can take a short while
depending on how busy the service is.

=== DockerHub

To be allowed to push images to DockerHub, Github needs to be authenticated. This is done again by generating a token in DockerHub using the technical account and provide it to github via actions secrets.