// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.



= Pipeline Configuration

This section briefly describes the organization of our CICD pipeline. If you are looking for more detailed information,
see
ifdef::single-page-doc[<<mock_pipeline, this document>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/resources/index.adoc#mock_pipeline, this document>>]
describing the steps that were necessary to create our mock pipeline as well as the issues we ran into.

Most of the access and permissions required by our CICD plateform (Travis) are managed by tokens that are created on
each of the required services (SonarCloud, DockerHub, GitHub).
A technical user account (opfabtech) has been created for each of these services so that these tokens are not linked
to the account of any member of the team.

== CICD Pipeline

=== GitHub

Work in progress
//TODO Describe two repos, groups, branch protection rules

=== Travis CI

We use Travis CI to manage our pipeline. As of today, it is composed of 7 stages:
[horizontal]
test-sonar:: Builds the commit, runs tests and sonar analysis
test:: Similar to `test-sonar` but without sonar analysis
doc:: Generates the documentation (from asciidoc sources and API documentation) and pushes it to the opfab.github.io
repository to update the website.
doc-dry-run:: Generates the documentation without pushing it
docker-push-version:: Builds Docker images, tags them with the current version (either `SNAPSHOT` or `X.X.X.RELEASE`) and
pushes them to DockerHub
docker-push-latest:: Builds Docker images, tags them with `latest` and pushes them to DockerHub
docker-tag-version:: Builds Docker images and tags them with the current version, without pushing them anywhere. This
stage can be triggered when we just want to check that the images can be built without actually updating them on DockerHub.

Among these stages, four can be considered "sensitive" because they push public content that serves as a reference for
the project (docker images, documentation and to a lesser extent, sonar analysis), meaning we don't want it tampered with.
These stages are `test-sonar`, `doc` and the two `docker-push` stages.

These stages are triggered depending on:

* branch type
* event type (CRON job, push or pull request)
* commit message hooks

In the table below:
[horizontal]
doc hook:: stands for adding the keyword `ci_documentation` to the commit message
docker hook:: stands for adding the keyword `ci_docker` to the commit message
latest hook:: stands for adding the keyword `ci_latest` to the commit message

.Summary of stage triggers
[caption="", cols="3,^1,^1,^1,^1,^1,^1,^1,^1,^1,^1,^1", stripes=even]
|==========================
h|      4+h|develop h|release 2+h|master 3+h|feature or hotfix h| pull request
h|Stage              h|CRON h|push h|doc hook h|docker hook h|push h|push h|latest hook h|push h|doc hook h|docker hook h|push
e|test-sonar          |X|X| | |X|X| |X| | |internal
e|test                | | | | | | | | | | |external
e|doc                 |X| |X| | |X| | | | |
e|doc-dry-run         | | | | |X| | | |X| |
e|docker-push-version |X| | |X| |X| | | | |
e|docker-push-latest  | | | | | | |X| | | |
e|docker-tag-version  | | | | |X| | | | |X|
|==========================

* The `test-sonar` phase is ran for every build except those triggered by external PRs (i.e. originating from a fork
of the repository). This is because the `sonar-scanner` step it comprises requires access to an encrypted token
(to be able to push the analysis to
https://sonarcloud.io/dashboard?id=org.lfenergy.operatorfabric%3Aoperatorfabric-core[SonarCloud], see below for details)
that is not shared with external PRs for security reasons, so this would cause the stage (and the build) to fail.
This is why in the case of external PRs the `test` phase is ran instead (leaving out sonar-scanner).

//TODO Finish explanations

=== SonarCloud

To be allowed to push results to SonarCloud, Travis needs to be authenticated. This is done by generating a token on
SonarCloud with an account (opfabtech) that has admin rights to the organization, and then providing this token to Travis
either through the .travis.yml file or as an environment variable through Travis settings.

=== GitHub (documentation)

To be allowed to push the generated documentation to the opfab.github.io, Travis needs write access to the repository.
This is done by setting up a Personal Access Token in GitHub using the technical account.
This token is then passed to Travis as an environment variable through Travis settings, and is used in the .travis.yml file.
Right now the scope of this token is maximal, it can probably be reduced (see https://opfab.atlassian.net/browse/OC-755[OC-755]).

NOTE: After new content is pushed to the opfab.github.io repository, it can take a few minutes before this content is
visible on the website because it needs to be built by GitHub pages, and this can take a short while
depending on how busy the service is.

=== DockerHub
To be allowed to push images to DockerHub, Travis needs to be authenticated. This is done by setting the DockerHub
login and password of the technical account as environment variables through Travis settings and referencing them in
the .travis.yml file.
