
== Third Party Endpoint Specification

URL Action may specify any url as action to trigger but those resource must
comply to certain constraints

=== GET

An access to the resource using GET method allow to gather information to
update the corresponding action.

==== return codes

|===
|code|message|payload
|200|ok|payload is an action status
|204|no content|action is not updated
|404|not found|no action associated with URL
|===

==== response payload


See Actions Service Rest API for complete structure.

This response gathers information to update the client side behavior of the action.

=== POST

An access to the resource using POST method allow to submit the action
to trigger business behavior.

==== return codes

|===
|code|message|payload
|200|ok|payload is an action status
|204|no content|action is not updated on submission
|404|not found|no action associated with URL
|===

==== submission payload

(Not implemented)

Submission payload is a json object containing information submitted by
the operator. The structure of the object reflects

==== response payload

See Actions Service Rest API for complete structure.

This response gathers information to update the client side behavior of the action.