// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Attribution for Sound Assets

The sound assets from this directory are licensed under the Creative Commons CC0 1.0 Universal license
(see link:CC0_LICENSE.txt[CC0_LICENSE.txt]).

== alarm.mp3

Source: https://freesound.org/people/Ozzie321/sounds/238075/

Original file name: uncle.mp3

Author: link:https://freesound.org/people/Ozzie321/[Ozzie321]

The original sound was shortened.

== action.mp3

Source: https://freesound.org/people/rj10328/sounds/139025/

Original file name: +131659__bertrof__game-sound-intro-to-game_&_80921__justinbw__buttonchime02up_4.mp3+

Author: link:https://freesound.org/people/rj10328/[rj10328]

== compliant.mp3

Source: https://freesound.org/people/LittleRainySeasons/sounds/335908/

Original file name: Correct.mp3

Author: link:https://freesound.org/people/LittleRainySeasons/[LittleRainySeasons]

== information.mp3

Source: https://freesound.org/people/breebles/sounds/487029/

Original file name: Music Box.mp3

Author: link:https://freesound.org/people/breebles/[breebles]
