// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


= Cloud Configuration service

Operator Fabric Configuration service is a Spring Cloud Config application
bootstrapped using SpringBoot.

In our spring micro service architecture Configuration instances are the first
services to bootstrap, thus they are configured in a specific way contrary to
other services.

== Mandatory configuration, Profiles and default properties

To get a working configuration service, there a few mandatory configuration
properties:

* in a bootstrap file:
** The application must have a set name (spring.application.name)
* in an application property file
** The application must have a configured rabbitmq service for configuration
change notification (spring.rabbitmq.*)
** The application must have a configured eureka server (eureka.client.*)

For other configuration see {spring_cloud_config_doc}single/spring-cloud-config.html[spring cloud config documentation].

Note that it is mandatory to define an environment repository for the service.
Dev and Docker profile uses a file system backend which is not suitable for
production and redundancy. You should prefer the usage of Git or Vault for
production.

=== default properties

It is preferable not to change the following bootstrap.yml file.

_bootstrap.yml_
```
include::../../main/resources/bootstrap.yml[]
```

_application.yml_
```
include::../../main/resources/application.yml[]
```

The above embedded configurations are the basic settings of the application:
* it sets its name as a service (config)
* it exposes management endpoints

=== dev profile
dev is the profile we use internally for developpement we make it available for
external developers so that they don't need extensive configuration to get a
jar working in the development environment

```
include::../../main/resources/application-dev.yml[]
```

* it exposes the service on port 2000 (defaults to 8080)
* it activates the dev and native profile (native is mandatory for serving
config from file system)
* it configures rabbitmq for dispatching config change messages to other services
* it configures registration in eureka discovery service

=== docker profile
docker is the profile we use in our docker images

```
include::../../main/resources/application-docker.yml[]
```

* it activates the native profile (native is mandatory for serving
config from file system)
* it configures rabbitmq for dispatching config change messages to other services
* it configures registration in eureka discovery service

== Specifying external configuration properties when lauching a jar file

See {springboot_doc}/reference/htmlsingle/#boot-features-external-config-application-property-files[Application Property Files]
on how to setup an external spring properties or yml file.

See{springboot_doc}/reference/htmlsingle/#howto-set-active-spring-profiles[Set the Active Spring Profiles] for specifying alternate profile.


== Specifying configuration properties when lauching a docker image

Our docker image expects optional property file to be stored in the container
/service-config folder. You can bind so docker volume to this path to make
properties or yml available.

At time of writting, you cannot specify an alternate profile at runtime.
The default profiles activated are docker and native.

=== Available environment variables for docker image

* RABBITMQ_HOST: Rabbitmq host name
* RABBITMQ_PORT: Rabbitmq host port
* RABBITMQ_USER: Rabbitmq user name used for authentication service
* RABBITMQ_PASSWORD: Rabbitmq user password used for authentication service
* REGISTRY_HOST: Registry (eureka) host name
* REGISTRY_PORT: Registry (eureka) host port
* JAVA_OPTIONS: Additional java options

== Specifying configuration properties when lauching on Kubernetes

In progress

=== Available environment variables when launching on Kubernetes

* RABBITMQ_HOST: Rabbitmq host name
* RABBITMQ_PORT: Rabbitmq host port
* RABBITMQ_USER: Rabbitmq user name used for authentication service
* RABBITMQ_PASSWORD: Rabbitmq user password used for authentication service
* REGISTRY_HOST: Registry (eureka) host name
* REGISTRY_PORT: Registry (eureka) host port
* JAVA_OPTIONS: Additional java options