dependencies {
    implementation project(':tools:generic:utilities'), project(':tools:spring:spring-utilities')
    implementation misc.jsonSmart
    implementation misc.commonsLang

//Transitive dependencies udpate needed for security reasons 
    implementation misc.guava
    implementation misc.compress
//End transitive dependencies

    implementation spring.securityOauthResource, spring.securityOauthJose

    compileOnly boot.annotationConfiguration
    annotationProcessor boot.annotationConfiguration

    implementation cloud.springKafka
    implementation cloud.kafkaAvroSchemaRegistryClient
    implementation cloud.kafkaAvroSerializer


    implementation boot.starterWeb, boot.starterUndertow
    implementation spring.securityOauthResource, spring.securityOauthJose
    implementation boot.starterSecurity
    implementation boot.starterValidation
    implementation boot.starterMongo
    testImplementation spring.securityTest

    // necessary for generated class for kafka-avro-serializer (org.opfab.avro.*)
    implementation project(':client:cards-client-data')

    implementation project(':services:common-service')
    implementation project(':tools:spring:spring-mongo-utilities')
    implementation project(':tools:spring:spring-oauth2-utilities')
    implementation project(':tools:user-action-tracing')
    testImplementation project(':tools:spring:spring-test-utilities')
}

bootJar {
    manifest {
        attributes( "Created-By"             : "Gradle ${gradle.gradleVersion}",
                    "Specification-Title"    : "OperatorFabric Card Manager Service",
                    "Implementation-Title"   : "OperatorFabric Card Manager Service",
                    "Implementation-Version" : operatorfabric.version,
                    "Specification-Version"  : operatorfabric.version
        )
    }
}

