plugins {
    id "com.github.davidmc24.gradle.plugin.avro"
}

dependencies {
    implementation project(':tools:generic:utilities')
    implementation misc.jsonSmart
    implementation misc.commonsLang

//Transitive dependencies udpate needed for security reasons 
    implementation misc.guava
    implementation misc.compress
//End transitive dependencies

    implementation spring.securityOauthResource, spring.securityOauthJose

    compileOnly boot.annotationConfiguration
    annotationProcessor boot.annotationConfiguration

    implementation cloud.springKafka
    implementation cloud.kafkaAvroSchemaRegistryClient
    implementation cloud.kafkaAvroSerializer


    implementation boot.starterWeb, boot.starterUndertow
    implementation spring.securityOauthResource, spring.securityOauthJose
    implementation boot.starterSecurity
    implementation boot.starterValidation
    implementation boot.starterMongo
    testImplementation spring.securityTest

    implementation project(':services:common-service')
    testImplementation project(':tools:spring:spring-test-utilities')
}

bootJar {
    manifest {
        attributes( "Created-By"             : "Gradle ${gradle.gradleVersion}",
                    "Specification-Title"    : "OperatorFabric Card Manager Service",
                    "Implementation-Title"   : "OperatorFabric Card Manager Service",
                    "Implementation-Version" : operatorfabric.version,
                    "Specification-Version"  : operatorfabric.version
        )
    }
}

avro {
    createSetters = true
    fieldVisibility = "PRIVATE"
    stringType = "String"
}
