// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


= Cloud Registry service

Operator Fabric Registry service is a Spring Eureka application
bootstrapped using SpringBoot.

In our spring micro service architecture Eureka Registry instances are the second
services to bootstrap, its configuration relies on the <<Cloud Configuration service>>.

== Mandatory configuration, Profiles and default properties

To get a working registry service, there a few mandatory configuration
properties:

* In a bootstrap file
** The application must have a set name (spring.application.name)
** The application must have a set configuration name (spring.cloud.config.name)
** The application must have a set configuration server (spring.cloud.config.uri)
** The application may have a retry/failfast configuration for config access
(spring.cloud.config.failfast, spring.cloud.config.retry)
* In a configuration service registry.yml file
** The application may deactivate eureka registration to avoid self registration
(deactivated by default in internal application.yml file)
** The application must set the Eureka instance hostname (eureka.instance.hostname)
** The application must set the Eureka default zone (eureka.lient.serviceUrl.defaultZone)

For other configuration see {spring_cloud_netflix_doc}single/spring-cloud-netflix.html[spring cloud netflix documentation].


=== default properties

It is preferable not to change the following bootstrap.yml file.

_bootstrap.yml_
```
include::../../main/resources/bootstrap.yml[]
```

_bootstrap-docker.yml_
```
include::../../main/resources/bootstrap-docker.yml[]
```

_bootstrap-dev.yml_
```
include::../../main/resources/bootstrap-dev.yml[]
```

_application.yml_
```
include::../../main/resources/application.yml[]
```

The bootstrap-docker.yml file is a replacement bootstrap file we use for our
docker images configuration.

The bootstrap-dev.yml file is a replacement bootstrap file we use for our
developpement environment

The above embedded configurations are the basic settings of the application:
* it sets its name as a service (config)
* it sets the configuration name to use (which configuration file to retrieve)
* it must set the configuration service (example in bootstrap-docker.yml)


=== dev profile
dev is the profile we use internally for developpement we make it available for
external developers so that they don't need extensive configuration to get a
jar working in the development environment

```
include::../../main/resources/application-dev.yml[]
```

=== Sample developpement configuration

```
include::../../../../config/src/main/docker/volume/dev-configurations/registry.yml[]
```

=== Sample docker image configuration

```
include::../../../../config/src/main/docker/volume/docker-configurations/registry.yml[]
```

== Specifying external configuration properties when lauching a jar file

See {springboot_doc}/reference/htmlsingle/#boot-features-external-config-application-property-files[Application Property Files]
on how to setup an external spring properties or yml file.

See {springboot_doc}/reference/htmlsingle/#howto-set-active-spring-profiles[Set the Active Spring Profiles] for specifying alternate profile.


== Specifying configuration properties when lauching a docker image

Our docker image expects optional property file to be stored in the container
/service-config folder. You can bind so docker volume to this path to make
properties or yml available.

At time of writting, you cannot specify an alternate profile at runtime.
The default profiles activated are docker and native.

=== Available environment variables for docker image

* CONFIG_HOST: Configuration service host
* CONFIG_PORT: Configuration service port
* JAVA_OPTIONS: Additional java options

== Specifying configuration properties when lauching on Kubernetes

In progress

=== Available environment variables when launching on Kubernetes

* CONFIG_HOST: Configuration service host
* CONFIG_PORT: Configuration service port
* JAVA_OPTIONS: Additional java options