apply plugin: 'java'
apply plugin: 'jacoco'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'org.springframework.boot'

dependencies {
    implementation boot.starterSecurity
    implementation misc.jsonSmart
    implementation spring.securityOauthResource, spring.securityOauthJose
    implementation boot.starterValidation
    implementation misc.guava
    implementation misc.commonsIO
    implementation boot.actuator
    implementation misc.micrometer
    
    compileOnly boot.annotationConfiguration
    annotationProcessor boot.annotationConfiguration

    implementation boot.starterWeb, boot.starterUndertow
    implementation project(':backend:java-common')

    testImplementation spring.securityTest
    testImplementation boot.starterTest, testing_deps.assertJ
    testImplementation project(':backend:java-common')
    testImplementation project(':backend:test-utilities')
}

configurations {
    implementation.exclude module: "spring-boot-starter-tomcat"
    testImplementation.exclude module: "spring-boot-starter-tomcat"
} 

tasks.named("processResources") {
    duplicatesStrategy = 'include'
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
        }
        resources{
            srcDir 'src/main/resources'
        }
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events = ["passed", "skipped", "failed"]
        exceptionFormat = "full"
    }
    filter {
        includeTestsMatching "*Should"
    }
}

jacocoTestReport {
    group = "Reporting"
    reports {
        xml.required = true
        csv.required = false
        html.outputLocation = file("${buildDir}/reports/jacoco/html")
        xml.outputLocation = file("${buildDir}/reports/jacoco/xml/report.xml")
    }
}

task buildDocker(type: Exec) {
    workingDir project.projectDir
    commandLine 'docker', 'build', 
                '--build-arg', "https_proxy=${proxy.https}",
                '--build-arg', "JAR_FILE=${project.name.toLowerCase()}-${project.version.toUpperCase()}.jar",
                '-t', "lfeoperatorfabric/of-${project.name}:${project.version}", '.'
}

task copyScriptsForDockerImage(type: Copy) {
    description 'copy script for docker image'
    from "$project.projectDir/../java-common/add-certificates.sh"
    from "$project.projectDir/../java-common/java-config-docker-entrypoint.sh"
    into "$project.projectDir/build/docker"
    doFirst {
        logger.info "creating $project.projectDir/build/dockerFiles/"
        new File("$project.projectDir/build/docker/").mkdirs()
    }
}

// Test data tasks >>>>>
task compressBundle1Data(type: Exec){
    description 'generate tar.gz businessconfig party configuration data for tests in build/test-data'
    workingDir "$project.projectDir/src/test/data/bundles/second/2.0/"
    executable "bash"
    args "-c", "tar -czf $project.projectDir/build/test-data/bundles/second-2.0.tar.gz *"
}
task compressBundle2Data(type: Exec){
    description 'generate tar.gz businessconfig party configuration data for tests in build/test-data'
    workingDir "$project.projectDir/src/test/data/bundles/second/2.1/"
    executable "bash"
    args "-c", "tar -czf $project.projectDir/build/test-data/bundles/second-2.1.tar.gz *"
}
task copyProcessGroupsFile(type: Exec){
    description 'copy processgroups.json file for businessconfig party configuration data for tests in build/test-data'
    workingDir "$project.projectDir/src/test/data/"
    executable "bash"
    args "-c", "cp processgroups.json $project.projectDir/build/test-data/"
}

task copyProcessGroupsFile2(type: Exec) {
    description 'copy processgroups_with_duplicate_in_same_group.json file for businessconfig party configuration data for tests in build/test-data'
    workingDir "$project.projectDir/src/test/data/"
    executable "bash"
    args "-c", "cp processgroups_with_duplicate_in_same_group.json $project.projectDir/build/test-data/"
}

task copyProcessGroupsFile3(type: Exec) {
    description 'copy processgroups_with_duplicate_in_different_groups.json file for businessconfig party configuration data for tests in build/test-data'
    workingDir "$project.projectDir/src/test/data/"
    executable "bash"
    args "-c", "cp processgroups_with_duplicate_in_different_groups.json $project.projectDir/build/test-data/"
}

task copyRealTimeScreensFile(type: Exec){
    description 'copy realtimescreens.json file for businessconfig party configuration data for tests in build/test-data'
    workingDir "$project.projectDir/src/test/data/"
    executable "bash"
    args "-c", "cp realtimescreens.json $project.projectDir/build/test-data/"
}

task createDevData(type: Copy){
    description 'prepare data in build/dev-data for running OpFab in dev mode'
    from 'src/main/docker/volume/businessconfig-storage'
    into 'build/dev-data/businessconfig-storage'
    doFirst{
        logger.info "copying src/main/docker/volume/* to build/dev-data/businessconfig-storage/"
    }
}

task prepareTestDataDir {
    description 'prepare directory (build/test-data) for test data'
    doFirst {
        logger.info "creating $project.projectDir/build/test-data/"
        new File("$project.projectDir/build/test-data/bundles/").mkdirs()
        new File("$project.projectDir/build/test-data/businessconfig-storage/").mkdirs()
    }
}

task prepareDevDataDir {
    description 'prepare directory (build/dev-data)'
    doFirst {
        logger.info "creating $project.projectDir/build/dev-data/"
        new File("$project.projectDir/build/dev-data/bundles/").mkdirs()
    }
}


tasks.buildDocker.dependsOn copyScriptsForDockerImage
tasks.buildDocker.dependsOn build
tasks.jacocoTestReport.dependsOn test
createDevData.dependsOn prepareDevDataDir
compressBundle1Data.dependsOn prepareTestDataDir
compressBundle2Data.dependsOn prepareTestDataDir
copyProcessGroupsFile.dependsOn prepareTestDataDir
copyProcessGroupsFile2.dependsOn prepareTestDataDir
copyProcessGroupsFile3.dependsOn prepareTestDataDir
copyRealTimeScreensFile.dependsOn prepareTestDataDir
test.dependsOn prepareTestDataDir,compressBundle1Data,compressBundle2Data,copyProcessGroupsFile,copyProcessGroupsFile2,copyProcessGroupsFile3,copyRealTimeScreensFile
bootRun.dependsOn createDevData


