server:
  port: 2103
operatorfabric.users.default:
  users:
    - login: admin
      groups: ["ADMIN"]
      entities: ["ENTITY1","ENTITY2"]
    - login: rte-operator
      groups: ["RTE","ADMIN","TRANS"]
    - login: tso1-operator
      groups: ["TSO1","TRANS"]
      entities: ["ENTITY1"]
    - login: tso2-operator
      groups: ["TSO2", "TRANS"]
      entities: ["ENTITY2"]
  groups:
    - name: ADMIN
      description: The admin group
    - name: RTE
      description: RTE TSO Group
    - name: TSO1
      description: TSO 1 Group
    - name: TSO2
      description: TSO 2 Group
    - name: TRANS
      description: Transnationnal Group
  user-settings:
    - login: rte-operator
      description: Da Operator Rulez
#logging.level.root: DEBUG