dependencies{
    implementation boot.starterWeb
    implementation boot.starterSecurity
    implementation boot.starterValidation
    implementation spring.securityOauthResource, spring.securityOauthJose
    implementation spring.webflux
    implementation misc.jacksonDatabind
    implementation project(":services:common-service")
    implementation project(":tools:generic:utilities")
}
