// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

//TODO Remove unnecessary anchors
[[card_structure]]
= Card Structure

Cards are represented as `Json` objects. The technical design of cards is described in
ifdef::single-page-doc[link:../api/cards/[the cards api documentation]]
ifndef::single-page-doc[link:{gradle-rootdir}/documentation/current/api/cards/[the cards api documentation]]
. A card correspond to the state of a Process in OperatorFabric.

== Technical Information of the card

Those attributes are used by OperatorFabric to manage how cards are stored, to whom and when they're sent.

=== Mandatory information

Below, the `json` technical key is in the '()' following the title.

==== Publisher (`publisher`)
The publisher field bears the identifier of the emitter of the card, be it an entity or an external service.

[[card_process]]
==== Process (`process`)
This field indicates which process the card is attached to. This information is used to resolve the presentation
resources (bundle) used to render the card and card details.

[[card_process_version]]
==== Process Version (`processVersion`)
The rendering of cards of a given process can evolve over time. To allow for this while making sure previous cards
remain correctly handled, OperatorFabric can manage several versions of the same process.
The `processVersion` field indicate which version of the process should be used to retrieve the presentation resources
(i18n, templates, etc.) to render this card.

==== Process Instance Identifier (`processInstanceId`)
A card is associated to a given process, which defines how it is rendered, but it is also more precisely associated to
a *specific instance* of this process. The `processInstanceId` field contains the unique identifier of the process instance.

=== State in the process (`state`)
The card represent a specific state in the process. In addition to the process, this information is used to resolve the presentation
resources used to render the card and card details.

[[start_date]]
==== Start Date (`startDate`)

Start date of the active period of the card (process business time).

==== Severity (`severity`)

The severity is a core principe of the OperatorFabric Card system. There are 4 severities available.
A color is associated in the GUI to each severity. Here the details about severity and their meaning for OperatorFabric:

1. ALARM: represents a critical state of the associated process, need an action from the operator. In the UI, the card is red;
2. ACTION: the associated process need an action form operators in order to evolve correctly. In the UI, the card is orange;
3. COMPLIANT: the process related to the card is in a compliant status. In the UI, the card is green.;
4. INFORMATION: give information to the operator. In the UI, the card is blue.

[[card_title]]
==== Title (`title`)

This attribute is display as header of a card in the feed of the GUI. It's the main User destined Information of a card. The value refer to an `i18n` value used to localize this information.

[[card_summary]]
==== Summary (`summary`)

This attribute is display as a description of a card in the feed of the GUI, when the card is selected by the operator. It's completing the information of the card title. The value refer to an `i18n` value used to localize this information.


=== Optional information



[[end_date]]
==== End Date (`endDate`)

End date of the active period of the card (process business time).

==== Tags (`tag`)

Tags are intended as an additional way to filter cards in the feed of the GUI.

==== EntityRecipients (`entityRecipients`)

Used to send cards to entity : all users members of the listed entities who have the right for the process/state of the card will receive it. 


==== GroupRecipients (`groupRecipients`)

Used to send cards to groups : all users members of the groups will receive it. If this field is used in conjunction with entityRecipients, to receive the cards :

* users must be members of one of the entities AND one of the groups to receive the cards.

OR

* users must be members of one of the entities AND have the right for the process/state of the card.

==== UserRecipients (`userRecipients`)

Used to send cards directly to users without using groups or entities for card routing.

==== Last Time to Decide (`lttd`)

Fixes the moment until when a `response` is possible for the card. After this moment, the response button won't be useable. When lttd time is approaching, a clock is visible on the card in the feed with the residual time.  The lttd time can be set for cards that don't expect any response

==== SecondsBeforeTimeSpanForReminder (`secondsBeforeTimeSpanForReminder`)

Fixes the time for remind before the event define by the card see  
ifdef::single-page-doc[<<card_reminder, Card reminder>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#card_reminder, Card reminder>>]

=== Business period 

We define the business period as starting form startDate to endDate.  The card will be visible on the UI if the business period overlap the user chosen period (i.e the period selected on  the timeline). If endDate is not set, the  card will be visible as soon as the startDate is before the end of the chosen period.


=== Store information 

==== uid (`uid`)

Unique identifier of the card in the OperatorFabric system. This attribute can be sent with card, but by default it's managed by OperatorFabric.

==== id (`id`)

State id of the associated process, determined by `OperatorFabric` can be set arbitrarily by the `publisher`. The id is determined by 'OperatorFabric' as follow : process.processIntanceId

==== Publish Date (`publishDate`)

Indicates when the card has been registered in `OperatorFabric` system. This is a technical information exclusively managed by `OperatorFabric`.

== User destined Information of the card

There are two kind of User destined information in a card. Some are restricted to the card format, others are defined by the publisher as long as there are encoded in `json` format. 

=== in Card Format

==== Title (`title`)

See
ifdef::single-page-doc[<<card_title, Title>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#card_title, Title>>]
.

==== Summary (`summary`)

See
ifdef::single-page-doc[<<card_summary, Summary>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#card_summary, Summary>>]
.

=== Custom part

==== Data (`data`)

Determines where custom information is store. The content in this attribute, is purely `publisher` choice.
This content, as long as it's in `json` format can be used to display details. For the way the details are
displayed, see below.


[WARNING]
You must not use dot in json field names. In this case, the card will be refused with following message :
"Error, unable to handle pushed Cards: Map key xxx.xxx contains dots but no replacement was configured!""

== Presentation Information of the card

=== TimeSpans (`timeSpans`)

When the simple startDate and endDate are not enough to characterize your
process business times, you can add a list of TimeSpan to your card. TimeSpans
are rendered in the timeline component as cluster bubbles. This has no effect on the feed
content.

*example :*

to display the card two times in the timeline you can add two TimeSpan to your
card:

....
{
	"publisher":"Dispatcher",
	"publisherVersion":"0.1",
	"process":"process",
	"processInstanceId":"process-000",
	"startDate":1546297200000,
	"severity":"INFORMATION",
	...
	"timeSpans" : [
        {"start" : 1546297200000},
        {"start" : 1546297500000}
    ]

}
....
In this sample, the card will be displayed twice in the time line. The card
start date will be ignored.


For timeSpans, you can specify an end date but it is not implemented in OperatorFabric (it was intended for future uses but it will be deprecated).
