// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Cards Examples

Before detailing the content of cards, let's show you what cards look like through few examples of json.

[[minimal_card]]
== Minimal Card

The OperatorFabric Card specification defines mandatory attributes, but some optional attributes are needed for cards to be useful in OperatorFabric. Let's clarify those point through few examples of minimal cards and what happens when they're used as if.

=== Send to One User
The following card contains only the mandatory attributes.

....
{
	"publisher":"Dispatcher",
	"processVersion":"0.1",
	"process":"process",
	"processInstanceId":"process-000",
	"state":"myState",
	"startDate":1546297200000,
	"severity":"INFORMATION",
	"title":{"key":"card.title.key"},
	"summary":{"key":"card.summary.key"},
	"userRecipients": ["operator1"]

}
....

This an information about the process instance `process-000` of process `process`, sent by `Dispatcher`. The title and the summary refer to `i18n` keys
defined in the associated `i18n` files of the process. This card is displayable since the first january 2019 and
should only be received by the user using the `operator1` login.

=== Send to several users

==== Simple case (sending to a group)

The following example is nearly the same as the previous one except for the recipient.

....
{
	"publisher":"Dispatcher",
	"processVersion":"0.1",
	"process":"process",
	"processInstanceId":"process-000",
	"state":"myState",
	"startDate":1546297200000,
	"severity":"INFORMATION",
	"title":{"key":"card.title.key"},
	"summary":{"key":"card.summary.key"},
	"groupRecipients": ["Dispatcher"]
}
....

Here, the recipient is a group, the `Dispatcher`. So all users who are members of this group will receive the card.



==== Simple case (sending to a group and an entity)

The following example is nearly the same as the previous one except for the recipient.

....
{
	"publisher":"Dispatcher",
	"processVersion":"0.1",
	"process":"process",
	"processInstanceId":"process-000",
	"state":"myState",
	"startDate":1546297200000,
	"severity":"INFORMATION",
	"title":{"key":"card.title.key"},
	"summary":{"key":"card.summary.key"},
	"groupRecipients": ["Dispatcher"],
	"entityRecipients" : ["ENTITY1"]
}
....

Here, the recipients are a group and an entity, the `Dispatcher` group and `ENTITY1` entity. So all users who are both members
of this group and this entity will receive the card.

==== Simple case (sending to an entity)

The following example is nearly the same as the previous one except for the recipient.

....
{
	"publisher":"Dispatcher",
	"processVersion":"0.1",
	"process":"process",
	"processInstanceId":"process-000",
	"state":"myState",
	"startDate":1546297200000,
	"severity":"INFORMATION",
	"title":{"key":"card.title.key"},
	"summary":{"key":"card.summary.key"},
	"entityRecipients" : ["ENTITY1"]
}
....

Here, the recipient is an entity and there is no more groups. So all users who has the right perimeter and who are members of this entity will receive the card. More information on perimeter can be found in 
ifdef::single-page-doc[<<'users_management,user documentation'>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#users_management, user documentation>>]


==== Complex case

If this card need to be viewed by a user who is not in the `Dispatcher` group, it's possible to tune more precisely the
definition of the recipient. If the `operator2` needs to see also this card, the recipient definition could be(the following code details only the recipient part):

....
"groupRecipients": ["Dispatcher"],
"userRecipients": ["operator2"]
....


So here, all the users of the `Dispatcher` group will receive the `INFORMATION` as should the `tos2-operator` user.

Another example, if a card is destined to the operators of `Dispatcher` and `Planner` and needs to be also seen by the `admin`, the recipient configuration looks like:

....
"groupRecipients": ["Dispatcher", "Planner"],
"userRecipients": ["admin"]
....


== Regular Card

The previous cards were nearly empty regarding information carrying. In fact, cards are intended to contain more information than a title and a summary. The optional attribute `data` is here for that. This attribute is destined to contain any `json` object. The creator of the card is free to put any information needed as long as it's in a `json` format.

=== Full of Hidden data

For this example we will use our previous example for the `Dispatcher` group with a `data` attribute containing the definition of a `json` object containing two attributes: `stringExample` and `numberExample`.

....
{
	"publisher":"Dispatcher",
	"processVersion":"0.1",
	"process":"process",
	"processInstanceId":"process-000",
	"state":"myState",
	"startDate":1546297200000,
	"severity":"INFORMATION",
	"title":{"key":"card.title.key"},
	"summary":{"key":"card.summary.key"},
	"userRecipients": ["operator1"],
	"data":{
		"stringExample":"This is a not so random string of characters.",
		"numberExample":123
		}

}
....

This card contains some data but when selected in the feed nothing more than the previous example of card happen because
there is no rendering configuration.

=== Fully useful

When a card is selected in the feed (of the GUI), the data is displayed in the detail panel.
The way details are formatted depends on the template contained in the bundle associated with the process as
ifdef::single-page-doc[<<template_description, described here>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#template_description, described here>>]
. To have an effective example without to many actions to performed, the following example will use an already existing
configuration.The one presents in the development version of OperatorFabric, for test purpose(`TEST` bundle).

At the card level, the attributes in the card telling OperatorFabric which template to use are the `process` and `state` attributes, the `templateName` can be retrieved from the definition of the bundle.

....
{
	"publisher":"TEST_PUBLISHER",
	"processVersion":"1",
	"process":"TEST",
	"processInstanceId":"process-000",
	"state":"myState",
	"startDate":1546297200000,
	"severity":"INFORMATION",
	"title":{"key":"process.title"},
	"summary":{"key":"process.summary"},
	"userRecipients": ["operator1"],
	"data":{"rootProp":"Data displayed in the detail panel"},

}
....

So here a single custom data is defined and it's `rootProp`. This attribute is used by the template called by the `templateName` attribute.




