// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




//TODO Remove unnecessary anchors

[[card_structure]]
= Card Structure

Cards are represented as `Json` objects. The technical design of cards is described in
ifdef::single-page-doc[link:../api/cards/[the cards api documentation]]
ifndef::single-page-doc[link:{gradle-rootdir}/documentation/current/api/cards/[the cards api documentation]]
. A card correspond to the state of a Process in OperatorFabric.

== Technical Information of the card

Those attributes are used by OperatorFabric to manage how cards are stored, to whom and when they're sent.

=== Mandatory information

Below, the `json` technical key is in the '()' following the title.

[[card_publisher]]
==== Publisher (`publisher`)

Quite obviously it's the Third party which publish the card. This information is used to look up for Presentation resources of the card.

[[card_publisher_version]]
==== Publisher Version (`publisherVersion`)

Refers the `version` of `publisher third` to use to render this card (i18n, title, summary and details).
As through time, the presentation of a publisher card data changes, this changes are managed through `publisherVersion` in OperatorFabric. Each version is keep in the system in order to be able to display correctly old cards.

==== Process Identifier (`processInstanceId`)

It's the way to identify the process to which the card is associated. A card represent a state of a process.

[[start_date]]
==== Start Date (`startDate`)

This attribute is a part of the card life management system. It's indicate OperatorFabric the moment since the card
can be displayed to the operators or main recipients, see
ifdef::single-page-doc[<<display_rules, Display rules>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#display_rules, Display rules>>]
.

==== Severity (`severity`)

The severity is a core principe of the OperatorFabric Card system. There are 4 severities available.
A color is associated in the GUI to each severity. Here the details about severity and their meaning for OperatorFabric:

1. ALARM: represents a critical state of the associated process, need an action from the operator. In the UI, the card is red;
2. ACTION: the associated process need an action form operators in order to evolve correctly. In the UI, the card is orange;
3. COMPLIANT: the process related to the card is in a compliant status. In the UI, the card is green.;
4. INFORMATION: give information to the operator. In the UI, the card is blue.

[[card_title]]
==== Title (`title`)

This attribute is display as header of a card in the feed of the GUI. It's the main User destined Information of a card. The value refer to an `i18n` value used to localized this information.

[[card_summary]]
==== Summary (`summary`)

This attribute is display as a description of a card in the feed of the GUI, when the card is selected by the operator. It's completing the information of the card title. The value refer to an `i18n` value used to localized this information.

=== Recipient (`recipient`)

Declares to whom the card is send. For more details about way recipient works see
ifdef::single-page-doc[<<display_rules, Display rules>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#display_rules, Display rules>>]
. Without recipient declaration a card is useless in `OperatorFabric` system.

=== Card Life Management Configuration

With this attributes OperatorFabric knows when to display or hide cards.

==== Start Date (`startDate`)

See
ifdef::single-page-doc[<<start_date, Start Date>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#start_date, Start Date>>]
 and
ifdef::single-page-doc[<<display_rules, Display rules>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#display_rules, Display rules>>]
for more examples.

==== End Date (`endDate`)

Fixes the moment until when `OperatorFabric` displays the card. After the card is remove from the GUI feed,
ifdef::single-page-doc[<<display_rules, Display rules>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#display_rules, Display rules>>]
for some examples.



=== Optional information

==== Tags (`tag`)

Tags are intended as an additional way to filter cards in the feed of the GUI.

==== EntityRecipients (`entityRecipients`)

Used to send to cards to entity : all users members of the listed entities will receive the card. If it is used in conjunction with groups recipients, users must be members of one of the entities AND one of the groups to receive the cards.


=== Last Time to Decide (`lttd`)

Fixes the moment until when a `actions` associated to the card are available. After then, the associated actions won't be displayed or actionable.

=== Store information 

==== uid (`uid`)

Unique identifier of the card in the OperatorFabric system. This attribute can be sent with card, but by default it's managed by OperatorFabric.

==== id (`id`)

State id of the associated process, determined by `OperatorFabric` can be set arbitrarily by the `publisher`.



=== Other technical attributes

=== Publish Date (`publishDate`)

Indicates when the card has been registered in `OperatorFabric` system. This is a technical information exclusively managed by `OperatorFabric`.

=== Deletion Date (`deletionDate°)

Indicates when the card has been removes from `OperatorFabric` system. Technical information manage by `OperatorFabric`.

== User destined Information of the card

There are two kind of User destined information in a card. Some are restricted to the card format, others are defined by the publisher as long as there are encoded in `json` format. 

=== in Card Format

==== Title (`title`)

See
ifdef::single-page-doc[<<card_title, Title>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#card_title, Title>>]
.

==== Summary (`summary`)

See
ifdef::single-page-doc[<<card_summary, Summary>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#card_summary, Summary>>]
.

=== Custom part

==== Data (`data`)

Determines where custom information is store. The content in this attribute, is purely `publisher` choice.
This content, as long as it's in `json` format can be used to display details. For the way the details are
displayed, see below.


[WARNING]
You must not use dot in json field names. In this case, the card will be refused with following message :  "Error, unable to handle pushed Cards: Map key xxx.xxx contains dots but no replacement was configured!""


== Presentation Information of the card

=== details (`details`)

This attribute is a string of objects containing a `title` attribute which is `i18n` key and a `template` attribute
which refers to a template name contained in the publisher bundle. The bundle in which those resources will be looked
for is the one corresponding of the
ifdef::single-page-doc[<<card_publisher_version, version>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#card_publisher_version, version>>]
declared in the card for the current
ifdef::single-page-doc[<<card_publisher, publisher>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#card_publisher, publisher>>]
.
If no resource is found, either because there is no bundle for the given version or
there is no resource for the given key, then the corresponding key is displayed in the details section of the GUI.

See more documentation about third bundles
ifdef::single-page-doc[<<bundle_technical_overview, here>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#bundle_technical_overview, here>>]
.

*example:*

The `TEST` publisher has only a `0.1` version uploaded in the current `OperatorFabric` system. The `details` value is `[{"title":{"key":"first.tab.title"},"template":"template0"}]`.

If the `publisherVersion` of the card is `2` then only the `title` key declared in the `details` array will be displays without any translation, i.e. the tab will contains `TEST.2.first.tab.title` and will be empty. If the `l10n` for the title is not available, then the tab title will be still `TEST.2.first.tab.title` but the template will be compute and the details section will display the template content.

=== TimeSpans (`timeSpans`)

When the simple startDate and endDate are not enough to characterize your
process business times, you can add a list of TimeSpan to your card. TimeSpans
are rendered in the timeline component as cluster bubbles. This has no effect on the feed
content

*example :*

to display the card two times in the timeline you can add two TimeSpan to your
card:

....
{
	"publisher":"TSO1",
	"publisherVersion":"0.1",
	"processInstanceId":"process-000",
	"startDate":1546297200000,
	"severity":"INFORMATION",
	...
	"timeSpans" : [
        {"start" : 1546297200000},
        {"start" : 1546297500000}
    ]

}
....
In this sample, the card will be displayed twice in the time line. The card
start date will be ignored.


For timeSpans, you can specify an end date but it is not implemented in OperatorFabric (it was intended for future uses but it will be deprecated).
