// Copyright (c) 2018-2023 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0


= Card notification

When a user receives a card, he is notified via a resume of the card on the left panel of the UI, what is called the "feed".

== Notification configuration

For each process/state, the user can choose to be notified or not when receiving a card. If he chooses not to be
notified then the card will not be visible:

* in the feed or the timeline
* in the monitoring screen
* in the calendar screen

However, it will be visible in the archives screen.

In order to have a better visual organization of the processes in the UI, you can define processes groups.
You can find more information
ifdef::single-page-doc[<<_processes_groups, here>>]
ifndef::single-page-doc[<</documentation/current/reference_doc/index.adoc#_processes_groups, here>>]

Some process/state may be non-filterable. In this case, the corresponding checkbox is disabled (and checked).
To make a process/state filterable or not, the admin must modify the "filtering notification allowed" field, in the
corresponding perimeter.

== Sound notification 

If the option is activated in the general configuration file web-ui.json, the user can choose to have a sound played
when they receive a card (either by the browser or by an external device if configured).
This can be managed by the user in the settings screen.

NOTE: To customize the sounds played by the browser, see `config/docker/custom-sounds/README.adoc`.

== Card read 

When the user receives a new card, he can see it in the feed with a bold title and card resume. Once the card is opened, the text is not bold anymore and becomes grey.

== Card acknowledgment

=== Acknowledgment done by the user

The user can set a card as "acknowledged," so he will not see it any more by default in the feed. It is as well possible to cancel it and set a card to "unacknowledged" (a filter permit to see acknowledged cards).

To offer the possibility for the user to acknowledge card, it has to be configured in process definition.
The configuration is done on a state by setting the `acknowledgmentAllowed` field. Allowed values are:

- "Never": acknowledgement not allowed

- "Always": acknowledgement allowed (default value)

- "OnlyWhenResponseDisabledForUser": acknowledgement allowed only when 
the response is disabled for the user

It is possible to cancel a card acknowledgment unless process state configuration has the `cancelAcknowledgmentAllowed` field set to false.

When the user acknowledges a card, the card detail is closed unless process state configuration has the `closeCardWhenUserAcknowledges` field set to false.

You can see examples in src/test/resources/bundles/defaultProcess_V1/config.json

=== Acknowledgment done by entity(ies)

A card can also be set as acknowledged if a member (or several) of the entity of the user has acknowledged it.
A user can be member of several entities, so you can configure if acknowledgment done by only one entity
(of the user) suffices for the card to appear as acknowledged or if all entities must acknowledge the card.

To configure how a card is considered as acknowledged for the user, it has to be configured in process definition.
The configuration is done on a state by setting the `consideredAcknowledgedForUserWhen` field. Allowed values are :

- "UserHasAcknowledged" : the card is set as acknowledged if the user acknowledges it

- "AllEntitiesOfUserHaveAcknowledged" : the card is set as acknowledged if all the entities of the user acknowledge it

=== Displaying the entities acknowledgments

The entities acknowledgments can be displayed in the footer of the card. You can choose to display it (or not) via the option
`showAcknowledgmentFooter` in a state definition. Allowed values are :

- "OnlyForEmittingEntity" (default value) : the entities acknowledgments are displayed only for the members of the entity
that has created the card

- "OnlyForUsersAllowedToEdit" : the entities acknowledgments are displayed for the users allowed to edit the card

- "ForAllUsers" : the entities acknowledgments are displayed for the members of all the entities

- "Never" : The entities acknowledgments are displayed to no one

== Pin cards
It is possible to configure the state of a process so that cards are automatically "pinned" when acknowledged. Pinned cards are displayed in Feed page as small boxes with the title of the card just under the timeline Pinned cards are still visible even if the card is no more visible in the feed. A pinned card remains visible until card end date. If no end date, card will always be visible unless it is updated or deleted.

To configure a process state to automatically pin cards set the `automaticPinWhenAcknowledged` property to true in state definition. 
For example:

....
"pinnedState": {
      "name": "⚠️ Network Contingencies ⚠️",
      "description": "Contingencies state",
      "templateName": "contingencies",
      "styles": [
        "contingencies"
      ],
      "acknowledgmentAllowed": "Always",
      "type" : "INPROGRESS",
      "automaticPinWhenAcknowledged" : true
    }
....


[[card_reminder]]
== Card reminder 

For certain process and state, it is possible to configure a reminder. The reminder triggers the resending of the card at a certain time with status "unread" and "unacknowledged" and publishDate updated.


The time for "reactivation" is defined with the parameter "secondsBeforeTimeSpanForReminder" in the card.

The reminder is done related to the timespans values :

- the startDate 

- or recurrently if a recurrence objet is defined.

=== Simple reminder

If a timespan is present without a recurrence object, a reminder will arise at `startDate - secondsBeforeTimeSpanForReminder`.

=== Recurrent reminder

It is possible to set a recurrent reminder for a card. There are two ways to do it :

==== Using `rRule` field :

`rRule` field defines a regular event (as defined in the RFC 5545). It is defined with the following fields :

- freq : frequency of the recurrence (possible values : 'SECONDLY', 'MINUTELY', 'HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY')

- byweekday : list of days of the week when the event arises (possible values : 'MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU')

- bymonth : list of months of the year when the event arises (possible values : number from 1 to 12, 1 being January and 12 being December)

- byhour : list of hours of the day for the recurrence (from 0 to 23)

- byminute : list of minutes within an hour for the recurrence (from 0 to 59)

The reminder will arise for each `recurrent date of event - secondsBeforeTimeSpanForReminder` starting from startDate.

===== Recurrent reminder example using `rRule` field :

....
rRule : {
    freq : 'DAILY',
    byweekday : ['TU', 'WE'],
    bymonth : [1, 3],
    byhour : [11],
    byminute : [30]
}
....

==== Using `recurrence` field in the timespan object (deprecated)

`recurrence` field defines a regular event in the timespan structure. It is defined with the following fields :

 - HoursAndMinutes : hours and minutes of day when the event arise

 - DaysOfWeek : a list of days of the week when the event arises. The day of week is a number with 1 being Monday and 7 being Sunday as defined in https://en.wikipedia.org/wiki/ISO_8601#Week_dates[the ISO Standard 8601 (weekday number) ]

 - Months : a list of months of the year when the event arises. The month of year is a number with 0 being January and 11 being December

 - TimeZone : the time zone of reference for the recurrence definition (default value is Europe/Paris)

 - DurationInMinutes : the duration in minutes of the event

The reminder will arise for each `recurrent date of event - secondsBeforeTimeSpanForReminder` starting from startDate. 

===== Recurrent reminder example using `recurrence` field :

If timespan is defined as follows :

.... 
startDate : 1231135161
recurrence : {
    hoursAndMinutes : { hours:10 ,minutes:30},
    daysOfWeek : [6,7],
    durationInMinutes : 15,
    months : [10,11]
}
....

If secondsBeforeTimeSpanForReminder is set to 600 seconds, the reminder will arise every Saturday and Sunday, in November and December at 10:20 starting from startDate.

=== Debugging 

When a card with a reminder set is sent, the log of the "cards-reminder" service will contain a line with the date when the reminder will arise . For example :

`2020-11-22T21:00:36.011Z Reminder Will remind card conferenceAndITIncidentExample.0cf5537b-f0df-4314-f17f-2797ccd8e4e9 at
                         Sun Nov 22 2020 22:55:00 GMT+0100 (heure normale d’Europe centrale)`
