// Copyright (c) 2021-2024 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0



= Monitoring

The monitoring screen is a realtime view of processes based on current cards received by the user (i.e. the last version of cards visible by the user). It can be seen as another view of the feed.

Not all the cards are visible, it depends on the business process they are part of. For a card to be visible in this screen, the parameter `uiVisibility.monitoring` must be set to `true` in the config.json file of its process.

== Export configuration 

An Excel export function is available in the monitoring screen, the content of the export can be configured. 
To do so, a json file describing the expected output can be sent to the businessconfig service through the /businessconfig/monitoring endpoint.

In opfab git repository, you can find in directory https://github.com/opfab/operatorfabric-core/tree/develop/src/test/resources/monitoringConfig[src/test/resources/monitoringConfig]  : 
  
  - a script to load a monitoring configuration `loadMonitoringConfig.sh`

  - an example of configuration in `monitoringConfig.json` (for the response fields to be filled , you need to respond to a card question in process messageOrQuestionExample )


A description of the structure of the configuration can be found in 
ifdef::single-page-doc[link:../api/businessconfig/[the businessconfig api documentation]]
ifndef::single-page-doc[link:/documentation/current/api/businessconfig/[the businessconfig api documentation]]


== Process monitoring

NOTE: This feature is experimental

The process monitoring screen has the following similarities with the monitoring screen :

- it is a realtime view of processes based on current cards received by the user
(i.e. the last version of cards visible by the user)
- not all the cards are visible, it depends on the business process they are part of. For a card to be visible on
this screen, the parameter `uiVisibility.processmonitoring` must be set to `true` in the `config.json` file of its
process.

This screen provides the following features :

- the columns displayed on this screen can be configured. To do that, you have to define the `processMonitoring.fields` field
in the `web-ui.json` configuration file. This object is a list of the fields you want to see in the array.
You also have the possibility to define the columns displayed per process. To do that, you have to configure the field
`processMonitoring.fieldsForProcesses`.
If more than one process is selected by the user or if a process has no configuration, the columns displayed will
be those of the default config (`processMonitoring.fields`).
- depending on the permissions of the groups to which the user is attached, he can also see the cards he is not the
recipient of.
- if geographical map view is enabled ('feed.geomap.enableMap' set to 'true' in web-ui.json) it is possible to view the cards on the map by checking the "View Results on a Geographical Map" checkbox.

Here is an example of processMonitoring configuration :
```
"processMonitoring": {
  "fields": [
    { "field": "startDate", "type": "date", "colName": "Start Date", "size": "200"},
    { "field": "titleTranslated", "colName": "Title", "size": "250"},
    { "field": "entityRecipients", "type": "array", "colName": "Entity Recipients", "size": "400"},
    { "field": "data.stateName", "colName": "My field", "size": "300"},
    { "field": "summaryTranslated", "colName": "Summary", "size": "250"},
    { "field": "data.error", "colName": "My second field", "size": "100"}
  ],
  "fieldsForProcesses": {
    "process1" : [
      { "field": "startDate", "type": "date", "colName": "Start Date", "size": "200"},
      { "field": "titleTranslated", "colName": "Title", "size": "250"},
      { "field": "entityRecipients", "type": "array", "colName": "Entity Recipients", "size": "400"}
    ],
    "process2" : [
      { "field": "startDate", "type": "date", "colName": "Start Date", "size": "200"},
      { "field": "endDate", "type": "date", "colName": "End Date", "size": "200"},
      { "field": "titleTranslated", "colName": "Title", "size": "250"},
      { "field": "entityRecipients", "type": "array", "colName": "Entity Recipients", "size": "400"}
    ]
  },
  "filters": {
    "tags": {
      "list": [
        {
          "label": "Label for tag 1",
          "value": "tag1"
        },
        {
          "label": "Label for tag 2",
          "value": "tag2"
        }
      ]
    }
  }
}
```

Here is the description of the fields :

- "field" : the name of the field in the card (or in the database) you want to display
- "type" : field type to be used for formatting. Possible values : `date`, `array`. Set to `date` if you want to display a date/time field, set it to `array` to display an array as a comma separated list.
- "colName" : name of the column on the UI
- "size" : size of the column on the UI, proportionally to each other

