// Copyright (c) 2023 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0


= Frontend API

The frontend API is intended to provide a way for template to communicate with the core opfab code. It's divided as follow :
- Users API : API to get information about users and entities
- Navigate API : API to ask opfab to navigate to a specific view
- CurrentCard API : API to get information regarding the current card 
- Utils API : utilities functions

== Users API 

=== Entities

Entity object contains the following fields :

- 'id' : id of the entity
- 'name' : name of the entity
- 'description' : description of the entity
- 'entityAllowedToSendCard' : boolean indicating whether the entity is allowed to send cards or not
- 'parents' : list of parent entities
- 'labels' : list of labels associated to the entity


==== Function getEntityName

Obtain the name of an entity :

```
const myEntityName = opfab.users.entities.getEntityName('myEntityId');
```

==== Function getEntity 

Obtain a specific entity : 

```
const myEntity = opfab.users.entities.getEntity('myEntityId');
```


==== Function getAllEntities

Obtain all entities as an array :

```
const entities = opfab.users.entities.getAllEntities();
```



== Navigate API 

=== Function redirectToBusinessMenu

It’s possible to redirect the user from a card to a business application declared in ui-menu.json.

This can be done by calling the following function from the template :

```
opfab.navigate.redirectToBusinessMenu(idMenu,idEntry);
```

- idMenu is the id of the menu defined in ui-menu.json
- idEntry is the id of the entry defined in ui-menu.json

It is also possible to append a url extension (sub paths and/or parameters) to the url that will be called:

```
opfab.navigate.redirectToBusinessMenu('myMenu','myEntry','/extension?param1=aParam&param2=anotherParam');
```

This can be useful to pass context from the card to the business application.

=== Function showCardDetail

It is possible from the template to redirect the user to another "card detail" in feed page 
```
 opfab.navigation.showCardDetail('cardId'); 
```

== CurrentCard API

=== Function displayLoadingSpinner

Once the card is loaded, there may be some processing that is time consuming. In this case, it is possible to show a spinner using the method displayLoadingSpinner and hideLoadingSpinner in the card template .

```
opfab.currentCard.displayLoadingSpinner();
// Time consumming code 
.... 
opfab.currentCard.hideLoadingSpinner(); 
```

=== Function hideLoadingSpinner

Hide loading spinner previously open with displayLoadingSpinner()
```
        opfab.currentCard.hideLoadingSpinner()
```

=== Function getChildCards

 Returns an array of the child cards. The structure of a child card is the same as the structure of a classic card.
```
const childCards =  opfab.currentCard.getChildCards(); 
```

=== Function getDisplayContext

To adapt the template content to the display context it is possible to get from OperatorFabric the page context where the template will be rendered by calling the javascript function getDisplayContext(). The function returns a string with one of the following values :

- 'realtime' : realtime page context (feed, monitoring)

- 'archive' : archive page context

- 'preview': preview context (user card)

```
    const displayContext =  opfab.currentCard.getDisplayContext();
```

===  Function getEntitiesAllowedToRespond

If inside your template, you want to get the ids of the entities allowed to send a response, you can call the method getEntitiesAllowedToRespond. This method returns an array containing the ids. An example of usage can be found in the file https://github.com/opfab/operatorfabric-core/tree/master/src/test/resources/bundles/messageOrQuestionExample/template/question.handlebars[src/test/resources/bundles/messageOrQuestionExample/template/question.handlebars].

```
    const entities = opfab.currentCard.getEntitiesAllowedToRespond(); 
```

=== Function  getEntityUsedForUserResponse

If inside your template, you want to get the id of the entity used by the user to send a response, you can call the method getEntityUsedForUserResponse. 
An example of usage can be found in the file https://github.com/opfab/operatorfabric-core/tree/master/src/test/resources/bundles/messageOrQuestionExample/template/question.handlebars[src/test/resources/bundles/messageOrQuestionExample/template/question.handlebars].

```
    const entity = opfab.currentCard.getEntityUsedForUserResponse()
        
```


=== Function isResponseLocked

To know if template is locked (i.e user can not respond unless he unlocks the card)
```
    const isResponseLocked =  opfab.currentCard.isResponseLocked()
```

=== Function isUserAllowedToRespond

The template can know if the current user has the permission to send a response to the current card by calling the isUserAllowedToRespond() function.
An example of usage can be found in the file
https://github.com/opfab/operatorfabric-core/tree/master/src/test/resources/bundles/conferenceAndITIncidentExample/template/incidentInProgress.handlebars[src/test/resources/bundles/conferenceAndITIncidentExample/template/incidentInProgress.handlebars].


```
    const = opfab.currentCard.isUserAllowedToRespond();
```

=== Function isUserMemberOfAnEntityRequiredToRespond

The template can know if the current user is member of an Entity required to respond by calling the isUserMemberOfAnEntityRequiredToRespond function.
An example of usage can be found in the file https://github.com/opfab/operatorfabric-core/tree/master/src/test/resources/bundles/defaultProcess_V1/template/question.handlebars[src/test/resources/bundles/defaultProcess_V1/template/question.handlebars].


``` 
    const isUserRequired = opfab.currentCard.isUserMemberOfAnEntityRequiredToRespond()
```

=== Function listenToResponseLock

Register a function to be informed when template is locked (i.e user has responded to the current card)

```
    opfab.currentCard.listenToResponseLock( () => {// do some stuff});
```

=== Function listenToResponseUnlock

Register a function to be informed when template is unlocked (i.e user has clicked the modify button to prepare a new response)


```
    opfab.currentCard.listenToResponseUnlock( () => {// do some stuff}))
```

=== Function listenToChildCards 

Register a function to receive the child cards on card loading and when the childCards list changes

```
opfab.currentCard.listenToChildCards( (childCards) => { // process child cards });
```


=== Function listenToLttdExpired

If the card has a last time to decide (lttd) configured, when the time is expired this information can be received by the template by registering a listener.

```
    opfab.currentCard.listenToLttdExpired( () => { // do some stuff });
```

=== Function listenToStyleChange

Card template can be informed when switching day/night mode by registering a listener as follow : 

```
    opfab.currentCard.listenToStyleChange( () => { // do some stuff });
```

It can be used by a template to refresh styles and reload embedded charts.

=== Function listenToScreenSize

To adapt the template content on screen size it is possible to receive from OperatorFabric information on the size of the window where the template will be rendered. To receive screen size information you need to implement a listener function which will receive as input a string parameter with one of the following values :

- 'md' : medium size window
- 'lg' : large size window


```
        opfab.currentCard.listenToScreenSize( (screenSize) => {
            if (screenSize == 'lg') // do some stuff
            else // do some other stuff
        })
```

=== Function listenToTemplateRenderingComplete


It is possible to be informed when opfab has finished all tasks regarding rendering template by registering a listener function .The function will be called after the call of the other listener (applyChildCard, lockAnswer ,lttdExpired and screenSize)

It can be used by a template to launch some processing when loading is complete

```
        opfab.currentCard.listenToTemplateRenderingComplete(() => {// do some stuff})
```

=== Function registerFunctionToGetUserResponse

Register the template function to call to get user response. This function will be call by opfab when user clicks on the "send reponse" button. More explanation can be found in the <<response_cards, response card chapter>>.

```
        opfab.currentCard.registerFunctionToGetUserResponse
```


== Utils API

=== Function escapeHtml 


To avoid script injection, OperatorFabric provides a utility function 'opfab.utils.escapeHtml()' to sanitize input content by escaping HTML specific characters. For example: 

```
<input id="input-message" type="text" name="message">
<button onClick="showMessage()">

<span id="safe-message"></span>


<script>
  showMessage : function() {
    let msg = document.getElementById("input-message");
    document.getElementById("safe-message").innerHTML = opfab.utils.escapeHtml(msg.value);
  }

</script>
```