// Copyright (c) 2018-2023 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0


= UI Customization

== UI configuration 

To customize the UI, declare specific parameters in the `web-ui.json` file as link:../deployment/index.html#ui_properties[listed here]

[[menu_entries]]
== Menu Entries

The `ui-menu.json` file is used:

* To manage the visibility of core OperatorFabric menus (feed, monitoring, etc.)
* To declare specific business menus to be displayed in the navigation bar of OperatorFabric

This file contains 4 fields :

* `navigationBar` : contains the navigation bar mixing core menus and custom menus
* `topRightIconMenus` : contains only the two menu icons `agenda` and `usercard` on the top right of the screen
* `topRightMenus` : contains core menus you want to see when you click the user, on the top right of the screen
* `locales` : contains the translations for the custom menus


[[core_menu_config]]
=== Core menus

Core menus are objects containing the following fields :

* `opfabCoreMenuId`: Id of the core menu (string)
* `visible`: Whether this menu should be visible for this OperatorFabric instance (boolean). This field is not
needed in `navigationBar` field but it is needed in `topRightIconMenus` and `topRightMenus`.
* `showOnlyForGroups` : List of groups for which this menu should be visible (array, optional)

.Menu visibility summary
* For a core menu with `"visible": true`:
** If `showOnlyForGroups` is not present, null or an empty array : the menu is visible for all users.
** If `showOnlyForGroups` is present and with a non-empty array as a value: menu is visible only for users from the
listed groups.


.List of core menus and corresponding ids
|===
|Location of menu |Menu |Id

.5+|Navigation bar

|Feed
|feed

|Archives
|archives

|Monitoring
|monitoring

|Dashboard
|dashboard

|Logging
|logging

.2+|Navigation bar (icon)

|User card
|usercard

|Calendar
|calendar

.11+|Top-right menu

|Administration
|admin

|External devices configuration
|externaldevicesconfiguration

|Real time users
|realtimeusers

|Settings
|settings

|Activity area
|activityarea

|Notification Configuration
|feedconfiguration

|User action logs
|useractionlogs

|About
|about

|Night/Day toggle
|nightdaymode

|Change password
|changepassword

|Logout
|logout

|===

See `/config/docker/ui-menu.json` for an example containing all core menus.

NOTE: If you decide not to make the night/day toggle visible (globally or for certain users), you should consider
setting the `settings.styleWhenNightDayModeDesactivated` property in `web-ui.json` to specify which mode should be used.

=== Custom business menus

A menu can target directly a link or give access to several sub-menus when clicked.
Those sub-menus can target a link or an opfab core menu.
A targeted link can be open in an iframe or in a new tab.

Menus support i18n following the i18n OperatorFabric rules.
The ui-menu.json file contains directly the i18n dictionary for the menus.

In case of a single menu, the navigation bar displays the l10n of the `label` of the entry menu.
In this case, the `label` declared at the root level of the menu is useless and can be omitted (see example below).

A single menu or a menu with sub-menus has at least attributes named `id` and `entries`.
The `entries` attribute is an array of `menu entry`. It is possible to restrict the visibility of one menu entry
to one or more user groups by setting the `showOnlyForGroups` parameter.
Note that menus with sub-menus need a `label` declaring an i18n key.

A menu entry can target a core menu id or a link. If it targets a link, it must declare the attributes listed below:

- `customMenuId`: identifier of the entry menu in the UI;
- `url`: url opening a new page in a tab in the browser;
- `label`: it's an i18n key used to l10n the entry in the UI.
- `linkType`: Defines how to display business menu links in the navigation bar and how to open them. Possible values:
** `TAB`: displays only a text link. Clicking it opens the link in a new tab.
** `IFRAME`: displays only a text link. Clicking it opens the link in an iframe in the main content zone below the navigation bar.
** `BOTH`: default value. Displays a text link plus a little arrow icon. Clicking the text link opens the link in an iframe while clicking the icon opens in a new tab.
**
- `showOnlyForGroups`: Defines the list of user groups entitled to see the menu entry, if not defined or empty it will be visible to every user.

In the following example, the configuration file declares two additional business menus.
The first has only one entry, which targets a link. The second business menu has three entries, one which targets the
core menu `Dashboard` and two others which target links.
The sample also contains the 2 top right icons (`usercard` and `calendar`), the composition of the top right menu and
the i18n translations in English and French.

.Example
[source, json]
----
{
  "navigationBar": [
    {
      "opfabCoreMenuId": "feed"
    },
    {
      "opfabCoreMenuId": "archives"
    },
    {
      "id": "menu1",
      "entries": [
        {
          "customMenuId": "uid_test_0",
          "url": "https://opfab.github.io/",
          "label": "entry.single",
          "linkType": "BOTH"
        }
      ]
    },
    {
      "id": "menu2",
      "label": "title.multi",
      "entries": [
        {
          "opfabCoreMenuId": "dashboard"
        },
        {
          "customMenuId": "uid_test_1",
          "url": "https://opfab.github.io/",
          "label": "entry.entry1",
          "linkType": "BOTH",
          "showOnlyForGroups": "ReadOnly,Dispatcher"
        },
        {
          "customMenuId": "uid_test_2",
          "url": "https://www.wikipedia.org/",
          "label": "entry.entry2",
          "linkType": "BOTH",
          "showOnlyForGroups": "Planner"
        }
      ]
    }
  ],
  "topRightIconMenus": [
    {
      "opfabCoreMenuId": "usercard",
      "visible": true
    },
    {
      "opfabCoreMenuId": "calendar",
      "visible": true
    }
  ],
  "topRightMenus": [
    {
      "opfabCoreMenuId": "admin",
      "visible": true,
      "showOnlyForGroups": ["ADMIN"]
    },
    {
      "opfabCoreMenuId": "settings",
      "visible": true
    },
    {
      "opfabCoreMenuId": "activityarea",
      "visible": true
    },
    {
      "opfabCoreMenuId": "feedconfiguration",
      "visible": true
    },
    {
      "opfabCoreMenuId": "realtimeusers",
      "visible": true
    },
    {
      "opfabCoreMenuId": "externaldevicesconfiguration",
      "visible": true,
      "showOnlyForGroups": ["ADMIN"]
    },
    {
      "opfabCoreMenuId": "useractionlogs",
      "visible": true,
      "showOnlyForGroups": ["ADMIN", "Supervisor"]
    },
    {
      "opfabCoreMenuId": "nightdaymode",
      "visible": true
    },
    {
      "opfabCoreMenuId": "about",
      "visible": true
    },
    {
      "opfabCoreMenuId": "changepassword",
      "visible": true
    },
    {
      "opfabCoreMenuId": "logout",
      "visible": true
    }
  ],
  "locales": [
    {
      "language": "en",
      "i18n": {
        "entry": {
          "single": "Single menu entry",
          "entry1": "First menu entry",
          "entry2": "Second menu entry"
        },
        "title": {
          "multi": "Second menu"
        }
      }
    },
    {
      "language": "fr",
      "i18n": {
        "entry": {
          "single": "Premier élément",
          "entry1": "Premier élément",
          "entry2": "Deuxième élément"
        },
        "title": {
          "multi": "Deuxième menu"
        }
      }
    }
  ]
}
----

NOTE: For iframes opened from menu, the associated request uses an extra parameter containing the current theme information.
Named `opfab_theme`, this parameter has a value corresponding to the current theme: `DAY` or `NIGHT`. For example:
`http://mysite.com/index.htm?opfab_theme=NIGHT`. Switching theme will trigger reload of open iframes.
