// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0


= UI Customization


== UI configuration 

The web-ui.json file permit to configure parameters for customization , the list of parameters is 
link:../deployment/index.html#ui_properties[described here]


[[menu_entries]]
== Menu Entries

The ui-menu.json file permit declare specific business menu in the upper part of  OperatorFabric.

If there are several items to declare for a businessc menu, a title for the menu section need to be declared within the `i18nLabelKey` attribute, otherwise the first and only `menu entry` item is used to create an entry in the menu nav bar of OperatorFabric.

The ui-menu.json file contains also the declaration of i18n translations.

=== ui-menu.json declaration

This kind of objects contains the following attributes :

- `id`: identifier of the entry menu in the UI;
- `url`: url opening a new page in a tab in the browser;
- `label`: it's an i18n key used to l10n the entry in the UI.
- `linkType`: Defines how business menu links are displayed in the navigation bar and how
they open. Possible values:
** TAB: Only a text link is displayed, and clicking it opens the link in a new tab.
** IFRAME: Only a text link is displayed, and clicking it opens the link in an iframe in the main content zone below
the navigation bar.
** BOTH: Both a text link and a little arrow icon are displayed. Clicking the text link opens the link in an iframe
while clicking the icon opens in a new tab. This is also the default value.


=== Examples

In following example is the configuration file to add two business menus: the first with only one entry, the second with two entries. The sample contain also the i18n translations in english anf french.


{
  "menus": [
    {
      "id": "menu1",
      "label": "title.single",
      "entries": [
        {
          "id": "uid_test_0",
          "url": "https://opfab.github.io/",
          "label": "entry.single",
          "linkType": "BOTH"
        }
      ]
    },
    {
      "id": "menu2",
      "label": "title.multi",
      "entries": [
        {
          "id": "uid_test_1",
          "url": "https://opfab.github.io/",
          "label": "entry.entry1",
          "linkType": "BOTH"
        },
        {
          "id": "uid_test_2",
          "url": "https://www.wikipedia.org/",
          "label": "entry.entry2",
          "linkType": "BOTH"
        }
      ]
    }
  ],
  "locales": [
    {
      "language": "en",
      "i18n": {
        "menu1": {
          "title": {
            "single": "First menu"
          },
          "entry": {
            "single": "Single menu entry"
          }
        },
        "menu2": {
          "title": {
            "multi": "Second menu"
          },
          "entry": {
            "entry1": "First menu entry",
            "entry2": "Second menu entry"
          }
        }
      }
    },
    {
      "language": "fr",
      "i18n": {
        "menu1": {
          "title": {
            "single": "Premiere menu"
          },
          "entry": {
            "single": "Unique menu entry"
          }
        },
        "menu2": {
          "title": {
            "multi": "Deuxieme menu"
          },
          "entry": {
            "entry1": "Premiere menu entry",
            "entry2": "Deuxieme menu entry"
          }
        }
      }
    }
  ]
}

=== Operator Fabric theme

If the page opened via the menu is in a iframe, the current theme of operator fabric will be passed as a parameter in the request send to the web site. The parameter is named opfab_theme and has the value of the current theme : DAY, NIGHT or LEGACY. 

Example : 

....
 http://mysite.com/index.htm?opfab_theme=NIGHT 
....

When user is switching theme and the iframe is opened, the iframe will be reloaded.