// Copyright (c) 2021-2022 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

[[user_cards]]
= User cards

Using the `Create card` menu, the user can send cards to entities. This feature needs to be configured.


== Configure the bundle

A card is related to a process and a state, if you want users to be able to emit a card for a specific process and state,
you need to define it in the bundle for this process.

For example : 

....
"id": "conferenceAndITIncidentExample",
"name": "conferenceAndITIncidentExample.label",
"version": "1",
"states": {
  "messageState": {
    "name": "message.title",
    "userCard" : {
      "template" : "usercard_message",
      "severityVisible" : true,
      "startDateVisible" : true,
      "endDateVisible" : true,
      "lttdVisible" : false,
      "recipientList" : [{"id": "ENTITY_FR", "levels": [0,1]}, {"id": "IT_SUPERVISOR_ENTITY"}]
    },
    "templateName": "message",
    "styles": [],
    "acknowledgmentAllowed": "Always"
  }
}
....

In this example, the field userCard states that we have a template called `usercard_message` that defines how
the specific business input fields for this user card will be displayed in the card sending form that will be
presented to the user (through the `Create Card` menu).

This template works the same as templates for card presentation. Here is an example :

....

<div class="opfab-textarea">
    <label> MESSAGE </label>
    <textarea id="message" name="message" placeholder="Write something.."
        style="width:100%"> {{card.data.message}} </textarea>
</div>


<script>
    usercardTemplateGateway.getSpecificCardInformation = function () {
        const message = document.getElementById('message').value;
        const card = {
          summary : {key : "message.summary"},
          title : {key : "message.title"},
          data : {message: message}
        };
        if (message.length<1) return { valid:false , errorMsg:'You must provide a message'}
        return {
            valid: true,
            card: card
        };

    }
</script>
....


The first part defines the HTML for the business-specific input fields. It should only include the form
fields specific to your process, because the generic fields (like startDate , endDate , severity ... ) are presented
by default. It is possible to hide certain generic fields, by setting their visibility to false in the config.json
(for example field `severityVisible`).

Please note that you should use an OpFab css class so the "business-specific" part of the form has the same look and
feel (See
ifdef::single-page-doc[<<opfab_template_style, OperatorFabric Style >>]
ifndef::single-page-doc[<</documentation/current/reference_doc/index.adoc#opfab_template_style, OperatorFabric Style>>]
for more information)

[WARNING]
Be aware that as we have a preview of the card, the application loads the html related to the usercard (build with the usercard template) and the html related to the card in preview (build with the card template) into the browser at the same time. This implies that you MUST NOT name the elements with the same names in both templates. This rule applies to HTML elements identifiers(id), global JavaScript variables and JavaScript function names.



Once the card has been sent, users with the appropriate rights can edit it. If they choose to do so, they're presented
with the same input form as for the card creation, but the fields are pre-filled with the current data of the card.
This way, they can only change what they need without having to re-create the card from scratch.
That's what the reference to `{{card.data.message}}` is for. It means that this text-area input field should be filled
with the value of the field `message` from the card's data.

The second part is a javascript method you need to implement to allow OperatorFabric to get your specific data .

To have a better understanding of this feature, we encourage you to have a look at the examples in the OperatorFabric
core repository under (https://github.com/opfab/operatorfabric-core/tree/develop/src/test/resources/bundles/conferenceAndITIncidentExample[src/test/resources/bundles/conferenceAndITIncidentExample]).


== Method getSpecificCardInformation

The following card fields can be set via the object `card` in the object returned by method `getSpecificCardInformation`:

* title 
* summary
* startDate (epoch date in ms)
* endDate (epoch date in ms)
* lttd (epoch date in ms)
* keepChildCards
* secondsBeforeTimeSpanForReminder
* severity (in case it is not visible from the user , when `severityVisible` set to false in `config.json`)
* data
* entityRecipients (in case recipient list is not visible from the user)
* entitiesAllowedToEdit
* entitiesAllowedToRespond
* entitiesRequiredToRespond
* externalRecipients (use to send cards to third party , see 
ifdef::single-page-doc[<<define_a_third_party_tool, Define a third party tool >>]
ifndef::single-page-doc[<</documentation/current/reference_doc/index.adoc#define_a_third_party_tool, Define a third party tool>>]
for more information) . 

If you send a card to an ExternalRecipient, when the user delete it, the external recipient will receive the information via an HTTP DELETE request with the id of the deleted card at the end of the request (example : http://myexternal_app/myendpoint/ID_CARD).

If you want the card to be visible in the agenda feature, you need to set 'timeSpans' field (as array of TimeSpans objects) in the object returned by the method. 
You can find an example in the file:
https://github.com/opfab/operatorfabric-core/tree/master/src/test/resources/bundles/taskExample/template/usercard_task.handlebars[src/test/resources/bundles/taskExample/template/usercard_task.handlebars].

If not using 'timeSpans' it's possible to set the 'viewCardInAgenda' field to true, the card will be visible using card's startDate and endDate as default timeSpan.

The 'recurrence' field is deprecated and could be removed in the future.


If the form is not filled correctly by the user, you can provide an error message (see example above).
Again, have a look to the examples provided. 


== Define permissions

To send a user card, the user must be member of a group that has a perimeter defining the right `ReceiveAndWrite`
or `Write` for the chosen process and state. For example:

....
{
  "id" : "perimeterUserCard",
  "process" : "conferenceAndITIncidentExample",
  "stateRights" : [
    {
      "state" : "messageState",
      "right" : "ReceiveAndWrite"
    }
  ]
}
....


NOTE: Using the `ReceiveAndWrite` right instead of the `Write` right allows the user to receive the card they sent and
edit or delete it.

[[restrict_possible_recipients]]
== Restrict the list of possible recipients

When sending a user card, by default it is possible to choose the recipients from all the available entities. To limit the list of available recipients it is possible to configure the list of possible recipients via javascript in the user template 

For example : 

....
    usercardTemplateGateway.setDropdownEntityRecipientList([
            {"id": "ENTITY_FR", "levels": [0,1]},
            {"id": "IT_SUPERVISOR_ENTITY"}
        ]);
....


In this example the list of available recipients will contain: "ENTITY_FR" (level 0), all the first level children of "ENTITY_FR" (level 1) and "IT_SUPERVISOR_ENTITY".

[[preselect_initial_recipients]]
== Configure the list of initially selected recipients

It is possible to configure the list of initially selected recipients via javascript in the user template by implementing the `usercardTemplateGateway.setInitialSelectedRecipients(selectedEntities)` method. The method takes as input the list of Entity ids to be preselected.

For example : 

....
    usercardTemplateGateway.setInitialSelectedRecipients([
            "ENTITY_FR",
            "IT_SUPERVISOR_ENTITY"
        ]);
....


In this example the dropdown list of available recipients will have "ENTITY_FR" and "IT_SUPERVISOR_ENTITY" preselected. The user can anyway change the selected recipients.

[[set_recipients_via_code]]
== Set the list of recipients via the template and not via user choice 

To do that , you have to :

* hide the recipient dropdown using the attribute `recipientVisible` in state definition in config.json 
* provide the list of recipients when returning the card object in usercardTemplateGateway.getSpecificCardInformation() in the field entityRecipients 


Example:
....

    usercardTemplateGateway.getSpecificCardInformation = function () {
        const message = document.getElementById('message').value;
        const card = {
          summary : {key : "message.summary"},
          title : {key : "message.title"},
          entityRecipients: ["ENTITY_FR","IT_SUPERVISOR_ENTITY"],
          data : {message: message}
        };
        if (message.length<1) return { valid:false , errorMsg:'You must provide a message'}
        return {
            valid: true,
            card: card
        };

....


== Setting card dates
From the template it is possible to set the initial values for `startDate`, `endDate` and `lttd` fields of the card by calling the following functions: 

* _usercardTemplateGateway.setInitialStartDate(epochMs)_ 
* _usercardTemplateGateway.setInitialEndDate(epochMs)_ 
* _usercardTemplateGateway.setInitialLttd(epochMs)_  

It is also possible to get the values of  `startDate`, `endDate` and `lttd` by calling the following functions:

* _usercardTemplateGateway.getStartDate()_ 
* _usercardTemplateGateway.getEndDate()_
* _usercardTemplateGateway.getLttd()_  

== Setting initial card severity
From the template it is possible to set the initial value for card severity choice by calling the following function: 

* _usercardTemplateGateway.setInitialSeverity(severity)_ 

Allowed severity values are:

* 'ALARM'
* 'ACTION'
* 'INFORMATION'
* 'COMPLIANT'

== Card editing
Once a user card has been sent it can be edited by a user member of the publisher entity.
It is possible to allow other entities to edit the card by specifying the 'entitiesAllowedToEdit' card field.

== Get edition mode
The template can know if the user is creating a new card or editing an existing card by calling the _usercardTemplateGateway.getEditionMode()_ function. The function will return one of the following values:

* 'CREATE'
* 'EDITION'

An example of _usercardTemplateGateway.getEditionMode()_ usage can be found in the file
https://github.com/opfab/operatorfabric-core/tree/master/src/test/resources/bundles/messageOrQuestionExample/template/usercard_question.handlebars[src/test/resources/bundles/messageOrQuestionExample/template/usercard_question.handlebars].

== Get current process and current state of the card
The template can know the process and the state of the card by calling the _usercardTemplateGateway.getCurrentProcess()_ and _usercardTemplateGateway.getCurrentState()_ functions. These functions will return a string corresponding to the process id (or state id).

== Receiving emitter entity of the card
The template can receive the emitter entity of the card by implementing the _usercardTemplateGateway.setEntityUsedForSendingCard()_  function. 
This function will be called by OperatorFabric after loading the template and every time the card emitter changes (if the user can choose from multiple entities).

An example of _usercardTemplateGateway.setEntityUsedForSendingCard()_ usage can be found in the file
https://github.com/opfab/operatorfabric-core/tree/master/src/test/resources/bundles/defaultProcess_V1/template/usercard_message.handlebars[src/test/resources/bundles/defaultProcess_V1/template/usercard_message.handlebars].


== Send response automatically (experimental feature)

It is possible to configure a template to automatically send a response when sending a user card expecting an answers from one of the entities of the emitting user. 
The response card will be sent only if the user is enabled to respond to the card.
 
To enable the automated response the template should add a `childCard` field to the object returned by 
 `getSpecificCardInformation` method. For example:

....
 <script>
    usercardTemplateGateway.getSpecificCardInformation = function () {
        const card = {...}

        childCard : { 
          summary : {key : "exampe.summary"},
          title : {key : "example.title"},
          state : "mystateForResponse"
          data : {
                  // specific child  card date 
                  }
          };
        ...
        return {
            valid: true,
            card: card,
            childCard: childCard
        };

    }
  </script>
....

The card preview will display the card detail with the automated response as it will be displayed in Feed page.

When editing a user card, the template can get the response sent by current user by calling the _usercardTemplateGateway.getUserEntityChildCardFromCurrentCard()_ function. The function will return the response child card sent by current user or null if there is no response from current user.

An example of _usercardTemplateGateway.getUserEntityChildCardFromCurrentCard()_ usage can be found in the file
https://github.com/opfab/operatorfabric-core/tree/master/src/test/resources/bundles/messageOrQuestionExample/template/usercard_confirmation.handlebars[src/test/resources/bundles/messageOrQuestionExample/template/usercard_confirmation.handlebars].

== Misc

When a user send a card, it is always sent to himself whatever he chooses in the recipient list.

