// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.



= OperatorFabric Users Service

The User service manages users, groups and entities.

Users:: represent account information for a person destined to receive cards in the OperatorFabric instance.
Groups::
- represent set of users destined to receive collectively some cards.
- can be used in a way to handle rights on card reception in OperatorFabric.
Entities::
- represent set of users destined to receive collectively some cards.
- can be used in a way to handle rights on card reception in OperatorFabric.

WARNING: The user define here is an internal representation of the individual card recipient in `OperatorFabric` the authentication is leave to specific OAuth2 external service.

NOTE: In the following commands the `$token` is an authentication token currently valid for the `OAuth2` service used by the current `OperatorFabric` system.


== Users, groups and entities

User service manages users, groups and entities.

=== Users

Users are the individuals and mainly physical person who can log in OperatorFabric.

The access to this service has to be authorized, in the `OAuth2` service used by the current `OperatorFabric` instance, at least to access User information and to manage Users. The membership of groups and entities are stored in the user information.

==== Automated user creation

In case of a user does exist in a provided authentication service but he does not exist in the `OperatorFabric` instance, when he is authenticated and connected
for the first time in the `OperatorFabric` instance, the user is automatically created in the system without attached group or entity.
The administration of the groups and entities is dealt by the administrator manually. More details about automated user creation
ifdef::single-page-doc[<<opfab_spec_conf, here>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/deployment/index.adoc#opfab_spec_conf, here>>]
.

=== Groups
opfab_spec_conf
The notion of group is loose and can be used to simulate role in `OperatorFabric`.
Groups are used to send cards to several users without a name specifically. The information about membership to a
group is stored in the user information. The rules used to send cards are described in the
ifdef::single-page-doc[<<card_recipients, recipients section>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference/index.adoc#card_recipients, recipients section>>]
.

=== Entities
Entities are used to send cards to several users without a name specifically. The information about membership to an
entity is stored in the user information. The rules used to send cards are described in the
ifdef::single-page-doc[<<card_recipients, recipients section>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference/index.adoc#card_recipients, recipients section>>]
.

==== Alternative way to manage groups

The standard way to handle groups in `OperatorFabric` instance is dealt on the user information.
There is an alternative way to manage groups through the authentication token, the groups are defined by the
administrator of the authentication service.
See
ifdef::single-page-doc[<<opfab_spec_conf, here>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/deployment/index.adoc#opfab_spec_conf, here>>]
for more details to use this feature.
