// Copyright (c) 2018-2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0



[[users_management]]
= User management 

The User service manages users, groups, entities and perimeters (linked to groups).

Users:: represent account information for a person destined to receive cards in the OperatorFabric instance.
Entities::
- represent set of users destined to receive collectively some cards.
- can be used to model organizations, for examples : control center, company , department... 
- can be used in a way to handle rights on card reception in OperatorFabric.
- can be inside another entity (via the notion of parent entity)
Groups::
- represent set of users destined to receive collectively some cards.
- has a set of perimeters to define rights for card reception in OperatorFabric.
- can be used to model roles in organizations, for examples : supervisor, dispatcher ... 

WARNING: The user define here is an internal representation of the individual card recipient in `OperatorFabric` the authentication is leave to specific OAuth2 external service.

NOTE: In the following commands the `$token` is an authentication token currently valid for the `OAuth2` service used by the current `OperatorFabric` system.


== Users, groups, entities and perimeters

User service manages users, groups, entities and perimeters.

=== Users

Users are the individuals and mainly physical person who can log in OperatorFabric.

The access to this service has to be authorized, in the `OAuth2` service used by the current `OperatorFabric` instance, at least to access User information and to manage Users. The membership of groups and entities are stored in the user information.

NOTE: User login must be lowercase. Otherwise, it will be converted to lowercase before saving to the database.


==== Automated user creation

In case of a user does exist in a provided authentication service but he does not exist in the `OperatorFabric`
instance, when he is authenticated and connected for the first time in the `OperatorFabric` instance, the user is
automatically created in the system without attached group or entity.
The administration of the groups, entities and perimeters is dealt by the administrator manually.
More details about automated user creation
ifdef::single-page-doc[<<opfab_spec_conf, here>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/deployment/index.adoc#opfab_spec_conf, here>>]

=== Entities
The notion of entity is loose and can be used to model organizations structures(examples : control center, company , department... ).
Entities are used to send cards to several users without a name specifically. The information about membership to an
entity is stored in the user information. An entity can be included in another entities using the  array field named `parents`, this feature permits to send card to a group of entities without having to define the detail list of entities for each card to send.


Examples using entities can be found 
ifdef::single-page-doc[<<_send_to_several_users, here>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#_send_to_several_users, here>>]
.

=== Groups
The notion of group is loose and can be used to simulate role in `OperatorFabric` (examples : supervisor, dispatcher ... ).
Groups are used to send cards to several users without a name specifically. The information about membership to a
group is stored in the user information. A group contains a list of perimeters which define the rights of reception/writing for a couple process/state. The rules used to send cards are described in the
ifdef::single-page-doc[<<card_recipients, recipients section>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/reference_doc/index.adoc#card_recipients, recipients section>>]
.
.

=== Perimeters
Perimeters are used to define rights for reading/writing cards. A perimeter is composed of an identifier (unique), a process name and a list of state/rights couple.
Possible rights for receiving/writing cards are :

- Receive : the rights for receiving a card
- Write : the rights for writing a card, that is to say respond to a card or create a new card
- ReceiveAndWrite : the rights for receiving and writing a card

=== Alternative way to manage groups and entities

The standard way to handle groups and entities in `OperatorFabric` instance is dealt on the user information.
There is an alternative way to manage groups and entities through the authentication token, the groups and entities are defined by the administrator of the authentication service.
See
ifdef::single-page-doc[<<jwt_mode, here>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/deployment/index.adoc#jwt_mode, here>>]
for more details to use this feature.
