// Copyright (c) 2018, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

=== Business Goals

==== Reduce cost integration of new Service (BCL-G-01)[[BCL-G-01, Reduce cost integration of new Service]]
To offer a mean to integrate new 3rd Party Information Systems to the operating
station in an uniform and integrated way to reduce the future cost of
integrating new services.

==== Reduce cost integration of new Business Process (BCL-G-02)[[BCL-G-02, Reduce cost integration of new Business Process]]
To offer a mean to integrate new 3rd Party Information Systems’ business
processes to the operating station. This should allow to integrate new tasks
in a uniform and centralized way to the operator tasks.

==== Unify user experience (BCL-G-03)[[BCL-G-03, Unify user experience]]
To offer a complete and centralized user experience around a holistic view of
running processes with a focus on what is specifically necessary to the user
accessing the view.