=== Business Roles

We limit business roles to the high level business role, it is not the purpose
of this document to delve into specific Business Process implementation
defined during the lifetime of the system

==== Administrator
Description:: Administer the system
Type:: Human
Access:: Intranet
Degree of confidence:: High
Location::
Number:: 1-2

==== Business Actor
Description:: Interrats with a business process
Type:: Human or Service
Access:: Mobile, Intranet, Internal
Degree of Confidence:: Medium
Location::
Number:: ??

==== Operator
Description:: Operates the systems, consult published information from business
process and interract with business process
Service business process instances.
Type:: Human
Access:: Mobile, Intranet
Degree of confidence:: Medium
Location:: Operating room
Number:: ?
Parent Role:: <<Business Actor>>

==== 3rd Party Information Service
Description:: Initiate Process instances and interacts with it. Performs
computation for business processes
Type:: Service
Access:: Internal
Degree of confidence:: Medium
Location::
Number:: ?
Parent Role:: Business Actor