// Copyright (c) 2018, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

=== Business Roles

We limit business roles to the high level business role, it is not the purpose
of this document to delve into specific Business Process implementation
defined during the lifetime of the system

==== Administrator Role
Description:: Administer the system
Type:: Human
Access:: Intranet
Degree of confidence:: High
Location::
Number:: 1-2

==== Business Actor Role
Description:: Interrats with a business process
Type:: Human or Service
Access:: Mobile, Intranet, Internal
Degree of Confidence:: Medium
Location::
Number:: ??

==== Operator Role
Description:: Operates the systems, consult published information from business
process and interract with business process
Service business process instances.
Type:: Human
Access:: Mobile, Intranet
Degree of confidence:: Medium
Location:: Operating room
Number:: ?
Parent Role:: <<Business Actor Role>>

==== ThirdParty Information Service Role
Description:: Initiate Process instances and interacts with it. Performs
computation for business processes
Type:: Service
Access:: Internal
Degree of confidence:: Medium
Location::
Number:: ?
Parent Role:: <<Business Actor Role>>