// Copyright (c) 2018, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

ifndef::imagesdir[:imagesdir: ../images]
=== Business Objects

==== Business Process Definition
Description:: Defines a process. A process describes interractions between
<<Operators Role, Operators>> and <<ThirdParty Information Service Role, ThirdParty Information Services>>
using a business workflow. An effective process realization is called a
<<Business Process Instance>>. Business Process Definition are defined by
<<Third Party Information Service, Third Party Information Services>>
+
Business process definitions have the following characteristics:
[cols=2*,options="header"]
|===
|Characteristic|Description
|id|Business Process Definition needs to be uniquely identified at business level
|version
|Multiple version of the same Business Process Defintion may cohabit in the system
Business process definition version is correlated to its associated
<<ThirdParty Information Service>>
|Representation| A Business Process Definition Instance defines representation of its data in
the <<Operator Roles>> end user interface
|===

==== Business Process Instance
Description:: A Business process Instance is the effective realization of a
<<Business Process Definition>>.
|===
|Characteristic|Description
|Business Process Definition|A business Process Instance is relative to a specific Business Process Definition version
|id|Business Process Instance needs to be uniquely identified at business level, for its associated definition
|===

==== Card
Description:: Cards are data object encapsulating the current state of a
<<Business Process Instance>>.
+
All cards have the following characteristics:
+
[cols=2*,options="header"]
|===
|Characteristic|Description
|publishing date|The date when the card was introduced in the information system
|process instance|A card is tied to a specific business process instance
|Time
a|A card must be associated to time information. There are different time indication.

* publication: input in the system
* validity: time frame when the card is relevant
* notification: time information to determine when the <<Operator>> is to be notified (may be recurring)
* actionnability: the last time some action may be triggered on the process state associated with the card
|Business Data| Arbitrary data may be attached to card
|Representation| The card contains clues on how to represent attached data in the Operator end user interface
|Actions| The card contains clues on what interaction with the <<Business Process Instance>> is available to <<Operator, Operators>>
|Recipient| The card contains clues on who is allowed to see the card
|===

==== Feed Subscription
Description:: Gathers characteristics of which <<Card>> ensemble an <<Operator>>
is currently following. It relies on the <<Operator>> Characteristics and a
time frame.
+
User is following the <<Card, cards>> he is a recipient for in a specific time frame.

==== User
Description:: a User is the internal description of a human actor
(<<Operator>>; <<Administrator>>; See <<Business Roles>>)

==== Group
Description:: Group are ensemble of <<User, Users>>, one <<User>> may belong to multiple Groups

==== ThirdParty Information Service
Description:: a ThirdParty Information Service is the internal description
of a ThirdParty actor (<<ThirdParty Information Service>>; See
<<Business Roles>>).
+
ThirdParty Information Service has the following characteristics
+
[cols=2*,options="header"]
|===
|id|ThirdParty Information Services are uniquely defined
|version| Multiple version of the same ThirdParty Information Service may coexist
|Business Process|<<Business Process Definition, Business process Definitions>> are associated to a ThirdParty Information Service
|authentication| Security means to ensure 
|===