// Copyright (c) 2018, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

ifndef::imagesdir[:imagesdir: ../images]
=== Technical Services

Technical services are non business automated services that intervene into business functionnalities

==== Persistence Service

Responsible for data persistence / data retrieval.

==== Asynchronous Communication Service

Responsible for service asynchronous communication.

==== Synchronous Communication Service

Responsible for service asynchronous communication.

==== Authentication Service

Responsible for user authentication and authorization.

==== User Management Service

Responsible for user management and user personal settings.

==== Monitoring Service

Responsible for global system monitoring.

==== Backup Restore Service

Responsible for backup and restore of system persisted data.