/* Copyright (c) 2018-2025, RTE (http://www.rte-france.com)
 * See AUTHORS.txt
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 * SPDX-License-Identifier: MPL-2.0
 * This file is part of the OperatorFabric project.
 */

package org.opfab.cards.consultation.controllers;

import org.opfab.users.model.CurrentUserWithPerimeters;
import java.time.Instant;

@SuppressWarnings("java:S1104") // it is just a data object , we choose to have all fields public for simplicity
public class CardOperationsGetParameters {
    /**
     * Whether it should be updated with new cards : if false, cards will be queried
     * only once, from the database, if true, it starts a subscription
     */
    public boolean notification;
    /**
     * Unique autogenerated ID to identify client and avoid re-creating a
     * subscription in case of short network unavailability for example
     */
    public String clientId;

    /**
     * UI version, if different from backend version will trigger a UI reload event
     */
    public String uiVersion;

    public Instant rangeStart;
    public Instant rangeEnd;
    public Instant updatedFrom;
    /**
     * Filter only cards for which this user is a recipient
     */
    public CurrentUserWithPerimeters currentUserWithPerimeters;

}
