// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

:sectnums:

= OperatorFabric Core User Interface

This project was partially generated with https://github.com/angular/angular-cli[Angular CLI] version 6.0.8. 

IMPORTANT: In the following document the variable declared as `OF_HOME` is the root folder of the `operator fabric core project`.

[horizontal]
CLI:: stands for *Command Line Interface*
SPA:: stands for *Single Page Application*
OS:: stands for *Operating System*

== Run

=== Linux

After launching docker containers, use the following command line `$OF_HOME/bin/run_all.sh start` to run the application.
Once the whole application is ready, you should have the following output in your terminal:

[source]
----
##########################################################
Starting client-gateway-cloud-service, debug port: 5008

##########################################################
pid file: $OF_HOME/services/infra/client-gateway/build/PIDFILE
Started with pid: 7479

##########################################################
Starting users-business-service, debug port: 5009

##########################################################
pid file: $OF_HOME/services/core/users/build/PIDFILE
Started with pid: 7483

##########################################################
Starting time-business-service, debug port: 5010

##########################################################
pid file: $OF_HOME/services/core/time/build/PIDFILE
Started with pid: 7488

##########################################################
Starting cards-consultation-business-service, debug port: 5011

##########################################################
pid file: $OF_HOME/services/core/cards-consultation/build/PIDFILE
Started with pid: 7493

##########################################################
Starting cards-publication-business-service, debug port: 5012

##########################################################
pid file: $OF_HOME/services/core/cards-publication/build/PIDFILE
----

Wait a moment before trying to connect to the`SPA`, leaving time for the`client-gateway` to boot up completely.

The `SPA`, on a local machine, is available at the following Url: `http://localhost:2002/ui/`.

To log in you need to use a valid user. Currently you need to use a connection pair define in `$OPERATOR_FABRIC_HOME/services/infra/auth/src/main/java/org/lfenergy/operatorfabric/auth/config/WebSecurityConfiguration.java`. It could be `admin` with `test`, for example.

To test the reception of cards, you can use the following script to create dummy cards:

[source]
----
$OF_HOME/services/core/cards-publication/src/main/bin/push_cards_loop.sh
----

Once logged in, with that script running in the background, you should be able to see some cards displayed in `http://localhost:2002/ui/feed`.

=== Windows

No script helpers provided for this OS. 

== Build

Run `ng build` to build the project. The build artifacts will be stored in :

[source,shell]
----
$OPERATOR_FABRIC_CORE_HOME/services/web/web-ui/build/src/generated/resources/static
----

== Test

=== Standalone tests

Run in the `$OF_HOME/ui/main` directory the command `ng test --watch=false` to execute the unit tests based on https://jasmine.github.io[Jasmine] using https://karma-runner.github.io[Karma] to drive the browser.

=== Test during UI development

. if the RabittMQ and MongoDB docker containers are not not running, launch them;
. set your environment variables with `. $OF_HOME/bin/load_environment_light.sh`;
. run the micro services using the same command as earlier: `$OF_HOME/bin/run_all.sh start`;
. if needed, enable a card-operation test flow using the script `$OF_HOME/service/core/cards-publication/src/main/bin/push_cards_loop.sh`;
. launch an angular server with the command: `ng serve`;
. test your changes in your browser using this url: `http://localhost:4200` which leads to `http://localhost:4200/#/feed`.

== Known Bugs

=== Login Page

* no error message displayed on wrong identification;

=== Light Card flow

* no unsubscription on logout;