// Copyright (c) 2018, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

ifndef::imagesdir[:imagesdir: ../../images]

==== Card Business Service

===== To Consult the Card Feed
Actors:: Operator
Description:: Access the feed of cards which display cards with a focus and the
operator needs to accomplish its tasks. The feed of card is an interface that
allows an Operator to consult a list of previously published cards that is
continuously updated with new cards. Cards represent a state in a business
process.

Pre requisite:: Authenticated user (see <<To Authenticate>>)

.Nominal Scenario
. Access the main operator-fabric ui to display the feed of cards

.Extended Scenario
Adjust the focus on the feed:

* With temporal filter adjustment (defaults to : from now to +24 hour);;.
* With recipient adjustment (defaults to only cards where the user is main recipient)
* With type adjustment through the use of tag filters

[NOTE]
====
The filters may impact the two complementary aspects of the feed:

* previously published cards;
* card updates;

This interraction will be depicted later in the document
====

===== To Consult the Timeline

Actors:: Operator
Description::
Pre requisite:: Authenticated user (see <<To Authenticate>>)

===== To Consult a Card
Actors:: Operator, 3rd Party IS (Secondary in extended scenario)
Description:: Access a specific card associated business content called details
Pre requisite:: Authenticated user (see To Authenticate)

.Nominal Scenario
. Select a card in the feed to display its associated details

.Extended Scenario
Details can be of two types:

* Templated details are a predefined rendering of the card associated business data;
* Embedded frame details are embedded frames loading a 3rd Party IS defined web page.

===== To Consult the Card Archive
Actors:: Operator
Description:: Access previously published cards
Pre requisite:: Authenticated user (see To Authenticate)

.Nominal Scenario
. Input search criteria
. Consult results

.Extended Scenario
[start=2]
 . Consult result
 . Navigate throught result pages