// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

:sectnums:

= OperatorFabric - Core - Time Management Service

This sub project manages OperatorFabric reference time.

== Set up and Build

see link:../../..[OperatorFabric main page]

== Features

This service allows to manage the reference time of OperatorFabric services along
with the speed of the time flow. This service doesn't allow translation of
Third party services provided data. The (not mandatory) time synchronization
is the sole responsibility of the third party services

== Rest Endpoints and Data Model

See https://opfab.github.io/projects/services/core/time/1.1.0.SNAPSHOT/api/index.html[swagger generated documentation]

== Disclaimer

The deprecated GridOS project included features
to fast-forward (resp. rewind) time up to the start time of the next card (resp. back to the last card). These features haven't been implemented yet.
