// Copyright (c) 2018, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

=== Constraints

==== Usage of open source technologies
Priority:: High
Impact::
Make technical choice in a refined candidate technologies. Technical choices
will avoid proprietary solutions for software architecture but may rely on not
complying solutions when it comes to specific deployments. When it comes to
friction with external IT solution or deployment solutions, the solution must
enforce widespread standards and protocols.

==== Usage of referenced technologies
Priority:: Low
Impact::
Make technical choice in a refined candidate technologies. RTE has its internal
set of validated technologies it would allow to run on its technical
infrastructure. This must be regarded has guideline rather then absolute
constraint has it’s meant to also be deployed outside of RTE infrastructure.
Also note that this rules may be circumvent by the usage of container
technologies to isolate new technologies (virtualization, docker, ...)

==== Open source project
Priority:: High
Impact:: Must comply to a chosen open source license (MPL v2.0), integrated
components must be compatible with the same license. Specifically we also want
to trace restrictive licensed components such as GPL components.

==== Integrate with varying existing infrastructure
Priority:: High
Impact:: This is an emanation of tue “No finite target audience” risk. We must
define outside components which would cope with Operator-Fabric and enforce
well known and widely adopted standards and protocols. For instance we will
enforce OAuth2 authentication has the authentication mean to integrate with
existing authentication solution or allow bridge implementation between OAuth2
and other standards or specific organization authentication.

==== Available skill pool
Priority:: Medium
Impact:: Technical choices must conform as much as possible to the available
pool of developer which are mainly java developers. Choices may be done outside
this scope but the learning phase must be taken into account.