// Copyright (c) 2023 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 3.14.0 to release 3.15.0

== CrossOrigin for GeoJSON

The option `feed.geomap.layer.geojson.crossOrigin`, used to set a cross-origin option when downloading GeoJSON, has been removed.

== Remove deprecated field from state definition
The deprecated field `recipientList` has been removed from card state definition.
To restrict the recipient list options use the method `usercardTemplateGateway.setDropdownEntityRecipientList` in template.

== Remove use of groups column in realtime screen
The field `groups` has been removed from the object `entitiesGroups` of the configuration file `realtimescreens.json`.
To conform to this new structure, you have to remove this field from your configuration file.