// Copyright (c) 2024 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 4.4.X to release 4.5.0


== Use of `docker compose v2`

OperatorFabric is now using `docker compose v2`, so you have to upgrade this tool to continue using opfab.
You can find more information in the docker documentation : https://docs.docker.com/compose/migrate/

== Use of `date-fns` instead of `Moment.js` library

OperatorFabric is now using `date-fns` library instead of `Moment.js`. The format used for defining a formatted date string
is now different. So, if needed, in the file `web-ui.json`, you have to modify your fields : `settings.dateTimeformat`
and `settings.dateFormat`. You can find the available formats here : https://date-fns.org/v3.6.0/docs/format

== Deletion of the parameter `secondsAfterPublicationToConsiderCardAsNotRead`

OperatorFabric is now sending emails whether a card is read or not. So, the parameter
`secondsAfterPublicationToConsiderCardAsNotRead` having become useless, it was deleted, and
you can safely remove it from your configuration file.

== UI Configuration
Some fields of the `web-ui.json` file have changed and renamed:

* `alerts.messageBusinessAutoClose` has been renamed as `alerts.alarmLevelAutoClose`
* `alerts.hideBusinessMessages` has been renamed as `alerts.doNotAlertForHiddenCardReceived`

== Process monitoring configuration
The configuration for process monitoring screen has been removed from `web-ui.json` and externalized in a dedicated JSON file. The process monitoring configuration file has to be loaded by sending an HTTP POST request to the `/processmonitoring` API of businessconfig service or using the CLI command `opfab processmonitoring load <file>`.
The structure of the process monitoring configuration fields has to be modified as follows:

- "fieldsForProcesses" is now an array of objects with "process" and "fields" fields.

- The "size" attribute in now a number, not a string as before

- "filters" is now an object with "pageSize" and "tags" fields

So for example the configuration should be changed from:
[source,json] 
----
"fieldsForProcesses": {
      "conferenceAndITIncidentExample" : [
        { "field": "startDate", "type": "date", "colName": "Start Date", "size": "200"},
        { "field": "titleTranslated", "colName": "Title", "size": "250"},
        { "field": "entityRecipients", "type": "array", "colName": "Entity Recipients", "size": "400"}
      ],
      "messageOrQuestionExample" : [
        { "field": "startDate", "type": "date", "colName": "Start Date", "size": "200"},
        { "field": "endDate", "type": "date", "colName": "End Date", "size": "200"},
        { "field": "titleTranslated", "colName": "Title", "size": "250"},
        { "field": "entityRecipients", "type": "array", "colName": "Entity Recipients", "size": "400"}
      ]
    },
    "filters": {
      "tags": {
        "list": [
          {
            "label": "Label for tag 1",
            "value": "tag1"
          },
          {
            "label": "Label for tag 2",
            "value": "tag2"
          }
        ]
      },
      "page": {
        "size": 10
      }
    }
----

to 

[source,json] 
----
   "fieldsForProcesses": [
      {
        "process": "conferenceAndITIncidentExample",
        "fields" : [
        { "field": "startDate", "type": "date", "colName": "Start Date", "size": 200},
        { "field": "titleTranslated", "colName": "Title", "size": 250},
        { "field": "entityRecipients", "type": "array", "colName": "Entity Recipients", "size": 400}
      ]}, {
        "process" : "messageOrQuestionExample",
        "fields" : [
        { "field": "startDate", "type": "date", "colName": "Start Date", "size": 200},
        { "field": "endDate", "type": "date", "colName": "End Date", "size": 200},
        { "field": "titleTranslated", "colName": "Title", "size": 250},
        { "field": "entityRecipients", "type": "array", "colName": "Entity Recipients", "size": 400}
      ]}
    ],
    "filters": {
      "tags": [
          {
            "label": "Label for tag 1",
            "value": "tag1"
          },
          {
            "label": "Label for tag 2",
            "value": "tag2"
          }
        ],
        "pageSize": 10
      }
----
