// Copyright (c) 2025 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 4.8.X to release 4.9.0

== Geomap configuration 

As a new layer type (`wmts`) has been added, the geomap configuration has been updated for improved clarity in layer management. All layers are now stored in a single property.

You must update your configuration to match this new structure.


The layers and tiles of the map can now be configured using the `feed.geomap.layers` property. This property accepts an array of objects, each representing a layer with a `type` property and additional configuration options depending on the layer type. The following layer types are supported:

    - `osm`: OpenStreetMap tiles. No additional configuration required.
    - `geojson`: GeoJSON layers. Requires a `url` for the GeoJSON file and optionally a `style` object for feature styling. The `style` object supports stroke, fill, image, and text styles as defined in the OpenLayers flat style format (see: https://openlayers.org/en/latest/apidoc/module-ol_style_flat.html).
    - `xyz`: XYZ tiles. Requires a `url` endpoint with `{x}`, `{y}`, and `{z}` variables (e.g., "https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/grijs/EPSG:3857/{z}/{x}/{y}.png"). You may also specify:

        ** `tileSize`: Integer value (e.g., 256). Required for custom background layers.
        ** `crossOrigin`: Optional. Default is `null`.
    - `wmts`: WMTS layers. Requires `capabilitiesUrl`, `layer`, and `matrixSet`.

Example configuration for the `feed.geomap.layers` property:
```
"layers": [
                {
                    "type":"osm"
                },
                {
                    "type":"wmts",
                    "capabilitiesUrl":"https://data.geopf.fr/annexes/ressources/wmts/essentiels.xml",
                    "layer":"CADASTRALPARCELS.PARCELLAIRE_EXPRESS",
                    "matrixSet":"PM_0_19"
                },
                {
                    "type": "geojson",
                    "url": "https://opendata.agenceore.fr/api/explore/v2.1/catalog/datasets/reseau-aerien-haute-tension-htb/exports/geojson?lang=fr&timezone=Europe%2FBerlin",
                    "style": {
                        "stroke-color": "red"
                    }
                },
                {
                    "type": "geojson",
                    "url": "assets/layers/geojson-layer2.json"
                }

            ]


```

== Entities in Token

When retrieving entities from a token, the recommended approach is to use an array attribute containing entity IDs as strings. The previous method, which uses a single string with semicolon-separated IDs, remains available for backward compatibility. To enable the old mode, set the parameter `operatorfabric.security.jwt.entitiesIdClaimSingleString` to `true` in your YAML services configuration.

== Deletion of monitoring screen

The monitoring screen is not needed anymore as a similar screen can be defined via custom screens.
Here is a custom screen configuration that can replace the monitoring screen :

```
{
    const CustomScreenMonitoring = {
        id: 'monitoringId',
        name: 'monitoring',
        headerFilters: ['PROCESS', 'TYPE_OF_STATE', 'RESPONSE_FROM_MY_ENTITIES'],

        results: {
            columns: [
                {
                    field: 'severity',
                    cardField: 'severity',
                    fieldType: 'SEVERITY'
                },
                {
                    field: 'TIME',
                    headerName: 'TIME',
                    cardField: 'publishDate',
                    fieldType: 'DATE_AND_TIME',
                    minWidth: 150,
                    flex: 0.5
                },
                {
                    field: 'title',
                    headerName: 'TITLE',
                    cardField: 'titleTranslated',
                    fieldType: 'STRING',
                    flex: 1,
                    minWidth: 150
                },
                {
                    field: 'summary',
                    headerName: 'SUMMARY',
                    cardField: 'summaryTranslated',
                    fieldType: 'STRING',
                    flex: 2,
                    minWidth: 150,
                    showTooltips: true
                },
                {
                    fieldType: 'TYPE_OF_STATE',
                    headerName: 'PROCESS STATUS',
                    flex: 0.6,
                    minWidth: 150
                },
                {
                    field: 'publisher',
                    headerName: 'EMITTER',
                    cardField: 'publisher',
                    fieldType: 'PUBLISHER',
                    flex: 1,
                    minWidth: 150
                },
                {
                    headerName: 'ANSWERS',
                    fieldType: 'RESPONSES',
                    flex: 2,
                    minWidth: 400
                }
            ]
        }
    };
    opfab.businessconfig.registerCustomScreen(CustomScreenMonitoring);
}
```

