// Copyright (c) 2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 2.3.0 to release 2.4.0

== Send card 

The API does not provide an endpoint to send an array of cards anymore.

- The endpoint `cards` now accepts only one card
- The endpoint `async/cards` no longer exists

So if you used to send several cards as array, you need to modify your code to send hem one by one via endpoint `cards`.

== Package name change

The name of the packages in the OperatorFabric code has been changed from `org.lfenergy.operatorfabric.*` to
`org.opfab.*` in preparation for an upload of the client library to Maven Central.
You need to update any code using the client library to reflect this name change.