// Copyright (c) 2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 2.10.0 to release 3.0.0

== New bundle structure

The bundle contains a new i18n.json file in the root directory. The i18n.json file contains internationalization information for title and summary fields.

=== Template directory

The `template` directory does not contain language repository anymore. There is one template per process/state
 and the templates are located directly in this directory.

Therefore, the enpoint to get a template has been modified. Till now, you could set 2 query parameters,
`version` and `locale`, now you can set only `version` parameter.

== Process bundles

In order to remove unnecessary complexity for third-party, we have decided to remove translation for
some of business data.
For process bundles, in the `config.json` file, here are the affected fields :

* Process name
* State name
* State description

These fields must not contain i18n data anymore, they must only contain string data. These data will be
simply displayed on the screen.

== Processes groups

We have also decided to remove locale mechanism in processes groups.
So there is no possibility anymore to have translation for the process group name. You can just define
the name of the group in the uploaded file. Here is an example of this file :
[source,json]
----
{
  "groups": [
    {
      "id": "processgroup1",
      "name": "Process Group 1",
      "processes": [
        "process1",
        "process2"
      ]
    },
    {
      "id": "processgroup2",
      "name": "Process Group 2",
      "processes": [
        "process3",
        "process4"
      ]
    }
  ]
}

----

== Configuration file `web-ui.json`

Some attributes have been renamed to be more consistent with their meaning.
Here are these attributes :

* `settings.infos.description` renamed `settings.infos.hide.description`
* `settings.infos.language` renamed `settings.infos.hide.language`
* `settings.infos.timezone` renamed `settings.infos.hide.timezone`
* `settings.infos.tags` renamed `settings.infos.hide.tags`
* `settings.infos.sounds` renamed `settings.infos.hide.sounds`

So if you use these fields in `web-ui.json` file, you have to rename them.

== Script to migrate an existing database

Opfab 3.0 needs two new fields in database : `titleTranslated` and `summaryTranslated`.
In order to add these two new fields to an existing database, you have to pull the image `migration-opfab3`,
go to the directory `OF_HOME/src/tooling/migration-opfab3` and execute the script `docker-compose.sh`, this way :

`./docker-compose.sh <containerNameMongoDB> <portMongoDB> <loginMongoDB> <passwordMongoDB> <pathToBundlesDirectory>`

WARNING: The bundles directory is the directory where you store all the "untar" bundles in the new
format with the `i18n.json` file. It is not the directory where the opfab instance stores the bundles.


