// Copyright (c) 2024 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 4.3.X to release 4.4.0

== Endpoints configuration 

To enhance consistency and avoid confusion, we made the following modifications to the endpoints:

  - When accessed via `web-ui`(nginx), the endpoint `/cards` has been replaced by `/cards-consultation`.
  - When accessed via `web-ui`(nginx), the endpoint `/cardspub` has been replaced by `/cards-publication`.
  - The base path for accessing the `businessconfig` service directly (without passing through `web-ui`) has been changed from `/businessconfig` to `/`.
  - Added endpoints `/cards-reminder` and `/cards-external diffusion` to access cards-reminder and cards-external diffusion services via nginx for opfab cli

Please note that the old endpoint `/businessconfig` is still available but will be removed in a future release.

We have simplified our nginx reference configuration. Instead of adjusting your configuration for the new release, you can rebuild your configuration using the new reference configuration (located at `config/docker/nginx.conf`) and adapt it to your specific needs.

If you prefer to adapt your existing file, the following changes should be made:


For example, consider this configuration:
....
  location /cards/ {
    proxy_buffering off;
    proxy_set_header Host $http_host;
    proxy_pass http://cards-consultation:2104/;
    proxy_set_header X-Forwarded-For $remote_addr;
  }

  location /cardspub/cards {
    proxy_set_header Host $http_host;
    proxy_pass http://cards-publication:2102/cards;
    proxy_set_header X-Forwarded-For $remote_addr;
  }

   location /businessconfig {
    gzip on;
    gzip_types application/json;
    proxy_set_header Host $http_host;
    proxy_pass http://businessconfig:2100;
    proxy_set_header X-Forwarded-For $remote_addr;
    client_max_body_size 100M;
  }
....

This should be changed to:

....
  location /cards-consultation/ {
    proxy_buffering off;
    proxy_set_header Host $http_host;
    proxy_pass http://cards-consultation:2104/;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
 
  location /cards-publication/ {
    proxy_set_header Host $http_host;
    proxy_pass http://cards-publication:2102/;
    proxy_set_header X-Forwarded-For $remote_addr;
  }

  location /businessconfig/ {
    gzip on;
    gzip_types application/json;
    proxy_set_header Host $http_host;
    proxy_pass http://businessconfig:2100/;
    proxy_set_header X-Forwarded-For $remote_addr;
    client_max_body_size 100M;
  }

  location /cards-external-diffusion/ {
    proxy_set_header Host $http_host;
    proxy_pass http://cards-external-diffusion:2106/;
    proxy_set_header X-Forwarded-For $remote_addr;
  }

  location /cards-reminder/ {
    proxy_set_header Host $http_host;
    proxy_pass http://cards-reminder:2107/;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
....


For a smooth, real-time migration, you can temporarily keep endpoints '/cards' and '/cardspub' in your Nginx configuration and remove the old one after a while.

If you are using the `businessconfig` service directly via some scripts, you need to update these scripts.


