// Copyright (c) 2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 1.7.0 to release 1.8.0 

== Refactoring of business configuration 

=== Motivation for the change
There is no more the need for multiple definitions of card's detail rendering because of the removal of multitab rendering.

The rendering of the detail of a card is configured specifing the detail title, template name and the list of styles.

=== Changes to the model

==== On the Businessconfig model
In the Businessconfig model definition the field `details` has been removed.

The new fields `datailTitle`, `templateName` and `styles` have been added.

Here is an example of a simple config.json file:

.Before
[source,json]
----

{
  "id": "TEST",
  "version": "1",
  "name": "process.label",
  "defaultLocale": "fr",
  "menuLabel": "menu.label",
  "menuEntries": [
    {"id": "uid test 0","url": "https://opfab.github.io/","label": "menu.first"},
    {"id": "uid test 1","url": "https://www.la-rache.com","label": "menu.second"}
  ],
  "states": {
    "firstState": {
      "name" :"mystate.label",
      "details": [
        {
          "title": {
            "key": "template.title"
          },
          "templateName": "operation",
		  "styles": ["style1","style2"]
        }
      ]
    }
  }
}

----

.After
[source,json]
----

{
  "id": "TEST",
  "version": "1",
  "name": "process.label",
  "defaultLocale": "fr",
  "menuLabel": "menu.label",
  "menuEntries": [
    {"id": "uid test 0","url": "https://opfab.github.io/","label": "menu.first"},
    {"id": "uid test 1","url": "https://www.la-rache.com","label": "menu.second"}
  ],
  "states": {
    "firstState": {
      "name" :"mystate.label",
	  "detailTitle": {
		"key": "template.title"
	  },
	  "templateName": "operation",
	  "styles": ["style1","style2"]
    }
  }
}
----
