// Copyright (c) 2024 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 4.2.0 to release 4.3.0


== ADMIN group 
Users belonging to 'ADMIN' group will not be automatically given admin rights anymore.
The admin rights will be set only if user is member of a group with ADMIN permission.

IMPORTANT: Before initiating the migration process, ensure that all users with administrative privileges are members of a group that has been explicitly granted the 'ADMIN' permission. Failing to do so may result in loss of the ability to administrate operator fabric

== Map multiple GeoJSON layers
It is now possible to add more than one GeoJSON layer to the map. To allow the configuration of multiple layers the `feed.geomap.layer.geojson` configuration parameter in web-ui.json is now an array. for each layer it is possible to specify the url and an optional style. The style object can have styling properties for stroke, fill, image, and text styles as defined in OpenLayer flat style (https://openlayers.org/en/latest/apidoc/module-ol_style_flat.html)
You should change your configuration for geoJSON layer to configure it as an array, for example:

....

      "layer": {
        "geojson": {
          "url": "assets/layers/geojson-layer.json"
        }
      }
....

should be changed to:

....

      "layer": {
        "geojson": [
          {
            "url": "assets/layers/geojson-layer.json"
          }
        ]
      }
....

Or adding the style:

....

      "layer": {
        "geojson": [
          {
            "url": "assets/layers/geojson-layer.json",
            "style": {
              "stroke-color": "blue",
              "stroke-width": 1.5,
              "fill-color": "rgba(39, 245, 164, 0.4)"
            }
          }
        ]
      }
....

If no style is defined the layer will be rendered with default Opfab style.