// Copyright (c) 2022 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 3.10.x to release 3.11.0

== Card publication 
OperatorFabric will now check user perimeter when publishing cards via endpoint `/cards` (it does not concern user cards
which are always controlled). To disable perimeter validation it is possible to set the configuration parameter
`checkPerimeterForCardSending` to `false` in cards-publication service configuration file.

== templateGateway `onStyleChange()` method

A new `onStyleChange()` method has been added to templateGateway.
OpFab will call this method when switching day/night mode.
It may have to be implemented by a template to refresh styles and reload embedded charts when user change day/night
mode, please check your existing templates.

== Nginx configuration
Nginx configuration file has to be modified to allow the forwarding of query parameters to the new 'userActionLogs' API.
You have to modify `nginx.conf` file as follows:

Replace
----
  location ~ "^/users/(.*)" {
    proxy_set_header Host $http_host;
    proxy_pass http://users:8080/$1;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
----

With 

----
  location ~ "^/users/(.*)" {
    proxy_set_header Host $http_host;
    proxy_pass http://users:8080/$1$is_args$args;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
----
