// Copyright (c) 2018, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

== Introduction

The aim of this document is to describe the role of the Time Service in OperatorFabric as well as
the features it provides.
It also includes code snippets demonstrating how to interact with the Time Service through its API.

OperatorFabric services rely on the Time Service to get their current time.
This allows the reference time to be set anywhere in the past or the future.
In addition, the speed of time flow can also easily be altered: for example, go twice as fast as real time.
This is useful mostly for test and demonstration purposes.

We are also planning to add methods to the Time Services allowing to fast forward in time (or rewind) up to the next received card (or the last received card).
See https://github.com/opfab/operatorfabric-core/issues/80[issue 80] for more details.

