// Copyright (c) 2018-2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Version 2.3.0.RELEASE

This release changes the way of exchanging between opfab and template when using response cards. If you are using response cards, you must modify your templates .To migrate your templates, see https://opfab.github.io/documentation/current/docs/single_page_doc.html#_migration_guide_from_release_2_2_0_to_release_2_3_0


== Features

* OC-1562 : Remove web-ui option to hidetime line as the user can himself hide timeline
* OC-1227 : Add lttd field as an option in user card
* OC-1572 : Do not use entiyAllowedToRespond to show/hide the clock for last time to decide
* OC-1505 : Add parent entities to edition modal in Admin
* OC-1491 : UserCard: check that end date is after start date, show a clear error message otherwise
* OC-1589 : Move the "from entity" for user cards from title to summary in feed
* OC-1606 : Add method isUserMemberOfAnEntityRequiredToRespond() for card template
* OC-1288 : Add a link to acknowledge all notification in 1 click (optional feature)

== Bugs

* OC-1538 : FeedNotification configuration - processes not sorted by their label
* OC-1560 : User card : fix title when using "process example" template
* OC-1509 : Fix recurring error message when posting user cards (endDate constraint)
* OC-1559 : EntitiesRequiredToRespond constraint doesn't handle parent entities
* OC-1582 : Fix bug when exporting to excel in logging screen
* OC-1581 : Deleting an entity that is listed as parent entity in some children entities should cause it to be removed from said children
* OC-1591 : Notification configuration screen : bug in display near the "save" button
* OC-1598 : ConfigService.getConfigValue() : function always returns the fallback if the variable is a boolean set to false (in web-ui.json)
* OC-1608 : Timeline buttons : replace "7 Day" by "7 Days"
* OC-1628 : BUG - Feed - receiving cards : changing a user setting stops cards reception
* OC-1629 : Bug when resetting user cache in consultation card service

== Tasks

* OC-1556 : Modify Karate API test to add test card with no end date
* OC-1566 : Adapt doc for settings.tags.hide option
* OC-1552 : Entity emitting the card shall not be able to respond
* OC-1476 : Migrating ngrx from v9 to v10. Replace deprecated Effect decorator (OC-1579)
* OC-1462 : Admin UI - Adapt column fiter to night mode
* OC-1471 : Updating to Angular v11 and bringing dependencies up to date
+
NOTE: This shouldn’t have any impact for deployments using docker. If you need to build the UI however, you need to run "npm install" first to get the new dependencies. In addition, see the documentation to troubleshoot any errors.
+
* OC-1567 : Activate nginx gzip compression
* OC-1537 : Fix karate tests to work with Karate 1.0.0
* OC-1554 : Adapting CICD for hotfixes
* OC-1575 : Refacto api tests launching to adapt for karate 1.0.0
* OC-1571 : Create a repository with common bundles
* OC-1522 : Remove unused SpringFox dependency
* OC-1578 : Create shell scripts for creating/deleting perimeters and cards. It replaces karate scripts (in src/test/utils/karate) for manual testing
* OC-1580 : Remove irrelevant UI tests
* OC-1573 : Re-factorize countdown module
* OC-1588 : Minor Kafka documentation update. Now mentions the card response topic setting.
* OC-1569 : Remove unused ui-home-e2e project configuration in angular.json
* OC-1487 : UI - User model exports (duplicate) Entity class
* OC-1536 : Usercard - Do not show Process or State if only one choice
* OC-1590 : Update dependencies (Update nginx to v1.19.9,gradle to v6.8.3, keycloak to v12.0.4 )
* OC-1601 : Launch api tests via gradle
* OC-1282 : Test with karate endpoint cardSubscription
* OC-1481 : When card references an existing process but for a state that doesn't exist, an error should be thrown
* OC-1597 : Improve communication between template and opfab
+
IMPORTANT: This change the way of exchanging between opfab and template when using response cards . If you are using response cards, you must modify your templates . To migrate your templates, see https://opfab.github.io/documentation/current/docs/single_page_doc.html#_migration_guide_from_release_2_2_0_to_release_2_3_0
+
* OC-1605 : Stop angular building for IE11
* OC-666  : Execute api none regression tests in travis build process
* OC-1586 : Remove TitlePositionEnum (dead code)
* OC-1610 : Confirmation popups : harmonize the closing cross
* OC-1594 : Translate true/false values in the Entity admin table
