// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Version 1.4.0.RELEASE

== Issues

* *UI Improvements* :
** [OC-868] As an admin I would like to be able to hide the time filter
+
See the link:https://opfab.github.io/documentation/current/deployment/#_web_ui[web-ui configuration documentation] for details
** [OC-864] As a user I want to be able to reset archives filters so I can change my search criteria
** [OC-402] As an Operator I want the archive screen to display an explicit message if no cards are found that match my filters
** [OC-939] Synchronize timeline with feed (When a filter is set in the feed, it is applied to the timeline as well (severity, tags or business period))
** [OC-947] As a user I want to be able to click on the links in the bubble so that i can display the related card on the feed
** [OC-945] Add a spinning icon when connection with server is lost
** [OC-972] Add charts functionality in template
+
It uses `charts.js` library, templates as example can be found in `src/test/utils/karate/thirds/resources/bundle_test_api`

* *Work in progress for the "Smart notification" epic* ( [OC-871][OC-872][OC-873][OC-874][OC-875][OC-881][OC-900][OC-913][OC-916][OC-917] )
+
It is now possible for the user to reply to a card, the response is sent back to an external app.
+
[IMPORTANT]
====
Work is in progress, it is not documented and usable yet in production.
====

* *Work in progress for the "Routing" epic*
** [OC-885] User Service : Perimeter model evolution
** [OC-876] User Service : Implement group in JWT Token Option
** [OC-742] When sending a card to an entity , use the group perimeter to send to the good users
+
[IMPORTANT]
====
Work is in progress, it is not documented and usable yet in production.
====

* *Remove old action feature* (front and back) ([OC-960][OC-961][OC-962])
+
This feature was not fully operational and is now replaced by the smart notification feature

* *Remove Netflix stack* ([OC-670][OC-836][OC-837][OC-838][OC-839][OC-971][OC-895][OC-906][OC-983][OC-996]) :
- remove registry/configuration components
- replace gateway with NGINX
- remove all calls from business services to registry and configuration components
- adapt documentation

+
[IMPORTANT]
====
- UI configuration is now done via a json file (web-ui.json) instead of a yaml file (web-ui.yml). Before upgrading, you
should save a copy of your web-ui.json to back-up custom changes.
- As there is no configuration server anymore, the content of services configuration files has changed, check the
documentation and/or see default configuration files in dev/docker folders under config. We also took this as an
opportunity to rearrange our docker-compose files so see the updated documentation on launching OperatorFabric.
====

* *Work in progress for the "Acknowledgment" epic* ([OC-920],[OC-921],[OC-944],[OC-976],[OC-977])
+
The backend code for the acknowledgment feature is ready. Front to be done.
+
[IMPORTANT]
====
Work is in progress, it is not documented and usable yet in production.
====

== Bugs
* [OC-772] Bug on archives screen: clear results when exiting archive page
* [OC-898] In implicit mode, first name and last name are not displayed
* [OC-775] Bug on archives screen: cards details remain displayed when selecting another criteria that doesn't return any result

== Tasks
* [OC-892] Add in documentation that it is not possible to use dot in json field names
* [OC-845] Implement Git flow as our contribution and release workflow
+
_We have transitioned from a GitHub flow to a Git flow. See the documentation to see how it impacted our
link:./single_page_doc.html#CICD[CICD pipeline]
and how it translate into our link:./single_page_doc.html#_contribution_workflow[contribution workflow]
(submitting a pull request etc.)._
+
[IMPORTANT]
====
_Now, the current state of developments is pushed daily to Docker Hub with the tag `SNAPSHOT`
(rather than `snapshot` as before)._
====
* [OC-888][OC-692][OC-973] Fix SonarCloud issues
* [OC-891] Removed unused field mainRecipient
* [OC-896] Update getting started with 1.3.0.RELEASE and change getToken script
* [OC-899] Use SNAPSHOT version on develop branch for docker and dev environment docker-compose
+
_When working on branch `develop`, the docker-compose files will rely on `SNAPSHOT` docker images generated daily.
This lets you test OperatorFabric with the latest merged code. If you're interested in running a particular release on
the other hand, you should checkout the associated X.X.X.RELEASE tag on `master`._

* [OC-907] Remove Keycloak from test-quality-environment docker-compose
* [OC-909] Simplify third menu code (Front)
* [OC-911] Changing sounds due to incompatible license
* [OC-897] Thirds service - added operation delete for the resource thirds
* [OC-904] Thirds service - added delete version of a third, minor changes on general sync working
* [OC-943] Add a gradle task to launch sonar analysis
* [OC-535] Make bin/run_all.sh working even if not in the root directory
* [OC-954] Add name field for process/state and color for state in third
* [OC-957] Field recipient in card should be optional



