// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0


= Version 2.2.0.RELEASE

== Features
- UI :
*  OC-1440 : New logging screen filters
*  OC-1512 : Adapt UI for small screens (Feed)
*  OC-1529 : Show card entity publisher on feed and card detail
*  OC-1441 : New monitoring screen
*  OC-1515 : Memorize choosen domain for timeline
*  OC-1499 : Disable service and process fields when editing a user card


- Administration feature :
* OC-1089 : Add perimeter management to admin screen
* OC-1524 : Admin UI - Avoid dismissal of modals on outside click

- Card templating :
* OC-1503 : Add an opfab style for border box with label in example templates
* OC-1508 : Communicate to the template if the user can respond by calling templateGateway.setUserCanRespond(boolean) function
* OC-1498 : Add the possibility to set the response state from the template (See the documentation for details).


- Misc :
* OC-1446 : In client lib avoid serialization of null fields:  You can now find an example client application using the client library to send a card under src/test/clientApp.
* OC-1530 : Usercard : when sending the card send it as well to the current user
* OC-1257 : Set groups of entities compatible with response card. Added "entityAllowedToSendCard " boolean field to Entity.
* OC-1506 : A new optional field "entitiesRequiredToRespond" has been added to cards. If it is present, this list will be used to display the expected responses in the card detail header instead of the list from "entitiesAllowedToRespond".
If present, "entitiesRequiredToRespond" should be a subset of "entitiesAllowedToRespond" or the card will be rejected.
* OC-1531 : Change rule of visibility for cards with no endDate : card will be visible when startDate is between start and end of chosen period. It applies to feed , archives , monitoring and loggin screens
* OC-1451 : Add support for Authorization flow 'NONE'

== Bugs

- OC-1502 : Correct rendering of chosen values in multi-select input field
- OC-1497 : Fixing issue with card edition and IT incident example
- OC-1464 : Fix bug when deleting all bundles
- OC-1526 : Fixes configuration in cards-consultation and cards-publication docker images
+
NOTE : 2.1.0.RELEASE images for these two services did not take custom configuration passed through docker-compose into account properly
- OC-1532 : Usercard - if process has no state available for sending card , do not show it
- OC-1563 : Bug Chrome - Timeline domain list on two lines sometimes
- OC-1540 : Moved JAVA_OPTIONS environment parameter in docker-entrypoint shell script. In the old position it was placed behind the -jar parameter. This caused java to skip the JAVA_OPTIONS and ignore the optional extra settings.

== Tasks

- OC-1514 : Add documentation for json handlebars helper
- OC-1511 : Permit to add param to third party iframe defined in menu configuration
+
NOTE : This allows business applications to be called from cards with some of the card's context.
+
- OC-1521 : Upgrade to MongoDB 4.4.4
- OC-1473 : Upgrade to keycloak 12.0.2
- OC-1519 : Start users, cards-consultation and cards-publication after mongo and rabbit (in docker-compose)
- OC-1555 : Permit to access opfab directly from localhost:2002 without /ui/

