// Copyright (c) 2025 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 4.9.X to release 4.10.0

== Response card in handlebars templates

If this has not been done in a previous migration, the object that should be returned by
the method registered via `opfab.currentCard.registerFunctionToGetUserResponse` is to be
changed.

Previously, the object was structured as follows:

----
{
    valid: true/false,
    errorMsg: string,
    responseCardData: {},
    responseState: string,
    publisher: string,
    actions: [string]
}
----

Now, all elements related to the response card are encapsulated within a `responseCard` object:

----
{
    valid: true/false,
    errorMsg: string,
    responseCard: {
        data: {},
        state: string,
        publisher: string,
        actions: [string]
    }
}
----

Note that the `responseState` field has been renamed to `state`.

The old structure has been supported as a fallback for a limited time, now it is removed, so you have to update your
code to use the new structure.


== Timeline domain J renamed D

To be consistent, the timeline domain J has been renamed D (Day).
So if necessary, you have to update your config file `web-ui.json`, replacing value `J` with `D` in the field
`feed.timeline.domains`, for example :

----
 "timeline": {
   "domains": [
     "RT",
     "D",
     "7D",
     "W",
     "M",
     "Y"
   ]
 }
----


== RabbitMQ configuration


In previous version, a default password was set for RabbitMQ connection if no password was provided in configuration. Using the default password was considered as acceptable as the rabbit server was not suppose to be accessible from outside the docker network and a security advice was present in the docker compose file. 

Starting from this version, no default password is set anymore in the services configuration to mitigate security risk by forcing user to set a password. 

So you must provide a password :

- in your docker compose configuration file via the env variable RABBITMQ_DEFAULT_PASS. 
- in your yaml common configuration file via the property `operatorfabric.rabbitmq.password`

If you do not provide any password, the application will not start and an error message will be logged.




