// Copyright (c) 2025-2026 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 4.10.X to release 4.11.0

== Java Client Library

We do not provide a Java client library for release 4.11.0. We choose to stop maintaining it because it was not widely used and it was a significant maintenance burden. Please use the REST API directly to interact with the platform.

The old Java client library is still available in the Maven central repository but it will not be updated anymore.

== Destroy listener for templates 


It is now possible to be notified when a template is destroyed, i.e., when a card or user card is removed from the display.
It is strongly recommended to use this feature to clean up resources allocated by your template, especially event listeners.

For cards :

```
opfab.currentCard.listenToDestroy(() => {// Do some stuff});
```

For usercards : 

```
opfab.currentUserCard.listenToDestroy(() => {// Do some stuff});
```

Only one listener can be registered at a time. If you register another listener, the previous listener will not receive events.

== Docker naming change

Some docker images where postfixed with `-services` and some others were not. To have a more consistent naming, all postfixes `-services` have been removed.

So : 

* `of-users-service` is now `of-users`
* `of-external-devices-service` is now `of-external-devices`
* `of-cards-consultation-service` is now `of-cards-consultation`
* `of-cards-publication-service` is now `of-cards-publication`
* `of-businessconfig-service` is now `of-businessconfig`
* `of-cards-external-diffusion-service` is now `of-cards-external-diffusion`

== Email configuration in bundles

The state parameter `emailBodyTemplate` has been moved to `email.bodyTemplate`. So you have to update
your file `config.json` if needed. For example:

Replace
----
  processState: {
      emailBodyTemplate: 'testTemplateMail'
  }
----

With

----
  processState: {
      email: {
          bodyTemplate: 'testTemplateMail'
      }
  }
----

== Email feature

For security reasons, the admin shall now set the email of a user via the user interface or the email shall be populated
by the JWT token.
The user can no longer enter its email itself.


== selectActivityAreaOnLogin configuration parameter


The configuration parameter `selectActivityAreaOnLogin` has been moved in the activityArea section of the 'web-ui.json' file.


Replace
----
    "selectActivityAreaOnLogin": true,
----

With


----
    "activityArea": {
        "selectActivityAreaOnLogin": true
    },
----

== Process monitoring screen configuration

The column parameter `size` is now expressed in pixels. It allows you to define the column width.


