// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

== Card Anatomy

Cards are modelized as `Json` objects. The technical design of card is describe in link:../api/#Card[the swagger api description of Card Publication Service]. A card correspond to the state of a Process in OperatorFabric.

=== Technical Information of the card

Those attributes are used by OperatorFabric to manage how cards are stored, to whom and when they're sent.

==== Mandatory information

Below, the `json` technical key is in the '()' following the title.

[#_card_publisher]
===== Publisher (`publisher`)

Quite obviously it's the Third party which publish the card. This information is used to look up for Presentation resources of the card.

[#_card_publisher_version]
===== Publisher Version (`publisherVersion`)

Refers the `version` of `publisher third` to use to render this card (i18n, title, summary, media and details).
As through time, the presentation of a publisher card data changes, this changes are managed through `publisherVersion` in OperatorFabric. Each version is keep in the system in order to be able to display correctly old cards.

===== Process Identifier (`processId`)

It's the way to identify the process to which the card is associated. A card represent a state of a process.

[#startDate]
===== Start Date (`startDate`)

This attribute is a part of the card life management system. It's indicate OperatorFabric the moment since the card can be displayed to the operators or main recipients, <<_displaying_rules, see Displaying rules>>.

===== Severity (`severity`)

The severity is a core principe of the OperatorFabric Card system. There are 4 severities available(link:../api/#SeverityEnum[Technical definition of OperatorFabric Card Severity]). A color is associated in the GUI to each severity. Here the details about severity and their meaning for OperatorFabric:

1. ALARM: represents a critical state of the associated process, need an action from the operator. In the Gui, the card is red;
2. ACTION: the associated process need an action form operators in order to evolve correctly. In the Gui, an action is orange;
3. COMPLIANT: the process related to the card is in a compliant status. In the UI, an action is green.;
4. INFORMATION: give information to the operator. In the GUI, a information is blue.

[#cardTitle]
===== Title (`title`)

This attribute is display as header of a card in the feed of the GUI. It's the main User destined Information of a card. The value refer to an `i18n` value used to localized this information.

[#cardSummary]
===== Summary (`summary`)

This attribute is display as a description of a card in the feed of the GUI, when the card is selected by the operator. It's completing the information of the card title. The value refer to an `i18n` value used to localized this information.

==== Recipient (`recipient`)

Declares to whom the card is send. For more details about way recipient works <<_displaying_rules, see Displaying rules>>. Without recipient declaration a card is useless in `OperatorFabric` system.

==== Store information

===== Tags (`tag`)

Tags are intended to enable filter of cards in the feed of the GUI.

===== uid (`uid`)

Unique identifier of the card in the OperatorFabric system. This attribute can be send with card, but normally it's manage by `OperatorFabric` system.

===== id (`id`)

State id of the associated process, determined by `OperatorFabric` can be set arbitrarily by the `publisher`.

==== Card Life Management Configuration

With this attributes OperatorFabric know when to display or hide cards, but also if an action is still available for a given card.

===== Start Date (`startDate`)

<<startDate, see Start Date in Technical Information of the Card>> and <<_displaying_rules, for more examples>>.

===== End Date (`endDate`)

Fixes the moment until when `OperatorFabric` displays the card. After the card is remove from the GUI feed, <<_display_rules, see Display Rules for some examples>>.

==== Last Time to Decide (`lttd`)

Fixes the moment until when a `actions` associated to the card are available. After then, the associated actions won't be displayed or actionable.

==== Other technical attributes

==== Publish Date (`publishDate`)

Indicates when the card has been registered in `OperatorFabric` system. This is a technical information exclusively managed by `OperatorFabric`.

==== Deletion Date (`deletionDate°)

Indicates when the card has been removes from `OperatorFabric` system. Technical information manage by `OperatorFabric`.

=== User destined Information of the card

There are two kind of User destined information in a card. Some are restricted to the card format, others are defined by the publisher as long as there are encoded in `json` format. 

==== in Card Format

===== Title (`title`)

<<cardTitle, see Title in Technical Information of the Card>>

===== Summary (`summary`)

<<cardSummary, see Summary in Technical Information of the Card>>

==== Custom part

===== Data (`data`)

Determines where custom information is store. The content in this attribute, is purely `publisher` choice. This content, as long as it's in `json` format can be used to display details. For the way the details are displayed <<_presentation_information_of_the_card,see below>>.

=== Presentation Information of the card

==== Media (`media`)

Some cards can emit a sound when displayed in the feed of the GUI, the id of audio notification is indicated in this attribute.

==== details (`details`)

This attribute is a string of objects containing a `title` attribute which is `i18n` key and a `template` attribute which refers to a template name contained in the publisher bundle. The bundle in which those resources will be looked for is the one corresponding of the <<_card_publisher_version, version>> declared in the card for the current <<_card_publisher, publisher>>. If no resource is found, either because there is no bundle for the given version or there is no resource for the given key, then the corresponding key is displayed in the details section of the GUI.

link:../../../thirds/1.0.0.RELEASE/reference/#_bundle[See the documentation about third bundle in the Third service documentation].

*example:*

The `TEST` publisher has only a `0.1` version uploaded in the current `OperatorFabric` system. The `details` value is `[{"title":{"key":"first.tab.title"},"template":"template0"}]`.

If the `publisherVersion` of the card is `2` then only the `title` key declared in the `details` array will be displays without any translation, i.e. the tab will contains `TEST.2.first.tab.title` and will be empty. If the `l10n` for the title is not available, then the tab title will be still `TEST.2.first.tab.title` but the template will be compute and the details section will display the template content.

==== TimeSpans (`timeSpans`)

When the simple startDate and endDate are not enough to characterize your
process business times, you can add a list of TimeSpan to your card. TimeSpans
are rendered in the timeline component as cluster bubbles are as lines
depending on your parametrization of the span. This as no effect on the feed
content

*example 1:*

to display the card two times in the timeline you can add two TimeSpan to your
card:

....
{
	"publisher":"TSO1",
	"publisherVersion":"0.1",
	"processId":"process-000",
	"startDate":1546297200000,
	"severity":"INFORMATION",
	...
	"timeSpans" : [
        {"start" : 1546297200000},
        {"start" : 1546297500000}
    ]

}
....
In this sample, the card will be displayed twice in the time line. The card
start date will be ignored.

*example 2:*

Instead of the default clustered view, you may want your card to be displayed
as a line in the time line.

....
{
	"publisher":"TSO1",
	"publisherVersion":"0.1",
	"processId":"process-000",
	"startDate":1546297200000,
	"severity":"INFORMATION",
	...
	"timeSpans" : [
        {"start" : 1546297200000, "end" : 1546297500000}
    ]

}
....
