server:
  port : 2103
  forward-headers-strategy: framework # Needed for IP control feature
spring:
  application:
    name: users
  data:
    mongodb:
      database: operator-fabric
      uri: ${operatorfabric.mongodb.uri}


# default values for docker mode 
operatorfabric:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

