// Copyright (c) 2018, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

= Cloud Registry service

Operator Fabric Client Gateway service is a Spring Cloud Gateway application
bootstrapped using SpringBoot.

In our spring micro service architecture Eureka Rgistry instances are the second
services to bootstrap, its configuration relies on the <<Cloud Configuration service>>.

== Mandatory configuration, Profiles and default properties

To get a working registry service, there a few mandatory configuration
properties:

In a configuration service client-gateway.yml file

* The application must set up a route to the oauth server
** /auth/token(?<path>.*) must match the oauth2 token entry point
** /auth/code/(?<params>.*) must match the auth entry point with specific query
parameters : response_type=code&client_id=[client id]&$\{params}
** /auth/check_token must match token introspection entry point
* The application may set up CORS rules if api are to be accessed outside of
the deployment domain

For other configuration see {spring_cloud_gateway_doc}single/spring-cloud-gateway.html[spring cloud gateway documentation].


=== default properties

Note that you must provide a bootstrap file with a convenient registry configuration

_bootstrap.yml_
```
include::../../main/resources/bootstrap.yml[]
```

_bootstrap-docker.yml_
```
include::../../main/resources/bootstrap-docker.yml[]
```

_bootstrap-dev.yml_
```
include::../../main/resources/bootstrap-dev.yml[]
```

The bootstrap-docker.yml file is a replacement bootstrap file we use for our
docker images configuration.

The bootstrap-dev.yml file is a replacement bootstrap file we use for our
development environment

The above embedded configurations are the basic settings of the application:

* it sets its name as a service (config)
* it sets the configuration name to use (which configuration file to retrieve)
* it must set the registry service (example in bootstrap-docker.yml)

=== Sample developpement configuration

```
include::../../../../config/src/main/docker/volume/dev-configurations/client-gateway.yml[]
```

=== Sample docker image configuration

```
include::../../../../config/src/main/docker/volume/docker-configurations/client-gateway.yml[]
```

== Specifying external configuration properties when lauching a jar file

See {springboot_doc}/reference/htmlsingle/#boot-features-external-config-application-property-files[Application Property Files]
on how to setup an external spring properties or yml file.

See {springboot_doc}/reference/htmlsingle/#howto-set-active-spring-profiles[Set the Active Spring Profiles] for specifying alternate profile.


== Specifying configuration properties when lauching a docker image

Our docker image expects optional property file to be stored in the container
/service-config folder. You can bind so docker volume to this path to make
properties or yml available.

At time of writting, you cannot specify an alternate profile at runtime.
The default profiles activated are docker and native.

=== Available environment variables for docker image

* REGISTRY_HOST: Registry service host
* REGISTRY_PORT: Registry service port

== Specifying configuration properties when lauching on Kubernetes

In progress

=== Available environment variables when launching on Kubernetes

* CONFIG_HOST: Configuration service host
* CONFIG_PORT: Configuration service port