// Copyright (c) 2018-2025 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

[[setup_dev_env]]
= Setting up your development environment

== Clone repository
[source,shell]
----
git clone https://github.com/opfab/operatorfabric-core.git
cd operatorfabric-core
----

Do not forget to set proxy if needed , for example : 

```
git config --global http.proxy http://LOGIN:PWD@PROXY_URL:PORT
```

== Install sdkman and  nvm 

sdkman is used to manage java version , see https://sdkman.io/ for installation

nvm is used to manage node and npm version , see https://github.com/nvm-sh/nvm for installation 
See : 

Do not forget to set proxy if needed , for example : 

```
export https_proxy= http://LOGIN:PWD@PROXY_URL:PORT
``` 

Once you have installed sdkman and nvm, you can **source** the following
script to set up your development environment (appropriate versions of Node 
Java and project variables set):

[source]
----
source bin/load_environment_light.sh
----

TIP: From now on, you can use environment variable `${OF_HOME}` to go back to
the home repository of `OperatorFabric`.

== Setting up your proxy configuration 

If you use a proxy to access internet, you must configure it for all tools needed to build opfab 

=== Docker 

To download images , you need to set the proxy for the docker daemon 

See  https://docs.docker.com/config/daemon/systemd/[docker documentation] to set the proxy 

To build docker images, you need to set a proxy via the variable https_proxy

```
export https_proxy= http://LOGIN:PWD@PROXY_URL:PORT
``` 

You may have some DNS error when building docker images, in this case use the IP address of your proxy instead of the FQDN .

=== Gradle 

In gradle.properties (in ~/.gradle repository)


Example : 
```
systemProp.https.proxyHost=PROXY_URL
systemProp.https.proxyPort=PROXY_PORT
systemProp.https.proxyUser=LOGIN
systemProp.https.proxyPassword=PASSWORD
```

=== Npm  

Example : 

```
npm config set https-proxy http://LOGIN:PWD@PROXY_URL:PORT
```

== Start Opfab 


For this, use:
[source,shell]
----
cd bin
./startOpfab.sh [mode]
----

This will download and start Opfab by loading the Docker images needed to run the application.

Opfab can be started in three different modes:

1. **Development mode** (`dev`): This is the default mode. It is CORS permissive and suitable for development.
2. **Production mode** (`prod`): This mode is more restrictive, suitable for production and used for CI/CD pipeline tests.
3. **Java mode** (`java`): This mode is similar to development mode, but executes the Java services directly on the host machine instead of using Docker containers. This mode provides an easier environment for Java service development.
4. **Light mode** ('light'): run only the essential services in docker, without test modules (Kafka,Zookeeper,Modbus dummy devices and ext app) permissive CORS"

To start Opfab in a specific mode, use `./startOpfab.sh [mode]` where `[mode]` can be `dev`, `prod`, `java` or `light`.

In java mode, you can start and stop each service individually using the `run_all.sh` script located in the `bin` directory. For example, to start all services, you can run:

[source,shell]
----
${OF_HOME}/bin/run_all.sh start
----


== Build OperatorFabric with Gradle

Using the wrapper in order to ensure building the project the same way from one machine to another.


To fully build opfab : 

[source,shell]
----
cd ${OF_HOME}
./gradlew buildDocker
----

Optionally, it is possible to 

=== Only compile and package the jars
[source,shell]
----
cd ${OF_HOME}
./gradlew assemble
----

=== Only launch the Unit Test, compile and package the jars
[source,shell]
----
cd ${OF_HOME}
./gradlew build
----


== Log into the UI

*_URL:_* localhost:2002 +
*_login:_* operator1_fr +
*_password:_* test

Other users available in development mode are `operator2_fr`, `operator3_fr`, `operator4_fr` and `admin`, with `test` as password.



== Push cards to the feed

You can check that you see cards into the feed by running the following scripts.
[source,shell]
----
./test/resources/loadTestConf.sh
./test/resources/send6TestCards.sh
----

