// Copyright (c) 2018-2025 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0



[[troubleshooting]]
= Troubleshooting

+++ <details><summary> +++
**Proxy error when starting opfab**
+++ </summary><div> +++

.Error message
[source]
----
Pulling rabbitmq (rabbitmq:3-management)...
ERROR: Get https://registry-1.docker.io/v2/: Proxy Authentication Required
----

.Possible causes & resolution
When running docker compose files using images(such as rabbitmq,
mongodb etc.) the first time, docker will need to pull these images from
their repositories.
If the docker proxy isn't set properly, you will see the above message.

To set the proxy, follow https://docs.docker.com/config/daemon/systemd/[these
steps from the docker documentation].

If your proxy needs authentication, add your user and password as follows:
----
HTTP_PROXY=http://user:password@proxy.example.com:80/
----

IMPORTANT: The password should be URL-encoded.

+++ </div></details> +++

+++ <details><summary> +++
**Gradle Metaspace error**
+++ </summary><div> +++

Gradle task (for example gradle build) fails with the following error:

.Error message
[source]
----
* What went wrong:
Metaspace
----

.Possible causes & resolution
Issue with the Gradle daemon. Stopping the daemon using `./gradlew --stop`
and re-launching the build should solve this issue.

+++ </div></details> +++

+++ <details><summary> +++
**Java version not available when setting up environment**
+++ </summary><div> +++
When sourcing the link:https://github.com/opfab/operatorfabric-core/blob/develop/bin/load_environment_light.sh[load_environment_light]
script to set up your environment, you might get the following error message:

.Error message
[source]
----
Stop! java 8.0.192-zulu is not available. Possible causes:
 * 8.0.192-zulu is an invalid version
 * java binaries are incompatible with Linux64
 * java has not been released yet
----

Select the next available version and update
link:https://github.com/opfab/operatorfabric-core/blob/develop/bin/load_environment_light.sh[load_environment_light] accordingly before
sourcing it again.

.Possible causes & resolution
The java version currently listed in the script might have been deprecated
(for security reasons) or might not be available for your operating system
(for example, 8.0.192-zulu wasn't available for Ubuntu).

Run `sdk list java` to find out which versions are available. You will get
this kind of output:

[source]
----
================================================================================
Available Java Versions
================================================================================
     13.ea.16-open       9.0.4-open          1.0.0-rc-11-grl
     12.0.0-zulu         8.0.202-zulu        1.0.0-rc-10-grl
     12.0.0-open         8.0.202-amzn        1.0.0-rc-9-grl
     12.0.0-librca       8.0.202.j9-adpt     1.0.0-rc-8-grl
     11.0.2-zulu         8.0.202.hs-adpt
     11.0.2-open         8.0.202-zulufx
     11.0.2-amzn         8.0.202-librca
     11.0.2.j9-adpt      8.0.201-oracle
     11.0.2.hs-adpt  > + 8.0.192-zulu
     11.0.2-zulufx       7.0.211-zulu
     11.0.2-librca       6.0.119-zulu
     11.0.2-sapmchn      1.0.0-rc-15-grl
     10.0.2-zulu         1.0.0-rc-14-grl
     10.0.2-open         1.0.0-rc-13-grl
     9.0.7-zulu          1.0.0-rc-12-grl

================================================================================
+ - local version
* - installed
> - currently in use
================================================================================
----


+++ </div></details> +++


+++ <details><summary> +++
**curl get Failed to connect to localhost:2002: Connection refused**
+++ </summary><div> +++

When using the following command line:
[source]
----
curl http://localhost:2002/
----

.Error message
[source]
----
curl: (7) Failed to connect to localhost port 2002: Connexion refused
----

.Possible causes & resolution
The `web-ui` docker container stops running. Check its configuration.


+++ </div></details> +++


