// Copyright (c) 2018, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

ifndef::imagesdir[:imagesdir: ../images]

=== Micro-Service Architecture Implementation

Our global microservices enforces Spring technologies.

Infrastructure services are based on Spring Cloud, they are Springboot services with specific enablements.

==== Spring Cloud Eureka (Registry)

Spring Cloud Eureka allows to setup a Netflix Eureka v1 server to use as a Registry/Discovery server using Springboot
enabler.

==== Spring Cloud Gateway (Gateway)

Spring Cloud Gateway is a gateway filtering and load balancing access to services discovered in Spring Cloud Eureka. It
is setup using Springboot enabler, property file and part of the route business configuration is done programmatically.

==== Spring Cloud Configuration (Configuration)

Spring Cloud configuration allows to share configuration between different services and service instances. It
is setup using Springboot enabler and spring property file.

==== RabbitMQ (Asynchronous Messaging) - To provide

Rabbitmq is an implementation of AMQP specification. From Spring services, Rabbitmq is accessed throught two layers of
technology: Spring AMQP and Spring Cloud Bus. The later delivers higher level concepts of events for microservices
synchronization

==== Mongo DB - To provide

MongoDB is our persistence layer. MngoDB is a document oriented NoSql database that suits our business data model whose
models are either highly coupled (data has no meaning without some other data) or loosely coupled (pices of data are
completely independent

==== Oauth2 - OpenID connect (Supported authentication services) - To provide

We support authentication through the use of an external Oauth2 - Open Id connect server. Two flow of authentication are
supportted: Password and Authentication Code Flow.

==== Business Services

Business services are based on Spring, they are Springboot services with specific enablements. Business services exposes
interfaces as REST endpoints either leveraging Spring MVC or Spring Webflux.



