operatorfabric:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:89/auth/realms/dev/protocol/openid-connect/certs
    jwt:
      login-claim: preferred_username
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mongodb:
    database: "operator-fabric"
    uri: "mongodb://root:password@localhost:27017/operator-fabric?authSource=admin"
  servicesUrls:
    authToken: "http://127.0.0.1:2002/auth/token"
    users: "http://127.0.0.1:2103"
    cardsConsultation: "http://127.0.0.1:2104"
    businessconfig: "http://127.0.0.1:2100"
  internalAccount:
    login: opfab
    password: test
  logConfig:
    logFolder: logs/
    logFile: "%DATE%.log"
    logLevel: info
  mail:
    host: localhost
    port: 1025
    auth:
      user: guest
      pass: guest
  cardsExternalDiffusion:
    adminPort: 2106
    activeOnStartup: true
    defaultConfig:
      mailFrom: opfab@localhost.it
      subjectPrefix: 'Opfab card received '
      bodyPrefix: 'You received a card in opfab : '
      bodyPostfix: 'This email has been sent by Opfab, there is no need to reply.'
      dailyEmailTitle: 'Cards received during the day'
      hourToSendDailyEmail: 7
      minuteToSendDailyEmail: 30
      opfabUrlInMailContent: http://localhost:2002
      windowInSecondsForCardSearch: 360
      secondsAfterPublicationToConsiderCardAsNotRead: 60
      checkPeriodInSeconds: 10
      activateCardsDiffusionRateLimiter: true
      sendRateLimit: 100
      sendRateLimitPeriodInSec : 3600