// Copyright (c) 2018-2022 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Deployment and Administration of OperatorFabric

The aim of this document is to explain how to configure and deploy OperatorFabric.

== Deployment

For now OperatorFabric consist of Docker images available either by compiling
the project or by using images releases from link:https://hub.docker.com/[Dockerhub]

Service images are all based on link:https://hub.docker.com/_/openjdk[openjdk:8-jre-alpine].

For simple one instance per service deployment, you can find a sample
deployment as a docker-compose file
link:https://github.com/opfab/operatorfabric-core/tree/master/config/docker[here]


To run OperatorFabric in development mode, see
ifdef::single-page-doc[<<dev_env, the development environment documentation>>]
ifndef::single-page-doc[<</documentation/current/dev_env/index.adoc#dev_env, the development environment documentation>>]
.

== User computer

From the user perspective, OperatorFabric is compatible with recent versions of chrome, edge and firefox and has no specific hardware performance constraints.

Be aware that if you use OperatorFabric in realtime you should prevent user's computers to go in "sleep mode".

In particular, *if you are using edge have a look to https://github.com/opfab/operatorfabric-core/issues/2754*


include::configuration/configuration.adoc[leveloffset=+1]

include::RABBITMQ.adoc[leveloffset=+1]

== Monitoring

Operator Fabric provides end points for monitoring via link:https://prometheus.io/[prometheus]. The monitoring is available for the four following services: user, businessconfig, cards-consultation, cards-publication. You can start a test prometheus instance via `config/monitoring/startPrometheus.sh` , the monitoring will be accessible on http://localhost:9090/

== Logging Administration

Operator Fabric includes the ability to view and configure the log levels at runtime through APIs. It is possible to configure and view an individual logger configuration, which is made up of both the explicitly configured logging level as well as the effective logging level given to it by the logging framework. These levels can be one of:

* TRACE
* DEBUG
* INFO
* WARN
* ERROR
* FATAL
* OFF
* null

null indicates that there is no explicit configuration.

Querying and setting logging levels is restricted to administrators.

To view the configured logging level for a given logger it is possible to send a GET request to the '/actuator/logger' URI as follows:
----
curl http://<server>:<port>/actuator/loggers/${logger} -H "Authorization: Bearer ${token}" -H "Content-type:application/json"
----
where `${token}` is a valid OAuth2 JWT for a user with administration privileges
and `${logger}` is the logger (ex: org.opfab)

The response will be a json object like the following:

----
{
  "configuredLevel" : "INFO",
  "effectiveLevel" : "INFO"
}
----

To get the log level for ROOT logger of a service it is possible to call the provided script  
https://github.com/opfab/operatorfabric-core/tree/master/src/test/resources/logs/getLogs.sh[src/test/resources/logs/getLogs.sh] as follows: `getLogs.sh <server:port> <user> <opfab_url>`. For example to get the current log level for "card-publication" service  execute: `getLogs.sh localhost:2102 admin http://localhost`

  

To configure a given logger, POST a json entity to the '/actuator/logger' URI, as follows:

----
curl -i -X POST http://<server>:<port>/actuator/loggers/${logger} -H "Authorization: Bearer ${token}" -H 'Content-Type: application/json' -d '{"configuredLevel": "DEBUG"}'
----

To “reset” the specific level of the logger (and use the default configuration instead) it is possible to pass a value of null as the configuredLevel.

To set the log level for ROOT logger of a service it is possible to call the provided script  
https://github.com/opfab/operatorfabric-core/tree/master/src/test/resources/logs/setLogs.sh[src/test/resources/logs/setLogs.sh] as follows: `setLogs.sh <server:port> <log_level>  <user> <opfab_url>`. For example to set the log level to DEBUG for "card-publication" service  execute: `setLogs.sh localhost:2102 DEBUG admin http://localhost`



include::users_groups_admin.adoc[leveloffset=+1]


include::port_table.adoc[leveloffset=+1]



== Restricted operations (administration)

Some operations are restricted to users with the **ADMIN** role, either because they are administration
operations with the potential to impact the OperatorFabric instance as a whole, or because they
give access to information that should be private to a user.

Below is a quick recap of these restricted operations.

.Users Service
Any action (read, create/update or delete) regarding a single user's data (their personal info such as their first and
last name, as well as their settings) can be performed either by the user in question or by a user with the ADMIN role.

Any action on a list of users or on the groups (or entities) (if authorization is managed in OperatorFabric) can only be performed by
a user with the ADMIN role.

.Businessconfig Service
Any write (create, update or delete) action on bundles can only be performed by a user with the ADMIN role. As such,
administrators are responsible for the quality and security of the provided bundles.
In particular, as it is possible to use scripts in templates, they should perform a security check to make sure that
there is no XSS risk.

IMPORTANT: The ADMIN role doesn't grant any special privileges when it comes to card consultation (be they current or
archived), so a user with the ADMIN role will only see cards that have been addressed to them (or to one of their
groups (or entities)), just like any other user.


