// Copyright (c) 2018-2024 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Deployment and Administration of OperatorFabric

The aim of this document is to explain how to configure and deploy OperatorFabric.

== Deployment

For now OperatorFabric consist of Docker images available either by compiling
the project or by using images releases from link:https://hub.docker.com/[Dockerhub]

For simple one instance per service deployment, you can find in our "Getting Started" a 
link:https://github.com/opfab/operatorfabric-getting-started/blob/master/server/docker-compose.yml[sample deployment as a docker compose file]

To run OperatorFabric in development mode, see
ifdef::single-page-doc[<<dev_env, the development environment documentation>>]
ifndef::single-page-doc[<</documentation/current/dev_env/index.adoc#dev_env, the development environment documentation>>]
.

== User computer

From the user perspective, OperatorFabric is compatible with recent versions of chrome, edge and firefox and has no specific hardware performance constraints.

Be aware that if you use OperatorFabric in realtime you should prevent user's computers to go in "sleep mode".

In particular, *if you are using edge have a look to https://github.com/opfab/operatorfabric-core/issues/2754*


include::configuration/configuration.adoc[leveloffset=+1]


== OperatorFabric CLI (Command Line Interface)

The OperatorFabric CLI is designed to streamline administrative tasks. It provides a user-friendly alternative to direct API access and custom scripting, enhancing efficiency and ease of use.

The CLI is automatically installed when you execute the `bin/load_environment_light.sh` script.

To use the CLI, simply type `opfab help` in your terminal to view a list of available commands.

Before you can start using the CLI, you must first authenticate yourself with the desired OperatorFabric instance using the login command. 

For those preferring not to install npm and nodejs locally, the CLI is accessible via a Docker container. Utilize the `cli/opfabDockerCli.sh` script to launch a shell environment pre-configured with the opfab CLI. The script mounts your current directory to `/host` within the Docker container.

Using the Docker version, you can pre-set environment configurations through a config file. This file should list each environment configuration on a separate line. For example:

----
dev DEV LOCALHOST_URL 2002 admin test
prod PROD PROD_URL 80
----

Each line consists of:

- The first value is the configuration name.
- The second value is the name to be added to the shell prompt.
- The third value is the URL of the OperatorFabric instance.
- The fourth value is the port number to use.
- The fifth value is the username.
- The sixth value is the password (if not provided, it will be requested via a prompt).

To launch the Docker CLI using the config file, execute `opfabDockerCli.sh` with the config file as an argument.

== Monitoring

Operator Fabric provides end points for monitoring via link:https://prometheus.io/[prometheus]. The monitoring is available for the five following services: user, businessconfig, cards-consultation, cards-publication and external-devices.  To enable the monitoring , you need to open the endpoint by adding in the common yml configuration file :

```
management:
  endpoints:
    web:
      exposure:
        include: '*'
```


You can start a test prometheus instance via `config/monitoring/startPrometheus.sh` , the monitoring will be accessible on http://localhost:9090/


It is also possible to monitor the health status of cards-external-diffusion, cards-reminder and supervisor services by making an HTTP GET request to the "/healthcheck" endpoint exposed by each service. The healthcheck endpoint will return a HTTP 200 status code if the service is up and running.

== Logging Administration


=== Logging configuration 

Log levels can be defined either globally in the YAML configuration file or individually for each service. You will find a commented configuration for each service within the directory config/docker.

Services are designed to write logs to two primary destinations: standard output and log files within the Docker containers.

If you want to save logs you can redirect the standard output to a file.

Or you can also map the Docker directory /var/log/opfab to a location on the host machine for each business services, keeping logs outside of the container.

For the web-ui service's logs are in the /var/log/nginx directory. You can map this directory to the host to preserve those logs.

=== Runtime configuration 


Operator Fabric includes the ability to view and configure the log levels at runtime through APIs for most of the business services. It is possible to configure and view an individual logger configuration, which is made up of both the explicitly configured logging level as well as the effective logging level given to it by the logging framework. 


Querying and setting logging levels is restricted to administrators.

==== Java services
For java services (user, businessconfig, cards-consultation, cards-publication and external-devices) the available logging levels are:

* TRACE
* DEBUG
* INFO
* WARN
* ERROR
* FATAL

To view the configured logging level for a given logger it is possible to send a GET request to the '/actuator/logger' URI as follows:
----
curl http://<server>:<port>/actuator/loggers/${logger} -H "Authorization: Bearer ${token}" -H "Content-type:application/json"
----
where `${token}` is a valid OAuth2 JWT for a user with administration privileges
and `${logger}` is the logger (ex: org.opfab)

The response will be a json object like the following:

----
{
  "configuredLevel" : "INFO",
  "effectiveLevel" : "INFO"
}
----

To get the log level for ROOT logger of a java service it is possible to use opfab CLI "log" command:
----
opfab log get-level <serviceName>
----

To configure a given logger, POST a json entity to the '/actuator/logger' URI, as follows:

----
curl -i -X POST http://<server>:<port>/actuator/loggers/${logger} -H "Authorization: Bearer ${token}" -H 'Content-Type: application/json' -d '{"configuredLevel": "DEBUG"}'
----

To “reset” the specific level of the logger (and use the default configuration instead) it is possible to pass a value of null as the configuredLevel.

To set the log level for ROOT logger of a java service it is possible to use opfab CLI "log" command:
----
opfab log set-level <serviceName> <level>
----


==== Node Services
For node services (supervisor, cards-external-diffusion and cards-reminder) the available logging levels are:

* silly
* debug
* verbose
* http
* info
* warn
* error


To view the configured logging level for a given logger it is possible to send a GET request to the '/logLevel' URI as follows:
----
curl http://<server>:<port>/logLevel -H "Authorization: Bearer ${token}" 
----
where `${token}` is a valid OAuth2 JWT for a user with administration privileges

The response will be a json object like the following:

----
{
  "configuredLevel" : "INFO",
  "effectiveLevel" : "INFO"
}
----

To get the log level for a node service it is possible to use opfab CLI "log" command:
----
opfab log get-level <serviceName>
----


To configure a given logger, POST a json entity to the '/logLevel' URI, as follows:

----
curl -i -X POST http://<server>:<port>/logLevel -H "Authorization: Bearer ${token}" -H 'Content-Type: application/json' -d '{"configuredLevel": "debug"}'
----

To “reset” the specific level of the logger (and use the default configuration instead) it is possible to pass a value of null as the configuredLevel.

To set the log level for a node service it is possible to use opfab CLI "log" command:
----
opfab log set-level <serviceName> <level>
----

Using the opfab CLI command to get or set log levels for node service, the custom node log levels will be converted to standard levels as follows:

* silly -> trace
* debug -> debug
* verbose -> debug
* http -> debug
* info -> info
* warn -> warn
* error -> error


include::users_groups_admin.adoc[leveloffset=+1]


include::port_table.adoc[leveloffset=+1]

== Rate limiter for card sending

External publishers are monitored by this module which limits how many cards they can send
ifdef::single-page-doc[<<cardSendingLimitCardCount, `cardSendingLimitCardCount`>>]
ifndef::single-page-doc[<</documentation/current/deployment/#cardSendingLimitCardCount, `cardSendingLimitCardCount`>>]
 in a period of time
ifdef::single-page-doc[<<cardSendingLimitPeriod, `cardSendingLimitPeriod`>>]
ifndef::single-page-doc[<</documentation/current/deployment/#cardSendingLimitPeriod, `cardSendingLimitPeriod`>>]
.
This is to avoid potential overloading due to external apps stuck in a card sending loop.
It can be disabled / enabled with
ifdef::single-page-doc[<<activateCardSendingLimiter, `activateCardSendingLimiter`>>]
ifndef::single-page-doc[<</documentation/current/deployment/#activateCardSendingLimiter, `activateCardSendingLimiter`>>]
.
It is also possible to reset the data of the limiter by calling the API through the "/cards/rateLimiter" endpoint (e.g.
POST "$url:2102/cards/rateLimiter" -H "Authorization:Bearer $token").

== Restricted operations (administration)

Some operations are restricted to users with administrative roles, either because they are administration
operations with the potential to impact the OperatorFabric instance as a whole, or because they
give access to information that should be private to a user.

Below is a quick recap of these restricted operations.

.Users Service
Any action (read, create/update or delete) regarding a single user's data (their personal info such as their first and
last name, as well as their settings) can be performed either by the user in question or by a user with the ADMIN role.

Any action on users, groups, entities or perimeters lists (if authorization is managed in OperatorFabric) is restricted to users with the ADMIN role.

Access to users action logs information is restricted to users with ADMIN role or VIEW_USER_ACTION_LOGS role.

.Businessconfig Service
Any write (create, update or delete) action on bundles can only be performed by a user with the ADMIN role or ADMIN_BUSINESS_PROCESS role. As such,
administrators are responsible for the quality and security of the provided bundles.
In particular, as it is possible to use scripts in templates, they should perform a security check to make sure that
there is no XSS risk.

.Cards consultation Service
Users holding the ADMIN role are authorized to read all archived cards, regardless of the card's sender, recipients, or the user's assigned perimeters
IMPORTANT: The ADMIN role doesn't grant any special privileges when it comes to current cards consultation so a user with the ADMIN role will only receive cards that have been addressed to them (or to one of their
groups or entities), just like any other user.

.External devices service
Any action (read, create/update or delete) on external devices configuration is restricted to users with th ADMIN role.
