// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




= Users, Groups and Entities Administration

A new operator call John Doe, who has OAuth granted right to connect ot current `OperatorFabric` instance, need to receive cards within current `OperatorFabric` instance. As a user of OperatorFabric, he needs to be added to the system with a `login` (john-doe-operator), his `firstName` (John) and his `lastName` (Doe).
operator
As there is no `Administration GUI` for the moment, it must be performed through command line, as detailed in the Users API.

== Users 

=== List all users

First of all, list the users (who are the recipients in OperatorFabric) of the system with the following commands:

Httpie
....
http http://localhost:2103/users "Authorization:Bearer $token" "Content-Type:application/type"
....
cURL
....
curl -v http://localhost:2103/users -H "Authorization:Bearer $token" -H "Content-Type:application/type"
....

response
....
HTTP/1.1 200 OK

[
    {
        "firstName": null,
        "groups": [
            "ADMIN"
        ],
        "entities": [
            "ENTITY1",
            "ENTITY2"
        ],
        "lastName": null,
        "login": "admin"
    },
    {
        "firstName": null,
        "groups": [
            "RTE",
            "ADMIN",
            "CORESO",
            "ReadOnly",
            "TEST"
        ],
        "lastName": null,
        "login": "operator3"
    },
    {
        "firstName": null,
        "groups": [
            "ELIA"
        ],
        "lastName": null,
        "login": "elia-operator"
    },
    {
        "firstName": null,
        "groups": [
            "CORESO"
        ],
        "lastName": null,
        "login": "coreso-operator"
    },
    {
        "firstName": null,
        "groups": [
            "Dispatcher",
            "ReadOnly",
            "TEST"
        ],
        "entities": [
            "ENTITY1"
        ],
        "lastName": null,
        "login": "operator1"
    },
    {
        "firstName": null,
        "groups": [
            "Planner",
            "ReadOnly"
        ],
        "entities": [
            "ENTITY2"
        ],
        "lastName": null,
        "login": "operator2"
    },
]
....

=== Create a new User

We are sure that no John-doe-operator exists in our OperatorFabric instance. We can add him in our OperatorFabric instance using the following command use httpie:
....
echo '{"login":"john-doe-operator","firstName":"Jahne","lastName":"Doe"}' | http POST http://localhost:2103/users "Authorization:Bearer $token" "Content-Type:application/json"
....
Or here cURL:
....
curl -X POST http://localhost:2103/users -H "Authorization:Bearer $token" -H "Content-Type:application/json" --data '{"login":"john-doe-operator","firstName":"Jahne","lastName":"Doe"}'
....
response
....
HTTP/1.1 200 OK

{
    "firstName": "Jahne",
    "lastName": "Doe",
    "login": "john-doe-operator"
}
....

=== Fetch user details

It's always a good thing to verify if all the information has been correctly recorded in the system:

with httpie:
....
http -b http://localhost:2103/users/john-doe-operator "Authorization:Bearer $token" "Content-Type:application/json"
....

or with cURL:
....
curl http://localhost:2103/users/john-doe-operator -H "Authorization:Bearer $token" -H "Content-Type:application/json"
....

response
....
HTTP/1.1 200 OK

{
    "firstName": "Jahne",
    "groups": [],
    "entities": [],
    "lastName": "Doe",
    "login": "john-doe-operator"
}
....

=== Update user details

//TODO Check if it hasn't been replaced with create
As shown by this result, the firstName of the new operator has been misspelled.We need
ifdef::single-page-doc[link:../api/users/index.html#/users/updateUser[to update the existing user]]
ifndef::single-page-doc[link:{gradle-rootdir}/documentation/current/api/users/index.html#/users/updateUser[to update the existing user]]
with `john-doe-operator` login. To correct this mistake, the following commands can be used :

with httpie:
....
echo '{"login":"john-doe-operator","lastName":"Doe","firstName":"John"}' | http PUT http://localhost:2103/users/john-doe-operator "Authorization:Bearer $token" "Content-Type:application/json"
....

or with cURL:
....
curl -X PUT http://localhost:2103/users/john-doe-operator -H "Authorization:Bearer $token" -H "Content-Type:application/json" --data '{"login":"john-doe-operator","firstName":"John","lastName":"Doe"}'
....

response
....
HTTP/1.1 200 OK

{
    "firstName": "John",
    "lastName": "Doe",
    "login": "john-doe-operator"
}
....

== Groups/Entities

All the commands below :

* List groups
* Create a new group
* Fetch details of a given group
* Update details of a group
* Add a user to a group
* Remove a user from a group

are available for both groups and entities. In order not to overload the documentation, we will only detail groups endpoints.

=== List groups (or entities)

This operator is the first member of a new group operator called the `OPERATORS`, which doesn't exist for the moment in
the system. As shown when we
ifdef::single-page-doc[link:../api/users/index.html#/groups/fetchGroups[list the groups]]
ifndef::single-page-doc[link:{gradle-rootdir}/documentation/current/api/users/index.html#/groups/fetchGroups[list the groups]]
existing in the server.

Httpie
....
http http://localhost:2103/groups "Authorization:Bearer $token" "Content-Type:application/type"
....

cURL
....
curl http://localhost:2103/groups -H "Authorization:Bearer $token" -H "Content-Type:application/json"
....

response
....
HTTP/1.1 200 OK

[
    {
        "description": "The admin group",
        "name": "ADMIN group",
        "id": "ADMIN"
    },
    {
        "description": "RTE TSO Group",
        "name": "RTE group",
        "id": "RTE"
    },
    {
        "description": "ELIA TSO group",
        "name": "ELIA group",
        "id": "ELIA"
    },
    {
        "description": "CORESO Group",
        "name": "CORESO group",
        "id": "CORESO"
    },
    {
        "description": "Dispatcher Group",
        "name": "Dispatcher",
        "id": "Dispatcher"
    },
    {
        "description": "Planner Group",
        "name": "Planner",
        "id": "Planner"
    },
    {
        "description": "ReadOnly Group",
        "name": "ReadOnly",
        "id": "ReadOnly"
    }
]
....

=== Create a new group (or entity)

Firstly, the group called `OPERATORS` has to be
ifdef::single-page-doc[link:../api/users/index.html#/groups/createGroup[added to the system]]
ifndef::single-page-doc[link:{gradle-rootdir}/documentation/current/api/users/index.html#/groups/createGroup[added to the system]]
using the following command:

using httpie:
....
echo '{"id":"OPERATORS","decription":"This is the brand new  group of operator"}' | http POST http://localhost:2103/groups "Authorization:Bearer $token" "Content-Type:application/json"
....

using cURL:
....
curl -X POST http://localhost:2103/groups -H "Authorization:Bearer $token" -H "Content-Type:application/json" --data '{"id":"OPERATORS","decription":"This is the brand new  group of operator"}'
....

response
....
HTTP/1.1 200 OK

{
    "description": null,
    "name": null,
    "id": "OPERATORS"
}
....

=== Fetch details of a given group (or entity)

The result returned seems strange, to verify if it's the correct answer by
ifdef::single-page-doc[link:../api/users/index.html#/groups/fetchGroup[displaying the details of the group]]
ifndef::single-page-doc[link:{gradle-rootdir}/documentation/current/api/users/index.html#/groups/fetchGroup[displaying the details of the group]]
called `OPERATORS`, use the following command:

using httpie:
....
http http://localhost:2103/groups/OPERATORS "Authorization:Bearer $token" "Content-Type:application/json"
....

using cURL:
....
curl http://localhost:2103/groups/OPERATORS -H "Authorization:Bearer $token" -H "Content-Type:application/json"
....

response
....
HTTP/1.1 200 OK

{
    "description": null,
    "name": null,
    "id": "OPERATORS"
}
....

=== Update details of a group (or entity)

The description is really null. After verification, in our first command used to create the group,
the attribute for the description is misspelled. Using the following command
ifdef::single-page-doc[link:../api/users/index.html#/groups/updateGroup[to update the group]]
ifndef::single-page-doc[link:{gradle-rootdir}/documentation/current/api/users/index.html#/groups/updateGroup[to update the group]]
with the correct spelling, the new group of operator gets a proper description:

with httpie:
....
echo '{"id":"OPERATORS","description":"This is the brand-new group of operator"}' | http -b PUT http://localhost:2103/groups/OPERATORS "Authorization:Bearer $token" "Content-Type:application/json"
....

with cURL:
....
curl -X PUT http://localhost:2103/groups/OPERATORS -H "Authorization:Bearer $token" -H "Content-Type:application/json" --data '{"id":"OPERATORS","description":"This is the brand-new group of operator"}'
....

response
....
{
    "description": "This is the brand-new group of operator",
    "name": null,
    "id": "OPERATORS"
}
....

=== Add a user to a group (or entity)

As both new group and new user are correct it's time
ifdef::single-page-doc[link:../api/users/index.html#/users/addGroupUsers[to make the user a member of the group]]
ifndef::single-page-doc[link:{gradle-rootdir}/documentation/current/api/users/index.html#/users/addGroupUsers[to make the user a member of the group]]
. To achieve this, use the following command:

with httpie:
....
echo '["john-doe-operator"]' | http PATCH http://localhost:2103/groups/OPERATORS/users "Authorization:Bearer $token" "Content-Type:application/json"
....

with cURL:
....
curl -X PATCH http://localhost:2103/groups/OPERATORS/users -H "Authorization:Bearer $token" -H "Content-Type:application/json" --data '["john-doe-operator"]'
....

response
....
HTTP/1.1 200 OK
....

Let's verify that the changes are correctly recorded by fetching the :
....
http http://localhost:2103/users/john-doe-operator "Authorization:Bearer $token" "Content-Type:application/json"
....

with cURL
....
curl http://localhost:2103/users/john-doe-operator -H "Authorization:Bearer $token" -H "Content-Type:application/json"
....

response
....
HTTP/1.1 200 OK

{
    "firstName": "John",
    "groups": ["OPERATORS"],
    "entities": [],
    "lastName": "Doe",
    "login": "john-doe-operator"
}
....

It's now possible to send cards either specifically to `john-doe-operator` or more generally to the `OPERATORS` group.

=== Remove a user from a group (or entity)

When John Doe is no longer in charge of hypervising cards for `OPERATORS` group, this group has to be removed from his login by using the following command:

with httpie:
....
http DELETE http://localhost:2103/groups/OPERATORS/users/john-doe-operator "Authorization:Bearer $token"
....

with cURL:
....
curl -X DELETE -H "Authorization:Bearer $token" http://localhost:2103/groups/OPERATORS/users/john-doe-operator
....

response
....

HTTP/1.1 200 OK

{
	"login":"john-doe-operator","
	firstName":"John",
	"lastName":"Doe",
	"groups":[],
    "entities":[]
}

....
A last command to verify that `OPERATORS` is no longer linked to `john-doe-operator`:

with httpie:
....
http http://localhost:2103/users/john-doe-operator "Authorization:Bearer $token" "Content-Type:application/json"
....

with cURL:
....
curl http://localhost:2103/users/john-doe-operator -H "Authorization:Bearer $token" -H "Content-Type:application/json"
....

response
....
HTTP/1.1 200 OK

{
    "firstName": "John",
    "groups": [],
    "entities": [],
    "lastName": "Doe",
    "login": "john-doe-operator"

}
....
