operatorfabric:
  mongodb:
    database: "operator-fabric"
  servicesUrls:
    authToken: "http://web-ui/auth/token"
    users: "http://users:2103"
    cardsPublication: "http://cards-publication:2102"
    cardsConsultation: "http://cards-consultation:2104"
  internalAccount:
    login: opfab
  logConfig:
    logFolder: /var/log/opfab/
    logFile: "opfab.%DATE%.log"
    logLevel: info
  emailToCard:
    adminPort: 2109
    activeOnStartup: true
    defaultConfig:
      secondsBetweenConnectionChecks: 10
      host: 'localhost'
      port: 3143
      tls: false
      authTimeout: 5000
      mailboxes:
        - mailbox: 'operator1@test.com'
          password: 'a'
        - mailbox: 'operator2@test.com'
          password: 'b'