operatorfabric:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:89/auth/realms/dev/protocol/openid-connect/certs
    jwt:
      login-claim: preferred_username
  internalAccount:
    login: opfab
    password: test # use for test environment only
  logConfig:
    logFolder: logs/
    logFile: "%DATE%.log"
    logLevel: info
  emailToCard:
    defaultConfig:
      secondsBetweenConnectionChecks: 10
      user: 'operator1@test.com'
      password: 'a'
      host: 'localhost'
      port: 3143
      tls: false
      authTimeout: 5000
      mailboxes:
        - mailbox: 'operator1@test.com'
          password: 'a'
        - mailbox: 'operator2@test.com'
          password: 'b'
    adminPort: 2108
    activeOnStartup: true

