server:
  port: 2104
  forward-headers-strategy: framework # Needed for IP control feature
spring:
  application:
    name: cards-consultation
  data:
    mongodb:
      database: operator-fabric
      uri: ${operatorfabric.mongodb.uri} # To be set outside of docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${operatorfabric.security.oauth2.resourceserver.jwt.jwk-set-uri} #To be set outside of docker

# default values for docker mode 
operatorfabric:
  servicesUrls:
    businessconfig: "businessconfig:2100"
    users: "users:2103"
# default values for docker mode 
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest