server:
  port: 2102
  forward-headers-strategy: framework # Needed for IP control feature
opfab:
  kafka:
    topics:
      card:
        topicname: opfab
      response-card:
        topicname: opfab-response
    schema:
      registry:
        url: http://localhost:8081
spring:
  application:
    name: cards-publication
  data:
    mongodb:
      database: operator-fabric
  deserializer:
    value:
      delegate:
        class: io.confluent.kafka.serializers.KafkaAvroDeserializer
  serializer:
    value:
      delegate:
        class: io.confluent.kafka.serializers.KafkaAvroSerializer

# default values for docker mode 
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

operatorfabric:
  servicesUrls:
    users: "users:2103"
    businessconfig: "businessconfig:2100"


