server:
  port: 2102
  forward-headers-strategy: framework # Needed for IP control feature

spring:
  application:
    name: cards-publication
  data:
    mongodb:
      database: operator-fabric
      uri: ${operatorfabric.mongodb.uri}
  deserializer:
    value:
      delegate:
        class: io.confluent.kafka.serializers.KafkaAvroDeserializer
  serializer:
    value:
      delegate:
        class: io.confluent.kafka.serializers.KafkaAvroSerializer

# default values for docker mode 
operatorfabric:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  servicesUrls:
    users: "users:2103"
    businessconfig: "businessconfig:2100"
  cards-publication:
    kafka:
      topics:
        card:
          topicname: opfab
        response-card:
          topicname: opfab-response
      schema:
        registry:
          url: http://localhost:8081


