// Copyright (c) 2018, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

== Introduction


=== A Smart Assistant For System Operators

OperatorFabric is a modular, extensible, industrial-strength and field-tested
platform for use in electricity, water, and other utility operations.

OperatorFabric provides a notification GUI with strong added value and powerful
backend modules:

* System visualization and console integration
* Precise alerting
* Workflow scheduling
* Historical browsing
* Scripting (ex: Python, JavaScript)

NOTE: Workflow Scheduling could be addressed either as an internal module or
through simplified and standardized (BPMN) integration with external workflow
engines, we're still weighing the pros and cons of the two options._

=== Open source

OperatorFabric is part of the https://www.lfenergy.org/[LF Energy] coalition,
a project of The Linux Foundation that supports open source innovation projects
within the energy and electricity sectors.

OperatorFabric is an open source platform licensed under
https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License V2].
The source code is hosted on GitHub in this repository:
https://github.com/opfab/operatorfabric-core[operatorfabric-core].

=== Where does the name come from ?

[horizontal]
Operator:: represents the human being at the center of the platform, whether
he's working in a control room or in the field
Fabric:: from a modern digital perspective, is used as a metaphor to
illustrate the idea of a simple work to create and weave together powerful
software

That's why when we started this project it felt kind of natural to call it
**OperatorFabric**, or **"OpFab"** for short (there's no need to explain it,
is there? :-) ).
And in the end, in emails and presentations and such, we started referring to
it as just **"OF"**.

=== What is the present document

The present document describes the reflexion process that leaded us from
business observations to the technical architecture solution of OperatorFabric.
