// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.



= Actions Business service

OperatorFabric Actions Business service is a Spring Webflux application
bootstrapped using SpringBoot.

== Mandatory configuration, Profiles and default properties

The service has the following mandatory configuration.

=== Mandatory properties

The following table recaps all the needed properties for the `action service` 
to run properly. They're defined in the `application.yml` configuration file.
The configuration use during the development should be included into the
`application-dev.yml` configuration file.

[options="header"]
|===
|key|Usage|Example
|server.port| Defines the port of the service | 2105
|spring.security.oauth2.resourceserver.jwt.jwk-set-uri|URI serving the public
key use to control OAuth2 jwt signature.
See link:https://tools.ietf.org/html/rfc7517[RFC 7517 - JSON Web Key (JWK)]|
http://localhost:89/auth/realms/dev/protocol/openid-connect/certs
|operatorfabric.services.base-url.cards| URL of the `action service` of the
current `OperatorFabric` instance | http://localhost:2104
|operatorfabric.services.base-url.thirds| URL of the `third service` of the
current `OperatorFabric` instance | http://localhost:2100
|operatorfabric.services.base-url.users| URL of the `user service` of the
current `OperatorFabric` instance | http://localhost:2103
|===

//TODO Include example application.yml?

== Specifying external configuration properties when launching a jar file

See link:{springboot_doc}/reference/htmlsingle/#boot-features-external-config-application-property-files[Application Property Files]
on how to setup an external spring properties or yml file.

See link:{springboot_doc}/reference/htmlsingle/#howto-set-active-spring-profiles[Set the Active Spring Profiles] for specifying alternate profile.


== Specifying configuration properties when launching a docker image

At time of writing, you cannot specify an alternate profile at runtime.
The profiles available to be activated at runtime are `docker` and `native`.

=== Available environment variables for docker image

* JAVA_OPTIONS: Additional java options

== Specifying configuration properties when launching on Kubernetes

In progress

=== Available environment variables when launching on Kubernetes

* JAVA_OPTIONS: Additional java options
