// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




= Cards-Consultation Business service

OperatorFabric Cards-Consultation Business service is a Spring Webflux application
bootstrapped using SpringBoot.


== Mandatory configuration, Profiles and default properties

The service has no mandatory configuration beside global configuration and
usual bootstrap configuration.

For other configuration see:

* link:{springboot_doc}/reference/htmlsingle/[Spring Boot documentation].
* link:{spring_doc}spring-framework-reference/web-reactive.html#webflux[Spring MVC documentation].

=== Service specific properties



=== default properties

The application-docker.yml file is a replacement application file we use for our
docker images configuration.

The application-dev.yml file is a replacement application file we use for our
development environment

The above embedded configurations are the basic settings of the application:

* it sets its service name


=== Sample development configuration

[source]
----
include::examples/dev-configurations/cards-consultation.yml[]
----

=== Sample docker image configuration

[source]
----
include::examples/docker-configurations/cards-consultation.yml[]
----

== Specifying external configuration properties when launching a jar file

See link:{springboot_doc}/reference/htmlsingle/#boot-features-external-config-application-property-files[Application Property Files]
on how to setup an external spring properties or yml file.

See link:{springboot_doc}/reference/htmlsingle/#howto-set-active-spring-profiles[Set the Active Spring Profiles] for specifying alternate profile.


== Specifying configuration properties when launching a docker image

Our docker image expects optional property file to be stored in the container
/service-config folder. You can bind so docker volume to this path to make
properties or yml available.

At time of writing, you cannot specify an alternate profile at runCards-Consultation.
The default profiles activated are docker and native.

=== Available environment variables for docker image

* JAVA_OPTIONS: Additional java options

== Specifying configuration properties when launching on Kubernetes

In progress

=== Available environment variables when launching on Kubernetes

* JAVA_OPTIONS: Additional java options
