// Copyright (c) 2018-2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

[[custom_certificates]]
= Adding certification authorities or certificates to the Java keystore

If you're using certificates (for example for Keycloak) that are not from a certification authority trusted by the JVM,
this will cause errors such as this one:

.Missing certificate error message
----
Caused by: sun.security.validator. ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to
requested target
at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
at sun.security.validator.Validator.validate(Validator.java:262)
at sun.security.ssl.X509TrustManager Impl.validate(x509TrustManagerImpl.java:330)
at sun.security.ssl.X509TrustManagerImpl.checkTrusted(x509TrustManagerImpl.java:237)
at sun.security.ssl.X509TrustManager Impl.checkServerTrusted(x509TrustManager Impl.java:132)
at sun.security.ssl.clientHandshaker.serverCertificate(ClientHandshaker.java:1621)
94 common frames omitted
Caused by: sun.security.provider.certpath. SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.provider.certpath. SunCertPathBuilder.build(SunCertPathBuilder.java:141)
at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
... 100 common frames omitted
----

If that is the case, you can pass the additional authorities or certificates that you use to the containers at runtime.

To do so, put the relevant files (+*+.der files for example) under *src/main/docker/certificates*.

. This directory should only contain the files to be added to the keystore.
. The files can be nested inside directories.
. Each certificate will be added with its filename as alias. For example, the certificate in file mycertificate.der
will be added under alias *mycertificate*. As a consequence, filenames should be unique or it will cause an error.
. If you need to add or remove certificates while the container is already running, the container will have to be
restarted for the changes to be taken into account.

If you would like certificates to be sourced from a different location, replace the volumes declarations in the deploy
docker-compose.yml file with the selected location:
....
volumes:
 - "path/to/my/selected/location:/certificates_to_add"
....
instead of
....
volumes:
 - "../../../../src/main/docker/certificates:/certificates_to_add"
....

IMPORTANT: The steps described here assume you're running OperatorFabric in docker mode using the deploy docker-compose,
but they can be adapted for single container deployments and development mode.

If you want to check that the certificates were correctly added, you can do so with the following steps:

. Open a bash shell in the container you want to check
+
....
docker exec -it deploy_businessconfig_1 bash
....
+
. Run the following command
+
....
$JAVA_HOME/bin/keytool -list -v -keystore /tmp/cacerts -storepass changeit
....

You can also look at the default list of authorities and certificates trusted by the JVM with this command:
....
$JAVA_HOME/bin/keytool -list -v -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit
....
