// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




= Filters and CORS configuration

== Authentication Server

In the configuration service `client-gateway.yml` file:

    * The application must set up a route to the oauth server
    ** `/auth/token(?<path>.*)`: must match the oauth2 token entry point;
    ** `/auth/code/(?<params>.*)`: must match the auth entry point with specific query
  parameters like `response_type=code&client_id=[client id]&$\{params}`;
    ** `/auth/check_token`: must match token introspection entry point
    * The application must add request header for each request:
    ** `AddRequestHeader: Authorization, Basic`: followed, separated with a space, by the `OAuth2 client-id` and the `OAuth2 client-secret` encoded in base64.
    * The application may set up CORS rules if api are to be accessed from browser outside of
the deployment domain

Configuration example of the filters, for the docker dev keycloak:
```
spring.cloud.gateway.routes[0].filters:
        - RewritePath=/auth/token(?<path>.*), /auth/realms/dev/protocol/openid-connect/token$\{path}
        - RewritePath=/auth/code/(?<params>.*), /auth/realms/dev/protocol/openid-connect/auth?response_type=code&client_id=opfab-client&$\{params}
        - RewritePath=/auth/check_token, /auth/realms/dev/protocol/openid-connect/token/introspect
        - AddRequestHeader=Authorization, Basic b3BmYWItY2xpZW50Om9wZmFiLWtleWNsb2FrLXNlY3JldA==
```

where:

- `spring.cloud.gateway.routes.uri`: is your keycloak instance
- `spring.cloud.gateway.routes[0]` is the routes with `id` equals to `auth`;
- `/realms/dev`: is the keycloak realm where `opfab-client` is defined.
- `b3BmYWItY2xpZW50Om9wZmFiLWtleWNsb2FrLXNlY3JldA==`: is the base64 encoded string of `opfab-client:opfab-keycloak-secret` with
`opfab-client` as client-id and `opfab-keycloak-secret` its client secret.


== Action Service

In the  configuration service `client-gateway.yml` file, the application must set up the `URI` of the `Action Service`.

To do so, the `spring.cloud.gateway.routes.id="action".uri` property is set with the actual value of this service.

In the case of a development set-up, this value is `http://localhost:2105` where `2105` 
is the default port as set in the `application.yml` used by the `Action service` as configuration.

`client-gateway.yml` of the `dev-configuration` as example:
```
spring:
  cloud:
    gateway:
      routes:
      - id: actions
        uri: http://localhost:2105
        predicates:
        - Path=/actions/**
        filters:
        - RewritePath=/actions/(?<path>.*), /$\{path}

```

As explained earlier, the key to configure is `uri` of the `spring.cloud.gateway.routes` with the `id`
equals to `actions`.
