// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




[[cloud_gateway_service_config]]
= Cloud Gateway service

OperatorFabric Client Gateway service is a Spring Cloud Gateway application
bootstrapped using SpringBoot.

In our spring micro service architecture the gateway service depends on Eureka
Registry.

== Mandatory configuration, Profiles and default properties

To get a working gateway service, there a few mandatory configuration
properties:

include::client-gateway_filters-and-cors-configuration.adoc[leveloffset=+1]

For other configuration see link:{spring_cloud_gateway_doc}single/spring-cloud-gateway.html[spring cloud gateway documentation].

=== Service specific properties

|===
|name|default|mandatory?|Description

|operatorfabric.gateway.configs|null|no|an array of string for each allowed config entries

|===

=== default properties

Note that you must provide a bootstrap file with a convenient registry configuration

_bootstrap.yml_

[source]
----
include::examples/client-gateway/bootstrap.yml[]
----

_bootstrap-docker.yml_

[source]
----
include::examples/client-gateway/bootstrap-docker.yml[]
----

_bootstrap-dev.yml_

[source]
----
include::examples/client-gateway/bootstrap-dev.yml[]
----

The bootstrap-docker.yml file is a replacement bootstrap file we use for our
docker images configuration.

The bootstrap-dev.yml file is a replacement bootstrap file we use for our
development environment

The above embedded configurations are the basic settings of the application:

* it sets its service name
* it sets the configuration name to use (which configuration file to retrieve)
* it must set the registry service (example in bootstrap-docker.yml)

=== Sample developpement configuration

[source]
----
include::examples/dev-configurations/client-gateway.yml[]
----

=== Sample docker image configuration

[source]
----
include::examples/docker-configurations/client-gateway.yml[]
----

== Specifying external configuration properties when lauching a jar file

See link:{springboot_doc}/reference/htmlsingle/#boot-features-external-config-application-property-files[Application Property Files]
on how to setup an external spring properties or yml file.

See link:{springboot_doc}/reference/htmlsingle/#howto-set-active-spring-profiles[Set the Active Spring Profiles] for specifying alternate profile.


== Specifying configuration properties when lauching a docker image

Our docker image expects optional property file to be stored in the container
/service-config folder. You can bind so docker volume to this path to make
properties or yml available.

At time of writting, you cannot specify an alternate profile at runtime.
The default profiles activated are docker and native.

=== Available environment variables for docker image

* REGISTRY_HOST: Registry service host
* REGISTRY_PORT: Registry service port
* JAVA_OPTIONS: Additional java options

== Specifying configuration properties when lauching on Kubernetes

In progress

=== Available environment variables when launching on Kubernetes

* REGISTRY_HOST: Registry service host
* REGISTRY_PORT: Registry service port
* JAVA_OPTIONS: Additional java options
