// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




= NGINX revers proxy and CORS configuration

OperatorFabric cConfigures Nginx with a custom `default.conf` file used as a docker
volume in the `web-ui` docker container.

== Reverse proxy

The reverse proxy configuration answers the front-end needs.

There are two different configurations depending on docker-compose environment.

The configuration contains the docker DNS provider as a resolver to find services within
the docker-compose network, such as `keycloak` in the http context (above server context).

[source]
====
# docker-compose DNS used to resolved keycloak services
resolver 127.0.0.11 ipv6=off;
====


=== `dev-environment` docker-compose

In this configuration, NGINX server maps front-end end-point calls
against the ports exposed by the running `core` services. As the NGINX server lives in the docker-compose network,
it accesses the native local services using the `172.17.0.1` ip.

==== Cards example
[source]
====
    location /cards/ {
## CORS configuration omitted
       proxy_set_header Host $http_host;
       proxy_pass http://172.17.0.1:2104/;
    }

====


=== `deploy` docker-compose

In this configuration, NGINX server maps front-end end-point calls against the `core` services in docker containers.
As all services run in the docker-compose environment, the mapping use directly their name with the `8080` port.

==== Cards example
[source]
====
    location /cards/ {
       proxy_set_header Host $http_host;
       proxy_pass http://cards-consultation:8080/;
    }
====

=== Common Authentication Configuration

To correctly reach the Authentication Provider, there are 3 properties to configures :

- $KeycloakBaseUrl: the url of the Authentication provider;
- $OperatorFabricRealm: the realm associated with OperatorFabric in the Authentication Provider (Keycloak):
- $ClientPairOFAuthentication: a base64 encoded string of the client id and associated secret id separated by a colon(':').

For both of the following examples, the encoded string corresponds to `opfab-client:opfab-keycloak-secret`.

=== `dev-environment` example
[source]
====
# Url of the Authentication provider
    set $KeycloakBaseUrl "http://keycloak:8080";
# Realm associated to OperatorFabric within the Authentication provider
    set $OperatorFabricRealm "dev";

# base64 encoded pair of authentication in the form of 'client-id:secret-id'
set $ClientPairOFAuthentication "b3BmYWItY2xpZW50Om9wZmFiLWtleWNsb2FrLXNlY3JldA==" ;
====

=== `deploy` example
[source]
====
# Url of the Authentication provider
    set $KeycloakBaseUrl "http://keycloak:8080";
# Realm associated to OperatorFabric within the Authentication provider
    set $OperatorFabricRealm "dev";

# base64 encoded pair of authentication in the form of 'client-id:secret-id'
set $ClientPairOFAuthentication "b3BmYWItY2xpZW50Om9wZmFiLWtleWNsb2FrLXNlY3JldA==" ;
====
== CORS for `ng serve`

The `dev-environment` docker-compose configuration is already compatible. See the end of this section to enable it into
`deploy` one.

Here is the way to declare in NGINX the headers needed in general to enable CORS.

[source]
====
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Credentials' 'true';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'authorization';
====

But as the `ng serve` is proxying all its requests, the http `OPTION` method needs specific headers.
As NGINX doesn't seem to mutualize header declaration, the declaration of the former ones is also mandatory as seen in the above example.

[source]
====
      if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Allow-Origin' '*';
          add_header 'Access-Control-Allow-Credentials' 'true';
          add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
          add_header 'Access-Control-Allow-Headers' 'authorization';
          add_header 'Content-Length' 0;
          add_header 'Vary' 'Origin';
          add_header 'Vary' 'Access-Control-Request-Method' ;
          add_header 'Vary' 'Access-Control-Request-Headers';

          return 204;
           }
====

The convention is to send a `204` status back.

This configuration needs to be repeated in each mapping.

== Use `ng serve` with `deploy` docker-compose

Modify `${OF_HOME}/src/main/docker/docker-compose.yml` as following.

For the `web-ui` service declaration change `./default.conf` with `./default-web-dev.conf`.

Then run your `docker-compose` or stop and re-run the `web-ui` service for the change to be activated.
