// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




:springboot_doc: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/
:mongo_doc: https://docs.mongodb.com/manual/reference/
:spring_kafka_doc: https://docs.spring.io/spring-kafka/reference/html/

= Configuration

OperatorFabric has multiple services to configure. 

See the
ifdef::single-page-doc[<<architecture, architecture documentation>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/architecture/index.adoc#architecture, architecture documentation>>]
for more information on the different services.

All services are SpringBoot applications and use jetty as an embedded servlet container. As such, they share some common
configuration which is described in the following documentation:

 * link:{springboot_doc}/reference/htmlsingle/[Springboot documentation]
 * link:{springboot_doc}/reference/htmlsingle/#boot-features-external-config[Springboot external configuration]
 * link:{springboot_doc}/reference/htmlsingle/#common-application-properties[Common application properties from Springboot documentation]

Configuration is centralized in the *config* directory, the *dev* sub-directory is specific to development environments
while the *docker* sub-directory is a specific configuration meant for use in a full docker environment.

== Business service configuration

=== Specify an external configuration

When starting docker in the full docker environment an external environment file could be provided like:

----
cd ./config/docker
./docker-compose.sh ~/config/local.env
----
In the provided environment file the Spring active profiles can be set.

----
SPRING_PROFILES_ACTIVE=docker,local
----
This way the configuration file 'cards-publication-local.yml' can be provided in the same configuration directory and can be read by SpringBoot


=== Shared business service configuration

The configuration shared by all business services is in a yaml file, you can find an example with the file
/config/docker/common-docker.yml.
In this file you will find, among others, the parameters below :

|===
|name|default|mandatory?|Description

|operatorfabric.businessLogActivated|false|no|Indicates whether or not operatorfabric should record business logs
|operatorfabric.servicesUrls.users||yes|Indicates where the Users service can we reached (to get information about the current user).

|===

=== Business service specific configurations

Each business service has a specific yaml configuration file. It should a least contain the name of the service:

[source, yaml]
----
spring:
  application:
    name: businessconfig
----

Examples of configuration of each business service can be found either under config/docker or config/dev depending on
the type of deployment you're looking for.

==== Businessconfig service

The businessconfig service has this specific property : 

|===
|name|default|mandatory?|Description

|operatorfabric.businessconfig.storage.path|null|no|File path to data storage folder

|===


==== Users service

The user service has these specific properties :

|===
|name|default|mandatory?|Description

|operatorfabric.users.default.users|null|no| Array of user objects to create upon startup if they don't exist
|operatorfabric.users.default.user-settings|null|no| Array of user settings objects to create upon startup if they don't exist
|operatorfabric.users.default.groups|null|no| Array of group objects to create upon startup if they don't exist
|operatorfabric.users.default.entities|null|no| Array of entity objects to create upon startup if they don't exist

|===


==== Cards-publication service

The cards-publication service has these specific properties :

|===
|name|default|mandatory?|Description

|checkPerimeterForResponseCard|true|no|If false, OperatorFabric will not check that a user has write rights on a process/state to respond to a card
|checkAuthenticationForCardSending|true|no|If false, OperatorFabric will not require user authentication to send or delete a card via endpoint /cards (it does not concerned user cards which always need authentication)
|spring.kafka.consumer.group-id |null|no| If set, support for receiving cards via Kafka is enabled
|spring.deserializer.value.delegate.class|io.confluent.kafka.serializers.
KafkaAvroDeserializer|yes| Deserializer used to convert the received bytes into objects
|spring.serializer.value.delegate.class |io.confluent.kafka.serializers.
KafkaAvroSerializer|yes|Serializer used to convert cards to bytes
|spring.kafka.producer.bootstrap-servers|http://localhost:9092|no|comma seperated list of URL(s) of the broker(s) / bootstrap server(s)
|opfab.kafka.topics.card.topicname |opfab|no|Name of the topic to read the messages from
|opfab.kafka.topics.response-card.topicname |opfab|no|Name of the topic to place the response cards to
|opfab.kafka.schema.registry.url|http://localhost:8081|yes|URL of the schema registry. Can be set to the empty string "" is no registry is used
|===


include::web-ui_configuration.adoc[leveloffset=+1]


[[opfab_spec_conf]]
include::security_configuration.adoc[leveloffset=+1]

== OperatorFabric Mongo configuration

We only use URI configuration for mongo through the usage of the ```spring.data.mongodb.uris```,
it allows us to share the same configuration behavior for simple or cluster
configuration and with both spring classic and reactive mongo configuration.
See link:{mongo_doc}connection-string/[mongo connection string] for the complete URI syntax.

=== Define time to live for archived cards

By default, archived cards will remain stored in the database forever. It is possible to have them automatically
removed after a specified duration by using the link:https://docs.mongodb.com/manual/core/index-ttl/[TTL index feature of mongoDB] on their publishDate field.

For example, to have cards expire after 10 days (864000s), enter the following commands in the mongo shell:

[source,shell]
----
use operator-fabric
db.archivedCards.createIndex( { "publishDate": 1 }, { expireAfterSeconds: 864000 } )
----

IMPORTANT: You cannot use createIndex() to change the value of expireAfterSeconds of an existing index.
Instead use the link:https://docs.mongodb.com/manual/reference/command/collMod/#dbcmd.collMod[collMod] database command in conjunction with the index collection flag. Otherwise, to
change the value of the option of an existing index, you must drop the index first and recreate.

== OperatorFabric Kafka configuration

Next to publishing cards to OperatorFabric using the REST API, OperatorFabric also supports publishing cards via a Kafka Topic. In the default configuration Kafka is disabled.
To enable Kafka you need to set the consumer group to the consumer group you assign to the OpFab Kafka consumer. This can be any group-id, as long as it isn't used by other consumers
(unless you explicitly want multiple consumers for the same group).

You can set the group_id by uncommenting the `kafka.consumer.group_id` in the `cards-publication.yml`

[source, yaml]
----
  kafka:
    consumer:
      group-id: opfab-command
----
By default, the consumer will consume messages from the `opfab` topic.
See link:{spring_kafka_doc}[Spring for Apache Kafka] for more information on the Spring Kafka implementation.

With the default settings, the Kafka consumer expects a broker running on http//127.0.0.1:9092 and a schema registry on http://127.0.0.1:8081.

Operator Fabric is also able to publish response cards to a Kafka topic. The default topic name  `opfab-response`. You can specify which response cards
are to be returned via Kafka by setting the `externalRecipients-url` in the `cards-publication` yaml file. Instead of setting `http://` URL you should set it to `kafka:`

[source, yaml]
----
externalRecipients-url: "{\
           processAction: \"http://localhost:8090/test\", \
           mykafka: \"kafka:topicname\"
           }"
----

Note that `topicname` is a placeholder for now. All response cards are returned via the same Kafka response topic, as specified in the `opfab.kafka.topics.response-card` field.

Also note enabling Kafka does not disable the REST interface.
