// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




= Security Configuration

Configure the security concern througout several files:

* `application.yml` of each `core service`;
* `web-ui.jsom` served by the `web-ui` service;
* `default.conf` of the `web-ui` service.

Each service use the `application.yml` file for its generic configuration. Customise the service using a dedicated `spring profile` or using a customised `application.yml`. Launch the service with a given profile to override all or part of the service properties.
There are two profiles awailable `dev` and `docker`. The associated files are respectivly `application-dev.yml` and `application-docker.yml` located in `src/main/resources`
of each `core service` root folder.

== Run time

Provide the `spring profile` as parameter of the CLI launching the service. Override the default `application.yml` by placing a customized `application.yml` in a folder named `config` created in the folder of the service `jar`.

== Within Docker images

By construction, the `application-docker.yml` configures the docker running service. To override this configuration, use a docker volume mapped to `/config/application.yml` path
within the images.

== application.yml

|===
|name|default|mandatory?|Description

|operatorfabric.security.oauth2.client-id|null|yes| Oauth2 client id used by OperatorFabric may be specific for each service
|operatorfabric.security.jwt.login-claim|sub|no| Jwt claim is used as user login or id
|operatorfabric.security.jwt.expire-claim|exp|no| Jwt claim is used as token expiration timestamp
|spring.security.provider-url|null|no|The keycloak instance url. Helper properties used in `application-dev.yml`
|spring.security.provider-realm|null|no|The realm name within the keycloak instance. Helper properties used in `application-dev.yml`
|spring.security.oauth2.resourceserver.jwt.jwk-set-uri|null|yes|The url providing the certificat used to verify the jwt signature
|===

[NOTE]
====
**example of `application-dev.yml`**

[source,yml]
----
operatorfabric:
    security:
        oauth2:
            client-id: opfab-client
        jwt:
            login-claim: preferred_username
            expire-claim: exp
spring:
  security:
    provider-url: http://localhost:89
    provider-realm: dev
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.provider-url}/auth/realms/${spring.security.provider-realm}/protocol/openid-connect/certs
----
where `operatorfabric.security.jwt.expire-claim` could have been omitted because having the same value as the default one 
and where `jwt-set-uri` reuses `provider-url` and `provider-realm` properties.

**example of `application-docker.yml`**

[source,yml]
----
operatorfabric:
    security:
        oauth2:
            client-id: opfab-client
        jwt:
            login-claim: preferred_username
            expire-claim: exp
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/dev/protocol/openid-connect/certs
----
where `operatorfabric.security.jwt.expire-claim` could have been omitted because having the same value as the default one
and
where `jwt-set-uri` property value is directly set.

====

Each service needs to be configured with such files.

=== `web-ui.json`

Nginx web server serves this file. OperatorFabric creates and uses a custom Docker image containing an Nginx server with a docker volume containing this file. The two docker-compose environments contain an example of it. The path in the image to it is `/usr/share/nginx/html/opfab/web-ui.json`. 

For OAuth2 security concerns into this file, there are two ways to configure it, based on the Oauth2 chosen flow.
There are several common properties:

- `security.realm-url`: OAuth2 provider realm under which the OpertaroFabric client is declared;
- `security.provider-url`: url of the keycloak server instance.
- `security.logout-url`: url used when a user is logged out of the UI;
- `security.oauth2.flow.provider`: name of the OAuth2 provider;
- `security.oauth2.flow.delegate-url`: url used to connect to the Authentication provider;
- `security.oauth2.flow.mode`: technical way to be authenticated by the Autentication provider.


=== OAuth2 Flows and specific configuration

There are 3 OAuth2 Authentication flows available into OperatorFabric UI:

- password grant: referred as `PASSWORD` mode flow;
- code flow : referred as `CODE` mode flow;
- implicit flow: referred as `IMPLICIT` mode flow.

==== OAuth2 PASSWORD or CODE Flows

These two modes share the same way of declaring the delegate URL.
`CODE` is the default mode of authentication for `deploy` docker-compose environment.

- `security.oauth2.flow.mode` to `PASSWORD` or `CODE`;
- `security.oauth2.flow.delegate-url` with the URL of the OAuth2 leading to the protocol used for authentication.

===== Example of Configuration For CODE Flow

[source,json]
----
{
    "security": {
      "oauth2": {
        "flow": {
          "mode": "CODE",
          "provider": "Opfab Keycloak",
          "delegate-url": "http://localhost:89/auth/realms/dev/protocol/openid-connect/auth?response_type=code&client_id=opfab-client"
      },
      "logout-url":"http://localhost:89/auth/realms/dev/protocol/openid-connect/logout?redirect_uri=http://localhost:2002/ui/",
    "provider-realm": "dev",
    "provider-url": "http://localhost:89"
    }
  }
}
----

Within the `delegate-url` property `dev` is the keycloak client realm of OperatorFabric.
For keycloak instance used for development purposes, this `delegate-url` correspond to the realm under which the client `opfab-client` is registred.
Here, the `client-id` value is `opfab-client` which is define as client under the `realm` named `dev` on the dev keycloak instance.

==== OAuth2 IMPLICIT Flow

It had its own way of configuration.
To enable IMPLICIT Flow authentication the following properties need to be set:

- `security.oauth2.flow.mode` to `IMPLICIT`;
- `security.oauth2.flow.delegate-url` with the URL of the OAuth2 leading to the `.well-known/openid-configuration` end-point used for authentication configuration.

===== Example of configuration for IMPLICIT Flow 

[source,json]
----
{
  "operatorfabric": {
    "security": {
      "oauth2": {
        "flow": {
          "mode": "IMPLICIT",
          "provider": "Opfab Keycloak",
          "delegate-url": "http://localhost:89/auth/realms/dev"
      },
      "logout-url":"http://localhost:89/auth/realms/dev/protocol/openid-connect/logout?redirect_uri=http://localhost:2002/ui/",
    "provider-realm": "dev",
    "provider-url": "http://localhost:89"
      }
    }
  }
}
----

Within the `delegate-url` property `dev` is the keycloak client realm of OperatorFabric.
For keycloak instance used for development purposes, this `delegate-url` correspond to the realm under which the client `opfab-client` is registred.
The url look up by the implicit ui mechanism is `http://localhost:89/auth/realms/dev/.well-known/openid-configuration`.
