// Copyright (c) 2018-2024 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




= Security Configuration

Configure the security concern throughout several files:

* `nginx.conf` of the nginx server
* `config/docker/common.yml` the common configuration file for back services
* `web-ui.json` served by the `web-ui` service;


== Authentication configuration 


There are 3 OAuth2 Authentication flows available into OperatorFabric UI:

- password grant: referred as `PASSWORD` mode flow;
- code flow : referred as `CODE` mode flow;
- implicit flow: referred as `IMPLICIT` mode flow.

Alternatively there is also another flow available:

- none flow: referred as `NONE` mode flow.

The `NONE` flow assumes that the application is behind a secured proxy which handles login and token generation.
Calls to backend services will get a valid token added to the headers and the token will not be visible for the (web)client.

=== Nginx Configuration


The UI calls need some mapping to reach the Authentication Provider. In the default OperatorFabric configuration it's a
`docker keycloak instance`, called `keycloak` in the project `docker-compose.yml` files.

There are 3 properties to configure within `nginx.conf` file:

* `$KeycloakBaseUrl`: the base url of keycloak;
* `$OperatorFabricRealm`: the realm configure within keycloak instance to provide authentication to OperatorFabric;
* `$ClientPairOFAuthentication`: base64 encoded string of the pair of client authentication used by OperatorFabric
to log to the Authentication Provider (keycloak). The client-id and the client-secret are separated by a colon(':').

[NOTE]
====
**Example of the `docker` configuration**
----
# Url of the Authentication provider
    set $KeycloakBaseUrl "http://keycloak:89";
# Realm associated to OperatorFabric within the Authentication provider
    set $OperatorFabricRealm "dev";

# base64 encoded pair of authentication in the form of 'client-id:secret-id'
    set $ClientPairOFAuthentication "b3BmYWItY2xpZW50Om9wZmFiLWtleWNsb2FrLXNlY3JldA==" ;
----

where `b3BmYWItY2xpZW50Om9wZmFiLWtleWNsb2FrLXNlY3JldA==` is the base64 encoded string of
`opfab-client:opfab-keycloak-secret` with `opfab-client` as client-id and `opfab-keycloak-secret` its client secret.
====


=== Configuration file common.yml

|===
|name|default|mandatory?|Description 
|operatorfabric.security.oauth2.resourceserver.jwt.jwk-set-uri|null|yes|The url providing the certificate used to verify the jwt signature
|operatorfabric.security.jwt.loginClaim|sub|no| Jwt claim used for user login
|===

[NOTE]
====
**example of `common.yml`**

[source,yml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:  http://localhost:89/auth/realms/dev/protocol/openid-connect/certs
----

====

=== Configuration file web-ui.json

Nginx web server serves this file. OperatorFabric creates and uses a custom Docker image containing an Nginx server with a docker volume containing this file. The  docker-compose.yml contains an example of it. The path in the image to it is `/usr/share/nginx/html/opfab/web-ui.json`. 

For OAuth2 security concerns into this file, there are two ways to configure it, based on the Oauth2 chosen flow.
There are several common properties:

- `security.logout-url`: url used when a user is logged out of the UI;
- `security.oauth2.flow.delegate-url`: url used to connect to the Authentication provider;
- `security.oauth2.flow.mode`: technical way to be authenticated by the Authentication provider.
- `security.oauth2.client-id` : the OAuth2 client ID
- `security.jwt.login-claim` : the field in the token that will be used to identify your account (default value : sub)

=== OAuth2 PASSWORD or CODE Flows

These two modes share the same way of declaring the delegate URL. This has to be defined in web-ui.json by setting : 

- `security.oauth2.flow.mode` to `PASSWORD` or `CODE`;
- `security.oauth2.flow.delegate-url` with the URL of the OAuth2 leading to the protocol used for authentication.

==== Example of Configuration For CODE Flow


[source,json]
----
{
    "security": {
      "jwt": {
        "login-claim": "preferred_username"
      },
      "oauth2": {
        "client-id": "OAUTHCLIENTID",
        "flow": {
          "mode": "CODE",
          "delegate-url": "http://localhost:89/auth/realms/dev/protocol/openid-connect/auth?response_type=code&client_id=opfab-client"
        }
      },
      "logout-url":"http://localhost:89/auth/realms/dev/protocol/openid-connect/logout?redirect_uri=http://localhost:2002/"
  }
}
----

Within the `delegate-url` property `dev` is the keycloak client realm of OperatorFabric.
For keycloak instance used for development purposes, this `delegate-url` correspond to the realm under which the client `opfab-client` is registered.
Here, the `client-id` value is `opfab-client` which is defined as client under the `realm` named `dev` on the dev keycloak instance.

=== OAuth2 IMPLICIT Flow


It had its own way of configuration.
To enable IMPLICIT Flow authentication the following properties need to be set in web-ui.json:

- `security.oauth2.flow.mode` to `IMPLICIT`;
- `security.oauth2.flow.delegate-url` with the URL of the OAuth2 leading to the `.well-known/openid-configuration` end-point used for authentication configuration.

It is possible to configure the URL to redirect the browser after logout by setting the `security.implicit-mode-post-logout-url` parameter in web-ui.json.
Be careful that the configured value should be one of the valid post logout redirect URIs configured on Keycloak realm.

==== Example of configuration for IMPLICIT Flow 


[source,json]
----
{
  "security": {
    "jwt": {
        "login-claim": "preferred_username"
      },
    "oauth2": {
      "client-id": "OAUTHCLIENTID",
      "flow": {
        "mode": "IMPLICIT",
        "delegate-url": "http://localhost:89/auth/realms/dev"
      }
    },
    "logout-url":"http://localhost:89/auth/realms/dev/protocol/openid-connect/logout?redirect_uri=http://localhost:2002/",
    "implicit-mode-post-logout-url": "https://opfab.github.io"
  }
}
----

Within the `delegate-url` property `dev` is the keycloak client realm of OperatorFabric.
For keycloak instance used for development purposes, this `delegate-url` correspond to the realm under which the client `opfab-client` is registered.
The url look up by the implicit ui mechanism is `http://localhost:89/auth/realms/dev/.well-known/openid-configuration`.

===  NONE Flow

The configuration for the NONE flow is a bit different because the token isn't handled/visible in the front-end.

==== Nginx 

The following variables can be removed:

* `$KeycloakBaseUrl`
* `$OperatorFabricRealm`
* `$ClientPairOFAuthentication`

The locations for handling tokens can be edited to return a 401 by default.
If one of these locations is called, the token generated by the secured proxy has expired.
[source, config]
----
location /auth/check_token {
  return 401;
}
location /auth/token {
  return 401;
}
location /auth/code/ {
  return 401;
}
----
==== Web-ui.json

Set the security.oauth2.flow.mode to `NONE`;

Set the security.oauth2.client-id to `Your Oauth client ID`;

Use the security.jwt.login-claim to select value from the token will be used to identify your account. In this example `preferred_username` is used;

Settings that are not required are:

* delegate-url


==== Example of configuration 
[source, json]
----
{
    "security": {
      "jwt": {
        "login-claim": "preferred_username"
      },
      "oauth2": {
        "client-id": "OAUTHCLIENTID",
        "flow": {
          "mode": "NONE"
        }
      },
      "logout-url":"http://my-secured-proxy/OAUTHTENANTID/oauth2/logout?client_id=OAUTHCLIENTID&post_logout_redirect_uri=https%3A%2F%2Flocalhost:2002%2Fui%2Fui/"
    }
 }
----

== User creation

If a user exists in the authentication system but not in Opfab, their profile will be automatically created upon their initial login. The user's name and family name will be extracted from the authentication token.

|===
|name|default|mandatory?|Description

|operatorfabric.security.jwt.givenNameClaim|given-name|no| Jwt claim to use to get the user's name
|operatorfabric.security.jwt.familyName-claim|family-name|no| Jwt claim to used to get the user's family name
|===

[[jwt_mode]]

== Alternative way to manage groups (and/or entities)

By default, `OperatorFabric` manages groups (and/or entities) through the user\'s collection in the database.
Another mode can be defined, the JWT mode. The groups (and/or entities) come from the authentication token.

To activate this option , you need to set some parameter in the common.yml file : 
  
|===
|name|default|mandatory?|Description

|operatorfabric.security.jwt.groups.mode|OPERATOR_FABRIC|no| Set the group mode, possible values JWT or OPERATOR_FABRIC 
|operatorfabric.security.jwt.groups.rolesClaim.rolesClaimStandard.path||no| path in the JWT to retrieve the claim that defines a group
|operatorfabric.security.jwt.groups.rolesClaim.rolesClaimStandardArray.path||no| path in the JWT to retrieve the claim that defines an array of groups
|operatorfabric.security.jwt.groups.rolesClaim.rolesClaimStandardList.path||no| path in the JWT to retrieve the claim that defines a list of group
|operatorfabric.security.jwt.groups.rolesClaim.rolesClaimStandardList.separator||no| set the separator value of the list of group
|operatorfabric.security.jwt.groups.rolesClaim.rolesClaimCheckExistPath.path||no| path in the JWT to check if that path does exist, if it does, use the roleValue as a group 
|operatorfabric.security.jwt.groups.rolesClaim.rolesClaimCheckExistPath.roleValue||no| set the value of the group if the path exists
|operatorfabric.security.jwt.entitiesIdClaim||no| set the name of the field in the token
|operatorfabric.security.jwt.gettingEntitiesFromToken||no| boolean indicating if you want the entities of the user to come from the token and not mongoDB (possible values : true/false)
|===

_application.yml_

[source]
----
include::./examples/application_JWT_group_config.yml[]
----

_JWT example_

[source]
----
include::./examples/jwt_example.json[]
----

As the result, the group will be [ATTR1, ATTR2, roleA, roleB, roleC, USER, roleBBB, roleAAA]



include::certificates.adoc[leveloffset=+1]

== IP address control

For each user it is possible to configure a list of authorized source ip addresses by setting the `authorizedIPAddresses` field in User object.
