// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.



= Users Business service

OperatorFabric Cards-Consultation Business service is a Spring Webflux application
bootstrapped using SpringBoot.

== Mandatory configuration, Profiles and default properties

The service has no mandatory configuration beside global configuration and
usual bootstrap configuration.

For other configuration see:

* link:{springboot_doc}/reference/htmlsingle/[Spring Boot documentation].
* link:{spring_doc}spring-framework-reference/web.html#mvc[Spring MVC documentation].

=== Service specific properties

|===
|name|default|mandatory?|Description

|operatorfabric.users.default.users|null|no| Array of user objects to create upon startup if they don't exist
|operatorfabric.users.default.user-settings|null|no| Array of user settings objects to create upon startup if they don't exist
|operatorfabric.users.default.groups|null|no| Array of group objects to create upon startup if they don't exist
|operatorfabric.users.default.entities|null|no| Array of entity objects to create upon startup if they don't exist

|===

=== default properties

The application-docker.yml file is a replacement application file we use for our
docker images configuration.

The application-dev.yml file is a replacement application file we use for our
development environment

The above embedded configurations are the basic settings of the application:

* it sets its service name


=== Sample development configuration

[source]
----
include::examples/dev-configurations/users.yml[]
----

=== Sample docker image configuration

[source]
----
include::examples/docker-configurations/users.yml[]
----

== Specifying external configuration properties when launching a jar file

See link:{springboot_doc}/reference/htmlsingle/#boot-features-external-config-application-property-files[Application Property Files]
on how to set up an external spring properties or yml file.

See link:{springboot_doc}/reference/htmlsingle/#howto-set-active-spring-profiles[Set the Active Spring Profiles] for specifying alternate profile.


== Specifying configuration properties when launching a docker image

Our docker image expects optional property file to be stored in the container
/service-config folder. You can bind so docker volume to this path to make
properties or yml available.

At time of writing, you cannot specify an alternate profile at runUsers.
The default profiles activated are docker and native.

=== Available environment variables for docker image

* JAVA_OPTIONS: Additional java options

== Specifying configuration properties when launching on Kubernetes

In progress

=== Available environment variables when launching on Kubernetes

* JAVA_OPTIONS: Additional java options
