// Copyright (c) 2018-2025 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




= Web UI Configuration

OperatorFabric Web UI service is built on top of a link:https://www.nginx.com/[NGINX] server.
It  serves the Angular SPA to browsers and act as a reverse proxy for other services.

== NGINX configuration

An external `nginx.conf` file configures the OperatorFabric Nginx instance named `web-ui` service.The file is mounted as docker volumes. 

Three version of the configuration file are available in config/web-ui directory:
* `nginx-prod.conf`: The default configuration file which is used in production. 
* `nginx-cors-permissive.conf`: The configuration file used in development mode that allows CORS requests from any origin. This is useful for development purposes, but should not be used in production.
* `nginx-java.conf`: The configuration file used in development mode that allows CORS requests from any origin and starts the java services outside of docker containers. This is useful for development purposes, but should not be used in production.

When starting Opfab, depending on the chosen mode, the related file is copied to nginx.conf and mounted in the `web-ui` service container.


[WARNING]
====
The line customized in the nginx configuration file must end with à semicolon (';') otherwise the Nginx server will stop immediately
====

[[ui_properties]]
== UI properties

The properties lie in the `web-ui.json`. The following table describes their meaning and how to use them, the properties regarding the geomap feature are found in the <<ui_properties_geomap, next section>>.  An example file can be found in the config/web-ui/ui-config directory.

|===
|name|default|mandatory?|Description

|about
a|none
a|no
a|Declares application names and their version into web-ui about section. +
Each entry is
a free key value followed by its name (a string of characters), its version (a string of characters) and its facultative rank of declaration (a number). +
It is not necessary to declare `OperatorFabric` as application because it is added automatically with current release version and rank `0`. +
For example adding `Keycloak` application, with `'Keycloak'` as `name`, `1` as `rank` and  `'6.0.1'` as `version` should look like:
[source, json]
----
"about": {
    "keycloak": {
      "name": "Keycloak",
      "rank": 1,
      "version": "6.0.1"
    }
  }
----
|alerts.doNotAlertForHiddenCardReceived|false|no| if set to true, alert messages are not shown when receiving cards not visible in the feed
|alerts.alarmLevelAutoClose|false|no| if set to true, the ALARM (red) alert message will automatically close after a few seconds
|alerts.messageOnBottomOfTheScreen|false|no| if set to true, the alert message is shown on the bottom of the page

|archive.filters.hidePublisherAndRecipientsFields|false|no|If set to true, the emitter and recipients fields will not be displayed in the archives filters
|archive.filters.publishDate.days|10|no|The default search period (days) for publish date filter in archives page
|archive.filters.tags.list||no|List of tags to choose from in the corresponding filter in archives page
|archive.history.size|100|no|The maximum size of card history visible

|checkIfUrlIsLocked|true|no| if set to false, an OperatorFabric url can be used by several tabs in the same browser. Note that there can only be one token per browser for a given OperatorFabric url, so the first session will be replaced by the second one

|customCssToLoad||no|List of URLs of css files to be loaded at startup

|customJsToLoad||no|List of URLs of javascript files to be loaded at startup

|dashboard.processStateRedirects||no| Declares if a state when clicked in the dashboard should redirect to a custom menu or custom screen. If nothing is specified the redirection is pointing to the card feed. Here is a declaration with one redirection to a custom menu and one to a custom screen. The ids declared should match the ones in the ui-menu config.
[source, json]
----
"dashboard": {
    "processStateRedirects": [
      {
        "processId": "defaultProcess",
        "stateId": "chartLineState",
        "menuId": "uid_test_0",
        "urlExtension": "?search=chart&fulltext=1"
      },
      {
        "processId": "defaultProcess",
        "stateId": "questionState",
        "screenId": "testId"
      }
    ]
  }
----

|dashboard.processCustomLinks||no| Declares a list of link to show under the states of processes.Here is a declaration with two links  to custom screens.
[source, json]
----
  "dashboard": {
        "processCustomLinks": [
            { 
            "processId": "defaultProcess",
            "customLinks": [
                    {
                        "label": "Custom screen",
                        "customScreenId": "testId"
                    },
                    {
                        "label": "Custom screen 2",
                        "customScreenId": "testId2"
                    }
                ]
            }
        ]
  }
----
|dateRangePickerConfig|default|no|Specifies the mode for the date range picker configuration. The default mode can be changed to "ahead", which displays three predefined periods: W-1 (Week ahead), M-1 (Month ahead), and Y-1 (Year ahead) for the date range picker across all screens.
|defaultEntryPage|feed|no|This configuration determines the default page that will be displayed after a user logs in. The possible values include all core menus, with the exception of 'usercard' and 'about'. Additionally, you can set a custom application as the entry page by using 'businessconfigparty/menuId' as the value.
|environmentColor|blue|no| Color of the background of the environment name. The format of color is css, for example : `red` , `#4052FF`
|environmentName||no| Name of the environment to display in the top-right corner (examples: PROD , TEST .. ), if the value not set the environment name is not shown .

|externalDevicesEnabled|false|no|If true, users have the opportunity to play sounds on external devices rather than in the browser. See `settings.playSoundOnExternalDevice`

|feed.card.hideAckAllCardsFeature|true|no|Control if you want to show or hide the option for acknowledging all the visible cards of the feed
|feed.card.hideApplyFiltersToTimeLineChoice|false|no|Control if you want to show or hide the option of applying filters or not to timeline in the feed page
|feed.card.hideResponseFilter|false|no|Control if you want to show or hide the response filter in the feed page
|feed.card.hideProcessFilter|false|no|Control if you want to show or hide the process filter in the feed page
|feed.card.hideStateFilter|false|no|Control if you want to show or hide the state filter in the feed page
|feed.card.maxNbOfCardsToDisplay|100|no| Max number of card visible in feed (This limit is used for performance reasons, setting the value too high can have consequences on browser response times)
|feed.card.secondsBeforeLttdForClockDisplay|180|no| Number of seconds before lttd when a clock is activated in cards on the feed
|feed.card.time.display|BUSINESS|no
a|card time display mode in the feed. Values :

- BUSINESS: displays card with entire business period. It is the fallback if the set value is none of the values listed here;
- BUSINESS_START: displays card with business start date;
- PUBLICATION: displays card with publication date;
- LTTD: displays card with lttd date;
- NONE: nothing displayed.
|feed.card.titleUpperCase|true|no| If set to true, the card titles are in UPPERCASE. (Option applies to the 'Card Feed' and 'Archives'.)
|feed.defaultAcknowledgmentFilter|"notack"|no|Default card acknowledgment filtering option in feed page, possible values are : "notack", "ack", "all".
|feed.defaultSorting|"unread"|no|Default card sorting option in feed page, possible values are : "unread", "date", "severity", "startDate", "endDate".
|feed.enableGroupedCards|false|no|_(Experimental feature)_: If true cards with the same tags are grouped together. Clicking on the grouped card will show the other cards with the same tags in the feed.
|feed.showSearchFilter|false|no| If set to false, the search filter is hidden.
|feed.timeline.domains|["RT", "D", "7D", "W", "M", "Y"]|no| List of domains to show on the timeline, possible domains are : "RT", "D", "7D", "W", "M", "Y".

|heartbeatSendingInterval|30|yes| Frequency in seconds at which the ui sends heartbeat to the server

|i18n.supported.locales||no|List of supported locales (Only fr and en so far)
Values should be taken from the link:https://en.wikipedia.org/wiki/List_of_tz_database_time_zones[TZ database].

|logging.filters.publishDate.days|10|no|The default search period (days) for publish date filter in logging page
|logging.filters.tags.list||no|List of tags to choose from in the corresponding filter in logging page

|logo.base64|medium OperatorFabric icon|no|The encoding result of converting the svg logo to Base64, use this link:https://base64.guru/converter/encode/image/svg[online tool] to encode your svg. If it is not set, a medium (32px) OperatorFabric icon is displayed.
|logo.height|40|no|The height of the logo (in px) (only taken into account if logo.base64 is set). The value cannot be more than 48px (if it is set to more than 48px, it will be ignored and set to 48px).
|logo.width|40|no|The width of the logo (in px) (only taken into account if logo.base64 is set).

|secondsToCloseSession|60|no|Number of seconds between logout and token expiration. If you use IMPLICIT authentication mode, exercise caution when modifying the value to prevent logouts before token silent refresh.

|security.changePasswordUrl||no|URL to change the user password (if the top-right menu item "Change password" is visible)
|security.logout-url||yes
a|The keycloak logout URL. Is a composition of:
- Your keycloak instance and the _auth_ keyword (ex: https://www.keycloakurl.com/auth), but we also support domains without _auth_ (ex: https://www.keycloakurl.com/customPath)
- The realm name (Ex: dev)
- The redirect URL (_redirect_uri_): The redirect URL after success authentication
|security.oauth2.flow.delegate-url|null|no
a|Url to redirect the browser to for authentication. Mandatory with:

- CODE flow: must be the url with protocol choice and version as query parameters;
- IMPLICIT flow: must be the url part before `.well-known/openid-configuration` (for example in dev configuration it's
`http://localhost:89/auth/realms/dev`).
|security.oauth2.flow.mode|PASSWORD|no
a|authentication mode, available options:

- CODE: Authorization Code Flow;
- PASSWORD: Direct Password Flow (fallback);
- IMPLICIT: Implicit Flow.

|security.implicit-mode-post-logout-url|null|no| The redirect URL after logout when using IMPLICIT flow 

|selectActivityAreaOnLogin|false|no| if set to true the users belonging to multiple Entities will be required to configure activity area on login

|settings.dateFormat|Value from the browser configuration|no|Format for date rendering (example : dd/MM/yyyy )
|settings.dateTimeFormat|Value from the browser configuration|no|Format for date and time rendering (example : HH:mm dd/MM/yyyy )
|settings.getEmailFromUserInsteadOfSettings|false|no|If set to true, the email address used to notify the user is fetched from the token, otherwise the user must fill the field on the settings screen
|settings.locale|en|no|Default user locale (use en if not set)
|settings.playSoundForAction|false|no|If set to true, a sound is played when Action cards are added or updated in the feed
|settings.playSoundForAlarm|false|no|If set to true, a sound is played when Alarm cards are added or updated in the feed
|settings.playSoundForCompliant|false|no|If set to true, a sound is played when Compliant cards are added or updated in the feed
|settings.playSoundForInformation|false|no|If set to true, a sound is played when Information cards are added or updated in the feed
|settings.playSoundOnExternalDevice|false|no|If set to true (and `externalDevicesEnabled` is set to true as well) and the user has an external device configured, sounds will be played on this device rather than in the browser
|settings.remoteLoggingEnabled|false|no| If set to true, some logs from the UI are sent to the back and write in the log file of the cards-consultation service
|settings.hallwayMode|false|no| If set to true, hallway mode for feed screen will be enabled 
|settings.replayEnabled|false|no|If set to true, sounds are replayed every `settings.replayInterval` seconds until the user interacts with the application
|settings.replayInterval|5|no|Interval between sound replays (see `settings.replayEnabled`)
|settings.systemNotificationAction|false|no|If set to true, a system notification is sent when Action cards are added or updated in the feed
|settings.systemNotificationAlarm|false|no|If set to true, a system notification is sent when Alarm cards are added or updated in the feed
|settings.systemNotificationCompliant|false|no|If set to true, a system notification is sent when Compliant cards are added or updated in the feed
|settings.systemNotificationInformation|false|no|If set to true, a system notification is sent when Information cards are added or updated in the feed
|settings.styleWhenNightDayModeDesactivated||no|Style to apply if not using day night mode, possible value are DAY or NIGHT
|settings.timeFormat|Value from the browser configuration|no|Format for time rendering (example : HH:mm )
|settings.hallwayMode|false|no|If set to true, hallway mode for feed screen will be enabled
|settings.openNextCardOnAcknowledgment|false|no|If set to true, automatically opens the next card in the feed after acknowledging the current card
|settings.showAcknowledgmentFooter|false|no|If set to true, always shows the acknowledgments footer in cards
|settingsScreen.hiddenSettings||no|Array of string indicating which field(s) we want to hide in the settings screen. Possible values : +
"language" : if present, language field will not be displayed +
"remoteLoggingEnabled" : if present, the checkbox to activate remote logging will not be displayed +
"sounds" : if present, the checkboxes for sound notifications will not be displayed +
"systemNotifications" : if present, the checkboxes for systemNotifications will not be displayed +
"sendCardsByEmail" : if present, the email options will not be displayed +
"emailToPlainText" : if present, the email option to have the emails sent as plain text will not be displayed +
"sendDailyEmail" : if present, the email option to have the daily email recap will not be displayed +
"sendWeeklyEmail" : if present, the email option to have the weekly email recap will not be displayed +
"timezoneForEmails" : if present, the field to choose the timezone for emails will not be displayed +
"hallwayMode": if present, the checkbox to activate hallway mode won't be displayed +
"openNextCardOnAcknowledgment": if present, the checkbox to automatically open next card after acknowledgment won't be displayed +
"showAcknowledgmentFooter" : if present, the checkbox to always show acknowledgments footer won't be displayed
|showUserEntitiesOnTopRightOfTheScreen|false|no|If set to true, the user's entities with the "ACTIVITY_AREA" role will be displayed under the login on the top right of the screen

|title|OperatorFabric|no|Title of the application, displayed on the browser

|usercard.useDescriptionFieldForEntityList|false|no|If true, show entity `description` field instead of `name` in user card page


|===




IMPORTANT:
====
To declare settings parameters, you now need to group all fields under `settings: { }`
For example:

Replace the following invalid settings config
```
  "settings.replayInterval": 10,
  "settings.replayEnabled": true,
  "settings": {
    "about": {
      "keycloak": {
        "name": "Keycloak",
        "rank": 2,
        "version": "6.0.1"
      },
    }
    "locale": "en",
    "dateTimeFormat": "HH:mm dd/MM/yyyy",
    "dateFormat": "dd/MM/yyyy",
    "styleWhenNightDayModeDesactivated": "NIGHT"
  },
```

By this valid one :

```
  "settings": {
    "replayInterval": 10,
    "replayEnabled": true,
    "about": {
      "keycloak": {
        "name": "Keycloak",
        "rank": 2,
        "version": "6.0.1"
      },
    }
    "locale": "en",
    "dateTimeFormat": "HH:mm dd/MM/yyyy",
    "dateFormat": "dd/MM/yyyy",
    "styleWhenNightDayModeDesactivated": "NIGHT"
  },
```

====




[[ui_properties_geomap]]
=== Geomap Configuration


In the web-ui.json, the geomap can be configure with the following properties: 

|===
|name|default|mandatory?|Description

|feed.geomap.defaultDataProjection|EPSG:4326|no| The default data projection of `card.wktGeometry` to use when no wktProjection is embedded in the card.
|feed.geomap.enableMap|false|no|_(Experimental feature)_: If true a geographical map will be shown and cards that have geographical coordinates will be drawn on the map.
|feed.geomap.darkMode|not defined|no| Controls **how/if** the night filter is applied. `false` = always light (no filter), `true` = always dark (apply filter), not defined = follows application theme.
|feed.geomap.enableGraph|false|no|Show a graph on the map with number of cards per severity.
|feed.geomap.highlightPolygonStrokeWidth|2|no| Define the stroke width when highlighting polygon in the geomap view of a card.
|feed.geomap.initialLatitude|0|no| The initial latitude of the map when no cards with geographical coordinates are present.
|feed.geomap.initialLongitude|0|no| The initial longitude of the map when no cards with geographical coordinates are present.
|feed.geomap.initialZoom|1|no| Initial zoom level of the map.
|feed.geomap.mapProjection|EPSG:3857|no| The map projection to use for displaying the map. Supported values: `EPSG:3857` (Web Mercator, default) and `EPSG:2154` (Lambert 93 for France). Initial coordinates (`initialLongitude`/`initialLatitude`) may be given in WGS84 (EPSG:4326) or in the target projection; the system auto‑detects the format.
|feed.geomap.maxZoom|11|no| Max zoom level, to prevent zooming in too much when only one card is shown (or multiple cards in close proximity).
|feed.geomap.popupContent|publishDateAndTitle|no| Define the content of the geomap popup. Possible values are : `publishDateAndTitle` (default value) or `summary`.
|feed.geomap.zoomDuration|500|no| Time in milliseconds it takes to zoom the map to the specific location. Set to 0 to disable the zoom animation.
|feed.geomap.zoomLevelWhenZoomToLocation|14|no| Zoom level when zooming to a location of a selected card.
|feed.geomap.constrainLambert93Extent|true|no| Applies only when mapProjection is `EPSG:2154` (Lambert 93). Constrains the map extent to the valid area for France (including Corsica) to avoid 404s outside provider coverage.

|===

==== Night/Light Mode Parameter

The map appearance is controlled by a single parameter under `feed.geomap`:

- **`darkMode`**
  * `false`: Always light (no CSS filter applied)
  * `true`: Always dark (CSS inversion filter applied)
  * Omit the parameter to automatically follow the application's day/night theme

**Examples:**
```jsonc
// Always bright map, even when OpFab is in dark theme
"darkMode": false

// Always dark map with inverted tiles
"darkMode": true

// Follows application theme
// (no darkMode property)
```

Precedence (from highest to lowest):

1. Explicit `darkMode` if explicitly set to `true` or `false`
2. Application theme (night/day) when `darkMode` is not defined

The layers and tiles of the map can be configured using the `feed.geomap.layers` property. This property accepts an array of objects, each representing a layer with a `type` property and additional configuration options depending on the layer type. 

==== Common Layer Properties

All layer types support the following optional properties:

    - `opacity`: Number between 0 and 1 (default: 1). Controls layer transparency.
    - `zIndex`: Integer (default: 0). Controls layer stacking order. Higher values appear on top.

==== Layer Types

    - `osm`: OpenStreetMap tiles. No additional configuration required beyond common properties.
    
    - `geojson`: GeoJSON layers. Requires:
        ** `url`: URL to the GeoJSON file
        ** `style`: Optional styling object using OpenLayers flat style format (see: https://openlayers.org/en/latest/apidoc/module-ol_style_flat.html)
    
    - `xyz`: XYZ tiles. Requires:
        ** `url`: Endpoint with `{x}`, `{y}`, and `{z}` variables (e.g., "https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/grijs/EPSG:3857/{z}/{x}/{y}.png")
        ** `tileSize`: Optional integer (default server is often 256). Set only if the provider uses a non‑default tile size.

    - `wmts`: WMTS layers. Requires:
        ** `capabilitiesUrl`: URL to WMTS capabilities document
        ** `layer`: Layer identifier from capabilities
        ** `matrixSet`: Matrix set identifier from capabilities. The matrixSet must match your `mapProjection` — e.g., a `2154_*` set for `EPSG:2154`.
        (Ensure the provider allows client access and CORS; some services require API keys or specific referers.)
    
    - `arcgis` or `esri`: ArcGIS REST Map Service layers. Requires:
        ** `url`: ArcGIS REST service endpoint URL
        ** `layers`: Optional string specifying which layers to show (e.g., "0,1,2")
        ** `format`: Optional image format (default: "png")
        ** `transparent`: Optional boolean (default: true)
        ** `ratio`: Optional number (default: 1). Device pixel ratio
        ** `visible`: Optional boolean (default: true). Initial visibility
        (ArcGIS services may enforce usage limits, API keys, or CORS restrictions; check provider terms.)

==== Example Configurations

===== Web Mercator Projection (Standard)

Example configuration for the `feed.geomap.layers` property with all supported layer types using Web Mercator projection:

```jsonc
"geomap": {
  "enableMap": true,
  "mapProjection": "EPSG:3857",
  "defaultDataProjection": "EPSG:4326",
  "initialLongitude": 2.4408,
  "initialLatitude": 46.7211,
  "initialZoom": 6,
  "maxZoom": 18,
  "zoomLevelWhenZoomToLocation": 14,
  "zoomDuration": 500,
  "highlightPolygonStrokeWidth": 20,
  "popupContent": "summary",
  "darkMode": false,
  "layers": [
    {
      "type": "osm",
      "zIndex": 0
    },
    {
      "type": "xyz",
      "url": "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
      "zIndex": 1
    },
    {
      "type": "wmts",
      "capabilitiesUrl": "https://data.geopf.fr/annexes/ressources/wmts/essentiels.xml",
      "layer": "GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2",
      "matrixSet": "PM_0_19",
      "opacity": 0.7,
      "zIndex": 2
    },
    {
      "type": "arcgis",
      "url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer",
      "transparent": true,
      "opacity": 0.8,
      "zIndex": 3
    },
    {
      "type": "geojson",
      "url": "https://opendata.agenceore.fr/api/explore/v2.1/catalog/datasets/reseau-aerien-haute-tension-htb/exports/geojson?lang=fr&timezone=Europe%2FBerlin",
      "style": {
        "stroke-color": "red"
      },
      "zIndex": 4
    },
    {
      "type": "geojson",
      "url": "assets/layers/geojson-layer2.json",
      "zIndex": 5
    }
  ]
}
```

===== Lambert 93 Projection (France)

Example configuration optimized for France using Lambert 93 projection:

```jsonc
"geomap": {
  "enableMap": true,
  "mapProjection": "EPSG:2154",
  "defaultDataProjection": "EPSG:2154",
  "constrainLambert93Extent": true,
  "darkMode": false,
  "initialLongitude": 651966,
  "initialLatitude": 6862314,
  "initialZoom": 4,
  "maxZoom": 8,
  "zoomLevelWhenZoomToLocation": 6,
  "zoomDuration": 500,
  "highlightPolygonStrokeWidth": 20,
  "popupContent": "summary",
  "layers": [
    {
      "type": "wmts",
      "capabilitiesUrl": "https://data.geopf.fr/annexes/ressources/wmts/essentiels.xml",
      "layer": "GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2",
      "matrixSet": "2154_16",
      "opacity": 0.7,
      "zIndex": 1
    },
    {
      "type": "wmts",
      "capabilitiesUrl": "https://data.geopf.fr/annexes/ressources/wmts/essentiels.xml",
      "layer": "CADASTRALPARCELS.PARCELLAIRE_EXPRESS",
      "matrixSet": "2154_16",
      "opacity": 1,
      "zIndex": 2
    }
  ]
}
```


The example configuration references a GeoJSON layer from  Open Data GRD (https://opendata.agenceore.fr) and a wmts layer from IGN (https://geoservices.ign.fr) both published under open licence v2.0 https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf 
