// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




= Web UI

OperatorFabric Web UI service is built on top of a link:https://www.nginx.com/[NGINX] server.
It  serves the Angular SPA to browsers and act as a reverse proxy for other services.

== NGINX configuration

An external `default.conf` file configures the OperatorFabric Nginx instance named `web-ui` service.
Those files are mounted as docker volumes.
There are three of them in OperatoFabric. The two named `default.conf` in `${OF_HOME}/src/main/docker/deploy`
and `${OF_HOME}/src/main/docker/dev-environment`. They are the default ones, hence the name. The one in `dev-environment`
by setting permissive `CORS` rules enables web development using `ng serve` within the `ui/main` project.
It's possible to use `ng serve` with the `deploy` docker-compose version also. To do so use the conf file named
`default-web-dev.conf` by configuring the `${OF_HOME}/src/main/docker/deploy/docker-compose.yml` with the following line:
----
- "./default-web-dev.conf:/etc/nginx/conf.d/default.conf"
----
instead of:
----
- "./default.conf:/etc/nginx/conf.d/default.conf"
----

=== Authentication Provider configuration

==== Nginx Configuration

[WARNING]
====
The line customized must end with à semi-colon (';') otherwise the Nginx server will stop immediately
====

The UI calls need some mapping to reach the Authentication Provider. In the default OperatorFabric configuration it's a
`docker keycloak instance`, called `keycloak` in the project `docker-compose.yml` files.

There are 3 properties to configure within `default.conf` file:

* `$KeycloakBaseUrl`: the base url of keycloak;
* `$OperatorFabricRealm`: the realm configure within keycloak instance to provide authentication to OperatorFabric;
* `$ClientPairOFAuthentication`: base64 encoded string of the pair of client authentication used by OperatorFabric
to log to the Authentication Provider (keycloak). The cient-id and the client-secret are separated by a colon(':').

[NOTE]
====
**Example of the `deploy` configuration**
----
# Url of the Authentication provider
    set $KeycloakBaseUrl "http://keycloak:8080";
# Realm associated to OperatorFabric within the Authentication provider
    set $OperatorFabricRealm "dev";

# base64 encoded pair of authentication in the form of 'client-id:secret-id'
    set $ClientPairOFAuthentication "b3BmYWItY2xpZW50Om9wZmFiLWtleWNsb2FrLXNlY3JldA==" ;
----

where `b3BmYWItY2xpZW50Om9wZmFiLWtleWNsb2FrLXNlY3JldA==` is the base64 encoded string of
`opfab-client:opfab-keycloak-secret` with `opfab-client` as client-id and `opfab-keycloak-secret` its client secret.
====

==== Front-End Configuration

There are 3 OAuth2 modes of connection for the UI :
* `PASSWORD`: password mode managed directly by the UI. It's the fallback solution when no mode is configured,
or the currently configured is not handle by the UI;
*  `CODE`: correspond to the OAuth2 code flow mode;
* `IWPLICIT`: OAuth2 implicit flow needing a specific configuration (cf section below).

The first two use the same url configuration.

Please refer to the link:https://docs.nginx.com/[NGINX documentation] for more details for any required customisations.



=== Service specific properties

The properties lie in the `web-ui.json`. There are two of them one in the `${OF_HOME}/src/main/docker/deploy` folder
and in the `${OF_HOME}/src/main/docker/dev-environment` folder.
The following table describes their meaning and  how to use them.

|===
|name|default|mandatory?|Description

|operatorfabric.security.realm-url||yes|The realm name in keycloak server settings page. This is used for the log out process to know which realm should be affected.
|operatorfabric.security.provider-url||yes|The keycloak server instance
|operatorfabric.security.logout-url||yes
a|The keycloak logout URL. Is a composition of:
 - Your keycloak instance and the _auth_ keyword (ex: https://www.keycloakurl.com/auth), but we also support domains without _auth_ (ex: https://www.keycloakurl.com/customPath)
 - The realm name (Ex: dev)
 - The redirect URL (_redirect_uri_): The redirect URL after success authentification
|operatorfabric.security.oauth2.flow.mode|PASSWORD|no
a|authentication mode, awailable options:

 - CODE: Authorization Code Flow;
 - PASSWORD: Direct Password Flow (fallback);
 - IMPLICIT: Implicit Flow.
|operatorfabric.security.oauth2.flow.provider|null|no|provider name to display on log in button
|operatorfabric.security.oauth2.flow.delegate-url|null|no
a|Url to redirect the browser to for authentication. Mandatory with:

- CODE flow: must be the url with protocol choice and version as query parameters;
- IMPLICIT flow: must be the url part before `.well-known/openid-configuration` (for example in dev configuration it's
 `http://localhost:89/auth/realms/dev`).
|operatorfabric.feed.subscription.timeout|60000|no|Milliseconds between card subscription renewal
|operatorfabric.feed.card.time.display|BUSINESS|no
a|card time display mode in the feed. Values :

 - BUSINESS: displays card with entire business period. It the fallback if the set value is none of the values listed here;
 - BUSINESS_START: displays card with business start date;
 - PUBLICATION: displays card with publication date;
 - LTTD: displays card with lttd date;
 - NONE: nothing displayed.
|operatorfabric.feed.timeline.hide|false|no|If set to true, the time line is not loaded in the feed screen
|operatorfabric.feed.card.hideTimeFilter|false|no|Control if you want to show or hide the time filtrer in the feed page
|operatorfabric.feed.notify|false|no|If set to true, new cards are notified in the OS through web-push notifications
|operatorfabric.playSoundForAlarm|false|no|If set to true, a sound is played when Alarm cards are added or updated in the feed
|operatorfabric.playSoundForAction|false|no|If set to true, a sound is played when Action cards are added or updated in the feed
|operatorfabric.playSoundForCompliant|false|no|If set to true, a sound is played when Compliant cards are added or updated in the feed
|operatorfabric.playSoundForInformation|false|no|If set to true, a sound is played when Information cards are added or updated in the feed
|operatorfabric.i18n.supported.locales||no|List of supported locales (Only fr and en so far)
|operatorfabric.i10n.supported.time-zones||no|List of supported time zones, for instance 'Europe/Paris'.
Values should be taken from the link:https://en.wikipedia.org/wiki/List_of_tz_database_time_zones[TZ database].
|operatorfabric.navbar.thirdmenus.type|BOTH|no
a|Defines how thirdparty menu links are displayed in the navigation bar and how
they open. Possible values:

- TAB: Only a text link is displayed, and clicking it opens the link in a new tab.
- IFRAME: Only a text link is displayed, and clicking it opens the link in an iframe in the main content zone below
the navigation bar.
- BOTH: Both a text link and a little arrow icon are displayed. Clicking the text link opens the link in an iframe
while clicking the icon opens in a new tab.


|operatorfabric.archive.filters.page.size||no|The page size of archive filters
|operatorfabric.archive.filters.page.first||no|The first page start of archiving module
|operatorfabric.archive.filters.process.list||no|List of processes to choose from in the corresponding filter in archives
|operatorfabric.archive.filters.tags.list||no|List of tags to choose from in the corresponding filter in archives
|operatorfabric.settings.tags.hide||no|Control if you want to show or hide the tags filter in settings and feed page 
|operatorfabric.settings.nightDayMode|false|no|if you want to activate toggle for night or day mode 
|operatorfabric.settings.styleWhenNightDayModeDesactivated||no|style to apply if not using day night mode, possible value are DAY,NIGHT or LEGACY (black background and white timeline) 
|operatorfabric.settings.infos.disable||no|Control if we want to disable/enable editing user email, description in the settings page
|operatorfabric.settings.infos.email|false|no|Control if we want to hide(true) or display(false or not specified) the user email in the settings page
|operatorfabric.settings.infos.description|false|no|Control if we want to hide(true) or display(false or not specified) the user description in the settings page
|operatorfabric.settings.infos.language|false|no|Control if we want to hide(true) or display(false or not specified) the language in the settings page
|operatorfabric.settings.infos.timezone|false|no|Control if we want to hide(true) or display(false or not specified) the timezone in the settings page
|operatorfabric.settings.infos.timeformat|false|no|Control if we want to hide(true) or display(false or not specified) the timeformat in the settings page
|operatorfabric.settings.infos.dateformat|false|no|Control if we want to hide(true) or display(false or not specified) the dateformat in the settings page
|operatorfabric.settings.infos.datetimeformat|false|no|Control if we want to hide(true) or display(false or not specified) the datetimeformat in the settings page
|operatorfabric.settings.infos.tags|false|no|Control if we want to hide(true) or display(false or not specified) the tags in the settings page
|operatorfabric.settings.infos.sounds|false|no|Control if we want to hide(true) or display(false or not specified) the checkboxes for sound notifications in the settings page
|operatorfabric.settings.about
a|none
a|no
a|Declares application names and their version into web-ui about section. +
Each entry is
a free key value followed by its name (a string of characters), its version (a string of characters) and its facultative rank of declaration (a number). +
For `OperatorFabric` value, with `'OperatorFabric'` as `name` and `0` as `rank`, the value of `${currentVersion}`
is the version of the current release, `1.3.0.RELEASE` for example. +
It should look like:
[source, json]
----
"operatorfabric": {
 "name":  "OperatorFabric",
 "version":  "1.3.0.RElEASE",
 "rank": 0
}
----
|operatorfabric.logo.base64|medium OperatorFabric icon|no|The encoding result of converting the svg logo to Base64, use this link:https://base64.guru/converter/encode/image/svg[online tool] to encode your svg. If it is not set, a medium (32px) OperatorFabric icon is displayed.
|operatorfabric.logo.height|32|no|The height of the logo (in px) (only taken into account if operatorfabric.logo.base64 is set).
|operatorfabric.logo.width|150|no|The width of the logo (in px) (only taken into account if operatorfabric.logo.base64 is set).
|operatorfabric.logo.limitSize|true|no|If it is true, the height limit is 32(px) and the width limit is 200(px), it means that if the height is over than 32, it will be set to 32, if the width is over than 200, it is set to 200. If it is false, no limit restriction for the height and the width. 
|operatorfabric.title|OperatorFabric|no|Title of the application, displayed on the browser

|===

*User Settings default values*

|===
|name|default|mandatory?|Description
|operatorfabric.settings.timeZone||no|Default user time zone for users (use|operatorfabric.settings.timeFormat|LT|no|Default user time format (moment)
|operatorfabric.settings.dateFormat|LL|no|Default user date format (moment)
|operatorfabric.settings.dateTimeFormat|LL LT|no|Default user date format (moment)
|operatorfabric.settings.locale|en|no|Default user locale (use en if not set)
|operatorfabric.settings.default-tags||no|Default user list of filtered in tags

|===

=== Sample development configuration

[source,json]
----
include::examples/dev-configurations/web-ui.json[]
----

=== Sample docker image configuration

[source, json]
----
include::examples/docker-configurations/web-ui.json[]
----

== Specifying external configuration properties when launching a jar file

See link:{springboot_doc}/reference/htmlsingle/#boot-features-external-config-application-property-files[Application Property Files]
on how to set up an external spring property or yml file.

See link:{springboot_doc}/reference/htmlsingle/#howto-set-active-spring-profiles[Set the Active Spring Profiles] for specifying alternate profile.


== Specifying configuration properties when launching a docker image

OperatorFabric docker images expect optional property file to be stored within the `/service-config` container folder.
To make custom property or yml files available, bind relevant files to this path using a docker volume.

There is yet no alternate profile available for `Cards-Publication` service run time.
The default activated profiles are `docker` and `native`.

=== Available environment variables for docker image

* REGISTRY_HOST: Registry service host
* REGISTRY_PORT: Registry service port
* JAVA_OPTIONS: Additional java options

== Specifying configuration properties when launching on Kubernetes

In progress

=== Available environment variables when launching on Kubernetes

* REGISTRY_HOST: Registry service host
* REGISTRY_PORT: Registry service port
* JAVA_OPTIONS: Additional java options
