// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

[[gradle_tasks]]
= Gradle Tasks

In this section only custom tasks are described. For more
information on tasks, refer to the output of the "tasks" gradle task and
to gradle and plugins official documentation.

== Services

=== Common tasks for all sub-projects

* Test tasks
** unitTest: runs unit tests
* Other:
** copyWorkingDir: copies [sub-project]/src/main/docker/volume to
[sub-project]/build/
** copyDependencies: copy dependencies to build/libs

=== Core

* Swagger Generator tasks
** debugSwaggerOperations: generate swagger code from
/src/main/modeling/config.json to build/swagger-analyse
** swaggerHelp: display help regarding swagger configuration options for java

=== Businessconfig Service

* Test tasks
** prepareTestDataDir: prepare directory (build/test-data) for test data
** compressBundle1Data, compressBundle2Data: generate tar.gz businessconfig party
configuration data for tests in build/test-data
** prepareDevDataDir: prepare directory (build/dev-data) for bootRun task
** createDevData: prepare data in build/test-data for running bootRun task
during development
* Other tasks
** copyCompileClasspathDependencies: copy compile classpath dependencies,
catching lombok that must be sent for sonarqube

=== tools/generic

* Test tasks
** prepareTestData: copy test data from src/test/data/simple to
build/test-data/
** compressTestArchive: compress the contents of /src/test/data/archive to
/build/test-data/archive.tar.gz

== Client Library

The jars produced by the projects under "client" will now be published to Maven Central after each release to make
integration in client applications more manageable (see https://central.sonatype.org/publish[the official Sonatype
documentation]) for more information about the requirements and publishing process.

To that end, we are using:

* the https://docs.gradle.org/current/userguide/publishing_maven.html[Maven Publish] Gradle plugin to take care of the
metadata (producing the required pom.xml for example) and publishing the artifacts to a staging repository
* the https://docs.gradle.org/current/userguide/signing_plugin.html[Signing] Gradle plugin to sign the produced artifacts
using a GPG key.

[[client_lib_pub_conf]]
=== Configuration

For the signing task to work, you need to : 

==== Import the opfab secret key file
----
gpg2 --import OPFAB_KEY_FILE
----

==== Set the signing configuration in your gradle.properties file

Add to your gradle.properties : 

----
signing.gnupg.keyName=ID_OF_THE_GPG_KEY_TO_USE
signing.secretKeyRingFile=LOCATION_OF_THE_KEYRING_HOLDING_THE_GPG_KEY
----

To get the keyName (ID_OF_THE_GPG_KEY_TO_USE) use : 
----
gpg2 --list-secret-keys 
----

LOCATION_OF_THE_KEYRING_HOLDING_THE_GPG_KEY is usually /YOUR_HOME_DIRECTORY/.gnupg/secring.gpg


==== Set the credential for the publication

For the publication to the staging repository (OSSRH) to work, you need to set the credentials in your gradle.properties file:

----
ossrhUsername=SONATYPE_JIRA_USERNAME
ossrhPassword=SONATYPE_JIRA_PASSWORD
----

NOTE: The credentials need to belong to an account that has been granted the required privileges on the project (this
is done by Sonatype on request via the same JIRA).


==== More information 

See https://makandracards.com/makandra-orga/notes/37763-gpg-extract-private-key-and-import-on-different-machine[this link]
for more information about importing a GPG key to your machine and getting its id.

=== Relevant tasks

These plugins and the associated configuration in the `client.gradle` file make the following tasks available:

* `publishClientLibraryMavenPublicationToOssrhRepository`: this will publish the client jars to the OSSRH repository (in the
case of a X.X.X.RELEASE version) or to a `repos` directory in the build directory (in the case of a `SNAPSHOT` version).

* `publishClientLibraryMavenPublicationToMavenLocal`: this will publish the client jars to the local Maven repository

The publication tasks will call the signing task automatically.

See the plugins documentations for more details on the other tasks available and the dependencies between them.

NOTE: As the client library publication is currently the only configured publication in our build, it is also possible
to use the corresponding aggregate tasks as shortcuts: `publish` instead of
`publishClientLibraryMavenPublicationToOssrhRepository` and `publishToMavenLocal` instead of
`publishClientLibraryMavenPublicationToMavenLocal`.

== Gradle Plugins

In addition to these custom tasks and standard Gradle tasks, OperatorFabric
uses several Gradle plugins, among which:

* link:https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/[Spring Boot Gradle Plugin]
* link:https://github.com/palantir/gradle-docker[Palantir Docker Gradle Plugin]
* link:https://github.com/avast/gradle-docker-compose-plugin/[Docker Compose Plugin]
* link:https://github.com/int128/gradle-swagger-generator-plugin[Gradle Swagger Generator Plugin]
* link:https://github.com/asciidoctor/asciidoctor-gradle-plugin[Gradle Asciidoctor Plugin]
