// Copyright (c) 2025 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Greenmail servers

Greenmail is an open source test suite of email servers designed for testing purposes.
OperatorFabric uses Greenmail to test its mail notification service, enabling automated retrieval and inspection of sent messages via a JSON API.

== Greenmail Docker Container

A Greenmail Docker container is configured in the Opfab `docker-compose.yaml` file.

The container exposes:
- Port `3025` for the SMTP protocol (sending emails)
- Port `8080` for the HTTP REST API (managing and retrieving messages)

Greenmail's REST API supports listing, retrieving, and deleting messages.

To retrieve the list of received messages for a specific user, send an HTTP GET request to:
`http://localhost:8080/api/user/{user}/messages/`

== Accessing Greenmail via Web Interface

You can use a web interface to interact with Greenmail's REST API. Run the script `bin/startEmailClient.sh` to start a mail client container, which connects to the Greenmail container and exposes a web interface on port `8000`.

To access a user's mailbox, you must first create the user in Greenmail using the REST API:
`http://localhost:8080/#post-/api/user`

Refer to the Greenmail REST API documentation (http://localhost:8080/#) for details on available endpoints and usage.
