// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

:imagesdir: ../images

[[setup_dev_env]]
= Setting up your development environment

WARNING: The steps below assume that you have installed and are using
https://sdkman.io/[sdkman] and
https://github.com/creationix/nvm[nvm] to manage tool versions ( for java,
gradle, node and npm).

There are several ways to get started with `OperatorFabric`. Please look into
the section that best fits your needs.

TIP: If you encounter any issue, see
ifdef::single-page-doc[<<troubleshooting, Troubleshooting>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/dev_env/index.adoc#troubleshooting, Troubleshooting>>]
below. In particular,
a command that hangs then fails is often a proxy issue.

The following steps describe how to launch MongoDB, RabbitMQ and Keycloak
using Docker,  build OperatorFabric using gradle and run it using the
`run_all.sh` script.

== Clone repository
[source,shell]
----
git clone https://github.com/opfab/operatorfabric-core.git
cd operatorfabric-core
----

== Set up your environment (environment variables & appropriate versions of gradle, maven, etc…)
[source,shell]
----
source bin/load_environment_light.sh
----

TIP: From now on, you can use environment variable `${OF_HOME}` to go back to
the home repository of `OperatorFabric`.

== Deploy needed docker containers

=== Minimal configuration for `gradle` build

Two docker container must be available during a gradle build of `OperatorFabric`:
* RabbitMQ;
* MongoDB.

They can be launch using the `${OF_HOME}/src/main/docker/test-environment/docker-compose.yml`.

Remind that, during a gradle build, before the `assemble` task, the `test` one is called. The Unit tests depend on those
two software.

=== Enabling local quality report generation

To get a Sonarqube report, in addition to the two previously listed docker containers, a `SonarQube` docker container is
required. Use the `${OF_HOME}/src/main/docker/test-quality-environment/docker-compose.yml` to get them all running.

To generate the quality report use the following command:
[source,shell]
---
cd ${OF_HOME}
./gradlew jacocoTestReport
---

To export the different report into the `SonarQube` docker instance you need to install and use link:https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/[SonarScanner].

=== Development environment

During `OperatorFabric` development the running docker images of `MongoDB`, `RabbitMQ`, `web-ui` and `Keycloak` are needed.

The `docker-compose` can be run in detached mode:
[source,shell]
----
cd ${OF_HOME}/src/main/docker/dev-environment/
docker-compose up -d
----

The configuration of the `web-ui` embeds a grayscale favicon which can be usefull to spot the `OperatorFabric` dev tab in the browser.
Sometime a `CTRL+F5` on the tab is required to refresh the favicon.

== Build OperatorFabric with Gradle

Using the wrapper in order to ensure building the project the same way from one machine to another.

To only compile and package the jars:
[source,shell]
----
cd ${OF_HOME}
./gradlew assemble
----

To launch the Unit Test, compile and package the jars:
[source,shell]
----
cd ${OF_HOME}
docker-compose -f ${OF_HOME}/src/main/docker/test-environment/docker-compose.yml up -d
./gradlew build
----

== Run OperatorFabric Services using the `run_all.sh` script
[source,shell]
----
cd ${OF_HOME}
docker-compose -f ${OF_HOME}/src/main/docker/dev-environment/docker-compose.yml up -d
bin/run_all.sh start
----

WARNING: the `${OF_HOME}/bin/run_all.sh` must be launched from `${OF_HOME}` otherwise some runtime exception will occur.

TIP: See `bin/run_all.sh -h` for details.

== Check services status
[source,shell]
----
cd ${OF_HOME}
bin/run_all.sh status
----

== Log into the UI

*_URL:_* localhost:2002/ui/ +
*_login:_* tso1-operator +
*_password:_* test

The other users available in development mode are `rte-operator` and `admin`, both with `test` as password.

WARNING: It might take a little while for the UI to load even after all services are running.

WARNING: Don't forget the *final slash* in the URL or you will get an error, a `404` page.

== Push cards to the feed

You can check that you see cards into the feed by running the
`push_card_loop.sh` script.
[source,shell]
----
services/core/cards-publication/src/main/bin/push_card_loop.sh
----
