// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




[[setup_dev_env]]
= Setting up your development environment

WARNING: The steps below assume that you have installed and are using
https://sdkman.io/[sdkman] and
https://github.com/nvm-sh/nvm[nvm] to manage tool versions ( for java,
gradle, node and npm).

There are several ways to get started with `OperatorFabric`. Please look into
the section that best fits your needs.

TIP: If you encounter any issue, see
ifdef::single-page-doc[<<troubleshooting, Troubleshooting>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/dev_env/index.adoc#troubleshooting, Troubleshooting>>]
below. In particular,
a command that hangs then fails is often a proxy issue.

The following steps describe how to launch MongoDB, RabbitMQ and Keycloak
using Docker,  build OperatorFabric using gradle and run it using the
`run_all.sh` script.

== Clone repository
[source,shell]
----
git clone https://github.com/opfab/operatorfabric-core.git
cd operatorfabric-core
----

== Set up your environment (environment variables & appropriate versions of gradle, maven, etc…)
[source,shell]
----
source bin/load_environment_light.sh
----

TIP: From now on, you can use environment variable `${OF_HOME}` to go back to
the home repository of `OperatorFabric`.

== Deploy needed docker containers

=== A Minimal Configuration for `gradle` Build

The gradle build of `OperatorFabric` needs two docker containers running:

* RabbitMQ;
* MongoDB.

Launch them using the `${OF_HOME}/src/main/docker/test-environment/docker-compose.yml`.

Remind that, during a gradle build the `test` task runs before the `assemble` one.
The Unit tests depend on those two software.

=== Enabling local quality report generation

Sonarqube reporting, in addition to the two previously listed docker containers, needs a `SonarQube` docker container.
Use the `${OF_HOME}/src/main/docker/test-quality-environment/docker-compose.yml` to get them all running.

To generate the quality report, run the following commands:
[source,shell]
----
cd ${OF_HOME}
./gradlew jacocoTestReport
----

To export the reports into the `SonarQube` docker instance, install and use link:https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/[SonarScanner].

[[_docker_dev_env]]
=== Development environment

`OperatorFabric` development needs docker images of `MongoDB`, `RabbitMQ`, `web-ui` and `Keycloak` running.
The `web-ui` configuration needs a `nginx.conf`.

The `${OF_HOME}/config/dev/$docker-compose.sh` creates the `nginx.conf` file and then runs `docker-compose` in detached mode.
For this, use:
[source,shell]
----
cd ${OF_HOME}/config/dev
./docker-compose.sh
----

Once the `nginx.conf` created, run `docker-compose` independently is possible using:
[source,shell]
----
cd ${OF_HOME}/config/dev
docker-compose up -d
----


The configuration of the `web-ui` embeds a grayscale favicon which can be useful to spot the `OperatorFabric` dev tab in the browser.
To refresh the favicon, hit `CTRL+F5` on the page.

== Build OperatorFabric with Gradle

Using the wrapper in order to ensure building the project the same way from one machine to another.

To only compile and package the jars:
[source,shell]
----
cd ${OF_HOME}
./gradlew assemble
----

To launch the Unit Test, compile and package the jars:
[source,shell]
----
cd ${OF_HOME}
docker-compose -f ${OF_HOME}/src/main/docker/test-environment/docker-compose.yml up -d
./gradlew build
----

== Run OperatorFabric Services using the `run_all.sh` script
[source,shell]
----
cd ${OF_HOME}
docker-compose -f ${OF_HOME}/config/dev/docker-compose.yml up -d
bin/run_all.sh start
----

TIP: See `bin/run_all.sh -h` for details.

== Check services status
[source,shell]
----
cd ${OF_HOME}
bin/run_all.sh status
----

== Log into the UI

*_URL:_* localhost:2002/ui/ +
*_login:_* operator1 +
*_password:_* test

The other users available in development mode are `operator3` and `admin`, both with `test` as password.

WARNING: It might take a little while for the UI to load even after all services are running.

WARNING: Don't forget the *final slash* in the URL or you will get an error, a `404` page.

== Push cards to the feed

You can check that you see cards into the feed by running the
`push_card_loop.sh` script.
[source,shell]
----
services/core/cards-publication/src/main/bin/push_card_loop.sh
----
