// Copyright (c) 2018-2023 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

[[setup_dev_env]]
= Setting up your development environment

== Clone repository
[source,shell]
----
git clone https://github.com/opfab/operatorfabric-core.git
cd operatorfabric-core
----

Do not forget to set proxy if needed , for example : 

```
git config --global http.proxy http://LOGIN:PWD@PROXY_URL:PORT
```

== Install sdkman and  nvm 

sdkman is used to manage java version , see https://sdkman.io/ for installation

nvm is used to manage node and npm version , see https://github.com/nvm-sh/nvm for installation 
See : 

Do not forget to set proxy if needed , for example : 

```
export https_proxy= http://LOGIN:PWD@PROXY_URL:PORT
``` 

Once you have installed sdkman and nvm, you can **source** the following
script to set up your development environment (appropriate versions of Node 
Java and project variables set):

[source]
----
source bin/load_environment_light.sh
----

TIP: From now on, you can use environment variable `${OF_HOME}` to go back to
the home repository of `OperatorFabric`.

== Setting up your proxy configuration 

If you use a proxy to access internet, you must configure it for all tools needed to build opfab 

=== Docker 

To download images , you need to set the proxy for the docker daemon 

See  https://docs.docker.com/config/daemon/systemd/[docker documentation] to set the proxy 

To build docker images, you need to set a proxy via the variable https_proxy

```
export https_proxy= http://LOGIN:PWD@PROXY_URL:PORT
``` 

You may have some DNS error when building docker images, in this case use the IP address of your proxy instead of the FQDN .

=== Gradle 

In gradle.properties (in ~/.gradle repository)


Example : 
```
systemProp.https.proxyHost=PROXY_URL
systemProp.https.proxyPort=PROXY_PORT
systemProp.https.proxyUser=LOGIN
systemProp.https.proxyPassword=PASSWORD
```

=== Npm  

Example : 

```
npm config set https-proxy http://LOGIN:PWD@PROXY_URL:PORT
```

== Deploy needed docker containers

`OperatorFabric` development needs docker images of `MongoDB`, `RabbitMQ`, `web-ui` and `Keycloak` running.

For this, use:
[source,shell]
----
cd ${OF_HOME}/config/dev
./docker-compose.sh
----

== Build OperatorFabric with Gradle

Using the wrapper in order to ensure building the project the same way from one machine to another.


To fully build opfab : 

[source,shell]
----
cd ${OF_HOME}
./gradlew dockerTagSnapshot
----

Optionally, it is possible to 

=== Only compile and package the jars
[source,shell]
----
cd ${OF_HOME}
./gradlew assemble
----

=== Only launch the Unit Test, compile and package the jars
[source,shell]
----
cd ${OF_HOME}
./gradlew build
----

== Run OperatorFabric Services using the `run_all.sh` script
[source,shell]
----
cd ${OF_HOME}
bin/run_all.sh -w start
----

TIP: See `bin/run_all.sh -h` for details.


== Log into the UI

*_URL:_* localhost:2002 +
*_login:_* operator1_fr +
*_password:_* test

Other users available in development mode are `operator2_fr`, `operator3_fr`, `operator4_fr` and `admin`, with `test` as password.



== Push cards to the feed

You can check that you see cards into the feed by running the following scripts.
[source,shell]
----
./src/test/resources/loadTestConf.sh
./src/test/resources/send6TestCards.sh
----

== Enabling local quality report generation

This step is optional and is generally not needed (only needed if you want a Sonarqube report locally)

Sonarqube reporting needs a `SonarQube` docker container.
Use the `${OF_HOME}/src/main/docker/test-quality-environment/docker-compose.yml` to get them all running.

To generate the quality report, run the following commands:
[source,shell]
----
cd ${OF_HOME}
./gradlew jacocoTestReport
----

To export the reports into the `SonarQube` docker instance, install and use link:https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/[SonarScanner].