// Copyright (c) 2018-2022 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Useful recipes

== Running sub-project from jar file

*  java -jar [sub-projectPath]/build/libs/[sub-project].jar

== Overriding properties when running from jar file

* java -jar [sub-projectPath]/build/libs/[sub-project].jar
–spring.config.additional-location=file:[filepath]
NB : properties may be set using ".properties" file or ".yml" file. See
https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config[Spring
Boot configuration] for more info.
* Generic property list extract :
** server.port : embedded server port
* :services:core:businessconfig-party-service properties list extract :
** operatorfabric.businessconfig.storage.path (defaults to &quot;&quot;) : where to
save/load OperatorFabric Businessconfig  data

== Generating docker images

To Generate all docker images run `./gradlew dockerTagSnaphot' 

== Generating documentation (from AsciiDoc sources)

The sources for the documentation are located under `src/docs/asciidoc`. To generate HTML pages from these sources,
use the `asciidoctor` gradle task from the project root:

[source,bash]
----
cd $OF_HOME
./gradlew asciidoctor
----

The task output can be found under `$OF_HOME/build/docs/asciidoc`

== Generating API documentation

The documentation for the API is generated from the `swagger.yaml` definitions using SwaggerUI. To generate the
API documentation, use the `generateSwaggerUI` gradle task, either from the project root or from one of the services:

[source,bash]
----
cd $OF_HOME
./gradlew generateSwaggerUI
----

The task output can be found for each service under `[service-path]/build/docs/api`
(for example `services/businessconfig/build/docs/api`). Open the `index.html` file in a browser to have a look at
the generated SwaggerUI.