// Copyright (c) 2018-2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0


= Requirements

This section describes the projects requirements regardless of installation options.
Please see
ifdef::single-page-doc[<<setup_dev_env, Setting up your environment>>]
ifndef::single-page-doc[<<{gradle-rootdir}/documentation/current/dev_env/index.adoc#setup_dev_env, Setting up your environment>>]
below for details on:

* setting up a development environment with these prerequisites
* building and running OperatorFabric

== Tools and libraries

* Gradle 7 +
* Java 11.0 +
* Docker
* Docker Compose with 2.1+ file format support
* Chrome (needed for UI tests in build)
* Angular CLI
* https://stedolan.github.io/jq/[jq]

NOTE: the current Jdk used for the project is Java 11.0.9-zulu.

IMPORTANT: It is highly recommended to use https://sdkman.io/[sdkman] and
https://github.com/nvm-sh/nvm[nvm] to manage tools versions. The following steps rely on these tools.

Once you have installed sdkman and nvm, you can **source** the following
script to set up your development environment (appropriate versions of Gradle,
Java, Maven and project variables set):

.Set up development environment (using sdkman and nvm)
[source]
----
source bin/load_environment_light.sh
----

== Software

* RabbitMQ 3.7.6 +: AMQP messaging layer allows inter
service communication
* MongoDB 4.4 +: Card persistent storage

RabbitMQ is required for :

* Card AMQP push
* Multiple service sync

MongoDB is required for :

* Current Card storage
* Archived Card storage
* User Storage

IMPORTANT: Installing MongoDB and RabbitMQ is not necessary as preconfigured
MongoDB and RabbitMQ are available in the form of docker-compose configuration
files at
link:https://github.com/opfab/operatorfabric-core/tree/master/src/main/docker[src/main/docker]

== Browser support

The project is tested on recent versions of Firefox, Chromium and Chrome.
