// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




= Scripts (bin and CICD)

[horizontal]
bin/build_all.sh:: builds all artifacts as gradle is not able to manage
inter project dependencies
bin/clean_all.sh:: remove IDE data (project configuration, build output
directory) - idea, vsc
bin/load_environment_light.sh:: sets up environment when *sourced* (java
version, gradle version, maven version, node version)
bin/load_environment_ramdisk.sh:: sets up environment and links build
subdirectories to a ramdisk when *sourced* at ~/tmp
bin/run_all.sh:: runs all all services (see below)
bin/setup_dockerized_environment.sh:: generate docker images for all services

== load_environment_ramdisk.sh

There are prerequisites before sourcing load_environment_ramdisk.sh:

* Logged user needs sudo rights for mount
* System needs to have enough free ram

CAUTION: Never ever run a `gradle clean` or `./gradlew clean` to avoid deleting those links.

== run_all.sh

Please see `run_all.sh -h` usage before running.

Prerequisites

* mongo running on port 27017 with user "root" and password "password"
(See src/main/docker/mongodb/docker-compose.yml for a pre configured instance).
* rabbitmq running on port 5672 with user "guest" and password "guest"
(See src/main/docker/rabbitmq/docker-compose.yml for a pre configured
instance).

+++ <details><summary> +++
**Ports configuration**
+++ </summary><div> +++

|===
|Port | |

|2002 |web-ui | Web ui and gateway  (Nginx server)
|2100 |thirds |Third party management service http (REST)
|2102 |cards-publication |card publication service http (REST)
|2103 |users |Users management service http (REST)
|2104 |cards-consultation |card consultation service http (REST)
|4100 |thirds |java debug port
|4102 |cards-publication |java debug port
|4103 |users |java debug port
|4103 |cards-consultation |java debug port
|===

+++ </div></details> +++

== setup_dockerized_environment.sh

Please see `setup_dockerized_environment.sh -h` usage before running.

Builds all sub-projects, generate docker images and volumes for docker-compose.
