// Copyright (c) 2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Testing the External Devices service with dummy devices

== Docker mode

To test the External Devices service with dummy devices, launch an OperatorFabric instance using the
`$OF_HOME/config/docker/docker-compose.sh` script.

As described in `$OF_HOME/config/docker/docker-compose.yml`, in addition to lauching all OperatorFabric services it
will also start up two containers based on the dummy-modbus-device image: `dummy-modbus-device_1` and
`dummy-modbus-device_2`, both listening on their port 4030.

This matches default configuration provided:
.$OF_HOME/config/docker/external-devices-docker.yml

[source,yaml]
----
include::../../../../config/docker/external-devices-docker.yml[]
----

This means that provided the users have chosen to play sounds for these severities and to play sounds
on external devices, sending an ALARM card to operator1 should result in a message about writing 1 in the
dummy-modbus-device_1 logs, and sending an ACTION card to operator2 should result in a message about writing
6 in dummy-modbus-device_2.

Since the watchdog is enabled, once the devices are connected (either by calling the /connect endpoint or
by sending the first signal), you should also see the corresponding messages in the logs.

== Dev mode

To test in "dev" mode

----
$OF_HOME/config/dev/docker-compose.sh <1>
$OF_HOME/bin/run_all.sh status --externalDevices <2>
$OF_HOME/src/test/dummyModbusDevice/src/main/bin/startDummy.sh <3>
----
<1> Launch supporting containers (MongoDB, Keycloak, etc.)
<2> Launch OperatorFabric services (including External Devices)
<3> Start a dummy modbus device

NOTE: Configuration for the dummy modbus device can be provided in
`src/test/dummyModbusDevice/src/main/resources/application.yml`.

NOTE: As only one dummy Modbus device is started in this case, the default configuration for external devices has been
adapted from the one provided in docker mode so both `CDS_1` and `CDS_2` point to the same device, but with different
signal mappings. The mapping for `CDS_2` is "broken" on purpose, as it attempts to write in registers that are outside
the allowed register range, to demonstrate exceptions.

== Dummy devices configuration

See the https://github.com/opfab/operatorfabric-core/blob/develop/src/test/dummyModbusDevice/README.adoc[README for the Dummy Modbus Device module].
