// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0




[[troubleshooting]]
= Troubleshooting

+++ <details><summary> +++
**Proxy error when running businessconfig-party docker-compose**
+++ </summary><div> +++

.Error message
[source]
----
Pulling rabbitmq (rabbitmq:3-management)...
ERROR: Get https://registry-1.docker.io/v2/: Proxy Authentication Required
----

.Possible causes & resolution
When running docker-compose files using businessconfig-party images(such as rabbitmq,
mongodb etc.) the first time, docker will need to pull these images from
their repositories.
If the docker proxy isn't set properly, you will see the above message.

To set the proxy, follow https://docs.docker.com/config/daemon/systemd/[these
steps from the docker documentation].

If your proxy needs authentication, add your user and password as follows:
----
HTTP_PROXY=http://user:password@proxy.example.com:80/
----

IMPORTANT: The password should be URL-encoded.

+++ </div></details> +++

+++ <details><summary> +++
**Gradle Metaspace error**
+++ </summary><div> +++

Gradle task (for example gradle build) fails with the following error:

.Error message
[source]
----
* What went wrong:
Metaspace
----

.Possible causes & resolution
Issue with the Gradle daemon. Stopping the daemon using `gradle --stop`
and re-launching the build should solve this issue.

+++ </div></details> +++

+++ <details><summary> +++
**Java version not available when setting up environment**
+++ </summary><div> +++
When sourcing the link:https://github.com/opfab/operatorfabric-core/blob/master/bin/load_environment_light.sh[load_environment_light]
script to set up your environment, you might get the following error message:

.Error message
[source]
----
Stop! java 8.0.192-zulu is not available. Possible causes:
 * 8.0.192-zulu is an invalid version
 * java binaries are incompatible with Linux64
 * java has not been released yet
----

Select the next available version and update
link:https://github.com/opfab/operatorfabric-core/blob/master/bin/load_environment_light.sh[load_environment_light] accordingly before
sourcing it again.

.Possible causes & resolution
The java version currently listed in the script might have been deprecated
(for security reasons) or might not be available for your operating system
(for example, 8.0.192-zulu wasn't available for Ubuntu).

Run `sdk list java` to find out which versions are available. You will get
this kind of output:

[source]
----
================================================================================
Available Java Versions
================================================================================
     13.ea.16-open       9.0.4-open          1.0.0-rc-11-grl
     12.0.0-zulu         8.0.202-zulu        1.0.0-rc-10-grl
     12.0.0-open         8.0.202-amzn        1.0.0-rc-9-grl
     12.0.0-librca       8.0.202.j9-adpt     1.0.0-rc-8-grl
     11.0.2-zulu         8.0.202.hs-adpt
     11.0.2-open         8.0.202-zulufx
     11.0.2-amzn         8.0.202-librca
     11.0.2.j9-adpt      8.0.201-oracle
     11.0.2.hs-adpt  > + 8.0.192-zulu
     11.0.2-zulufx       7.0.211-zulu
     11.0.2-librca       6.0.119-zulu
     11.0.2-sapmchn      1.0.0-rc-15-grl
     10.0.2-zulu         1.0.0-rc-14-grl
     10.0.2-open         1.0.0-rc-13-grl
     9.0.7-zulu          1.0.0-rc-12-grl

================================================================================
+ - local version
* - installed
> - currently in use
================================================================================
----


+++ </div></details> +++

+++ <details><summary> +++
**BUILD FAILED with message `Execution failed for task ':ui:main-user-interface:npmInstall'.`**
+++ </summary><div> +++

.Error message
[source]
----
FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':ui:main-user-interface:npmInstall'.
----

.Possible causes & resolution
A `sudo` has been used before the `./gradlew assemble`.

IMPORTANT: Don't use *sudo* to build OperatorFabric otherwise unexpected problems could arise.

+++ </div></details> +++



+++ <details><summary> +++
**curl get Failed to connect to localhost:2002: Connection refused**
+++ </summary><div> +++

When using the following command line:
[source]
----
curl http://localhost:2002/ui/
----

.Error message
[source]
----
curl: (7) Failed to connect to localhost port 2002: Connexion refused
----

.Possible causes & resolution
The `web-ui` docker container stops running. Check its configuration.


+++ </div></details> +++


+++ <details><summary> +++
**curl 404 status return by ngnix**
+++ </summary><div> +++

When using the following command line:
[source]
----
curl http://localhost:2002/thirds/
----

The following error appears:

.Error message
[source]
----
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.17.10</center>
</body>
</html>
----

.Possible causes & resolution

The requested page is not or no more mapped by the `nginx.conf` of `web-ui`.
Update it or check for the new end point of the desired page.

For this example, `businessconfig` replaces now the former `thirds` end-point.

+++ </div></details> +++

+++ <details><summary> +++
**curl 404 status return by OperatorFabric**
+++ </summary><div> +++

When using the following command line:
[source]
----
curl http://localhost:2002/businessconfig/ -H "Authorization: Bearer ${token}"
----

where `${token}` is a valid OAuth2 JWT.

The following error appears:

.Error message
[source]
----
{"timestamp":"XXXX-XX-XXTXX:XX:XX.XXX+00:00","status":404,"error":"Not Found","message":"","path":"/businessconfig"}
----

where `XXXX-XX-XXTXX:XX:XX.XXX+00:00` is a time stamp corresponding to the moment when the request has been sent.

.Possible causes & resolution

The requested end-point is not or no more valid in `OperatorFabric`.
Check the API documentation for correct path.

For this example, `businessconfig/processes` is a correct end-point whereas `businessconfig` alone is not.

+++ </div></details> +++

+++ <details><summary> +++
**`ERROR: for web-ui` when running docker-compose in `${OF_HOME}/config/dev`**
+++ </summary><div> +++

When using the following commands:
[source]
----
cd ${OF_HOME}/config/dev
docker-compose up -d
----

The following error appears:

.Error message
[source]
----
ERROR: for web-ui  Cannot start service web-ui: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/home/legallron/projects/operatorfabric-core/config/dev/nginx.conf\\\" to rootfs …
----

where `…` is specific to the runtime environment.

.Possible causes & resolution

There is no `nginx.conf` file in the `${OF_HOME}/conf/dev` directory.

A first run of OperatorFabric `docker-compose` in dev config needs a `nginx.conf` file.
To create it, and run a docker-compose environment use:
[source]
----
cd ${OF_HOME}/config/dev
./docker-compose.sh
----

If docker-compose has created a `nginx.conf` directory, delete it before running the previous commands.

Once this `nginx.conf` file created a simple `docker-compose up -d` is enough to run a dev docker-compose environment.
Sometimes a `nginx.conf` has been created as an attempt to launch the `web-ui` docker.
See the following section to resolve this.

+++ </div></details> +++

+++ <details><summary> +++
**`/docker-compose.sh: ligne 7: ./nginx.conf: is a folder` when running `${OF_HOME}/config/dev/docker-compose.sh`**
+++ </summary><div> +++

When using the following commands:
[source]
----
cd ${OF_HOME}/config/dev
./docker-compose.sh
----

The following error appears:

.Error message
[source]
----
./docker-compose.sh: ligne 7: ./nginx.conf: is a folder
----

.Possible causes

A `docker-compose up` has been run previously without `nginx.conf`.
A folder named `nginx.conf` has been created by `docker-compose`.

.Resolution

You have rights to delete the folder:
[source]
----
cd ${OF_HOME}/config/dev
rm -rf nginx.conf
./docker-compose.sh # if you want to run OperatorFabric directly after.
cd ${OF_HOME}
bin/run_all.sh start
----

You don't have the rights to delete the folder:
[source]
----
cd ${OF_HOME}/config/dev
docker run -ti --rm -v $(pwd):/current alpine # if there is no `alpine` docker available it will pull it from dockerHub
# your are now in the alpine docker container
cd /current
rm -rf nginxconf
<ctrl-d> # to exit the `alpine` container bash environement
./docker-compose.sh # if you want to run OperatorFabric directly after.
cd ${OF_HOME}
bin/run_all.sh start
----


+++ </div></details> +++
