// Copyright (c) 2018-2022 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= User Interface

IMPORTANT: In the following document the variable declared as `OF_HOME` is the root folder of the `operatorfabric-core project`.

[horizontal]
CLI:: stands for *Command Line Interface*


== Build

Within the folder `${OF_HOME}/ui/main`, run `ng build` to build the project.

The build artifacts will be stored in:

[source,shell]
----
${OF_HOME}/ui/main/build/distribution
----

The previous command could lead to the following error:
[source, shell]
----
Generating ES5 bundles for differential loading...
An unhandled exception occurred: Call retries were exceeded
See "/tmp/ng-<random-string>/angular-errors.log" for further details.
----

where `ng-<random-string>` is a temporary folder created by Angular to build the front-end.

Use `node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build` instead to solve this problem.

== Test

=== Standalone tests

Run in the `${OF_HOME}/ui/main` directory the command `ng test --watch=false` to execute the unit tests
on https://jasmine.github.io[Jasmine] using https://karma-runner.github.io[Karma] to drive the browser.

=== Test during UI development

. if the RabbitMQ, MongoDB and Keycloak docker containers are not running, launch them;
. set your environment variables with `source ${OF_HOME}/bin/load_environment_light.sh`;
. run the micro services using the same command as earlier: `${OF_HOME}/bin/run_all.sh start`;
. launch an angular server with the command: `ng serve`;
. test your changes in your browser using this url: `http://localhost:4200` which leads to `http://localhost:4200/#/feed`.

==== Troubleshooting : 

If `ng serve` returns the error `Command 'ng' not found`, install the Angular CLI globally with the following
command.

----
npm install -g @angular/cli
----

This will install the latest version of the Angular command line, which might not be in line with the one used by the
project, but it's not an issue as when you run `ng serve` the local version of the Angular CLI
(as defined in the package.json file) will be used.

If it is still not running , launch in the ui/main directory 

----
npm link @angular/cli
----