// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

:imagesdir: ../images

= User Interface

The https://github.com/angular/angular-cli[Angular CLI] version 6.0.8 has been used to generate this project.

IMPORTANT: In the following document the variable declared as `OF_HOME` is the root folder of the `operatorfabric-core project`.

[horizontal]
CLI:: stands for *Command Line Interface*
SPA:: stands for *Single Page Application*

== Run

=== Linux

//TODO Explain that the back needs to be running to be able to test in 4200. Replace steps below by link to appropriate doc

After launching docker containers, use the following command line `$OF_HOME/bin/run_all.sh start` to run the application.
Once the whole application is ready, you should have the following output in your terminal:

[source, shell]
----
##########################################################
Starting client-gateway-cloud-service, debug port: 5008

##########################################################
pid file: $OF_HOME/services/infra/client-gateway/build/PIDFILE
Started with pid: 7479

##########################################################
Starting users-business-service, debug port: 5009

##########################################################
pid file: $OF_HOME/services/core/users/build/PIDFILE
Started with pid: 7483

##########################################################
Starting cards-consultation-business-service, debug port: 5011

##########################################################
pid file: $OF_HOME/services/core/cards-consultation/build/PIDFILE
Started with pid: 7493

##########################################################
Starting cards-publication-business-service, debug port: 5012

##########################################################
pid file: $OF_HOME/services/core/cards-publication/build/PIDFILE
----

Wait a moment before trying to connect to the`SPA`, leaving time for the`client-gateway` to boot up completely.

The `SPA`, on a local machine, is available at the following Url: `http://localhost:2002/ui/`.

To log in you need to use a valid user among the following: `tso1-operator`, `rte-operator` or `admin`.
The common password is `test` for them all.

To test the reception of cards, you can use the following script to create dummy cards:

[source,shell]
----
${OF_HOME}/services/core/cards-publication/src/main/bin/push_cards_loop.sh
----

Once logged in, with that script running in the background, you should be able to see some cards displayed in `http://localhost:2002/ui/feed`.


== Build

Run `ng build` to build the project. The build artifacts will be stored in :

[source,shell]
----
${OF_HOME}/ui/main/build/distribution
----

== Test

=== Standalone tests

Run in the `${OF_HOME}/ui/main` directory the command `ng test --watch=false` to execute the unit tests
on https://jasmine.github.io[Jasmine] using https://karma-runner.github.io[Karma] to drive the browser.

=== Test during UI development

. if the RabbitMQ, MongoDB and Keycloak docker containers are not running, launch them;
. set your environment variables with `source ${OF_HOME}/bin/load_environment_light.sh`;
. run the micro services using the same command as earlier: `${OF_HOME}/bin/run_all.sh start`;
. if needed, enable a card-operation test flow using the script `${OF_HOME}/service/core/cards-publication/src/main/bin/push_cards_loop.sh`;
. launch an angular server with the command: `ng serve`;
. test your changes in your browser using this url: `http://localhost:4200` which leads to `http://localhost:4200/#/feed`.
