// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

= Version 0.15.1.RELEASE

== Bug
* [OC-458] - Fix/test docker-compose
+
_The containers created by test-environment and test-quality-environment docker-compose now have default
docker-generated names rather than set names (e.g. *+test-environment_keycloak_1+* rather than *keycloak*). This is
done to avoid conflicts._
* [OC-442] - Cards in the feed aren't no longer sorted according to their arrival 
* [OC-487] - Feed empty or unresponsive when changing user
* [OC-615] - Once logged if the user reload the UI the navbar alone is displayed
+
_See configuration https://opfab.github.io/documentation/0.16.1.SNAPSHOT/user_guide/#_web_ui[doc] and  see https://opfab.github.io/documentation/0.16.1.SNAPSHOT/user_guide/#_operator_fabric_specific_configuration[doc]: add the relam name and keycloak server instance ip address to web-ui.json and application.yml_

== Story
* [OC-579] -Now, for each microservice DockerHub will offer the following tags:
+
** snapshot: Current snapshot version as generated by the daily CRON travis job.
** X.X.X.RELEASE: Image corresponding to the given release. Past releases are kept.
** latest: Shortcut for the latest release.

* [OC-616] - Change severity names :
+
** INFORMATION is replaced by NOTIFICATION 
** QUESTION is replaced by COMPLIANT 
+
It is necessary to remove or modify card created with previous version in the mongoDB database for the sytem to work properly.

* [OC-618] - Add the possibility  to hide some fields in settings page
+
_See the *web-ui* configuration doc from here:  https://opfab.github.io/documentation/0.16.1.SNAPSHOT/user_guide/#_web_ui[Service specific properties]. (All the properties starting with *operatorfabric.settings.infos*)_

== Task

* [OC-507] - CI/CD hooks should only be triggered on the master branch
+
_No administration/user impact._
* [OC-552] - Network and service names should be consistent in docker-compose files
+
_Creating the *opfabnet* and *operatorfabricnet* networks is no longer required, docker-compose files now rely on
default docker-generated networks (such as *+deploy_default+*)._
* [OC-560] - Fix SEVERE warnings in doc generation
+
_No administration/user impact._
* [OC-585][OC-595][OC-600][OC-601] - Multiple security correction 
+
_No administration/user impact._
* [OC-602] - Deprecated MongoClient constructor 
+
_Today we have only one MongoDB server. But if one day we have several servers then there can only be one login/password for all the servers._
* [OC-611] - Create missing Unit Test for Implicit flow in the UI
* [OC-612] - Document the dev keycloak configuration to test implicit flow authentication
+
_See the *web-ui* configuration doc frome here: link:https://opfab.github.io/documentation/0.16.1.SNAPSHOT/user_guide/#_operator_fabric_specific_configuration[OperatorFabric User Guide]_
* [OC-625] - Fix add_header script and update copyright headers
+
_Note to contributors: Copyright headers are up to date as of today, please make sure to add headers to any new file
that you add._
* [OC-630] - Delete demo docker-compose
+
_The demo docker compose has been deprecated in favour of using the deploy docker-compose and the push_card_loop as
described in the https://github.com/opfab/operatorfabric-core#8-docker-demo[README]._
* [OC-641] - Correct deprecated warning in build



