// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

= Version 0.16.1.RELEASE

== Bug
* [OC-549] - Thirds API does't return 404 when requested third doesn't exist.
* [OC-325] - Put a long heardbeatTimeout to avoid loosing cards
* [OC-349] - Correct bug in token silent refresh (Implicit Mode) 
* [OC-715] - [Cards-consultation][tests] : clean must be done after each unit test

== Task

* [OC-712] - When Token refresh is not possible redirect to login page (Implcit Mode)
[%hardbreaks]
* [OC-649] - Upgrade the backend
* [OC-681] - Migrate angular from version 7 to 8
_In this task, we moved to version 8 of Angular, we would draw your attention that there is a breaking changes during this migration, especially, we passed from v10.10.0 to v10.16.3 of node, and from 7 to 8 of ng command (angular-cli)_
_Please refer to angular.json file the packages we have migrated_
