// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

= Version 1.0.0.RELEASE

== Story
* [OC-624] As a user I want to sort cards on the feed either by severity, lttd, publishDate or by lttd, publishDate only.
+
_In the feed, the cards remain sorted by default by severity, then by lttd (last time to decide) desc.
(i.e. closest lttd first), then by publication date asc. (i.e. latest cards first)._
+
_This version adds a toggle to the feed buttons to switch to a second sort order that doesn't take severity
into account, so that cards are sorted by closest lttd then latest publication date._
+
_Note: No configuration is necessary._

== Bug
* [OC-549] - Thirds API does't return 404 when requested third doesn't exist.
* [OC-325] - Put a long heartbeat timeout to avoid losing cards
* [OC-349] - Correct bug in token silent refresh (Implicit Mode) 
* [OC-715] - [Cards-consultation][tests] : clean must be done after each unit test
* [OC-727] - regression in Action Service - feign.codec.DecodeException
* [OC-368] - Cards with an end date that is before their start date should be refused
* [OC-720] - CSS in card detail is not correctly applied until reload
* [OC-604] - On first opening the app, the feed filter isn't synchronized with timeline time horizon

== Task
* [OC-669] Card publication service refactoring
           - Remove unused and non working recipient options : INTERSECT , RANDOM, WEIGHTED and FAVORITE 
           - Remove unused field mainRecipient
           - Remove internal asynchronous mecanism to push cards in Mongo and Rabbit 
* [OC-643] - Remove code regarding unused virtual time in frontend
* [OC-687] - Remove unused OAuth2 micro-service
* [OC-712] - When Token refresh is not possible redirect to login page (Implicit Mode)
* [OC-724] - Adding an Endpoint for the logout process
+
_To successfully destroy the current session user in Keycloak, you need to provide a *logout-url* as explained in the https://opfab.github.io/documentation/0.16.1.SNAPSHOT/user_guide/#_web_ui[doc]_
[%hardbreaks]
* [OC-649] - Upgrade the backend
* [OC-681] - Migrate angular from version 7 to 8
+
_In this task, we moved to version 8 of Angular, we would draw your attention that there is a breaking changes during this migration, especially, we passed from v10.10.0 to v10.16.3 of node, and from 7 to 8 of ng command (angular-cli)_
_Please refer to angular.json file the packages we have migrated_
* [OC-652] - Update API Action documentation, more precisely, remove unused fields : lockCard, needsConfirm, updateState, contentStyle, inputs

== Feature
* [OC-204] - As a Client, I need a about section "about" with a fixed value and a freely configurable value
  ** adds release version and application name into jar manifests;
  ** displays current release version of `OperatorFabric` into the `UI about section`;
  ** enables new settings into `web-ui.yml` of `config service` to be displayed in the `UI about section`, cf user guide - web-ui section for more details.
