// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

== Version 1.1.0.RELEASE

=== Task
* [OC-636] - Delete backend time service
+
_The OperatorFabric deployment no longer requires a Time microservice._
* [OC-749] Build is passing even though documentation wasn't pushed
+
_Builds with a documentation stage will now fail if the push to the website repository wasn't successful._

=== Bug
* [OC-614] The possibility to associate sounds to cards is described in the card API but not implemented
+
_The API described the possibility to associate sounds to cards and to provide them in bundles. However, this was never
fully implemented. So in this release we removed all the existing code and API documentation regarding this feature.
Instead, OC-682 (see above) implements instance-wide sound notifications (one sound by severity)._
+
NOTE: Existing bundles and cards with media information will continue to work as before. Pushing a bundle or a card
with media information won't generate an error.

* [OC-730][OC-797] Correct bugs in timeline and major refactoring
+
_Please note that configuration and settings under timeLineDefaultClusteringFormats, defining date and time formats for
the timeline, no longer exist and have been replace by hard-coded defaults._
* [OC-783] Fix settingsOrConfig selector behaviour for booleans
* [OC-698] API testing - Get css - wrong response when fetching non-existing css file
* [OC-342] Set a new version of feed time filter to solve firefox incompatibility with datetime-local html5 attribut
* [OC-795] API testing - DELETE endpoints - deletion of "Content-Type:application/json" for header
* [OC-679] API testing- UserCreation - wrong response when the request body is erroneous
* [OC-779] API testing - Push cards - update documentation for return codes

=== Issue
* [OC-682] As a user I want sound to be played on cards arrival
+
_This feature allows (predefined) sounds to be played when cards of a given severity are added or updated in the feed.
Only cards that are currently visible in the feed based on its filters (severity, tag, time) can trigger sounds.
For sounds to be played for a given severity, the administrator needs to set the corresponding property to true.
See operatorfabric.sounds.* properties in the
https://opfab.github.io/documentation/1.1.0.RELEASE/user_guide/#_web_ui[configuration documentation] for more details.
Depending on their browser default settings, users might also need to allow sounds (globally or for the OperatorFabric url)
for this to work._
+
IMPORTANT: Due to the autoplay policy of some browsers (recent versions of Chrome for example), sounds won't be played
until the user has "interacted" with the application at least once: clicked a filter or menu, a card, etc. This is to
prevent malicious sites to autoplay unwanted content.
+
https://www.zapsplat.com[Sound effects obtained from zapsplat.com]

* [OC-773] As a user I want sound notifications to be manageable in my settings
+
_This feature allows the user to override the sound playing policy that has been defined in the configuration by the
administrator (see OC-682) in the settings screen._
+
IMPORTANT: To disable sounds for a given severity, you need to click the checkbox twice (check then uncheck) to set it
to false, otherwise your settings for this severity will remain "undefined" an the instance-wide configuration value
will be applied instead.
