// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

== Version 1.2.0.RELEASE

=== Bug
* [OC-799] Show date when timeline is on 1 day
* [OC-791] Add translation mechanism for timeline buttons
* [OC-816] API testing - User update (PUT) - error "500" NullPointerException instead of "'400" BAD_REQUEST
* [OC-360] On very wide screens, the filter panel at the top of the feed appears wider than the cards below it.
* [OC-648] API testing - Group fetching - wrong response when fetching information about an existing group

=== Task
* [OC-753] Add API tests with karate DSL
* [OC-801] - Allow for custom certification authorities or certificates
+
_See link:https://opfab.github.io/documentation/1.2.0.RELEASE/developer_guide/#_deployment[Deployment] for details_
* [OC-818] Implement automatic logout when token expired (code flow authentification mode )
* [OC-814] Remove registry and configuration microservice for action service
+
_ `Actions service` is now configured with it's own `application.yml` configuraion file._