// Copyright (c) 2018, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
:springboot_doc: https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/
:spring_doc: https://docs.spring.io/spring/docs/5.1.4.RELEASE/
:spring_cloud_config_doc: https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.1.0.RELEASE/
:spring_cloud_netflix_doc: https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.1.0.RC3/
:spring_cloud_gateway_doc: https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.1.0.RELEASE/
:mongo_doc: https://docs.mongodb.com/manual/reference/
:spring_amqp_doc: https://docs.spring.io/spring-amqp/docs/2.1.3.RELEASE/reference/htmlsingle/
:opfab_architecture_doc: https://opfab.github.io/documentation/0.4.1.SNAPSHOT/architecture/

== Configuration

As a micro service architectured solution, Operator Fabric has multiple services
to configure. These configuration are gathered by a Configuration Service that
can be redunded for safety.

See {opfab_architecture_doc}[Operator Fabric Architecture] for more information
on the different services.

All services are springboot application and share some common configuration and
uses jetty as an embedded servlet container. The following documentation
references describes Springboot configuration.

 * {springboot_doc}/reference/htmlsingle/[Springboot documentation]
 * {springboot_doc}/reference/htmlsingle/#boot-features-external-config[Springboot external configuration]
 * {springboot_doc}/reference/htmlsingle/#common-application-properties[Common application properties from Springboot documentation]

=== Global configuration

Aside from the configuration service, all configurations are gathered in the
configuration service environment backend (see <<Cloud Configuration service>>).

Note that a few things cannot be set in the global configuration backend and
must be set in each services bootstrap configuration file. In this regard,
<<Cloud Configuration service>>[Configuration] and <<Cloud Registry service>>[Registry]
services have specific configuration but for other services, they all require
the same minimal information:

* *mandatory* service name(spring.application.name)
* *mandatory* configuration name (spring.cloud.config.name)
* *mandatory* configuration fetch from registry enabled (spring.cloud.config.discovery.enabled: true)
* *mandatory* configuration service name in registry (spring.cloud.config.discovery.service-id)
* *mandatory* eureka registration (eureka.client.register-with-eureka: true and
eureka.client.fetch-registry: true)
* *mandatory* eureka registry urls (eureka.client.service-url.defaultZone)
* configuration fail fast (spring.cloud.config.fail-fast)
* configuration fetch maximum retry (spring.cloud.config.retry.max-attempts)

In most situation, you do not need to change the default bootstrap
configuration for those services. Make a copy of the default bootstrap (inside
the jar or from the sources) and set eureka up (see above).

The different services also share common configuration you can setup in the
config service backend. those common configuration may be set up in the backend ```application.yml``` file.

```
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uris:
        - mongodb://root:password@mongodb:27017/operator-fabric?authSource=admin&authMode=scram-sha1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authserver/auth/realms/dev/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://registry:8080/eureka
    region: default
  registryFetchIntervalSeconds: 5

operatorfabric:
  security:
    oauth2:
      client-id: opfab-client
      client-secret: opfab-oauth-secret
    jwt:
      login-claim: preferred_username
      expire-claim: exp
```

In the above exemple you can see that we need to configure:

* RabbitMQ (See {spring_amqp_doc}/reference/htmlsingle/[spring-amqp doc])
* MongoDB
* Eureka (See {spring_cloud_netflix_doc}/single/spring-cloud-netflix.html#_service_discovery_eureka_clients[spring eureka])
* Operator Fabric

==== Operator Fabric Mongo configuration

We only use URI configuration for mongo through the usage of the ```spring.data.mongodb.uris```,
it allows us to share the same configuration behavior for simple or cluster
configuration and with both spring classic and reactive mongo configuration.
See {mongo_doc}/connection-string/[mongo connection string] for the complete URI syntax.

==== Operator Fabric Specific configuration

Bellow are description of Operator Fabric specific configuration properties.

Note that other components may have specific configuration, see they relevant
sub-sections.

===== Security

|===
|name|default|mandatory?|Description

|operatorfabric.security.oauth2.client-id|null|yes| Oauth2 client id used by operator fabric may be specific for each service|
|operatorfabric.security.oauth2.client-secret|null|yes| Oauth2 client secret used by operator fabric may be specific for each service|
|operatorfabric.security.jwt.login-claim|sub|no| Jwt claim to use as user login or id|
|operatorfabric.security.jwt.expire-claim|exp|no| Jwt claim to use as token expiration timestamp|

|===

=== Per service Configuration Guides

include::../../../../services/infra/config/src/docs/asciidoc/configuration.adoc[leveloffset=+3]
include::../../../../services/infra/registry/src/docs/asciidoc/configuration.adoc[leveloffset=+3]
include::../../../../services/infra/client-gateway/src/docs/asciidoc/configuration.adoc[leveloffset=+3]
include::../../../../services/core/cards-publication/src/docs/asciidoc/configuration.adoc[leveloffset=+2]
include::../../../../services/core/cards-consultation/src/docs/asciidoc/configuration.adoc[leveloffset=+2]
include::../../../../services/core/thirds/src/docs/asciidoc/configuration.adoc[leveloffset=+3]
include::../../../../services/core/users/src/docs/asciidoc/configuration.adoc[leveloffset=+3]
include::../../../../services/core/time/src/docs/asciidoc/configuration.adoc[leveloffset=+3]
include::../../../../services/web/web-ui/src/docs/asciidoc/configuration.adoc[leveloffset=+2]