// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

= Security


== OAuth2 configuration

This concern is configured within the `${OF_HOME}/services/infra/config` project
into 3 distinct files:

* `application.yml`;
* `web-ui.yml`;
* `client-gateway.yml`.

They are located into the following folders within the `${OF_HOME}/services/infra/config/java/src/main/docker/volume` folder:

* `dev-configurations`: to be use into `dev` mode;
* `docker-configurations`: used by docker at run time.

EXAMPLE: the configuration for `dev` before compilation is done in the following files:
    - `${OF_HOME}/services/infra/config/java/src/main/docker/volume/dev-configurations/application.yml`;
    - `${OF_HOME}/services/infra/config/java/src/main/docker/volume/dev-configurations/client-gateway.ym`;
    - `${OF_HOME}/services/infra/config/java/src/main/docker/volume/dev-configurations/web-ui.yml`.

For test purposes in `dev` mode, it's possible to edit files located into ``${OF_HOME}/services/infra/config/build/docker-volume/dev-configurations`.
Be aware that those changes will be lost after a new compilation or even a simple re-run of the project.

This configuration files follow the `springframework` configuration convention. Within a same file it's possible to
use `link:https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions[SpEL ${}]` convention. For example,  `${AnotheProperty}` allows to re-use the value of `AnotherProperty` already declared.
It helps to avoid typos or missing to report some changes. An example could be find below into the `delegate-url` property.

=== application.yml

|===
|name|default|mandatory?|Description

|operatorfabric.security.oauth2.client-id|null|yes| Oauth2 client id used by OperatorFabric may be specific for each service
|operatorfabric.security.oauth2.client-secret|null|yes| Oauth2 client secret used by OperatorFabric may be specific for each service
|operatorfabric.security.jwt.login-claim|sub|no| Jwt claim is used as user login or id
|operatorfabric.security.jwt.expire-claim|exp|no| Jwt claim is used as token expiration timestamp
|spring.security.oauth2.resourceserver.jwt.provider-url|null|yes|The keycloak instance url
|spring.security.oauth2.resourceserver.jwt.provider-realm|null|yes|The realm name within the keycloak instance
|===

example of `application.yml`
```
operatorfabric:
    security:
        oauth2:
            client-id: opfab-client
            client-secret: opfab-keycloak-secret
        jwt:
            login-claim: preferred_username
            expire-claim: exp
```

where `operatorfabric.security.jwt.expire-claim` could have been omitted because having the same value as the default one.

=== client-gateway.yml

include::../../../../services/infra/client-gateway/src/docs/asciidoc/filters-and-cors-configuration.adoc[leveloffset=+3]

=== web-ui.yml

For OAuth2 security concerns into this file, there are two way to configure it, based on the Oauth2 chosen flow.
There are two common properties:

- `operatorfabric.security.oauth2.flow.provider` which corresponds to the OAuth2 provider.
- `operatorfabric.security.realm-url`: which is the OAuth2 realm provider under which the OpertaroFabric client is declared.
- `operatorfabric.security.provider-url`: which is the The keycloak server instance.

==== OAuth2 Flow Mode

There are 3 OAuth2 Authentication flows available into OperatorFabric UI:

- password grant: referred as PASSWORD mode flow;
- code flow : referred as  CODE mode flow;
- implicit flow: referred as IMPLICIT mode flow.

===== OAuth2 IMPLICIT Flow

It had its own way of configuration.
To enable IMPLICIT Flow authentication the following properties need to be set:

- `operatorfabric.security.oauth2.flow.mode` to `IMPLICIT`;
- `operatorfabric.security.oauth2.flow.delegate-url` with the URL of the OAuth2 leading to the `.well-known/openid-configuration` end-point used for authentication configuration.

====== Example of Keycloak configuration for OperatorFabric OAuth2

```
operatorfabric:
  keycloak:
    realm: dev
  security:
    oauth2:
      flow:
        mode: IMPLICIT
        provider: Opfab Keycloak
        delagate-url: http://localhost:89/auth/realms/${operatorfabric.keycloak.realm}
```

Within the `delegate-url` property the `${operatorfabric.keycloak.realm}` refers to the value of the `operatorfabric.keycloak.realm` declared earlier, `dev` here.
For keycloak instance used for dev purposes, this `delegate-url` correspond to the realm under which the client `opfab-client` is registred. The 
url look up by the implicit ui mechanism is `http://localhost:89/auth/realms/dev/.well-known/openid-configuration`.

====== Keycloak instance additional configuration for dev purposes

Once connected as Admin (login:_admin_,password:_admin_ ) on keycloak (`http://localhost:89/auth/admin`) The first thing is to enable the implicit flow for `opfa-client`. To do so
select `Dev` in the upper select of the right panel then click on Clients. In the table, click on `opfab-client` in the column `Client ID`. Then in the `Settings` tabs turn on the
`Implicit Flow Enabled`. In the same tab, modify `http://localhost:2002/ui/` to `http://localhost:2002/*` and `http://localhost:4200` to `http://localhost:4200/*`.

===== OAuth2 PASSWORD or CODE Flows

These two modes share the same way of declaring the delegate URL. The default configuration for dev is set to `CODE` and work straight away.

- `operatorfabric.security.oauth2.flow.mode` to `PASSWORD` or `CODE`;
- `operatorfabric.security.oauth2.flow.delegate-url` with the URL of the OAuth2 leading to the protocol used for authentication.

====== Example of Keycloak Configuration For OperatorFabric OAuth2

```
operatorfabric:
  keycloak:
    realm: dev
  security:
    oauth2:
      flow:
        mode: CODE
        provider: Opfab Keycloak
        delagate-url: http://localhost:89/auth/realms/${operatorfabric.keycloak.realm}/protocol/openid-connect/auth?response_type=code&client_id=opfab-client
```

Within the `delegate-url` property the `${operatorfabric.keycloak.realm}` refers to the value(also `dev` here) of the `operatorfabric.keycloak.realm` declared earlier.
Here, the `client-id` value is `opfab-client` which is define as client under the `realm` named dev on the dev keycloak instance.

== Using token

=== Get a token

End point: `http://localhost:2002/auth/token`

Method: `POST`

Body arguments:

- client_id: `string` constant=`clientIdPassword`;
 - grant_type: `string` constant=`password`;
 - username: `string` any value, must match an OperatorFabric registered user
name;
 - password: `string` any value;

The following examples will be for `admin` user.

==== Curl

command:
....
curl -s -X POST -d 
"username=admin&password=test&grant_type=password&client_id=clientIdPassword" 
http://localhost:2002/auth/token
....

example of expected result:
....
{"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cC
I6MTU1MjY1OTczOCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJqdGkiOi
IwMmQ4MmU4NS0xM2YwLTQ2NzgtOTc0ZC0xOGViMDYyMTVhNjUiLCJjbGllbnRfaWQiOiJjbGllbnRJZF
Bhc3N3b3JkIiwic2NvcGUiOlsicmVhZCIsInVzZXJfaW5mbyJdfQ.SDg-BEzzonIVXfVBnnfq0oMbs_0
rWVtFGAZzRHj7KPgaOXT3bUhQwPOgggZDO0lv2U1klwB94c8Cb6rErzd3yjJ8wcVcnFLO4KxrjYZZxdK
VAz0CkMKqng4kQeQm_1UShsQXGLl48ezbjXyJn6mAl0oS4ExeiVsx_kYGEdqjyb5CiNaAzyx0J-J5jVD
SJew1rj5EiSybuy83PZwhluhxq0D2zPK1OSzqiezsd5kX5V8XI4MipDhaAbPYroL94banZTn9RmmAKZC
AYVM-mmHbjk8mF89fL9rKf9EUNhxOG6GE0MDqB3LLLcyQ6sYUmpqdP5Z94IkAN-FpC7k93_-RDw","to
ken_type":"bearer","refresh_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWI
iOiJhZG1pbiIsInNjb3BlIjpbInJlYWQiLCJ1c2VyX2luZm8iXSwiYXRpIjoiMDJkODJlODUtMTNmMC0
0Njc4LTk3NGQtMThlYjA2MjE1YTY1IiwiZXhwIjoxNTUyNzAxMTM4LCJhdXRob3JpdGllcyI6WyJST0x
FX0FETUlOIiwiUk9MRV9VU0VSIl0sImp0aSI6IjMwOWY2ZDllLWNmOGEtNDg0YS05ZjMxLWViOTAxYzk
4YTFkYSIsImNsaWVudF9pZCI6ImNsaWVudElkUGFzc3dvcmQifQ.jnZDt6TX2BvlmdT5JV-A7eHTJz_s
lC5fHrJFVI58ly6N7AUUfxebG_52pmuVHYULSKqTJXaLR866r-EnD4BJlzhk476FtgtVx1nazTpLFRLb
8qDCxeLrzClQBkzcxOt6VPxB3CD9QImx3bcsDwjkPxofUDmdg8AxZfGTu0PNbvO8TKLXEkeCztLFvSJM
GlN9zDzWhKxr49I-zPZg0XecgE9j4WITkFoDVwI-AfDJ3sGXDi5AN55Sz1j633QoqVjhtc0lO50WPVk5
YT7gU8HLj27EfX-6vjnGfNb8oeq189-NX100QHZM9Wgm79mIm4sRgwhpv-zzdDAkeb3uwIpb8g","exp
ires_in":1799,"scope":"read 
user_info","jti":"02d82e85-13f0-4678-974d-18eb06215a65"}
....

==== Httpie

....
http --form POST http://localhost:2002/auth/token username=admin password=test 
grant_type=password client_id=clientIdPassword
....

example of expected result:
....
.HTTP/1.1 200 OK
Cache-Control: no-store
Content-Type: application/json;charset=utf-8
Date: Fri, 15 Mar 2019 13:57:19 GMT
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
transfer-encoding: chunked

{
    "access_token": 
"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTU1MjY2MDAzOS
wiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJqdGkiOiI2MjQzMDliMS03Yz
g3LTRjZGMtODQ0My0wMTI0NTE1Zjg3ZjgiLCJjbGllbnRfaWQiOiJjbGllbnRJZFBhc3N3b3JkIiwic2
NvcGUiOlsicmVhZCIsInVzZXJfaW5mbyJdfQ.VO4OZL7ycqNez0cHzM5WPuklr0r6SAOkUdUV2qFa5Bd
3PWx3DFHAHUxkfSX0-R4OO6iG2Zu7abzToAZNVLwk107LH_lWXOMQBriGx3d2aSgCf1yx_wI3lHDd8ST
8fxV7uNeolzywYavSpMGfgz9GXLzmnyeuPH4oy7eyPk9BwWVi0d7a_0d-EfhE1T8eaiDfymzzNXJ4Bge
8scPy-93HmWpqORtJaFq1qy4QgU28N2LgHFEEEWCSzfhYXH-LngTCP3-JSNcox1hI51XBWEqoeApKdfD
J6o4szR71SIFCBERxCH9TyUxsFywWL3e-YnXMiP2J08eB8O4YwhYQEFqB8Q",
    "expires_in": 1799,
    "jti": "624309b1-7c87-4cdc-8443-0124515f87f8",
    "refresh_token": 
"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInNjb3BlIjpbInJlYWQiLC
J1c2VyX2luZm8iXSwiYXRpIjoiNjI0MzA5YjEtN2M4Ny00Y2RjLTg0NDMtMDEyNDUxNWY4N2Y4IiwiZX
hwIjoxNTUyNzAxNDM5LCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sImp0aS
I6ImRiYzMxNTJiLTM4YTUtNGFmZC1hY2VmLWVkZTI4MjJkOTE3YyIsImNsaWVudF9pZCI6ImNsaWVudE
lkUGFzc3dvcmQifQ.Ezd8kbfNQHOOvUCNNN4UmOOkncHiT9QVEM63FiW1rq0uXDa3xfBGil8geM5MsP0
7Q2He-mynkFb8sGNDrAXTdO-8r5o4a60zWrktrMg2QH4icC1lyeZpiwZxe6675QpLpSeMlXt9PdYj-pb
14lrRookxXP5xMQuIMteZpbtby7LuuNAbNrjveZ1bZ4WMi7zltUzcYUuqHlP1AYPteGRrJVKXiuPpoDv
gwMsEk2SkgyyACI7SdZZs8IT9IGgSsIjjgTMQKzj8P6yYxNLUynEW4o5y1s2aAOV0xKrzkln9PchH9zN
qO-fkjTVRjy_LBXGq9zkn0ZeQ3BUe1GuthvGjaA",
    "scope": "read user_info",
    "token_type": "bearer"
}
....

==== Extract token

From the previous results, the data need to be considered to be authenticated 
by OperatorFabric services is the content of the `"access_token"` attribute of 
the body response. 

Once this value extracted, it need to be passed at the end of the value of the 
http HEADER of type `Authorization:Bearer`.
example from previous results:

from cURL:
....
Authorization:Bearer 
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTU1MjY1OTczOCw
iYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJqdGkiOiIwMmQ4MmU4NS0xM2Y
wLTQ2NzgtOTc0ZC0xOGViMDYyMTVhNjUiLCJjbGllbnRfaWQiOiJjbGllbnRJZFBhc3N3b3JkIiwic2N
vcGUiOlsicmVhZCIsInVzZXJfaW5mbyJdfQ.SDg-BEzzonIVXfVBnnfq0oMbs_0rWVtFGAZzRHj7KPga
OXT3bUhQwPOgggZDO0lv2U1klwB94c8Cb6rErzd3yjJ8wcVcnFLO4KxrjYZZxdKVAz0CkMKqng4kQeQm
_1UShsQXGLl48ezbjXyJn6mAl0oS4ExeiVsx_kYGEdqjyb5CiNaAzyx0J-J5jVDSJew1rj5EiSybuy83
PZwhluhxq0D2zPK1OSzqiezsd5kX5V8XI4MipDhaAbPYroL94banZTn9RmmAKZCAYVM-mmHbjk8mF89f
L9rKf9EUNhxOG6GE0MDqB3LLLcyQ6sYUmpqdP5Z94IkAN-FpC7k93_-RDw
....

from Httpie:
....
Authorization:Bearer 
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTU1MjY2MDAzOSw
iYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJqdGkiOiI2MjQzMDliMS03Yzg
3LTRjZGMtODQ0My0wMTI0NTE1Zjg3ZjgiLCJjbGllbnRfaWQiOiJjbGllbnRJZFBhc3N3b3JkIiwic2N
vcGUiOlsicmVhZCIsInVzZXJfaW5mbyJdfQ.VO4OZL7ycqNez0cHzM5WPuklr0r6SAOkUdUV2qFa5Bd3
PWx3DFHAHUxkfSX0-R4OO6iG2Zu7abzToAZNVLwk107LH_lWXOMQBriGx3d2aSgCf1yx_wI3lHDd8ST8
fxV7uNeolzywYavSpMGfgz9GXLzmnyeuPH4oy7eyPk9BwWVi0d7a_0d-EfhE1T8eaiDfymzzNXJ4Bge8
scPy-93HmWpqORtJaFq1qy4QgU28N2LgHFEEEWCSzfhYXH-LngTCP3-JSNcox1hI51XBWEqoeApKdfDJ
6o4szR71SIFCBERxCH9TyUxsFywWL3e-YnXMiP2J08eB8O4YwhYQEFqB8Q
....


=== Check a token 

=== Curl

from previous example

....
curl -s -X POST -d 
"token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTU1MjY1
OTczOCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJqdGkiOiIwMmQ4MmU4
NS0xM2YwLTQ2NzgtOTc0ZC0xOGViMDYyMTVhNjUiLCJjbGllbnRfaWQiOiJjbGllbnRJZFBhc3N3b3Jk
Iiwic2NvcGUiOlsicmVhZCIsInVzZXJfaW5mbyJdfQ.SDg-BEzzonIVXfVBnnfq0oMbs_0rWVtFGAZzR
Hj7KPgaOXT3bUhQwPOgggZDO0lv2U1klwB94c8Cb6rErzd3yjJ8wcVcnFLO4KxrjYZZxdKVAz0CkMKqn
g4kQeQm_1UShsQXGLl48ezbjXyJn6mAl0oS4ExeiVsx_kYGEdqjyb5CiNaAzyx0J-J5jVDSJew1rj5Ei
Sybuy83PZwhluhxq0D2zPK1OSzqiezsd5kX5V8XI4MipDhaAbPYroL94banZTn9RmmAKZCAYVM-mmHbj
k8mF89fL9rKf9EUNhxOG6GE0MDqB3LLLcyQ6sYUmpqdP5Z94IkAN-FpC7k93_-RDw" 
http://localhost:2002/auth/check_token
....

which gives the following example of result:

....
{
    "sub":"admin",
    "scope":["read","user_info"],
    "active":true,"exp":1552659738,
    "authorities":["ROLE_ADMIN","ROLE_USER"],
    "jti":"02d82e85-13f0-4678-974d-18eb06215a65",
    "client_id":"clientIdPassword"
}
....


=== Httpie

from previous example:

....
http --form POST http://localhost:2002/auth/check_token 
token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTU1MjY2M
DAzOSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJqdGkiOiI2MjQzMDliM
S03Yzg3LTRjZGMtODQ0My0wMTI0NTE1Zjg3ZjgiLCJjbGllbnRfaWQiOiJjbGllbnRJZFBhc3N3b3JkI
iwic2NvcGUiOlsicmVhZCIsInVzZXJfaW5mbyJdfQ.VO4OZL7ycqNez0cHzM5WPuklr0r6SAOkUdUV2q
Fa5Bd3PWx3DFHAHUxkfSX0-R4OO6iG2Zu7abzToAZNVLwk107LH_lWXOMQBriGx3d2aSgCf1yx_wI3lH
Dd8ST8fxV7uNeolzywYavSpMGfgz9GXLzmnyeuPH4oy7eyPk9BwWVi0d7a_0d-EfhE1T8eaiDfymzzNX
J4Bge8scPy-93HmWpqORtJaFq1qy4QgU28N2LgHFEEEWCSzfhYXH-LngTCP3-JSNcox1hI51XBWEqoeA
pKdfDJ6o4szR71SIFCBERxCH9TyUxsFywWL3e-YnXMiP2J08eB8O4YwhYQEFqB8Q
....

which gives the following example of result:

....

HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json;charset=utf-8
Date: Fri, 15 Mar 2019 14:19:31 GMT
Expires: 0
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
transfer-encoding: chunked

{
    "active": true,
    "authorities": [
        "ROLE_ADMIN",
        "ROLE_USER"
    ],
    "client_id": "clientIdPassword",
    "exp": 1552660039,
    "jti": "624309b1-7c87-4cdc-8443-0124515f87f8",
    "scope": [
        "read",
        "user_info"
    ],
    "sub": "admin"
}
....



