management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      discovery:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/dev/protocol/openid-connect/certs
#          jwk-set-uri: http://oauth2:8080/auth/jwks.json
  data:
    mongodb:
      uris:
        - mongodb://root:password@mongodb:27017/operator-fabric?authSource=admin&authMode=scram-sha1
eureka:
  client:
    service-url:
      defaultZone: http://registry:8080/eureka
    region: default
  registryFetchIntervalSeconds: 5
  
operatorfabric:
  security:
    oauth2:
      client-id: opfab-client
      client-secret: opfab-keycloak-secret
    jwt:
      login-claim: preferred_username    
      expire-claim: exp
#logging.level.root: DEBUG     
