// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

:sectnums:

= OperatorFabric - Core - Third Party Management Service

This sub project manages Third Party Business Module registration

== Set up and Build

see link:../../../[OperatorFabric main page]

== Features

see https://opfab.github.io/projects/services/core/thirds/1.2.0.SNAPSHOT/reference/#_techincal_overview[reference documentation : Technical overview ]

=== Third Party bundle

Bundle files are uploaded to service to declare Third Party Business
Module resources. These bundle are `tar.gz` archives enclosing resource
files and a configuration file.

Bundle is composed of one subdirectory per resource. When the resource is
internationalized (template, i18n) , those subdirectories themselves need to have
one subdirectory per supported language.

==== Layout

[source]
----
bundle
└──css
│   └──tab.css
│   └──emergency.css
└──i18n
│   └──en.json
│   └──fr.json
└──template
│   └──en
│       └──emergency.handlebars
│   └──fr
│       └──emergency.handlebars
└──config.json
----

==== Configuration

[source]
----
{
  "name": "sample",
  "version": "0.1",
  "defaultLocale": "fr",
  "templates": [
    "emergency"
  ],
  "csses": [
    "tab",
    "emergency"
  ],
  "locales": [
    "fr",
    "en"
  ]
}
----

See https://opfab.github.io/projects/services/core/thirds/1.2.0.SNAPSHOT/api/#__Models[swagger generated documentation model section] for data description

== 3. Rest Endpoints and Data Model

See https://opfab.github.io/projects/services/core/thirds/1.2.0.SNAPSHOT/api[swagger generated documentation]
