
name: Test with old mongo & keycloak versions

on:
  schedule:
    # launch a build every day on develop
    - cron:  '0 23 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Job  status
        run: | 
          export OF_VERSION=$(<VERSION)
          echo "----------------------------"
          echo "Trigger by  : ${{ github.event_name }}"
          echo "On branch : ${{ github.ref_name }} "
          echo "---------------------------"
          
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle.properties','**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Install 
        run: ./CICD/github/install.sh

      - name: Build
        run: |
          ./CICD/github/build.sh
          ./CICD/github/setOldMongoKeycloakVersions.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Karate tests
        run: ./CICD/github/launch_karate_tests.sh
    
      - name: Cypress tests 
        run: ./CICD/github/launch_cypress_tests.sh
      
      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
            name: cypress-screenshots
            path: src/test/cypress/cypress/screenshots


