name: Test with old mongo version

on:
  schedule:
    # launch a build every day on develop
    - cron: "0 23 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Job  status
        run: |
          export OF_VERSION=$(<VERSION)
          echo "----------------------------"
          echo "Trigger by  : ${{ github.event_name }}"
          echo "On branch : ${{ github.ref_name }} "
          echo "---------------------------"

      - name: Cache Gradle packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle.properties','**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Install
        run: ./bin/github/install.sh

      - name: Build
        run: |
          ./bin/github/build.sh
          ./bin/github/setOldMongoVersion.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Karate tests
        run: ./bin/github/launch_karate_tests.sh

      - name: Cypress tests
        run: ./bin/github/launch_cypress_tests.sh

      - name: Upload cypress screenshots
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/cypress/cypress/screenshots
