name: Verify Copyright headers

on:
  pull_request:


# Declare default permissions as read only.
permissions: read-all

jobs:
  in_changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45.0.2

      - name: Verify copyright headers
        run: ./CICD/github/licenceHeaderCheck.sh ${{ steps.changed-files.outputs.all_changed_files }}