name: Verify Copyright headers

on:
  pull_request:

jobs:
  in_changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39.0.3

      - name: Verify copyright headers
        run: ./CICD/github/licenceHeaderCheck.sh ${{ steps.changed-files.outputs.all_changed_files }}