name: Verify Copyright headers

on:
  pull_request:


# Declare default permissions as read only.
permissions: read-all

jobs:
  in_changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@d6babd6899969df1a11d14c368283ea4436bca78 # v44.5.2

      - name: Verify copyright headers
        run: ./CICD/github/licenceHeaderCheck.sh ${{ steps.changed-files.outputs.all_changed_files }}